import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentActor } from "@/lib/auth/server";
import { AccessDeniedError, requireCapability } from "@/lib/access/server";
import { hasCapability } from "@/lib/core/access.mjs";
import { withTenant } from "@/lib/db/client";
import { normalizeRequestIntake, toJsonValue } from "@/lib/commercial/request-intake";

const roleSchema=z.object({specialtyId:z.string().uuid().nullable().optional(),specialtyName:z.string().trim().min(2).max(160),count:z.number().int().positive().max(5000),schedule:z.record(z.string(),z.json()).default({}),requirements:z.record(z.string(),z.json()).default({}),targetClientRate:z.number().nonnegative().nullable().default(null)});
const schema=z.object({clientId:z.string().uuid().nullable().default(null),title:z.string().trim().min(3).max(240),source:z.string().trim().min(1).max(120).default("manual"),location:z.string().trim().max(500).default(""),regionId:z.string().uuid().nullable().default(null),startDate:z.string().date().nullable().default(null),durationText:z.string().trim().max(160).nullable().default(null),schedule:z.record(z.string(),z.json()).default({}),intake:z.record(z.string(),z.json()).default({}),lunchPaid:z.boolean().default(false),vatMode:z.string().trim().max(40).nullable().default("with_vat"),comments:z.string().trim().max(5000).nullable().default(null),ownerUserId:z.string().uuid().nullable().default(null),observerUserIds:z.array(z.string().uuid()).max(30).default([]),roles:z.array(roleSchema).max(250).default([])});
function canAssign(actor:NonNullable<Awaited<ReturnType<typeof getCurrentActor>>>){return actor.roleCode==="director"||hasCapability(actor.access,"organization.manage")||hasCapability(actor.access,"sales.request.archive");}
function rule(intake:ReturnType<typeof normalizeRequestIntake>,key:"housing"|"travel"|"shuttle"|"workwear"|"ppe"|"medical"|"medbook"|"tools"){return intake.provision[key].provider;}

export async function POST(request:Request){try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"sales.request.create");if(actor.demo)return NextResponse.json({error:"Демонстрационные данные доступны только для чтения"},{status:409});const body=schema.parse(await request.json());const intake=normalizeRequestIntake(body.intake);const ownerUserId=body.ownerUserId??actor.userId;if(ownerUserId!==actor.userId&&!canAssign(actor))throw new AccessDeniedError("sales.request.assign");
  const result=await withTenant(actor.organizationId,actor.userId,async(sql)=>sql.begin(async(tx)=>{if(body.clientId){const [client]=await tx<Array<{id:string}>>`SELECT id FROM client_companies WHERE id=${body.clientId}::uuid`;if(!client)throw new Error("Клиент не найден в текущей организации");}if(body.regionId){const [region]=await tx<Array<{id:string}>>`SELECT id FROM regions WHERE id=${body.regionId}::uuid`;if(!region)throw new Error("Регион не найден в текущей организации");}const [owner]=await tx<Array<{id:string}>>`SELECT user_id id FROM organization_memberships WHERE organization_id=${actor.organizationId}::uuid AND user_id=${ownerUserId}::uuid AND status='active'`;if(!owner)throw new Error("Ответственный не состоит в текущей организации");
    const [row]=await tx<Array<{id:string}>>`INSERT INTO requests(organization_id,client_company_id,title,status,workflow_stage_code,source,location_text,region_id,expected_start_date,duration_text,schedule_json,intake_json,lunch_paid,vat_mode,housing_rule,travel_rule,shuttle_rule,ppe_rule,medical_rule,citizenship_rule,tools_rule,comments,owner_user_id,created_by_user_id,assigned_team_id) VALUES(${actor.organizationId}::uuid,${body.clientId}::uuid,${body.title},'draft','new',${body.source},${body.location},${body.regionId}::uuid,${body.startDate}::date,${body.durationText},${sql.json(toJsonValue(body.schedule))},${sql.json(toJsonValue(intake))},${body.lunchPaid},${body.vatMode},${rule(intake,"housing")},${rule(intake,"travel")},${rule(intake,"shuttle")},${`${rule(intake,"workwear")} / ${rule(intake,"ppe")}`},${`${rule(intake,"medical")} / ${rule(intake,"medbook")}`},${intake.compliance.workerCategories.join(", ")},${rule(intake,"tools")},${body.comments},${ownerUserId}::uuid,${actor.userId}::uuid,${actor.teamIds[0]??null}::uuid) RETURNING id`;
    for(const role of body.roles){let specialtyId=role.specialtyId??null;if(specialtyId){const [specialty]=await tx<Array<{id:string}>>`SELECT id FROM specialties WHERE id=${specialtyId}::uuid AND active`;if(!specialty)specialtyId=null;}if(!specialtyId){const [existing]=await tx<Array<{id:string}>>`SELECT id FROM specialties WHERE active AND lower(name)=lower(${role.specialtyName}) LIMIT 1`;if(existing)specialtyId=existing.id;else{const [created]=await tx<Array<{id:string}>>`INSERT INTO specialties(organization_id,code,name) VALUES(${actor.organizationId}::uuid,${`custom-${randomUUID().slice(0,8)}`},${role.specialtyName}) RETURNING id`;specialtyId=created.id;}}await tx`INSERT INTO request_roles(organization_id,request_id,specialty_id,count_required,schedule_json,requirements_json,target_client_rate) VALUES(${actor.organizationId}::uuid,${row.id}::uuid,${specialtyId}::uuid,${role.count},${sql.json(toJsonValue(role.schedule))},${sql.json(toJsonValue(role.requirements))},${role.targetClientRate})`;}
    for(const userId of [...new Set(body.observerUserIds)].filter((id)=>id!==ownerUserId)){const [member]=await tx<Array<{id:string}>>`SELECT user_id id FROM organization_memberships WHERE organization_id=${actor.organizationId}::uuid AND user_id=${userId}::uuid AND status='active'`;if(member)await tx`INSERT INTO request_observers(organization_id,request_id,user_id,added_by_user_id) VALUES(${actor.organizationId}::uuid,${row.id}::uuid,${userId}::uuid,${actor.userId}::uuid) ON CONFLICT DO NOTHING`;}
    return row;}));return NextResponse.json(result,{status:201});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте заполнение полей",issues:error.issues},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав для назначения ответственного"},{status:403});console.error(error);return NextResponse.json({error:error instanceof Error?error.message:"Internal error"},{status:500});}}
