import {NextResponse} from "next/server";
import {z} from "zod";
import {getCurrentActor} from "@/lib/auth/server";
import {AccessDeniedError,requireCapability} from "@/lib/access/server";
import {canReadRow} from "@/lib/core/access.mjs";
import {withTenant} from "@/lib/db/client";
const schema=z.object({name:z.string().trim().min(2).max(300),category:z.enum(["client_instruction","access","ppe","safety","act","template","client","other"]),documentNumber:z.string().trim().max(160).nullable().optional(),documentDate:z.string().date().nullable().optional(),versionLabel:z.string().trim().min(1).max(80).nullable().optional(),sourceUrl:z.string().url().max(2000).nullable().optional(),status:z.enum(["active","needs_update","archived"]),validFrom:z.string().date().nullable().optional(),expiresAt:z.string().date().nullable().optional(),notes:z.string().trim().max(3000).nullable().optional()});
export async function PATCH(request:Request,{params}:{params:Promise<{id:string;documentId:string}>}){
 try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"operations.object.edit");const {id,documentId}=await params;const body=schema.parse(await request.json());if(actor.demo)return NextResponse.json({error:"Демонстрационные данные доступны только для чтения"},{status:409});
 await withTenant(actor.organizationId,actor.userId,async sql=>sql.begin(async tx=>{const [scope]=await tx<Array<{organizationId:string;objectId:string;ownerUserId:string|null;regionId:string|null;assigneeUserIds:string[]}>>`SELECT o.organization_id "organizationId",o.id "objectId",o.owner_user_id "ownerUserId",o.region_id "regionId",ARRAY(SELECT oa.user_id::text FROM object_assignments oa WHERE oa.object_id=o.id AND oa.effective_to IS NULL) "assigneeUserIds" FROM objects o WHERE o.id=${id}::uuid`;if(!scope||!canReadRow(actor.access,"operations.object.edit",scope,actor))throw new AccessDeniedError("operations.object.edit");const [exists]=await tx`SELECT id FROM object_documents WHERE id=${documentId}::uuid AND object_id=${id}::uuid`;if(!exists)throw new Error("Документ не найден");await tx`UPDATE object_documents SET name=${body.name},category=${body.category},document_number=${body.documentNumber??null},document_date=${body.documentDate??null}::date,version_label=${body.versionLabel??null},source_url=${body.sourceUrl??null},status=${body.status},valid_from=${body.validFrom??null}::date,expires_at=${body.expiresAt??null}::date,notes=${body.notes??null},updated_by_user_id=${actor.userId}::uuid,updated_at=now() WHERE id=${documentId}::uuid`;await tx`INSERT INTO activity_events(organization_id,actor_user_id,entity_type,entity_id,verb,summary,metadata) VALUES(${actor.organizationId}::uuid,${actor.userId}::uuid,'object',${id}::uuid,'document_updated',${`Обновлён документ объекта: ${body.name}`},${tx.json({documentId,category:body.category,status:body.status})})`;}));return NextResponse.json({ok:true});
 }catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте документ",issues:error.issues},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});console.error(error);return NextResponse.json({error:error instanceof Error?error.message:"Не удалось обновить документ"},{status:500});}
}