import Link from "next/link";
import { requireActor } from "@/lib/auth/server";
import { listCommercialRequests } from "@/lib/data/commercial-service";
import { requestStageLabels,requestStageTones,requestStages,closeReasonLabels } from "@/lib/commercial/constants";
import { PageHeader,Section,Status } from "@/components/UI";
import { hasCapability } from "@/lib/core/access.mjs";

export default async function Requests({searchParams}:{searchParams:Promise<{view?:string}>}){
 const {view:rawView}=await searchParams;const view=rawView==="table"||rawView==="archive"?rawView:"funnel";const actor=await requireActor();const rows=await listCommercialRequests(actor);const active=rows.filter(x=>!x.archived),archived=rows.filter(x=>x.archived);
 const actions=<div className="page-actions"><div className="segmented"><Link className={view==="funnel"?"active":""} href="/requests?view=funnel">Воронка</Link><Link className={view==="table"?"active":""} href="/requests?view=table">Таблица</Link><Link className={view==="archive"?"active":""} href="/requests?view=archive">Архив</Link></div>{hasCapability(actor.access,"sales.request.create")&&<Link className="button primary" href="/requests/new">Новая заявка</Link>}</div>;
 return <><PageHeader eyebrow="Коммерция → Продажи" title="Заявки" subtitle="Центральный коммерческий контур: условия клиента, расчёты, согласование, версии КП и переговоры." breadcrumbs={[{label:"Коммерция"},{label:"Заявки"}]} actions={actions}/>
 {view==="funnel"&&<div style={{display:"grid",gridAutoFlow:"column",gridAutoColumns:"minmax(220px,1fr)",gap:10,overflowX:"auto",paddingBottom:10}}>{requestStages.map(stage=>{const stageRows=active.filter(x=>x.stage===stage);return <Section key={stage} title={requestStageLabels[stage]} note={`${stageRows.length} заявок`}><div className="stack-list">{stageRows.map(row=><div className="stack-item" key={row.id}><div><Link className="cell-title" href={`/requests/${row.id}`}>{row.number}</Link><strong>{row.title}</strong><small>{row.client} · {row.totalHeadcount} чел.</small>{row.nextAction&&<small>{row.nextAction}</small>}</div><Status tone={requestStageTones[stage]}>{requestStageLabels[stage]}</Status></div>)}{!stageRows.length&&<div style={{padding:"18px 14px",color:"var(--soft)",fontSize:11}}>Нет заявок</div>}</div></Section>})}</div>}
 {view==="table"&&<Section><table className="data-table"><thead><tr><th>№ / заявка</th><th>Заказчик</th><th>Площадка</th><th>Позиции</th><th>Численность</th><th>Ответственный</th><th>Этап</th><th>Следующее действие</th></tr></thead><tbody>{active.map(row=><tr key={row.id}><td><Link className="cell-title" href={`/requests/${row.id}`}>{row.number}</Link><span className="cell-sub">{row.title}</span></td><td>{row.client}<span className="cell-sub">{row.contactName??"Контакт не указан"}</span></td><td>{row.siteName??row.location}<span className="cell-sub">{row.city??row.region??"—"}</span></td><td>{row.roles.map(role=>role.name).join(" · ")||"—"}</td><td className="num">{row.totalHeadcount}</td><td>{row.owner}</td><td><Status tone={requestStageTones[row.stage]}>{requestStageLabels[row.stage]}</Status></td><td>{row.nextAction??"—"}<span className="cell-sub">{row.nextActionAt??""}</span></td></tr>)}</tbody></table></Section>}
 {view==="archive"&&<Section title="Архив заявок" note="Архивное состояние не меняет историю коммерческого процесса"><table className="data-table"><thead><tr><th>№ / заявка</th><th>Заказчик</th><th>Последний этап</th><th>Результат</th><th>Причина закрытия</th><th>Архивировано</th></tr></thead><tbody>{archived.map(row=><tr key={row.id}><td><Link className="cell-title" href={`/requests/${row.id}`}>{row.number}</Link><span className="cell-sub">{row.title}</span></td><td>{row.client}</td><td><Status tone={requestStageTones[row.stage]}>{requestStageLabels[row.stage]}</Status></td><td>{row.businessResult==="lost"?"Не реализовано":row.businessResult==="won"?"Принято":row.businessResult}</td><td>{row.closeReason?closeReasonLabels[row.closeReason]??row.closeReason:"—"}<span className="cell-sub">{row.closeComment}</span></td><td>{row.archivedAt??"—"}</td></tr>)}</tbody></table>{!archived.length&&<div style={{padding:20,color:"var(--muted)"}}>Архив пуст.</div>}</Section>}
 </>;
}
