"use client";
import {Fragment,useEffect,useMemo,useRef,useState,type ReactNode} from "react";
import {ArrowDown,ArrowUp,ChevronDown,ChevronLeft,ChevronRight,Columns3,Layers3,Settings2,X} from "lucide-react";
import {RegistryToolbar,type RegistryFilter} from "@/components/registry/RegistryToolbar";
import {RegistrySelect} from "@/components/registry/RegistrySelect";
export type PatternColumn<T>={id:string;label:string;text:(row:T)=>string;render?:(row:T)=>ReactNode;width?:number;required?:boolean;numeric?:boolean};
type SavedView={name:string;columns:string[];pinned:string[];widths:Record<string,number>;group:string;query?:string;conditions?:Record<string,string>};
/** Data/permissions belong to callers. This component owns presentation preferences only. */
export function PatternRegistry<T extends {id:string}>({rows,columns,filters=[],quickFilter,storageKey,onOpen,actions,initialPageSize=5}:{rows:T[];columns:PatternColumn<T>[];filters?:RegistryFilter[];quickFilter?:RegistryFilter;storageKey:string;onOpen:(row:T)=>void;actions?:ReactNode;initialPageSize?:number}){
 const settingsTrigger=useRef<HTMLButtonElement|null>(null);const conditionsKey=JSON.stringify([quickFilter?.value,...filters.map(f=>f.value)]);
 const [query,setQuery]=useState("");const [visible,setVisible]=useState(columns.map(c=>c.id));const [pinned,setPinned]=useState<string[]>([]);const [widths,setWidths]=useState<Record<string,number>>({});const [group,setGroup]=useState("");const [sort,setSort]=useState({id:columns[0].id,asc:true});const [panel,setPanel]=useState<"columns"|"group"|null>(null);const [selected,setSelected]=useState<string[]>([]);const [collapsed,setCollapsed]=useState<string[]>([]);const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(initialPageSize);const [saved,setSaved]=useState<SavedView[]>([]);const [view,setView]=useState("Основной");const [loaded,setLoaded]=useState(false);const [notice,setNotice]=useState("");
 useEffect(()=>{const timer=setTimeout(()=>{try{const parsed=JSON.parse(localStorage.getItem(storageKey)??"[]");if(Array.isArray(parsed))setSaved(parsed.filter(x=>typeof x?.name==="string"&&Array.isArray(x.columns)&&Array.isArray(x.pinned)&&typeof x.group==="string"&&x.widths&&typeof x.widths==="object"))}catch{}setLoaded(true)},0);return()=>clearTimeout(timer)},[storageKey]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(storageKey,JSON.stringify(saved))}catch{}},[loaded,saved,storageKey]);
 useEffect(()=>{const timer=setTimeout(()=>{setSelected([]);setPage(1)},0);return()=>clearTimeout(timer)},[conditionsKey]);
 function closeSettings(){setPanel(null);settingsTrigger.current?.focus()}
 const shown=visible.map(id=>columns.find(c=>c.id===id)).filter((c):c is PatternColumn<T>=>Boolean(c));
 const filtered=useMemo(()=>rows.filter(row=>columns.some(c=>c.text(row).toLocaleLowerCase("ru").includes(query.trim().toLocaleLowerCase("ru")))).sort((a,b)=>{const c=columns.find(c=>c.id===sort.id)!;return c.text(a).localeCompare(c.text(b),"ru",{numeric:true})*(sort.asc?1:-1)}),[rows,columns,query,sort]);
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const currentPage=Math.min(page,pages);const current=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize);
 const groups=useMemo(()=>{const c=columns.find(c=>c.id===group);if(!c)return [["",current]] as [string,T[]][];const map=new Map<string,T[]>();for(const row of current){const name=c.text(row)||"Не указано";map.set(name,[...(map.get(name)??[]),row])}return [...map]},[current,columns,group]);
 function selectView(name:string){setView(name);const item=saved.find(x=>x.name===name);setVisible(item?columns.filter(c=>c.required||item.columns.includes(c.id)).map(c=>c.id).sort((a,b)=>item.columns.indexOf(a)-item.columns.indexOf(b)):columns.map(c=>c.id));setPinned(item?.pinned.filter(id=>columns.some(c=>c.id===id))??[]);setWidths(item?.widths??{});setGroup(columns.some(c=>c.id===item?.group)?item!.group:"");setQuery(typeof item?.query==="string"?item.query:"");[...(quickFilter?[quickFilter]:[]),...filters].forEach(f=>{const value=item?.conditions?.[f.label];f.onChange(typeof value==="string"&&f.options.some(o=>o.value===value)?value:f.emptyValue)});setSelected([]);setPage(1)}
 function toggleColumn(id:string){setVisible(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);setView("Настроенный")}
 function move(id:string,offset:number){setVisible(current=>{const result=[...current],i=result.indexOf(id),next=i+offset;if(next<0||next>=result.length)return result;[result[i],result[next]]=[result[next],result[i]];return result});setView("Настроенный")}
 function sticky(id:string){if(!pinned.includes(id))return {};return {position:"sticky" as const,left:40+shown.filter(c=>pinned.includes(c.id)).slice(0,shown.filter(c=>pinned.includes(c.id)).findIndex(c=>c.id===id)).reduce((n,c)=>n+(widths[c.id]??c.width??180),0),zIndex:2}}
 function renderRow(row:T){return <tr key={row.id} className={selected.includes(row.id)?"selected":""}><td className="pattern-check"><input type="checkbox" aria-label={`Выбрать: ${columns[0].text(row)}`} checked={selected.includes(row.id)} onChange={()=>setSelected(s=>s.includes(row.id)?s.filter(id=>id!==row.id):[...s,row.id])}/></td>{shown.map((c,i)=><td key={c.id} className={c.numeric?"pattern-number":undefined} style={sticky(c.id)}>{i===0?<button className="pattern-cell-open" onClick={()=>onOpen(row)}>{c.render?.(row)??c.text(row)}</button>:c.render?.(row)??c.text(row)}</td>)}<td><button className="button" onClick={()=>onOpen(row)} aria-label={`Открыть: ${columns[0].text(row)}`}>Открыть</button></td></tr>}
 return <div className="pattern-registry" onKeyDown={e=>{if(e.key==="Escape"&&!e.defaultPrevented&&panel){closeSettings();e.preventDefault()}}}>
 <RegistryToolbar query={query} onQueryChange={q=>{setQuery(q);setPage(1);setSelected([])}} searchLabel="Поиск в образце" placeholder="Название, ответственный, контакт…" quickFilter={quickFilter} filters={filters} onReset={()=>{setQuery("");quickFilter?.onChange(quickFilter.emptyValue);filters.forEach(f=>f.onChange(f.emptyValue));setSelected([]);setPage(1)}} actions={<><RegistrySelect label="Представление" value={view} options={[{value:"Основной",label:"Основной"},...saved.map(v=>({value:v.name,label:v.name})),...(view==="Настроенный"?[{value:view,label:view}]:[])]} onChange={selectView}/><button className="button" aria-expanded={panel==="group"} onClick={e=>{settingsTrigger.current=e.currentTarget;setPanel(panel==="group"?null:"group")}}><Settings2 size={15}/>Группировка</button><button className="button" aria-expanded={panel==="columns"} onClick={e=>{settingsTrigger.current=e.currentTarget;setPanel(panel==="columns"?null:"columns")}}><Columns3 size={15}/>Колонки</button>{actions}</>}/>
 {panel&&<section className="pattern-settings" aria-label={panel==="columns"?"Настройка колонок":"Настройка группировки"}><header><strong>{panel==="columns"?"Колонки и представления":"Группировка"}</strong><button className="icon-button" aria-label="Закрыть настройки" onClick={closeSettings}><X size={16}/></button></header>{panel==="group"?<RegistrySelect label="Группировать по" value={group} options={[{value:"",label:"Без группировки"},...columns.map(c=>({value:c.id,label:c.label}))]} onChange={value=>{setGroup(value);setCollapsed([]);setView("Настроенный")}}/>:<><div className="pattern-column-settings">{columns.map(c=><div key={c.id}><label><input type="checkbox" checked={visible.includes(c.id)} disabled={c.required} onChange={()=>toggleColumn(c.id)}/>{c.label}</label><button className="icon-button" aria-label={`Левее: ${c.label}`} disabled={!visible.includes(c.id)||visible.indexOf(c.id)===0} onClick={()=>move(c.id,-1)}><ChevronLeft size={14}/></button><button className="icon-button" aria-label={`Правее: ${c.label}`} disabled={!visible.includes(c.id)||visible.indexOf(c.id)===visible.length-1} onClick={()=>move(c.id,1)}><ChevronRight size={14}/></button><button className="icon-button" aria-pressed={pinned.includes(c.id)} aria-label={`Закрепить: ${c.label}`} onClick={()=>{setPinned(p=>p.includes(c.id)?p.filter(id=>id!==c.id):[...p,c.id]);setView("Настроенный")}}><Layers3 size={14}/></button><label className="pattern-width">Ширина<input aria-label={`Ширина: ${c.label}`} type="number" min={120} max={480} step={10} value={widths[c.id]??c.width??180} onChange={e=>{setWidths(w=>({...w,[c.id]:Math.max(120,Math.min(480,Number(e.target.value)||180))}));setView("Настроенный")}}/></label></div>)}</div><div className="pattern-settings-actions"><button className="button" onClick={()=>{let index=1;while(saved.some(v=>v.name===`Мой вид ${index}`))index++;const name=`Мой вид ${index}`;setSaved(s=>[...s,{name,columns:visible,pinned,widths,group,query,conditions:Object.fromEntries([...(quickFilter?[quickFilter]:[]),...filters].map(f=>[f.label,f.value]))}]);setView(name);setNotice(`Сохранено: ${name}`)}}>Сохранить мой вид</button>{saved.some(v=>v.name===view)&&<button className="button" onClick={()=>{setSaved(s=>s.filter(v=>v.name!==view));selectView("Основной");setNotice("Представление удалено")}}>Удалить представление</button>}</div></>}</section>}
 <div className="pattern-result" role="status"><span>{filtered.length?`${(currentPage-1)*pageSize+1}–${Math.min(currentPage*pageSize,filtered.length)} из ${filtered.length}`:"Ничего не найдено"}</span><span>{notice}</span></div>
 {selected.length>0&&<div className="pattern-selection">Выбрано: {selected.length}<button className="button" onClick={()=>setSelected([])}>Снять выделение</button></div>}
 <div className="pattern-table-scroll"><table className="pattern-table" style={{width:40+shown.reduce((n,c)=>n+(widths[c.id]??c.width??180),0)+110}}><colgroup><col style={{width:40}}/>{shown.map(c=><col key={c.id} style={{width:widths[c.id]??c.width??180}}/>)}<col style={{width:110}}/></colgroup><thead><tr><th className="pattern-check"><input type="checkbox" aria-label="Выбрать страницу" checked={current.length>0&&current.every(r=>selected.includes(r.id))} onChange={()=>setSelected(current.every(r=>selected.includes(r.id))?[]:current.map(r=>r.id))}/></th>{shown.map(c=><th key={c.id} style={sticky(c.id)} aria-sort={sort.id===c.id?(sort.asc?"ascending":"descending"):"none"}><button onClick={()=>setSort({id:c.id,asc:sort.id===c.id?!sort.asc:true})}>{c.label}{sort.id===c.id&&(sort.asc?<ArrowUp size={12}/>:<ArrowDown size={12}/>)}</button></th>)}<th>Действия</th></tr></thead><tbody>{groups.map(([label,members])=><Fragment key={label}>{group&&<tr className="pattern-group"><td colSpan={shown.length+2}><button aria-expanded={!collapsed.includes(label)} onClick={()=>setCollapsed(s=>s.includes(label)?s.filter(x=>x!==label):[...s,label])}><ChevronDown size={14}/>{label}<small>{members.length}</small></button></td></tr>}{!collapsed.includes(label)&&members.map(renderRow)}</Fragment>)}{!filtered.length&&<tr><td className="pattern-empty" colSpan={shown.length+2}><strong>Записей не найдено</strong><span>Измените условия поиска или сбросьте фильтры.</span></td></tr>}</tbody></table></div>
 <footer className="pattern-pagination"><span>Страница {currentPage} из {pages}</span><label>На странице<select aria-label="Записей на странице" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[5,10,20].map(n=><option key={n}>{n}</option>)}</select></label><button className="icon-button" aria-label="Предыдущая страница" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></button><button className="icon-button" aria-label="Следующая страница" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></button></footer>
 </div>
}
