"use client";
import {useState} from "react";
import {Plus,Download,Upload,ChevronLeft,ChevronRight} from "lucide-react";
import {RegistryHeader} from "@/components/registry/RegistryHeader";
import {RegistryDrawer} from "@/components/registry/RegistryDrawer";
import {PatternRegistry,type PatternColumn} from "./PatternRegistry";
import {PatternAmount,PatternName,PatternStatus} from "./PatternCells";
import {PatternEntity,PatternBlock} from "./PatternEntity";
import {PatternBoard} from "./PatternBoard";

type Row={id:string;name:string;note:string;owner:string;object:string;status:string;phone:string;amount:number;date:string};
const sampleDirections=["Направление А","Направление Б","Направление В"];
const sampleOwners=["Анна Примерова","Мария Образцова","Иван Тестов"];
const samples:Row[]=Array.from({length:44},(_,i)=>{const day=String(1+i%28).padStart(2,"0");return{id:`sample-${i+1}`,name:["Запись с коротким названием","Запись с длинным названием для проверки переноса и ширины колонки","Запись без контактного телефона","Запись с дополнительной информацией"][i%4]+` №${i+1}`,note:`Условные данные · ПР-${String(i+1).padStart(3,"0")}`,owner:sampleOwners[i%3],object:sampleDirections[i%3],status:["В работе","На проверке","Завершено"][i%3],phone:i%4===2?"":`+7 900 300-${String(i%100).padStart(2,"0")}-${String(i*7%100).padStart(2,"0")}`,amount:25000+i*3500,date:`${day}.10.2026`}});

const columns:PatternColumn<Row>[]=[
 {id:"name",label:"Название",text:r=>r.name,render:r=><PatternName title={r.name} note={r.note}/>,width:300,required:true,filter:{kind:"text"}},
 {id:"object",label:"Направление",text:r=>r.object,width:180,filter:{kind:"enum",options:sampleDirections.map(value=>({value,label:value}))}},
 {id:"owner",label:"Ответственный",text:r=>r.owner,render:r=><PatternName title={r.owner}/>,width:200,filter:{kind:"enum",options:sampleOwners.map(value=>({value,label:value}))}},
 {id:"status",label:"Состояние",text:r=>r.status,render:r=><PatternStatus tone={r.status==="Завершено"?"good":r.status==="На проверке"?"warn":"neutral"}>{r.status}</PatternStatus>,width:155,filter:{kind:"enum",options:["В работе","На проверке","Завершено"].map(value=>({value,label:value}))}},
 {id:"phone",label:"Контакт",text:r=>r.phone,render:r=>r.phone||<span className="pattern-muted">Не указан</span>,width:175,filter:{kind:"text"}},
 {id:"amount",label:"Сумма",text:r=>String(r.amount),render:r=><PatternAmount value={r.amount}/>,width:160,numeric:true,filter:{kind:"number",value:r=>r.amount}},
 {id:"date",label:"Дата",text:r=>r.date,width:145,filter:{kind:"date",value:r=>{const [day,month,year]=r.date.split(".");return `${year}-${month}-${day}`}}}
];
const presetViews=[
 {name:"Основной",visible:["name","object","owner","status","phone"],pinned:["name"]},
 {name:"Контроль",visible:["name","object","owner","status","date"],pinned:["name"],group1:"owner",sorts:[{column:"owner",direction:"asc" as const},{column:"name",direction:"asc" as const}]},
 {name:"Расчёты",visible:["name","object","owner","amount","date"],pinned:["name"],group1:"object",sorts:[{column:"amount",direction:"desc" as const}]}
];
const sections=[{id:"tables",label:"Таблицы"},{id:"boards",label:"Доски"},{id:"entities",label:"Карточки"},{id:"forms",label:"Формы и панели"},{id:"analytics",label:"Аналитика"},{id:"special",label:"Спецэкраны"},{id:"elements",label:"Элементы"},{id:"adoption",label:"Карта внедрения"}];
const contract:Record<string,string>={tables:"Реестр: поиск и фильтры слева, представления и настройки справа. Статусы, колонки и группировка используют общие обозначения.",boards:"Одинаковая структура колонок и карточек. Количество этапов и содержание определяются рабочим процессом.",entities:"В обзоре — боковая сводка и основные блоки. Остальные вкладки используют всю доступную ширину.",forms:"Одинаковые поля, подписи, ошибки и действия. Большая форма открывается в панели; короткие действия располагаются внутри блока.",analytics:"Период и условия над результатами. Показатели, графики и расшифровка используют единый ритм и обозначения.",special:"Табель, календарь и структура сохраняют собственную рабочую плотность. Общие поля, кнопки и статусы остаются едиными.",elements:"Один способ показывать статус, имя, контакт, сумму, дату и отсутствующее значение во всех разделах.",adoption:"Образцы готовы к проверке. Рабочие разделы подключаются после согласования: совпадение отдельных размеров ещё не означает переход на общий шаблон."};
export function TemplatesWorkspace(){const [records,setRecords]=useState(samples);const [section,setSection]=useState("tables");const [direction,setDirection]=useState("all");const [selected,setSelected]=useState<Row|null>(null);const [formOpen,setFormOpen]=useState(false);const [formName,setFormName]=useState("");const [formContact,setFormContact]=useState("");const [formError,setFormError]=useState("");const [savedMessage,setSavedMessage]=useState("");const [entityNote,setEntityNote]=useState("Контакт и условия можно обновлять в форме редактирования.");const [editEntity,setEditEntity]=useState(false);const [entityDraft,setEntityDraft]=useState(entityNote);const [period,setPeriod]=useState("month");const [month,setMonth]=useState(9);const [year,setYear]=useState(2026);const [special,setSpecial]=useState("timesheet");const [bulkRows,setBulkRows]=useState<Row[]>([]);const [bulkOwner,setBulkOwner]=useState(sampleOwners[0]);const [importOpen,setImportOpen]=useState(false);const [importFileName,setImportFileName]=useState("");
 const rows=records.filter(r=>direction==="all"||r.object===direction);
 function openForm(){setFormName("");setFormContact("");setFormError("");setSavedMessage("");setFormOpen(true)}
 function changeMonth(delta:number){const date=new Date(year,month+delta,1);setMonth(date.getMonth());setYear(date.getFullYear())}
 function exportRegistry(){const data=["Название;Направление;Ответственный;Состояние;Контакт;Сумма;Дата",...rows.map(r=>[r.name,r.object,r.owner,r.status,r.phone,r.amount,r.date].map(value=>`"${String(value).replaceAll('"','""')}"`).join(";"))].join("\n");const blob=new Blob(["\ufeff"+data],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="operis-registry.csv";link.click();URL.revokeObjectURL(url);setSavedMessage(`Экспортировано записей: ${rows.length}`)}

 const analyticsRows=period==="week"?records.slice(0,5):records;
 return <div className="operis-data-registry operis-patterns"><RegistryHeader title="Шаблоны" subtitle="Общие образцы экранов и элементов OPERIS" breadcrumbs={[{label:"Шаблоны"},{label:"Эталон интерфейса"}]} actions={section==="tables"?<><button className="button" onClick={exportRegistry}><Download size={15}/>Экспорт</button><button className="button" onClick={()=>{setImportFileName("");setImportOpen(true)}}><Upload size={15}/>Импорт</button><button className="button primary" onClick={openForm}><Plus size={15}/>Добавить запись</button></>:undefined}/>
 <div className="pattern-catalog-note"><span>Образцы для согласования</span><span>Все записи и показатели ниже — условные данные.</span></div>
 {savedMessage&&<p className="pattern-note" role="status">{savedMessage}</p>}
 <nav className="pattern-tabs pattern-catalog-tabs" aria-label="Разделы шаблонов">{sections.map(item=><button key={item.id} aria-pressed={section===item.id} onClick={()=>setSection(item.id)}>{item.label}</button>)}</nav><p className="pattern-intro">{contract[section]}</p>
 {section==="tables"&&<><PatternRegistry rows={rows} columns={columns} storageKey="operis.patterns.registry.views.v2" onOpen={setSelected} presetViews={presetViews} onBulkEdit={setBulkRows} quickFilter={{id:"direction",label:"Направление",value:direction,emptyValue:"all",options:[{value:"all",label:"Все направления"},...sampleDirections.map(value=>({value,label:value}))],onChange:setDirection}}/><p className="pattern-note">Проверьте dropdown, сложные фильтры и сортировку, два уровня группировки, Drawer колонок, resize в заголовке, сохранение вида и массовые действия.</p></>}
 {section==="boards"&&<PatternBoard initialCards={samples.slice(0,6).map((r,i)=>({id:r.id,title:r.name,note:r.object,owner:r.owner,stage:['new','work','review'][i%3],date:r.date}))} stages={[{id:"new",label:"Новые"},{id:"work",label:"В работе"},{id:"review",label:"На проверке"},{id:"done",label:"Завершено"}]} onOpen={id=>setSelected(samples.find(r=>r.id===id)!)}/>}
 {section==="entities"&&<PatternEntity title="Название карточки" subtitle="Условный пример сущности · ПР-001" actions={<button className="button" onClick={()=>{setEntityDraft(entityNote);setEditEntity(true)}}>Редактировать</button>} summary={<><PatternName title="Название карточки" note="Основные сведения"/><PatternStatus>В работе</PatternStatus><dl><div><dt>Ответственный</dt><dd>Анна Примерова</dd></div><div><dt>Направление</dt><dd>Направление А</dd></div><div><dt>Контакт</dt><dd>+7 000 000-00-00</dd></div></dl></>} tabs={[{id:"overview",label:"Обзор",content:<div className="pattern-paired"><PatternBlock title="Контакты"><dl><div><dt>Телефон</dt><dd>+7 000 000-00-00</dd></div><div><dt>Дополнительная связь</dt><dd>Не указана</dd></div></dl></PatternBlock><PatternBlock title="Рабочая информация"><dl><div><dt>Состояние</dt><dd><PatternStatus>В работе</PatternStatus></dd></div><div><dt>Комментарий</dt><dd>{entityNote}</dd></div></dl></PatternBlock></div>},{id:"records",label:"Связанные записи",content:<PatternRegistry rows={samples.slice(0,4)} columns={columns.slice(0,4)} storageKey="operis.patterns.entity.views.v1" onOpen={setSelected}/>},{id:"documents",label:"Документы",content:<PatternBlock title="Документы"><div className="pattern-list-row"><span>Пример документа.pdf<small>Условный файл · пример оформления списка</small></span><PatternStatus tone="good">Проверен</PatternStatus></div><div className="pattern-list-row"><span>Дополнительный документ<small>Файл отсутствует</small></span><PatternStatus tone="warn">Ожидается</PatternStatus></div></PatternBlock>},{id:"history",label:"История",content:<PatternBlock title="История изменений"><div className="pattern-list-row"><span>Обновлены контактные данные<small>Анна Примерова · 04.10.2026, 10:00</small></span></div><div className="pattern-list-row"><span>Создана карточка<small>Мария Образцова · 03.10.2026, 14:30</small></span></div></PatternBlock>} ]}/>}
 {section==="forms"&&<div className="pattern-paired"><PatternBlock title="Создание и редактирование"><p>Поля с подписями, проверка обязательного названия, сохранение и отмена.</p><button className="button primary" onClick={openForm}>Открыть форму</button>{savedMessage&&<p role="status">{savedMessage}</p>}</PatternBlock><PatternBlock title="Быстрый просмотр"><p>Краткая сводка открывается в общей боковой панели.</p><button className="button" onClick={()=>setSelected(samples[0])}>Открыть просмотр</button></PatternBlock></div>}
 {section==="analytics"&&<><div className="pattern-actions"><label>Период<select aria-label="Период аналитики" value={period} onChange={e=>setPeriod(e.target.value)}><option value="week">Неделя</option><option value="month">Месяц</option></select></label></div><div className="pattern-metrics"><div><span>Всего записей</span><strong>{analyticsRows.length}</strong></div><div><span>Завершено</span><strong>{analyticsRows.filter(r=>r.status==="Завершено").length}</strong></div><div><span>На проверке</span><strong>{analyticsRows.filter(r=>r.status==="На проверке").length}</strong></div><div><span>Общая сумма</span><strong><PatternAmount value={analyticsRows.reduce((n,r)=>n+r.amount,0)}/></strong></div></div><PatternBlock title="Распределение по состояниям">{['В работе','На проверке','Завершено'].map(label=><div className="pattern-chart-row" key={label}><span>{label}</span><div><i style={{width:`${analyticsRows.filter(r=>r.status===label).length/analyticsRows.length*100}%`}}/></div><strong>{analyticsRows.filter(r=>r.status===label).length}</strong></div>)}</PatternBlock><PatternRegistry rows={analyticsRows} columns={columns} storageKey="operis.patterns.analytics.views.v1" onOpen={setSelected}/></>}
 {section==="special"&&<><nav className="pattern-tabs" aria-label="Специальные шаблоны">{[{id:"timesheet",label:"Табель"},{id:"calendar",label:"Календарь"},{id:"structure",label:"Структура"},{id:"calculation",label:"Расчёт"}].map(item=><button key={item.id} aria-pressed={special===item.id} onClick={()=>setSpecial(item.id)}>{item.label}</button>)}</nav>{['timesheet','calendar'].includes(special)&&<><div className="pattern-month"><button className="icon-button" aria-label="Предыдущий месяц" onClick={()=>changeMonth(-1)}><ChevronLeft size={16}/></button><strong>{new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(new Date(year,month,1))}</strong><button className="icon-button" aria-label="Следующий месяц" onClick={()=>changeMonth(1)}><ChevronRight size={16}/></button></div>{special==="timesheet"?<div className="pattern-table-scroll"><table className="pattern-table pattern-timesheet"><thead><tr><th>Запись</th>{Array.from({length:new Date(year,month+1,0).getDate()},(_,i)=><th key={i}>{i+1}</th>)}<th>Смены</th></tr></thead><tbody>{samples.slice(0,3).map((r,index)=><tr key={r.id}><td>{r.owner}</td>{Array.from({length:new Date(year,month+1,0).getDate()},(_,i)=><td key={i}>{(i+index+month)%7<5?'Д':'В'}</td>)}<td>{Array.from({length:new Date(year,month+1,0).getDate()},(_,i)=>i).filter(i=>(i+index+month)%7<5).length}</td></tr>)}</tbody></table></div>:<div className="pattern-calendar">{Array.from({length:(new Date(year,month,1).getDay()+6)%7},(_,i)=><div key={`blank-${i}`} aria-hidden="true"/>)}{Array.from({length:new Date(year,month+1,0).getDate()},(_,i)=><div key={i}><strong>{i+1}</strong>{i%7===2&&<span>Пример события</span>}</div>)}</div>}<p className="pattern-note">Условный график для проверки календарной сетки. Д — дневная смена, В — выходной.</p></>}{special==="structure"&&<PatternBlock title="Структура подразделений"><ul className="pattern-tree"><li>Организация<ul><li>Операции<ul><li>Направление А</li><li>Направление Б</li></ul></li><li>Подбор<ul><li>Команда подбора</li></ul></li></ul></li></ul></PatternBlock>}{special==="calculation"&&<PatternBlock title="Расчёт — пример рабочей таблицы"><p>Суммы рассчитаны из условных записей.</p><div className="pattern-list-row"><span>Основная сумма</span><PatternAmount value={samples.reduce((n,r)=>n+r.amount,0)}/></div><div className="pattern-list-row"><span>Количество записей</span><strong>{samples.length}</strong></div><div className="pattern-list-row"><span>Средняя сумма</span><PatternAmount value={samples.reduce((n,r)=>n+r.amount,0)/samples.length}/></div></PatternBlock>}</>}
 {section==="elements"&&<div className="pattern-paired"><PatternBlock title="Состояния"><div className="pattern-element-line"><PatternStatus>В работе</PatternStatus><PatternStatus tone="good">Завершено</PatternStatus><PatternStatus tone="warn">На проверке</PatternStatus><PatternStatus tone="bad">Требует исправления</PatternStatus></div><p className="pattern-note">Цвет сопровождается подписью. Статус не выглядит как кнопка.</p></PatternBlock><PatternBlock title="Люди и контакты"><PatternName title="Анна Примерова" note="Условный ответственный · +7 000 000-00-00" avatar/><div className="pattern-list-row"><span>Дополнительный контакт</span><span className="pattern-muted">Не указан</span></div></PatternBlock><PatternBlock title="Значения"><dl><div><dt>Сумма</dt><dd><PatternAmount value={42500}/></dd></div><div><dt>Дата</dt><dd>04.10.2026</dd></div><div><dt>Пустое значение</dt><dd className="pattern-muted">Не указано</dd></div></dl></PatternBlock><PatternBlock title="Пустое состояние"><div className="pattern-empty"><strong>Здесь пока нет записей</strong><span>Добавьте запись или измените условия поиска.</span><button className="button" onClick={openForm}>Добавить запись</button></div></PatternBlock><PatternBlock title="Задачи и согласования"><div className="pattern-list-row"><span>Проверить данные<small>Анна Примерова · срок 05.10.2026</small></span><PatternStatus tone="warn">Ожидает проверки</PatternStatus></div><div className="pattern-list-row"><span>Подтвердить изменения<small>Мария Образцова</small></span><PatternStatus>На согласовании</PatternStatus></div></PatternBlock><PatternBlock title="Настройки"><label className="pattern-form-field">Название правила<input defaultValue="Основное правило"/></label><label className="pattern-checkbox"><input type="checkbox" defaultChecked/>Правило активно</label></PatternBlock></div>}
 {section==="adoption"&&<PatternBlock title="Подключение рабочих разделов"><div className="pattern-table-scroll"><table className="pattern-table"><thead><tr><th>Шаблон</th><th>Разделы</th><th>Состояние</th></tr></thead><tbody>{[['Реестр','Сотрудники, кандидаты, объекты, клиенты, заявки'],['Реестр с группировкой','Потребности по объектам'],['Доска','Подбор, заявки, тендеры'],['Карточка','Сотрудник, кандидат, объект, клиент'],['Формы и панели','Создание, редактирование, быстрый просмотр'],['Аналитика','Портфель, подбор, коммерция, финансы'],['Специальные экраны','Табели, смены, структура, расчёты']].map(([name,modules])=><tr key={name}><td>{name}</td><td>{modules}</td><td><PatternStatus tone="warn">Ожидает согласования</PatternStatus></td></tr>)}</tbody></table></div><p className="pattern-note">В рабочие разделы уже вынесены общие заголовки и часть фильтров. Полный перенос на эти шаблоны ещё не выполнен.</p></PatternBlock>}
 {bulkRows.length>0&&<RegistryDrawer title="Массовое редактирование" subtitle={`Выбрано записей: ${bulkRows.length}`} onClose={()=>setBulkRows([])} footer={<><button className="button" onClick={()=>setBulkRows([])}>Отмена</button><button className="button primary" onClick={()=>{const ids=new Set(bulkRows.map(row=>row.id));setRecords(currentRecords=>currentRecords.map(row=>ids.has(row.id)?{...row,owner:bulkOwner}:row));setSavedMessage(`Изменён ответственный у записей: ${bulkRows.length}`);setBulkRows([])}}>Сохранить</button></>}><div className="operis-patterns"><p className="pattern-note">В рабочем модуле здесь показываются только поля, разрешённые его бизнес-правилами и capabilities.</p><label className="pattern-form-field">Ответственный<select value={bulkOwner} onChange={event=>setBulkOwner(event.target.value)}>{sampleOwners.map(owner=><option key={owner}>{owner}</option>)}</select></label></div></RegistryDrawer>}
 {importOpen&&<RegistryDrawer title="Импорт" subtitle="Образец импорта данных в реестр" onClose={()=>setImportOpen(false)} footer={<><button className="button" onClick={()=>setImportOpen(false)}>Отмена</button><button className="button primary" disabled={!importFileName} onClick={()=>{setSavedMessage(`Файл «${importFileName}» выбран. В каталоге импорт не меняет рабочие данные.`);setImportOpen(false)}}>Продолжить</button></>}><div className="operis-patterns"><label className="pattern-form-field">Файл<input type="file" accept=".csv,.xlsx,.xls" onChange={event=>setImportFileName(event.target.files?.[0]?.name??"")}/></label><p className="pattern-note">Фактический разбор файла, проверки и запись выполняются сервисом конкретного модуля.</p></div></RegistryDrawer>}
 {selected&&<RegistryDrawer title={selected.name} subtitle="Быстрый просмотр · условная запись" onClose={()=>setSelected(null)} footer={<button className="button" onClick={()=>setSelected(null)}>Закрыть</button>}><div className="operis-patterns"><PatternName title={selected.name} note={selected.note}/><dl><div><dt>Ответственный</dt><dd>{selected.owner}</dd></div><div><dt>Направление</dt><dd>{selected.object}</dd></div><div><dt>Контакт</dt><dd>{selected.phone||"Не указан"}</dd></div><div><dt>Состояние</dt><dd><PatternStatus>{selected.status}</PatternStatus></dd></div><div><dt>Сумма</dt><dd><PatternAmount value={selected.amount}/></dd></div></dl></div></RegistryDrawer>}
 {formOpen&&<RegistryDrawer title="Новая запись" subtitle="Образец формы · изменения сохраняются только в этом примере" onClose={()=>setFormOpen(false)} footer={<><button className="button" onClick={()=>setFormOpen(false)}>Отмена</button><button className="button primary" onClick={()=>{if(formName.trim().length<2){setFormError("Введите название: не менее двух символов");return}setRecords(current=>[{id:crypto.randomUUID(),name:formName.trim(),note:"Условная запись · создана в образце",owner:"Анна Примерова",object:"Направление А",status:"В работе",phone:formContact.trim(),amount:0,date:"04.10.2026"},...current]);setSavedMessage(`Образец «${formName.trim()}» добавлен в таблицу. Записи этого примера сбросятся после обновления страницы.`);setFormOpen(false)}}>Сохранить</button></>}><div className="operis-patterns"><label className="pattern-form-field">Название *<input aria-label="Название записи" value={formName} aria-invalid={Boolean(formError)} aria-describedby={formError?'pattern-name-error':undefined} onChange={e=>{setFormName(e.target.value);setFormError("")}}/></label><label className="pattern-form-field">Контакт<input value={formContact} onChange={e=>setFormContact(e.target.value)} placeholder="Телефон или другой способ связи"/></label>{formError&&<p id="pattern-name-error" className="pattern-error" role="alert">{formError}</p>}</div></RegistryDrawer>}
 {editEntity&&<RegistryDrawer title="Редактировать карточку" subtitle="Условный пример" onClose={()=>setEditEntity(false)} footer={<button className="button primary" onClick={()=>{setEntityNote(entityDraft);setEditEntity(false)}}>Сохранить</button>}><div className="operis-patterns"><label className="pattern-form-field">Комментарий<textarea value={entityDraft} onChange={e=>setEntityDraft(e.target.value)}/></label></div></RegistryDrawer>}
 </div>
}
