import { NextResponse } from "next/server";
import { requireActor } from "@/lib/auth/server";
import { getProposalDocument } from "@/lib/data/proposal-document";
import { createDocx } from "@/lib/export/docx";
import { rub } from "@/lib/ui/format";

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){
  const {id}=await params;const actor=await requireActor();const doc=await getProposalDocument(actor,id);if(!doc)return NextResponse.json({error:"Коммерческое предложение не найдено"},{status:404});
  const paragraphs=[{text:`Коммерческое предложение ${doc.proposalNumber}`,bold:true},{text:`Версия: v${doc.version}`},{text:`Заказчик: ${doc.client}`},{text:`Проект: ${doc.requestTitle}`},{text:`Площадка: ${doc.siteName??"Не указана"}`},{text:`Адрес: ${doc.location??"Не указан"}`},{text:`Дата: ${doc.createdAt}`},{text:`Действует до: ${doc.validUntil??"Не указано"}`},{text:""},{text:"Позиции",bold:true},...doc.positions.flatMap(position=>[{text:`${position.name} — ${position.count} чел.`},{text:`Ставка: ${rub(position.clientRate)} / час${position.vatMode?` · ${position.vatMode}`:""}`},{text:`График: ${position.scheduleType??"по условиям заявки"}${position.paidHours?` · ${position.paidHours} оплачиваемых часов`:""}`}]),{text:""},{text:"Условия",bold:true},...clientTerms(doc.provision,doc.terms).map(text=>({text}))];
  const file=createDocx(paragraphs);return new NextResponse(new Uint8Array(file),{headers:{"content-type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","content-disposition":`attachment; filename="proposal-v${doc.version}.docx"`,`cache-control":"private, no-store"}});
}
function clientTerms(provision:Record<string,unknown>,terms:Record<string,unknown>){const lines:string[]=[];const labels:Record<string,string>={workwear:"Спецодежда",ppe:"СИЗ",food:"Питание",housing:"Проживание",shuttle:"Развозка",travel:"Проезд иногородних",medical:"Медосмотр",medicalBook:"Медкнижка",training:"Обучение",permits:"Допуски",tools:"Инструменты",other:"Другие расходы"};for(const [key,label] of Object.entries(labels)){const item=provision[key];if(item&&typeof item==="object"){const provider=(item as Record<string,unknown>).provider;lines.push(`${label}: ${provider==="client"?"предоставляет заказчик":provider==="us"?"включено в предложение":"не требуется"}`)}}for(const key of ["additionalConditions","included","paymentTerms","notes"]){const value=terms[key];if(typeof value==="string"&&value.trim())lines.push(value)}return lines.length?lines:["Дополнительные условия — согласно согласованной версии предложения."]}
