import Link from "next/link";
import { notFound } from "next/navigation";
import { requireActor } from "@/lib/auth/server";
import { listCalculations, listClients, listFinance, listObjects, listRequests } from "@/lib/data/service";
import { hasCapability } from "@/lib/core/access.mjs";
import { Empty, EntityTabs, KeyValue, Metric, PageHeader, Section, Status } from "@/components/UI";
import { modelLabel, pct, rub } from "@/lib/ui/format";

const labels: Record<string, string> = { overview: "Обзор", contacts: "Контакты", requests: "Заявки", calculations: "Расчёты", proposals: "КП", objects: "Объекты", documents: "Документы", finance: "Финансы", activity: "Журнал действий" };

export default async function ClientPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ tab?: string }> }) {
  const { id } = await params; const { tab: raw } = await searchParams; const tab = raw && labels[raw] ? raw : "overview";
  const actor = await requireActor(); const clients = await listClients(actor); const client = clients.find((item) => item.id === id); if (!client) notFound();
  const [requests, objects, calculations, finance] = await Promise.all([hasCapability(actor.access, "sales.request.read") ? listRequests(actor) : Promise.resolve([]), hasCapability(actor.access, "operations.object.read") ? listObjects(actor) : Promise.resolve([]), hasCapability(actor.access, "calculation.scenario.read") ? listCalculations(actor) : Promise.resolve([]), hasCapability(actor.access, "finance.pnl.read") ? listFinance(actor) : Promise.resolve([])]);
  const clientRequests = requests.filter((item) => item.clientId === id); const clientObjects = objects.filter((item) => item.clientId === id); const clientCalculations = calculations.filter((item) => clientRequests.some((request) => request.id === item.requestId)); const clientFinance = finance.filter((item) => clientObjects.some((object) => object.id === item.objectId));
  const revenue = clientFinance.reduce((sum, item) => sum + Number(item.revenue), 0); const contribution = clientFinance.reduce((sum, item) => sum + Number(item.contribution), 0);
  const tabs = Object.entries(labels).filter(([key]) => key !== "finance" || hasCapability(actor.access, "finance.pnl.read")).map(([key, label]) => ({ label, href: `/clients/${id}?tab=${key}`, count: key === "requests" ? clientRequests.length : key === "objects" ? clientObjects.length : key === "calculations" ? clientCalculations.length : undefined }));

  return <><PageHeader eyebrow="Клиент" title={client.name} subtitle={client.legalName ?? "Юридическое лицо не указано"} breadcrumbs={[{ label: "Коммерция" }, { label: "Клиенты", href: "/clients" }, { label: client.name }]}/><EntityTabs items={tabs} active={labels[tab]}/>
    {tab === "overview" && <><div className="metrics-grid"><Metric label="Контакты" value={client.contacts}/><Metric label="Заявки" value={clientRequests.length}/><Metric label="Объекты" value={clientObjects.length}/>{hasCapability(actor.access, "finance.pnl.read") && <Metric label="Вклад в прибыль" value={rub(contribution)} tone={contribution >= 0 ? "good" : "bad"}/>}</div><div className="workspace-grid"><Section title="Коммерческий контур"><div style={{ padding: "6px 15px 14px" }}><KeyValue label="Статус" value={<Status tone="good">{client.status}</Status>}/><KeyValue label="Последняя заявка" value={clientRequests[0] ? <Link href={`/requests/${clientRequests[0].id}`}>{clientRequests[0].title}</Link> : "—"}/><KeyValue label="Принятые расчёты" value={clientCalculations.filter((item) => item.status === "accepted").length}/><KeyValue label="Действующие объекты" value={clientObjects.filter((item) => item.status === "active").length}/></div></Section><Section title="Операционный портфель"><div className="stack-list">{clientObjects.map((item) => <div className="stack-item" key={item.id}><div><Link className="cell-title" href={`/objects/${item.id}`}>{item.name}</Link><small>{item.region} · укомплектованность {item.coverage}%</small></div><Status tone={item.risk === "critical" ? "bad" : item.risk === "high" ? "warn" : "good"}>{item.risk ?? item.status}</Status></div>)}</div></Section></div></>}
    {tab === "requests" && <Section title="Заявки клиента"><table className="data-table"><thead><tr><th>Заявка</th><th>Позиции</th><th>Старт</th><th>Статус</th></tr></thead><tbody>{clientRequests.map((item) => <tr key={item.id}><td><Link className="cell-title" href={`/requests/${item.id}`}>{item.title}</Link></td><td>{item.roles.map((role) => `${role.name} × ${role.count}`).join(" · ")}</td><td>{item.start}</td><td><Status tone="info">{item.status}</Status></td></tr>)}</tbody></table></Section>}
    {tab === "calculations" && <Section title="Расчёты"><table className="data-table"><thead><tr><th>Сценарий</th><th>Роль</th><th>Модель</th><th>Ставка клиенту</th><th>Маржа</th><th>Статус</th></tr></thead><tbody>{clientCalculations.map((item) => <tr key={item.id}><td className="cell-title">{item.name}</td><td>{item.role}</td><td>{modelLabel(item.model)}</td><td className="num">{rub(item.clientRate)}</td><td className="num">{pct(item.marginPct)}</td><td><Status tone={item.status === "accepted" ? "good" : "warn"}>{item.status}</Status></td></tr>)}</tbody></table></Section>}
    {tab === "objects" && <Section title="Объекты"><div className="stack-list">{clientObjects.map((item) => <div className="stack-item" key={item.id}><div><Link className="cell-title" href={`/objects/${item.id}`}>{item.name}</Link><small>{item.region} · {item.code}</small></div><Status tone={item.risk === "critical" ? "bad" : "good"}>{item.status}</Status></div>)}</div></Section>}
    {tab === "finance" && <Section title="Финансы клиента"><div style={{ padding: 16, maxWidth: 560 }}><KeyValue label="Выручка" value={rub(revenue)} sensitive/><KeyValue label="Вклад в прибыль" value={rub(contribution)} sensitive/><KeyValue label="Маржа" value={revenue ? pct(contribution / revenue * 100) : "—"} sensitive/></div></Section>}
    {["contacts", "proposals", "documents", "activity"].includes(tab) && <Section title={labels[tab]}><Empty title="Записей нет" text="В доступном контуре клиента записи этого типа отсутствуют."/></Section>}
  </>;
}
