import Link from "next/link";
import { notFound } from "next/navigation";
import { requireActor } from "@/lib/auth/server";
import { getCommercialRequest } from "@/lib/data/commercial";
import { hasCapability } from "@/lib/core/access.mjs";
import { KeyValue,PageHeader,Section,Status } from "@/components/UI";
import { RequestCommercialActions } from "@/components/RequestCommercialActions";
import { approvalStatusLabel,commentTypeLabel,proposalStatusLabel,requestOutcomeLabel,requestStageLabel } from "@/lib/ui/commercial";
import { pct,rub } from "@/lib/ui/format";

const tabs=[['overview','Обзор'],['conditions','Условия'],['calculations','Расчёты'],['approval','Согласование'],['proposals','КП'],['comments','Комментарии'],['history','История']] as const;
const scenarioLabels:Record<string,string>={draft:'Черновик',review:'На согласовании',accepted:'Согласован',rejected:'Отклонён'};
export default async function RequestPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{tab?:string}>}){
  const {id}=await params;const {tab='overview'}=await searchParams;const actor=await requireActor();const data=await getCommercialRequest(actor,id);if(!data)notFound();const {request,calculations,proposals,approvals,comments,history}=data;
  const total=request.roles.reduce((sum,role)=>sum+Number(role.count||0),0);const selected=calculations.find(x=>x.status==='accepted')??calculations[0];const latestProposal=proposals[0];const canSeeMargin=hasCapability(actor.access,'sales.request.margin.read')||hasCapability(actor.access,'finance.client_margin.read');
  return <>
    <PageHeader eyebrow={`Заявка ${request.requestNumber}`} title={request.title} subtitle={`${request.client} · ${request.siteName||request.location||'Площадка не указана'}`} breadcrumbs={[{label:'Коммерция'},{label:'Заявки',href:'/requests'},{label:request.requestNumber}]}/>
    <div className="segmented" style={{marginBottom:12,overflowX:'auto'}}>{tabs.map(([key,label])=><Link key={key} className={tab===key?'active':''} href={`/requests/${id}?tab=${key}`}>{label}</Link>)}</div>
    {request.archivedAt&&<div className="compliance-note" style={{marginBottom:12}}>Заявка находится в архиве. Коммерческая история сохранена; для продолжения работы восстановите её на подходящий этап.</div>}
    {tab==='overview'&&<div className="workspace-grid"><div><Section title="Коммерческий контекст"><div style={{padding:'6px 15px 14px'}}><KeyValue label="№ заявки" value={request.requestNumber}/><KeyValue label="Рабочее название" value={request.title}/><KeyValue label="Компания" value={request.client}/><KeyValue label="Контакт" value={request.contactName||'Не указан'}/><KeyValue label="Телефон / email" value={[request.contactPhone,request.contactEmail].filter(Boolean).join(' · ')||'Не указаны'}/><KeyValue label="Площадка" value={request.siteName||'Не указана'}/><KeyValue label="Адрес" value={request.location||'Не указан'}/><KeyValue label="Ответственный" value={request.owner||'Не назначен'}/><KeyValue label="Этап" value={<Status tone={request.stage==='accepted'?'good':'warn'}>{requestStageLabel(request.stage)}</Status>}/><KeyValue label="Результат" value={requestOutcomeLabel(request.outcome)}/><KeyValue label="Общая численность" value={`${total} чел.`}/><KeyValue label="Старт / срок" value={`${request.start||'Не указан'} · ${request.projectIndefinite?'Бессрочно':request.duration||'срок не указан'}`}/></div></Section><Section title="Позиции"><table className="data-table"><thead><tr><th>Специальность</th><th>Количество</th><th>Квалификация</th><th>График</th><th>Оплачиваемые часы</th></tr></thead><tbody>{request.roles.length?request.roles.map((role,i)=><tr key={role.id||`${role.name}-${i}`}><td className="cell-title">{role.name}</td><td className="num">{role.count}</td><td>{role.qualification||'—'}</td><td>{role.scheduleType||'—'}</td><td className="num">{role.paidHours??'—'}</td></tr>):<tr><td colSpan={5}>Позиции пока не добавлены — черновик можно сохранить без них.</td></tr>}</tbody></table></Section></div><div><Section title="Коммерция"><div style={{padding:'6px 15px 14px'}}><KeyValue label="Ориентир клиента" value={formatLimit(request.commercialLimits)}/><KeyValue label="Выбранный расчёт" value={selected?selected.name:'Не выбран'}/><KeyValue label="Согласованная ставка" value={selected?rub(selected.clientRate):'—'}/>{canSeeMargin&&<KeyValue label="Маржа" value={selected?pct(selected.marginPct):'—'}/>}<KeyValue label="Последнее КП" value={latestProposal?`v${latestProposal.version} · ${proposalStatusLabel(latestProposal.status)}`:'Не создано'}/><KeyValue label="Следующее действие" value={request.nextAction||'Не назначено'}/><KeyValue label="Дата" value={request.nextActionAt||'—'}/><KeyValue label="Изменено" value={request.updatedAt||'—'}/></div></Section><Section title="Действия"><RequestCommercialActions requestId={id} stage={request.stage} archived={Boolean(request.archivedAt)} canEdit={hasCapability(actor.access,'sales.request.edit')} canArchive={hasCapability(actor.access,'sales.request.archive')} canCreateObject={hasCapability(actor.access,'operations.object.edit')}/></Section></div></div>}
    {tab==='conditions'&&<div className="workspace-grid"><Section title="Заказчик и площадка"><div style={{padding:'6px 15px 14px'}}><KeyValue label="Компания" value={request.client}/><KeyValue label="ИНН" value={request.customerInn||'Не указан'}/><KeyValue label="Контактное лицо" value={request.contactName||'Не указано'}/><KeyValue label="Должность" value={request.contactPosition||'Не указана'}/><KeyValue label="Телефон" value={request.contactPhone||'Не указан'}/><KeyValue label="Email" value={request.contactEmail||'Не указан'}/><KeyValue label="Площадка" value={request.siteName||'Не указана'}/><KeyValue label="Город / регион" value={[request.city,request.region].filter(Boolean).join(' · ')||'Не указаны'}/><KeyValue label="Транспорт" value={request.transportAccess||request.nearestTransport||'Не указан'}/><KeyValue label="Логистика" value={request.logisticsComment||'—'}/></div></Section><Section title="Обеспечение и коммерческие ограничения"><div style={{padding:'6px 15px 14px'}}><JsonRows value={request.provision}/><div style={{height:8}}/><JsonRows value={request.commercialLimits}/></div></Section></div>}
    {tab==='calculations'&&<Section title="Сценарии расчёта" note="Согласованные и использованные версии не меняются задним числом"><div style={{padding:12}}><Link className="button primary" href={`/calculations?request=${id}`}>Новый расчёт из заявки</Link></div><table className="data-table"><thead><tr><th>Сценарий</th><th>Роль</th><th>Модель</th><th>Себестоимость</th><th>Ставка клиенту</th><th>Маржа</th><th>Статус</th></tr></thead><tbody>{calculations.map(x=><tr key={x.id}><td className="cell-title">{x.name}</td><td>{x.role||'Все позиции'}</td><td>{x.model}</td><td className="num">{rub(x.totalCost)}</td><td className="num">{rub(x.clientRate)}</td><td className="num">{canSeeMargin?pct(x.marginPct):'Скрыто'}</td><td><Status tone={x.status==='accepted'?'good':x.status==='rejected'?'bad':'warn'}>{scenarioLabels[x.status]??x.status}</Status></td></tr>)}</tbody></table></Section>}
    {tab==='approval'&&<Section title="Согласование" note="Решение относится к конкретной версии сценария"><table className="data-table"><thead><tr><th>Сценарий</th><th>Запросил</th><th>Согласующий</th><th>Решение</th><th>Дата</th><th>Комментарий</th></tr></thead><tbody>{approvals.length?approvals.map(x=><tr key={x.id}><td className="cell-title">{x.scenario}</td><td>{x.requestedBy}</td><td>{x.assignedTo||'По правилам доступа'}</td><td><Status tone={x.status==='approved'?'good':x.status==='rejected'?'bad':'warn'}>{approvalStatusLabel(x.status)}</Status></td><td>{x.decidedAt||x.requestedAt}</td><td>{x.comment||'—'}</td></tr>):<tr><td colSpan={6}>Согласований пока нет.</td></tr>}</tbody></table></Section>}
    {tab==='proposals'&&<Section title="Версии коммерческого предложения" note="Клиентская версия не содержит внутренней себестоимости и маржи"><table className="data-table"><thead><tr><th>КП</th><th>Версия</th><th>Сценарии</th><th>Сумма</th><th>Срок действия</th><th>Отправлено</th><th>Статус</th></tr></thead><tbody>{proposals.length?proposals.map(x=><tr key={x.id}><td className="cell-title">{'proposalNumber' in x&&x.proposalNumber?x.proposalNumber:'КП'}</td><td>v{x.version}</td><td className="num">{x.scenarioCount}</td><td className="num">{Number(x.totalValue)?rub(x.totalValue):'—'}</td><td>{'validUntil' in x?x.validUntil||'—':'—'}</td><td>{'sentAt' in x?x.sentAt||'—':'—'}</td><td><Status tone={x.status==='accepted'?'good':x.status==='rejected'?'bad':'warn'}>{proposalStatusLabel(x.status)}</Status></td></tr>):<tr><td colSpan={7}>КП пока не создавались.</td></tr>}</tbody></table></Section>}
    {tab==='comments'&&<Section title="Комментарии" note="Комментарии сотрудников отделены от системной истории"><div className="stack-list">{comments.length?comments.map(x=><div className="stack-item" key={x.id}><div><strong>{commentTypeLabel(x.type)} · {x.author}</strong><small>{x.createdAt} · {x.entityType==='request'?'Заявка':'Связанная сущность'}</small><div style={{marginTop:6}}>{x.body}</div></div></div>):<div className="stack-item">Комментариев пока нет.</div>}</div></Section>}
    {tab==='history'&&<Section title="Системная история" note="Автоматический аудит значимых коммерческих изменений"><table className="data-table"><thead><tr><th>Дата</th><th>Пользователь</th><th>Сущность</th><th>Действие</th><th>Изменение</th></tr></thead><tbody>{history.length?history.map(x=><tr key={x.id}><td>{x.createdAt}</td><td>{x.actor}</td><td>{historyResource(x.resourceType)}</td><td>{historyAction(x.action)}</td><td>{summarizeChange(x.before,x.after)}</td></tr>):<tr><td colSpan={5}>История появится после изменений в рабочей базе.</td></tr>}</tbody></table></Section>}
  </>;
}
function formatLimit(value?:Record<string,unknown>){if(!value)return 'Не указан';const rate=value.maxClientRate??value.desiredClientRate;return rate?`${rub(Number(rate))}/ч · ${value.vatMode==='without_vat'?'без НДС':'с НДС'}`:'Не указан'}
function JsonRows({value}:{value?:Record<string,unknown>}){if(!value||Object.keys(value).length===0)return <span>Не заполнено</span>;return <>{Object.entries(value).filter(([,v])=>v!==undefined&&v!==null&&v!=='').map(([key,v])=><KeyValue key={key} label={fieldLabel(key)} value={typeof v==='object'?formatObject(v):String(v)}/>)}</>}
function formatObject(value:object){const record=value as Record<string,unknown>;const provider=record.provider;const providerLabel=provider==='client'?'Заказчик':provider==='us'?'Мы':provider==='not_required'?'Не требуется':undefined;return [providerLabel,record.amount?`${record.amount} ${record.unit||'₽'}`:undefined,record.comment].filter(Boolean).join(' · ')||'—'}
function fieldLabel(key:string){return ({housing:'Проживание',travel:'Проезд иногородних',shuttle:'Развозка',workwear:'Спецодежда',ppe:'СИЗ',food:'Питание',medical:'Медосмотр',medicalBook:'Медкнижка',training:'Обучение',permits:'Допуски',tools:'Инструменты',desiredClientRate:'Желаемая ставка',maxClientRate:'Максимальная ставка',employeeSalaryOffer:'Зарплата от заказчика',totalBudget:'Общий бюджет',monthlyLimit:'Месячный лимит',vatMode:'НДС',other:'Другие ограничения'} as Record<string,string>)[key]??key}
function historyResource(value:string){return ({requests:'Заявка',calculation_scenarios:'Сценарий расчёта',calculation_approvals:'Согласование',proposals:'КП'} as Record<string,string>)[value]??value}
function historyAction(value:string){return ({insert:'Создано',update:'Изменено',delete:'Удалено'} as Record<string,string>)[value]??value}
function summarizeChange(before?:Record<string,unknown>|null,after?:Record<string,unknown>|null){if(!before)return 'Создание';if(!after)return 'Удаление';const changed=Object.keys(after).filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k])&&!['updated_at'].includes(k));return changed.length?changed.slice(0,4).join(', '):'Техническое изменение'}
