"use client";

import Link from "next/link";
import { Fragment, useEffect, useMemo, useRef, useState } from "react";
import { ArrowDown, ArrowUp, ChevronDown, ChevronLeft, ChevronRight, Columns3, Download, Ellipsis, Filter, Layers3, Pin, Plus, Search, Settings2, Upload, X } from "lucide-react";
import type { WorkerRow } from "@/lib/data/service";
import { employmentTypeLabel } from "@/lib/ui/labels";
import { rub } from "@/lib/ui/format";
import { RegistryDrawer } from "./RegistryDrawer";
import { PersonAvatar, type PersonAvatarKind } from "./PersonAvatar";
import { documentsLabel, nextChange, operationalState, rateLabel, scheduleLabel, todayState, todayStateTone, workerNeedsAttention } from "./worker-labels";

type ColumnId="person"|"object"|"specialty"|"manager"|"state"|"schedule"|"today"|"change"|"documents"|"ppe"|"phone"|"source"|"employment"|"start"|"mode"|"rate"|"accrued"|"paid"|"payable";
type GroupId=""|"manager"|"object"|"specialty"|"state"|"mode";
type TabId="all"|"active"|"attention"|"absent"|"dismissed";
type Column={id:ColumnId;label:string;width:number;private?:boolean};
const COLUMNS:Column[]=[{id:"person",label:"Сотрудник",width:248},{id:"object",label:"Объект",width:176},{id:"specialty",label:"Специальность",width:154},{id:"manager",label:"Менеджер",width:164},{id:"state",label:"Состояние",width:144},{id:"schedule",label:"График",width:130},{id:"today",label:"Сегодня",width:164},{id:"change",label:"Ближайшее изменение",width:216},{id:"documents",label:"Документы",width:132},{id:"ppe",label:"Обеспечение",width:144},{id:"phone",label:"Телефон",width:164},{id:"source",label:"Источник",width:170},{id:"employment",label:"Оформление",width:154},{id:"start",label:"Дата начала",width:130},{id:"mode",label:"Формат работы",width:130},{id:"rate",label:"Ставка",width:210,private:true},{id:"accrued",label:"Начислено",width:150,private:true},{id:"paid",label:"Выплачено",width:150,private:true},{id:"payable",label:"К выплате",width:150,private:true}];
const GROUPS:{id:GroupId;label:string}[]=[{id:"",label:"Без группировки"},{id:"manager",label:"Менеджер"},{id:"object",label:"Объект"},{id:"specialty",label:"Специальность"},{id:"state",label:"Состояние"},{id:"mode",label:"Формат работы"}];
type View={id:string;name:string;columns:ColumnId[];pinned:ColumnId[];group:GroupId;subgroup:GroupId;widths:Partial<Record<ColumnId,number>>};
const BASE:View={id:"main",name:"Основной",columns:["person","object","specialty","manager","state"],pinned:["person"],group:"",subgroup:"",widths:{}};
const PRESETS:View[]=[BASE,{...BASE,id:"documents",name:"Документы и СИЗ",columns:["person","object","documents","ppe","change"]},{...BASE,id:"schedule",name:"Графики и смены",columns:["person","object","schedule","today","change"]},{...BASE,id:"payroll",name:"Расчёты",columns:["person","object","rate","accrued","paid","payable"]}];
const TABS:{id:TabId;label:string}[]=[{id:"all",label:"Все сотрудники"},{id:"active",label:"Действующие"},{id:"attention",label:"Требуют внимания"},{id:"absent",label:"Отсутствуют"},{id:"dismissed",label:"Работа завершена"}];
const date=(s?:string|null)=>s?new Intl.DateTimeFormat("ru-RU").format(new Date(s+"T00:00:00")):"—";
function absent(r:WorkerRow){return r.status==="active"&&Boolean(r.absenceStatus==="confirmed"&&r.absenceFrom&&r.absenceFrom<=new Date().toISOString().slice(0,10)&&(!r.absenceTo||r.absenceTo>=new Date().toISOString().slice(0,10)))}
function matchesTab(r:WorkerRow,t:TabId){return t==="all"||t==="active"&&r.status==="active"||t==="attention"&&workerNeedsAttention(r)||t==="absent"&&absent(r)||t==="dismissed"&&r.status==="dismissed"}
function value(r:WorkerRow,id:ColumnId):string{
  switch(id){
    case"person":return r.fullName;case"object":return r.object??"Без назначения";case"specialty":return r.specialty??"Не указана";case"manager":return r.managerName??"Не назначен";
    case"state":return operationalState(r);case"schedule":return scheduleLabel(r);case"today":return todayState(r);case"change":return nextChange(r);case"documents":return documentsLabel(r.employmentDocumentsStatus);
    case"ppe":return Number(r.ppeRequiredCount)>0?`${r.ppeIssuedCount??0}/${r.ppeRequiredCount}${r.ppeMissingNames?.length?" · "+r.ppeMissingNames.join(", "):""}`:"Не задано";
    case"phone":return r.phone??"—";case"source":return r.source??"—";case"employment":return employmentTypeLabel(r.employment);case"start":return date(r.startDate);case"mode":return r.workMode==="rotation"?"Вахта":"Местный";
    case"rate":return rateLabel(r);case"accrued":case"paid":case"payable":return r[id]==null?"—":rub(r[id]);
  }
}
function reasons(r:WorkerRow){const list:string[]=[];if(r.status!=="active")return list;if(!r.objectId||!r.specialtyId)list.push("Не завершено назначение на объект");if(r.todayTimeCode==="NO_SHOW"||r.todayAttendanceEvent==="no_show")list.push("Зафиксирован невыход");if(r.employmentDocumentsStatus&&r.employmentDocumentsStatus!=="completed")list.push("Документы: "+documentsLabel(r.employmentDocumentsStatus));if(Number(r.ppeRequiredCount??0)>Number(r.ppeIssuedCount??0))list.push("Не выданы все необходимые СИЗ");if(r.todayShiftAssigned&&!r.todayShiftConfirmed)list.push("Смена ожидает подтверждения");if(r.absenceStatus==="confirmed"&&r.absenceFrom&&r.absenceFrom<=new Date().toISOString().slice(0,10)&&!r.absenceTo)list.push("Не задана дата возврата");if(r.plannedExitDate||r.plannedTransferDate)list.push("Запланировано: "+nextChange(r));return list}
function Dot({tone="neutral",children}:{tone?:"good"|"warn"|"bad"|"neutral";children:React.ReactNode}){return <span className={`operis-status ${tone}`}><i/>{children}</span>}
function safeView(input:unknown,allowed:ColumnId[]):View|null{
  if(!input||typeof input!=="object")return null;const v=input as Partial<View>;
  if(typeof v.id!=="string"||typeof v.name!=="string"||!Array.isArray(v.columns))return null;
  const columns=Array.from(new Set(["person" as ColumnId,...v.columns.filter(id=>allowed.includes(id))]));
  const group=GROUPS.some(x=>x.id===v.group)?v.group!:"";const subgroup=GROUPS.some(x=>x.id===v.subgroup)&&v.subgroup!==group?v.subgroup!:"";
  const widths:View["widths"]={};for(const id of columns){const w=v.widths?.[id];if(typeof w==="number"&&Number.isFinite(w))widths[id]=Math.max(110,Math.min(420,w))}
  return {id:v.id.slice(0,80),name:v.name.slice(0,40),columns,pinned:Array.from(new Set((Array.isArray(v.pinned)?v.pinned:[]).filter(id=>columns.includes(id)))),group,subgroup,widths};
}
function exportCsv(rows:WorkerRow[],columns:Column[]){
  const escape=(v:string)=>'"'+(/^[=+\-@\t\r]/.test(v)?"'":"")+v.replace(/"/g,'""')+'"';
  const text="\uFEFF"+[columns.map(c=>escape(c.label)).join(";"),...rows.map(r=>columns.map(c=>escape(value(r,c.id))).join(";"))].join("\r\n");
  const url=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="operis-workers.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}

export function WorkersRegistry({rows,sensitive,canEdit,preferenceScope,onCreate,onImport}:{rows:WorkerRow[];sensitive:boolean;canEdit:boolean;preferenceScope:string;onCreate:()=>void;onImport:()=>void}){
  const allowed=useMemo(()=>COLUMNS.filter(c=>sensitive||!c.private),[sensitive]);
  const key=`operis:workers:views:v1:${preferenceScope}:${sensitive?"finance":"standard"}`;
  const [view,setView]=useState<View>(BASE);const [custom,setCustom]=useState<View[]>([]);const [loaded,setLoaded]=useState(false);const [storageError,setStorageError]=useState("");
  const [query,setQuery]=useState("");const [tab,setTab]=useState<TabId>("all");const [filters,setFilters]=useState({object:"",manager:"",specialty:"",mode:"",state:""});
  const [popup,setPopup]=useState<""|"views"|"columns"|"groups"|"filters">("");const [viewName,setViewName]=useState("");const [sort,setSort]=useState<{id:ColumnId;asc:boolean}>({id:"person",asc:true});
  const [collapsed,setCollapsed]=useState<Set<string>>(new Set());const [selected,setSelected]=useState<Set<string>>(new Set());const [quick,setQuick]=useState<WorkerRow|null>(null);const [menu,setMenu]=useState<string|null>(null);
  const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(20);const [avatar,setAvatar]=useState<PersonAvatarKind>("workerMan");
  const wrapper=useRef<HTMLDivElement>(null);const scroller=useRef<HTMLDivElement>(null);const dock=useRef<HTMLDivElement>(null);const [dockWidth,setDockWidth]=useState(0);const [showDock,setShowDock]=useState(false);
  useEffect(()=>{
    // Restore browser-only presentation preferences after hydration; no employee data is stored.
    let current:View=BASE,saved:View[]=[];
    try{const raw=JSON.parse(localStorage.getItem(key)??"null");current=safeView(raw?.current,allowed.map(x=>x.id))??BASE;saved=Array.isArray(raw?.custom)?raw.custom.map((x:unknown)=>safeView(x,allowed.map(c=>c.id))).filter(Boolean).slice(0,20):[];}catch{}
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setView(current);setCustom(saved);setLoaded(true);
  },[key,allowed]);
  useEffect(()=>{if(!loaded)return;try{localStorage.setItem(key,JSON.stringify({current:view,custom}));}catch{setTimeout(()=>setStorageError("Настройки действуют до закрытия вкладки: браузер не разрешил сохранение."),0)}},[view,custom,key,loaded]);
  useEffect(()=>{const click=(e:MouseEvent)=>{if(!wrapper.current?.contains(e.target as Node)){setPopup("");setMenu(null)}};const escape=(e:KeyboardEvent)=>{if(e.key==="Escape"){setPopup("");setMenu(null)}};document.addEventListener("mousedown",click);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("mousedown",click);document.removeEventListener("keydown",escape)}},[]);
  const columns=useMemo(()=>{const cols=view.columns.map(id=>allowed.find(c=>c.id===id)).filter((c):c is Column=>Boolean(c));return [...cols.filter(c=>view.pinned.includes(c.id)),...cols.filter(c=>!view.pinned.includes(c.id))]},[view,allowed]);
  const widths=columns.map(c=>view.widths[c.id]??c.width);const tableWidth=widths.reduce((a,b)=>a+b,0)+88;
  useEffect(()=>{const update=()=>{const el=scroller.current;if(!el)return;const bounds=el.getBoundingClientRect();setDockWidth(el.scrollWidth);setShowDock(el.scrollWidth>el.clientWidth+2&&bounds.top<window.innerHeight-90&&bounds.bottom>window.innerHeight&&!quick)};update();const observer=new ResizeObserver(update);if(scroller.current)observer.observe(scroller.current);window.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);return()=>{observer.disconnect();window.removeEventListener("scroll",update);window.removeEventListener("resize",update)}},[tableWidth,rows.length,quick,pageSize]);
  const searched=useMemo(()=>rows.filter(r=>{
    const needle=query.trim().toLocaleLowerCase("ru");const text=[r.fullName,r.phone,r.id,r.object,r.managerName,r.specialty,r.source].filter(Boolean).join(" ").toLocaleLowerCase("ru");const phone=query.replace(/\D/g,"");
    return (!needle||text.includes(needle)||phone.length>=4&&Boolean(r.phone?.replace(/\D/g,"").includes(phone)))&&(!filters.object||value(r,"object")===filters.object)&&(!filters.manager||value(r,"manager")===filters.manager)&&(!filters.specialty||value(r,"specialty")===filters.specialty)&&(!filters.mode||value(r,"mode")===filters.mode)&&(!filters.state||value(r,"state")===filters.state);
  }),[rows,query,filters]);
  const filtered=useMemo(()=>searched.filter(r=>matchesTab(r,tab)).sort((a,b)=>{
    const id=sort.id;const av=["rate","accrued","paid","payable"].includes(id)?(a[id as "rate"]??-Infinity):value(a,id);const bv=["rate","accrued","paid","payable"].includes(id)?(b[id as "rate"]??-Infinity):value(b,id);const cmp=typeof av==="number"&&typeof bv==="number"?(av===bv?0:av<bv?-1:1):String(av).localeCompare(String(bv),"ru",{numeric:true});return sort.asc?cmp:-cmp;
  }),[searched,tab,sort]);
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),currentPage=Math.min(page,pages);const visible=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize);
  const selectedRows=filtered.filter(r=>selected.has(r.id));const allChecked=visible.length>0&&visible.every(r=>selected.has(r.id));
  const choices=(id:ColumnId)=>Array.from(new Set(rows.map(r=>value(r,id)))).sort((a,b)=>a.localeCompare(b,"ru"));
  const updateView=(patch:Partial<View>)=>setView(v=>({...v,...patch}));const changePopup=(p:typeof popup)=>{setPopup(popup===p?"":p);setMenu(null)};
  function toggleSelection(id:string){setSelected(s=>{const n=new Set(s);if(n.has(id))n.delete(id);else n.add(id);return n})}
  function sticky(c:Column){if(!view.pinned.includes(c.id))return {};return {position:"sticky" as const,left:40+columns.slice(0,columns.indexOf(c)).filter(x=>view.pinned.includes(x.id)).reduce((sum,x)=>sum+(view.widths[x.id]??x.width),0),zIndex:2}}
  function resize(e:React.PointerEvent,c:Column){e.preventDefault();e.stopPropagation();const node=e.currentTarget as HTMLElement;node.setPointerCapture(e.pointerId);const start=e.clientX,initial=view.widths[c.id]??c.width;const move=(event:PointerEvent)=>setView(v=>({...v,widths:{...v.widths,[c.id]:Math.max(110,Math.min(420,initial+event.clientX-start))}}));const end=()=>{node.removeEventListener("pointermove",move);node.removeEventListener("pointerup",end);node.removeEventListener("pointercancel",end)};node.addEventListener("pointermove",move);node.addEventListener("pointerup",end);node.addEventListener("pointercancel",end)}
  function moveColumn(id:ColumnId,delta:number){const ids=[...view.columns],i=ids.indexOf(id),j=i+delta;if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];updateView({columns:ids})}
  function renderCell(r:WorkerRow,c:Column){
    if(c.id==="person")return <button className="operis-person" onClick={()=>{setAvatar("workerMan");setQuick(r)}}><PersonAvatar/><span><strong>{r.fullName}</strong><small>{r.phone??(r.workMode==="rotation"?"Вахта":"Местный персонал")}</small></span></button>;
    if(c.id==="object"&&r.objectId)return <Link className="operis-cell-link" href={`/objects/${r.objectId}?tab=workforce`}>{value(r,c.id)}</Link>;
    if(c.id==="state")return <Dot tone={r.status==="dismissed"?"neutral":absent(r)?"warn":operationalState(r)==="Ожидает выхода"?"neutral":"good"}>{value(r,c.id)}</Dot>;
    if(c.id==="today")return <><Dot tone={todayStateTone(r)}>{value(r,c.id)}</Dot>{r.todayShiftTime&&<small className="operis-cell-sub">{r.todayShiftTime}</small>}</>;
    if(c.id==="documents")return <Dot tone={r.employmentDocumentsStatus==="completed"?"good":r.employmentDocumentsStatus?"warn":"neutral"}>{value(r,c.id)}</Dot>;
    if(c.id==="ppe")return <Dot tone={Number(r.ppeRequiredCount)>Number(r.ppeIssuedCount??0)?"warn":"neutral"}>{value(r,c.id)}</Dot>;
    return <span title={value(r,c.id)}>{value(r,c.id)}</span>;
  }
  function renderRow(r:WorkerRow){return <tr key={r.id} className={selected.has(r.id)?"is-selected":""} onClick={e=>{if(!(e.target as HTMLElement).closest("a,button,input")){setAvatar("workerMan");setQuick(r)}}}>
    <td className="operis-check-cell"><input type="checkbox" aria-label={`Выбрать ${r.fullName}`} checked={selected.has(r.id)} onChange={()=>toggleSelection(r.id)}/></td>
    {columns.map(c=><td key={c.id} style={sticky(c)}>{renderCell(r,c)}</td>)}
    <td className="operis-actions-cell"><button className="icon-button" aria-label={`Действия: ${r.fullName}`} aria-expanded={menu===r.id} onClick={()=>{setMenu(menu===r.id?null:r.id);setPopup("")}}><Ellipsis size={18}/></button>{menu===r.id&&<div className="operis-row-menu"><button onClick={()=>{setAvatar("workerMan");setQuick(r);setMenu(null)}}>Быстрый просмотр</button><Link href={`/workers/${r.id}`}>Открыть карточку</Link><Link href={`/workers/${r.id}?tab=documents`}>Документы</Link>{sensitive&&<Link href={`/workers/${r.id}?tab=accruals`}>Расчёты</Link>}</div>}</td>
  </tr>}
  function renderGroups(items:WorkerRow[],level=0,path=""):React.ReactNode{
    const group=level===0?view.group:view.subgroup;if(!group)return items.map(renderRow);
    const map=new Map<string,WorkerRow[]>();for(const r of items){const label=value(r,group);map.set(label,[...(map.get(label)??[]),r])}
    return Array.from(map).map(([label,members])=>{const id=JSON.stringify([path,group,label]);return <Fragment key={id}><tr className="operis-group-row"><td colSpan={columns.length+2}><button style={{paddingLeft:level?32:12}} aria-expanded={!collapsed.has(id)} onClick={()=>setCollapsed(s=>{const n=new Set(s);if(n.has(id))n.delete(id);else n.add(id);return n})}><ChevronRight size={16} className={collapsed.has(id)?"":"is-open"}/><span>{label}</span><small>{members.length} на странице</small>{members.some(workerNeedsAttention)&&<em>{members.filter(workerNeedsAttention).length} требуют внимания</em>}</button></td></tr>{!collapsed.has(id)&&(level===0&&view.subgroup?renderGroups(members,1,id):members.map(renderRow))}</Fragment>})
  }
  return <div className="operis-worker-registry" ref={wrapper}>
    <div className="operis-registry-crumb">Операции <ChevronRight size={12}/> Персонал объектов</div>
    <header className="operis-registry-header"><div><h1>Сотрудники</h1><p>Персонал, назначения и состояние работы</p></div><div className="operis-header-actions"><button className="button" onClick={()=>exportCsv(filtered,columns)}><Download size={15}/> Экспорт</button>{canEdit&&<><button className="button" onClick={onImport}><Upload size={15}/> Импорт</button><button className="button primary" onClick={onCreate}><Plus size={16}/> Добавить сотрудника</button></>}</div></header>
    <nav className="operis-registry-tabs" aria-label="Состояние сотрудников">{TABS.map(t=><button key={t.id} className={tab===t.id?"active":""} aria-current={tab===t.id?"page":undefined} onClick={()=>{setTab(t.id);setPage(1);setSelected(new Set())}}>{t.label}<span>{searched.filter(r=>matchesTab(r,t.id)).length}</span></button>)}</nav>
    <div className="operis-registry-toolbar"><label className="operis-registry-search"><Search size={16}/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);setSelected(new Set())}} placeholder="Имя, телефон, объект…" aria-label="Поиск сотрудников"/>{query&&<button aria-label="Очистить поиск" onClick={()=>setQuery("")}><X size={14}/></button>}</label>
      <select aria-label="Быстрый фильтр по объекту" value={filters.object} onChange={e=>{setFilters({...filters,object:e.target.value});setPage(1);setSelected(new Set())}}><option value="">Все объекты</option>{choices("object").map(x=><option key={x}>{x}</option>)}</select>
      <button className={"button "+(popup==="filters"?"is-active":"")} onClick={()=>changePopup("filters")}><Filter size={15}/> Фильтры{Object.values(filters).filter(Boolean).length>0&&<span className="operis-count">{Object.values(filters).filter(Boolean).length}</span>}</button>
      <div className="operis-toolbar-spacer"/>
      <button className="button" onClick={()=>changePopup("views")} aria-expanded={popup==="views"}><Layers3 size={15}/>{view.name}<ChevronDown size={14}/></button><button className="button" onClick={()=>changePopup("groups")}><Settings2 size={15}/> Группировка</button><button className="button" onClick={()=>changePopup("columns")}><Columns3 size={15}/> Колонки</button>
    </div>
    {Object.values(filters).some(Boolean)&&<div className="operis-filter-chips">{Object.entries(filters).filter(([,v])=>v).map(([k,v])=><button key={k} onClick={()=>{setFilters({...filters,[k]:""});setSelected(new Set())}}>{v}<X size={12}/></button>)}<button onClick={()=>{setFilters({object:"",manager:"",specialty:"",mode:"",state:""});setPage(1);setSelected(new Set())}}>Сбросить фильтры</button></div>}
    {popup&&<section className={`operis-registry-popover ${popup}`} aria-label={popup==="columns"?"Настройка колонок":popup==="groups"?"Настройка группировки":popup==="views"?"Представления реестра":"Дополнительные фильтры"}>
      <div className="operis-popover-head"><strong>{popup==="columns"?"Колонки таблицы":popup==="groups"?"Группировка":popup==="views"?"Представления":"Фильтры"}</strong><button className="icon-button" aria-label="Закрыть настройки" onClick={()=>setPopup("")}><X size={16}/></button></div>
      {popup==="columns"&&<><p>Выберите данные, порядок и закрепление.</p><div className="operis-column-list">{[...view.columns,...allowed.map(x=>x.id).filter(id=>!view.columns.includes(id))].map(id=>{const c=allowed.find(x=>x.id===id);if(!c)return null;return <div key={id}><label><input type="checkbox" disabled={id==="person"} checked={view.columns.includes(id)} onChange={()=>updateView({columns:view.columns.includes(id)?view.columns.filter(x=>x!==id):[...view.columns,id],pinned:view.pinned.filter(x=>x!==id)})}/>{c.label}</label><button className={"icon-button "+(view.pinned.includes(id)?"is-active":"")} disabled={!view.columns.includes(id)} title="Закрепить колонку" aria-label={`Закрепить: ${c.label}`} aria-pressed={view.pinned.includes(id)} onClick={()=>updateView({pinned:view.pinned.includes(id)?view.pinned.filter(x=>x!==id):[...view.pinned,id]})}><Pin size={13}/></button><button className="icon-button" aria-label={`Выше: ${c.label}`} disabled={!view.columns.includes(id)||view.columns.indexOf(id)===0} onClick={()=>moveColumn(id,-1)}><ArrowUp size={13}/></button><button className="icon-button" aria-label={`Ниже: ${c.label}`} disabled={!view.columns.includes(id)||view.columns.indexOf(id)===view.columns.length-1} onClick={()=>moveColumn(id,1)}><ArrowDown size={13}/></button></div>})}</div><button className="button" onClick={()=>updateView({columns:BASE.columns,pinned:BASE.pinned,widths:{}})}>Восстановить основные колонки</button></>}
      {popup==="groups"&&<><p>До двух уровней. Группы можно свернуть стрелкой.</p><label>Первый уровень<select value={view.group} onChange={e=>{const group=e.target.value as GroupId;updateView({group,subgroup:group&&group!==view.subgroup?view.subgroup:""});setCollapsed(new Set())}}>{GROUPS.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><label>Второй уровень<select disabled={!view.group} value={view.subgroup} onChange={e=>{updateView({subgroup:e.target.value as GroupId});setCollapsed(new Set())}}>{GROUPS.filter(g=>!g.id||g.id!==view.group).map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><button className="button" onClick={()=>setCollapsed(new Set())}>Развернуть все группы</button></>}
      {popup==="filters"&&<>{(["manager","specialty","mode","state"] as const).map((id)=><label key={id}>{({manager:"Менеджер",specialty:"Специальность",mode:"Формат работы",state:"Состояние"})[id]}<select value={filters[id]} onChange={e=>{setFilters({...filters,[id]:e.target.value});setPage(1);setSelected(new Set())}}><option value="">Все</option>{choices(id).map(x=><option key={x}>{x}</option>)}</select></label>)}</>}
      {popup==="views"&&<><p>Колонки, ширина, закрепление и группировка.</p>{[...PRESETS.filter(v=>sensitive||v.id!=="payroll"),...custom].map(v=><div className="operis-view-option" key={v.id}><button aria-pressed={view.id===v.id} onClick={()=>{setView(v);setPopup("");setCollapsed(new Set())}}><Layers3 size={15}/>{v.name}{view.id===v.id&&<span>Выбран</span>}</button>{custom.some(x=>x.id===v.id)&&<button className="icon-button" aria-label={`Удалить вид ${v.name}`} onClick={()=>{setCustom(custom.filter(x=>x.id!==v.id));if(view.id===v.id)setView(BASE)}}><X size={14}/></button>}</div>)}<form className="operis-save-view" onSubmit={e=>{e.preventDefault();if(!viewName.trim()||custom.length>=20)return;const saved={...view,id:crypto.randomUUID(),name:viewName.trim().slice(0,40)};setCustom([...custom,saved]);setView(saved);setViewName("")}}><label>Сохранить текущий вид<input required maxLength={40} placeholder="Например, моя команда" value={viewName} onChange={e=>setViewName(e.target.value)}/></label><button className="button primary" disabled={custom.length>=20}>Сохранить</button></form><small>Настройки сохраняются в этом браузере для вашего рабочего пространства.</small></>}
    </section>}
    {storageError&&<p className="operis-storage-note">{storageError}</p>}
    <div className="operis-registry-result"><span>{filtered.length?`${(currentPage-1)*pageSize+1}–${Math.min(currentPage*pageSize,filtered.length)} из ${filtered.length}`:"0 сотрудников"}{query||Object.values(filters).some(Boolean)?` · всего доступно ${rows.length}`:""}</span><span>{view.group?`Группировка: ${GROUPS.find(g=>g.id===view.group)?.label}`:"Нажмите на сотрудника для быстрого просмотра"}</span></div>
    {selectedRows.length>0&&<div className="operis-selection-bar"><strong>Выбрано: {selectedRows.length}</strong><button className="button" onClick={()=>exportCsv(selectedRows,columns)}><Download size={14}/> Экспорт выбранных</button><button className="icon-button" aria-label="Снять выделение" onClick={()=>setSelected(new Set())}><X size={16}/></button></div>}
    <div className="operis-registry-table-wrap" ref={scroller} onScroll={()=>{if(dock.current&&scroller.current)dock.current.scrollLeft=scroller.current.scrollLeft}}>
      <table className="operis-registry-table" style={{width:Math.max(tableWidth,950)}}><colgroup><col style={{width:40}}/>{columns.map((c,i)=><col key={c.id} style={{width:widths[i]}}/>)}<col style={{width:48}}/></colgroup><thead><tr><th className="operis-check-cell"><input type="checkbox" aria-label="Выбрать страницу" checked={allChecked} ref={el=>{if(el)el.indeterminate=!allChecked&&visible.some(r=>selected.has(r.id))}} onChange={()=>setSelected(s=>{const n=new Set(s);visible.forEach(r=>{if(allChecked)n.delete(r.id);else n.add(r.id)});return n})}/></th>{columns.map(c=><th key={c.id} style={sticky(c)} aria-sort={sort.id===c.id?(sort.asc?"ascending":"descending"):"none"}><button onClick={()=>{setSort({id:c.id,asc:sort.id===c.id?!sort.asc:true});setPage(1)}}>{c.label}{sort.id===c.id&&(sort.asc?<ArrowUp size={12}/>:<ArrowDown size={12}/>)}</button><span className="operis-column-resize" onPointerDown={e=>resize(e,c)} title="Потяните для изменения ширины"/></th>)}<th aria-label="Действия"/></tr></thead><tbody>{renderGroups(visible)}{!visible.length&&<tr><td className="operis-empty" colSpan={columns.length+2}><Search size={24}/><strong>Сотрудники не найдены</strong><span>Попробуйте изменить поиск или фильтры.</span><button className="button" onClick={()=>{setQuery("");setFilters({object:"",manager:"",specialty:"",mode:"",state:""});setTab("all")}}>Сбросить поиск и фильтры</button></td></tr>}</tbody></table>
    </div>
    <footer className="operis-registry-pagination"><span>Всего: {filtered.length}</span><label>На странице<select aria-label="Сотрудников на странице" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option value={20}>20</option><option value={50}>50</option><option value={100}>100</option></select></label><button className="icon-button" disabled={currentPage===1} aria-label="Предыдущая страница" onClick={()=>{setPage(currentPage-1);wrapper.current?.scrollIntoView({block:"start"})}}><ChevronLeft size={16}/></button><span>{currentPage} / {pages}</span><button className="icon-button" disabled={currentPage===pages} aria-label="Следующая страница" onClick={()=>{setPage(currentPage+1);wrapper.current?.scrollIntoView({block:"start"})}}><ChevronRight size={16}/></button></footer>
    {showDock&&<div className="operis-horizontal-dock" ref={dock} onScroll={()=>{if(dock.current&&scroller.current)scroller.current.scrollLeft=dock.current.scrollLeft}}><div style={{width:dockWidth,height:1}}/></div>}
    {quick&&<RegistryDrawer title="Сотрудник" subtitle="Быстрый просмотр" onClose={()=>setQuick(null)} footer={<><button className="button" onClick={()=>setQuick(null)}>Закрыть</button><Link className="button primary" href={`/workers/${quick.id}`}>Подробнее<ChevronRight size={15}/></Link></>}>
      <div className="operis-quick-person"><PersonAvatar kind={avatar} size={64}/><div><h3>{quick.fullName}</h3><p>{quick.specialty??"Специальность не указана"}</p><Dot tone={quick.status==="dismissed"?"neutral":absent(quick)?"warn":operationalState(quick)==="Ожидает выхода"?"neutral":"good"}>{operationalState(quick)}</Dot></div></div>
      <section className="operis-drawer-section"><h3>Основная информация</h3><dl>{(["object","manager","phone","start","employment","mode"] as ColumnId[]).map(id=><div key={id}><dt>{COLUMNS.find(c=>c.id===id)?.label}</dt><dd>{id==="phone"&&quick.phone?<a href={`tel:${quick.phone.replace(/[^+\d]/g,"")}`}>{quick.phone}</a>:value(quick,id)}</dd></div>)}</dl></section>
      {reasons(quick).length>0&&<section className="operis-attention-note"><h3>Требует внимания</h3><ul>{reasons(quick).map(x=><li key={x}>{x}</li>)}</ul></section>}
      <section className="operis-drawer-section"><h3>Работа и обеспечение</h3><dl>{(["schedule","today","change","documents","ppe"] as ColumnId[]).map(id=><div key={id}><dt>{COLUMNS.find(c=>c.id===id)?.label}</dt><dd>{value(quick,id)}</dd></div>)}</dl></section>
      {sensitive&&<section className="operis-drawer-section"><h3>Расчёты</h3><dl>{(["rate","accrued","paid","payable"] as ColumnId[]).map(id=><div key={id}><dt>{COLUMNS.find(c=>c.id===id)?.label}</dt><dd>{value(quick,id)}</dd></div>)}</dl></section>}
    </RegistryDrawer>}
  </div>
}
