import {NextResponse} from "next/server";
import {z} from "zod";
import type {Sql} from "postgres";
import {getCurrentActor} from "@/lib/auth/server";
import {AccessDeniedError,requireCapability} from "@/lib/access/server";
import {canReadRow} from "@/lib/core/access.mjs";
import {withTenant} from "@/lib/db/client";

const statuses=["available","update_needed","prepare","requested","ready","not_required"] as const;
const createSchema=z.object({name:z.string().trim().min(2).max(300),category:z.string().trim().min(2).max(100).default("other"),required:z.boolean().default(true),status:z.enum(statuses).default("prepare"),companyDocumentId:z.string().uuid().nullable().optional(),ownerUserId:z.string().uuid().nullable().optional(),dueAt:z.string().datetime({offset:true}).nullable().optional(),notes:z.string().trim().max(2000).nullable().optional()});
const updateSchema=createSchema.partial().extend({requirementId:z.string().uuid()});
const deleteSchema=z.object({requirementId:z.string().uuid()});
type Scope={organizationId:string;ownerUserId:string|null;createdByUserId:string;teamId:string|null;regionId:string|null;clientId:string|null};
async function assertEditable(actor:NonNullable<Awaited<ReturnType<typeof getCurrentActor>>>,id:string,sql:Sql){const [row]=await sql<Scope[]>`SELECT organization_id "organizationId",owner_user_id "ownerUserId",created_by_user_id "createdByUserId",assigned_team_id "teamId",region_id "regionId",client_company_id "clientId" FROM tenders WHERE id=${id}::uuid`;if(!row||!canReadRow(actor.access,"sales.tender.edit",row,actor))throw new AccessDeniedError("sales.tender.edit");}
async function validateRefs(sql:Sql,companyDocumentId:string|null|undefined,ownerUserId:string|null|undefined){if(companyDocumentId){const [doc]=await sql`SELECT id FROM company_documents WHERE id=${companyDocumentId}::uuid AND status<>'archived'`;if(!doc)throw new Error("Документ компании не найден");}if(ownerUserId){const [member]=await sql`SELECT id FROM organization_memberships WHERE user_id=${ownerUserId}::uuid AND status='active'`;if(!member)throw new Error("Ответственный сотрудник не найден");}}

export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"sales.tender.edit");if(actor.demo)return NextResponse.json({error:"Демонстрационные данные доступны только для чтения"},{status:409});const {id}=await params;const body=createSchema.parse(await request.json());const row=await withTenant(actor.organizationId,actor.userId,async sql=>{await assertEditable(actor,id,sql);await validateRefs(sql,body.companyDocumentId,body.ownerUserId);const [created]=await sql<Array<{id:string}>>`INSERT INTO tender_document_requirements(organization_id,tender_id,company_document_id,name,category,required,status,owner_user_id,due_at,notes,created_by_user_id) VALUES(${actor.organizationId}::uuid,${id}::uuid,${body.companyDocumentId??null}::uuid,${body.name},${body.category},${body.required},${body.status},${body.ownerUserId??null}::uuid,${body.dueAt??null}::timestamptz,${body.notes??null},${actor.userId}::uuid) RETURNING id`;await sql`UPDATE tenders SET updated_at=now() WHERE id=${id}::uuid`;return created;});return NextResponse.json(row,{status:201});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте требование"},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});return NextResponse.json({error:error instanceof Error?error.message:"Internal error"},{status:500});}}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"sales.tender.edit");if(actor.demo)return NextResponse.json({error:"Демонстрационные данные доступны только для чтения"},{status:409});const {id}=await params;const body=updateSchema.parse(await request.json());await withTenant(actor.organizationId,actor.userId,async sql=>{await assertEditable(actor,id,sql);await validateRefs(sql,body.companyDocumentId,body.ownerUserId);const [current]=await sql<Array<{id:string;name:string;category:string;required:boolean;status:string;companyDocumentId:string|null;ownerUserId:string|null;dueAt:string|null;notes:string|null}>>`SELECT id,name,category,required,status,company_document_id "companyDocumentId",owner_user_id "ownerUserId",due_at::text "dueAt",notes FROM tender_document_requirements WHERE id=${body.requirementId}::uuid AND tender_id=${id}::uuid`;if(!current)throw new Error("Требование не найдено");await sql`UPDATE tender_document_requirements SET name=${body.name??current.name},category=${body.category??current.category},required=${body.required??current.required},status=${body.status??current.status},company_document_id=${body.companyDocumentId===undefined?current.companyDocumentId:body.companyDocumentId}::uuid,owner_user_id=${body.ownerUserId===undefined?current.ownerUserId:body.ownerUserId}::uuid,due_at=${body.dueAt===undefined?current.dueAt:body.dueAt}::timestamptz,notes=${body.notes===undefined?current.notes:body.notes},updated_at=now() WHERE id=${body.requirementId}::uuid`;await sql`UPDATE tenders SET updated_at=now() WHERE id=${id}::uuid`;});return NextResponse.json({ok:true});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте требование"},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});return NextResponse.json({error:error instanceof Error?error.message:"Internal error"},{status:500});}}

export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"sales.tender.edit");if(actor.demo)return NextResponse.json({error:"Демонстрационные данные доступны только для чтения"},{status:409});const {id}=await params;const body=deleteSchema.parse(await request.json());await withTenant(actor.organizationId,actor.userId,async sql=>{await assertEditable(actor,id,sql);await sql`DELETE FROM tender_document_requirements WHERE id=${body.requirementId}::uuid AND tender_id=${id}::uuid`;await sql`UPDATE tenders SET updated_at=now() WHERE id=${id}::uuid`;});return NextResponse.json({ok:true});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Некорректное требование"},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});return NextResponse.json({error:error instanceof Error?error.message:"Internal error"},{status:500});}}
