import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db/client";

const provisionItem=z.object({provider:z.enum(["client","us","not_required"]),amount:z.number().nonnegative().optional(),unit:z.string().max(40).optional(),comment:z.string().max(500).optional()});
const role=z.object({specialtyId:z.string().uuid(),count:z.number().int().positive().max(5000),qualification:z.string().max(200).optional(),experience:z.string().max(500).optional(),salaryTarget:z.number().nonnegative().optional(),salaryUnit:z.string().max(40).optional(),scheduleType:z.string().max(40).optional(),startsAt:z.string().optional(),endsAt:z.string().optional(),presenceHours:z.number().nonnegative().max(24).optional(),paidHours:z.number().nonnegative().max(24).optional(),lunchMinutes:z.number().int().nonnegative().max(300).optional(),lunchPaid:z.boolean().optional(),nightHours:z.number().nonnegative().max(24).optional(),overtimeRule:z.string().max(500).optional(),requirements:z.record(z.string(),z.json()).default({})});
const payload=z.object({title:z.string().trim().min(2).max(240),contactName:z.string().trim().max(200).optional(),contactPosition:z.string().trim().max(160).optional(),contactPhone:z.string().trim().max(80).optional(),contactEmail:z.string().trim().email().max(240).optional(),siteName:z.string().trim().max(240).optional(),location:z.string().trim().max(300).optional(),city:z.string().trim().max(120).optional(),transportAccess:z.string().trim().max(500).optional(),nearestTransport:z.string().trim().max(200).optional(),logisticsComment:z.string().trim().max(1000).optional(),startDate:z.string().date().optional(),durationText:z.string().trim().max(120).optional(),projectIndefinite:z.boolean().default(false),schedule:z.record(z.string(),z.json()).default({}),staffingRequirements:z.record(z.string(),z.json()).default({}),provision:z.record(z.string(),provisionItem).default({}),commercialLimits:z.record(z.string(),z.json()).default({}),roles:z.array(role).max(40).default([])});
function hash(token:string){return createHash("sha256").update(token).digest("hex")}
export async function GET(_:Request,{params}:{params:Promise<{token:string}>}){try{const {token}=await params;if(token.length<20)return NextResponse.json({error:"Ссылка недействительна"},{status:404});const sql=db();const [row]=await sql<Array<{payload:unknown}>>`SELECT public_request_link_read(${hash(token)}) payload`;if(!row?.payload)return NextResponse.json({error:"Ссылка недействительна или срок её действия истёк"},{status:404});return NextResponse.json(row.payload,{headers:{"cache-control":"no-store"}})}catch(error){console.error(error);return NextResponse.json({error:"Форма временно недоступна"},{status:500})}}
export async function POST(request:Request,{params}:{params:Promise<{token:string}>}){try{const {token}=await params;const body=payload.parse(await request.json());const sql=db();const [row]=await sql<Array<{id:string}>>`SELECT public_request_link_submit(${hash(token)},${sql.json(body)}) id`;return NextResponse.json({requestId:row.id},{status:200})}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте заполненные поля",issues:error.issues},{status:400});if(error instanceof Error&&/INVALID_PUBLIC_LINK/.test(error.message))return NextResponse.json({error:"Ссылка недействительна или срок её действия истёк"},{status:404});console.error(error);return NextResponse.json({error:"Не удалось отправить форму"},{status:500})}}
