import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
function load(path,deps={}){const compiled=ts.transpileModule(fs.readFileSync(new URL('../'+path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};new Function('exports','require',compiled)(exports,name=>deps[name]??require(name));return exports;}
const intake=load('lib/commercial/request-intake.ts');
const {mergeRequestSection}=load('lib/commercial/request-section.ts',{'@/lib/commercial/request-intake':intake});
const {assertEditVersion,EditConflictError}=load('lib/commercial/edit-conflict.ts');
const current=()=>({title:'Сохранённая заявка',clientId:'client',location:'Объект',ownerUserId:'owner',comments:'Заметка',roles:[{id:'role',count:5,requirements:{certificates:'Высота'}}],schedule:{paidHours:11},lunchPaid:false,observerUserIds:['observer'],intake:{...intake.emptyRequestIntake(),companyName:'Клиент',contact:{...intake.emptyRequestIntake().contact,name:'Анна'},schedule:{...intake.emptyRequestIntake().schedule,paidHours:11},provision:{...intake.emptyRequestIntake().provision,housing:{provider:'client',cost:850,unit:'day',comment:'Сохранить'}}}});
test('schedule edits preserve role IDs, contacts, provision costs and responsibility',()=>{const old=current();const submitted={...old,title:'Unrelated stale value',roles:[],ownerUserId:'other',intake:{...intake.emptyRequestIntake(),schedule:{...old.intake.schedule,paidHours:9}},schedule:{paidHours:9}};const next=mergeRequestSection(old,submitted,'schedule');assert.equal(next.title,old.title);assert.equal(next.ownerUserId,old.ownerUserId);assert.deepEqual(next.roles,old.roles);assert.deepEqual(next.intake.contact,old.intake.contact);assert.deepEqual(next.intake.provision,old.intake.provision);assert.equal(next.intake.schedule.paidHours,9);});
test('quick edits preserve notes, positions and unknown logistics',()=>{const old=current();const submitted={...old,title:'Новое название',comments:null,roles:[],intake:{...intake.emptyRequestIntake(),contact:{...old.intake.contact,phone:'+79991234567'}}};const next=mergeRequestSection(old,submitted,'quick');assert.equal(next.title,'Новое название');assert.equal(next.comments,old.comments);assert.deepEqual(next.roles,old.roles);assert.deepEqual(next.intake.provision,old.intake.provision);assert.equal(next.intake.contact.phone,'+79991234567');});
test('position edits update volume without clearing contact or commercial values',()=>{const old=current();const submitted={...old,roles:[{...old.roles[0],count:8}],intake:{...old.intake,volume:{...old.intake.volume,guaranteedHours:100}}};const next=mergeRequestSection(old,submitted,'need');assert.equal(next.roles[0].id,'role');assert.equal(next.roles[0].count,8);assert.equal(next.intake.volume.guaranteedHours,100);assert.deepEqual(next.intake.contact,old.intake.contact);});
test('stale versions fail and the same server version is accepted',()=>{assert.throws(()=>assertEditVersion('old','new'),EditConflictError);assert.doesNotThrow(()=>assertEditVersion('new','new'));assert.doesNotThrow(()=>assertEditVersion(undefined,'new'));});

test('block edits retain extra historical intake fields while replacing edited arrays',()=>{const old=current();old.intake.legacyReview={reference:'keep'};old.intake.schedule.legacyNotes='keep';old.intake.provision.housing.legacyCostSource='keep';const submitted={...old,intake:{...intake.emptyRequestIntake(),schedule:{...intake.emptyRequestIntake().schedule,paidHours:9}}};const next=mergeRequestSection(old,submitted,'schedule');assert.deepEqual(next.intake.legacyReview,old.intake.legacyReview);assert.equal(next.intake.schedule.legacyNotes,'keep');assert.equal(next.intake.provision.housing.legacyCostSource,'keep');assert.equal(next.intake.schedule.paidHours,9);});
