import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
const base=process.env.BASE_URL??'http://127.0.0.1:4024';const dir='/tmp/operis-templates-qa';await mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true});
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'oo_workspace_mode',value:'demo',url:base},{name:'oo_demo_role',value:'director',url:base}]);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/templates/',{waitUntil:'networkidle'});const root=page.locator('.operis-patterns.operis-data-registry');const catalog=root.getByRole('navigation',{name:'Разделы шаблонов'});
 assert(await page.getByRole('link',{name:'Шаблоны интерфейса',exact:true}).isVisible());assert.equal(await root.locator('tbody tr').count(),5);
 await root.getByRole('textbox',{name:'Поиск в образце'}).fill('несуществующее');assert(await root.getByText('Записей не найдено',{exact:true}).isVisible());await root.getByRole('button',{name:'Очистить поиск',exact:true}).click();
 await root.locator('.operis-shared-registry-controls').getByRole('button',{name:'Направление',exact:true}).click();await root.getByRole('option',{name:'Направление А',exact:true}).click();assert(await root.getByRole('button',{name:'Сбросить Направление'}).isVisible());await root.getByRole('button',{name:'Сбросить всё'}).click();
 await root.getByRole('button',{name:'Фильтры',exact:false}).click();await root.locator('.operis-shared-registry-controls').getByRole('button',{name:'Состояние',exact:true}).click();await root.getByRole('option',{name:'Завершено',exact:true}).click();assert.equal(await root.locator('tbody tr').count(),4);await root.getByRole('button',{name:'Сбросить всё'}).click();await root.getByRole('button',{name:'Закрыть фильтры'}).click();
 await root.getByRole('button',{name:'Колонки',exact:true}).click();await root.getByRole('checkbox',{name:'Контакт',exact:true}).uncheck();await root.getByRole('spinbutton',{name:'Ширина: Название',exact:true}).fill('350');await root.getByRole('button',{name:'Закрепить: Название'}).click();await root.getByRole('button',{name:'Сохранить мой вид',exact:true}).click();await root.getByRole('button',{name:'Закрыть настройки'}).click();assert(!(await root.locator('thead').innerText()).includes('Контакт'));
 await page.reload({waitUntil:'networkidle'});await root.getByRole('button',{name:'Представление',exact:true}).click();await root.getByRole('option',{name:'Мой вид 1',exact:true}).click();assert(!(await root.locator('thead').innerText()).includes('Контакт'));assert.equal(await root.locator('thead th').nth(1).evaluate(el=>getComputedStyle(el).position),'sticky');await root.getByRole('button',{name:'Представление',exact:true}).click();await root.getByRole('option',{name:'Основной',exact:true}).click();
 await root.getByRole('button',{name:'Группировка',exact:true}).click();await root.getByRole('button',{name:'Группировать по',exact:true}).click();await root.getByRole('option',{name:'Направление',exact:true}).click();await root.getByRole('button',{name:'Закрыть настройки'}).click();const group=root.locator('.pattern-group button').first();assert(await group.isVisible());await group.click();assert.equal(await group.getAttribute('aria-expanded'),'false');await group.click();
 await root.getByRole('button',{name:'Следующая страница'}).click();assert(await root.getByText('Страница 2 из 3',{exact:true}).isVisible());
 await root.getByRole('button',{name:'Новая запись',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();assert(await dialog.getByRole('alert').isVisible());await dialog.getByRole('textbox',{name:'Название записи',exact:true}).fill('Созданная условная запись');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();assert.equal(await dialog.count(),0);await root.getByRole('textbox',{name:'Поиск в образце'}).fill('Созданная условная запись');assert(await root.getByText('Созданная условная запись',{exact:true}).isVisible());await root.getByRole('button',{name:'Очистить поиск',exact:true}).click();
 await catalog.getByRole('button',{name:'Доски',exact:true}).click();const card=root.locator('.pattern-board-card').first();await card.locator('select').selectOption('done');assert.equal(await root.locator('.pattern-board-column').last().locator('.pattern-board-card').count(),1);await card.locator('.pattern-cell-open').click();assert(await dialog.isVisible());await page.keyboard.press('Escape');assert.equal(await dialog.count(),0);
 await catalog.getByRole('button',{name:'Карточки',exact:true}).click();assert(await root.locator('.pattern-entity-summary').isVisible());await root.getByRole('button',{name:'Связанные записи',exact:true}).click();assert.equal(await root.locator('.pattern-entity-summary').count(),0);assert(await root.locator('.pattern-entity-full table').isVisible());await root.getByRole('button',{name:'Обзор',exact:true}).click();await root.getByRole('button',{name:'Редактировать',exact:true}).click();await dialog.locator('textarea').fill('Новый комментарий');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();assert(await root.getByText('Новый комментарий',{exact:true}).isVisible());
 await catalog.getByRole('button',{name:'Аналитика',exact:true}).click();await root.getByRole('combobox',{name:'Период аналитики'}).selectOption('week');assert.equal(await root.locator('.pattern-metrics>div').first().locator('strong').innerText(),'5');
 await catalog.getByRole('button',{name:'Спецэкраны',exact:true}).click();const oldMonth=await root.locator('.pattern-month strong').innerText();await root.getByRole('button',{name:'Следующий месяц',exact:true}).click();assert.notEqual(await root.locator('.pattern-month strong').innerText(),oldMonth);await root.getByRole('button',{name:'Календарь',exact:true}).click();assert(await root.locator('.pattern-calendar').isVisible());
 for(const theme of ['light','dark'])for(const label of ['Таблицы','Доски','Карточки','Формы и панели','Аналитика','Спецэкраны','Элементы','Карта внедрения']){await catalog.getByRole('button',{name:label,exact:true}).click();await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);assert(await root.isVisible());await page.screenshot({path:dir+'/'+theme+'-'+label.replaceAll(' ','_')+'.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))}
 for(const width of [1920,1024,768,390]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(250);for(const label of ['Таблицы','Карточки','Элементы']){await catalog.getByRole('button',{name:label,exact:true}).click();const bounds=await root.boundingBox();assert(bounds.x+bounds.width<=width+1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:dir+'/'+width+'-'+label+'.png'})}}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'passed',checks:'navigation/search/filter/columns/width/pin/saved-view/reload/group/page/create/validation/board-move/drawer/entity-edit/overview-only-summary/period/month/8-tabs/themes/5-widths',errors}));
}finally{await browser.close()}
