import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
const base=process.env.BASE_URL??'http://127.0.0.1:4024';const dir='/tmp/operis-templates-qa';await mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true});
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'oo_workspace_mode',value:'demo',url:base},{name:'oo_demo_role',value:'director',url:base}]);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/templates/',{waitUntil:'networkidle'});const root=page.locator('.operis-patterns.operis-data-registry');const catalog=root.getByRole('navigation',{name:'Разделы шаблонов'});const dialog=page.getByRole('dialog');
 assert(await page.getByRole('link',{name:'Шаблоны интерфейса',exact:true}).isVisible());assert.equal(await root.locator('tbody tr').count(),20);
 await root.getByRole('textbox',{name:'Поиск в образце'}).fill('несуществующее');assert(await root.getByText('Записей не найдено',{exact:true}).isVisible());await root.getByRole('button',{name:'Очистить поиск',exact:true}).click();
 await root.locator('.operis-shared-registry-controls').getByRole('button',{name:'Направление',exact:true}).click();await root.getByRole('option',{name:'Направление А',exact:true}).click();assert(await root.getByRole('button',{name:'Сбросить Направление'}).isVisible());await root.getByRole('button',{name:'Сбросить всё'}).click();
 await root.getByRole('button',{name:'Фильтры',exact:true}).click();await root.getByRole('button',{name:'Добавить условие',exact:true}).click();await root.getByRole('button',{name:'Поле условия 1',exact:true}).click();await root.getByRole('option',{name:'Сумма',exact:true}).click();await root.getByRole('button',{name:'Оператор условия 1',exact:true}).click();await root.getByRole('option',{name:'Больше',exact:true}).click();await root.getByRole('spinbutton',{name:'Значение: Сумма',exact:true}).fill('100000');assert(await root.locator('.pattern-active-filters button').count()>0);await root.getByRole('button',{name:'Применить',exact:true}).click();
 await root.getByRole('button',{name:'Группировка',exact:true}).click();await root.getByRole('button',{name:'Первый уровень группировки',exact:true}).click();await root.getByRole('option',{name:'Ответственный',exact:true}).click();await root.getByRole('button',{name:'Второй уровень группировки',exact:true}).click();await root.getByRole('option',{name:'Направление',exact:true}).click();await root.getByRole('button',{name:'Закрыть группировку'}).click();assert(await root.locator('.pattern-group-level-1').count()>0);assert(await root.locator('.pattern-group-level-2').count()>0);
 await root.getByRole('button',{name:'Колонки',exact:true}).click();assert(await dialog.getByRole('heading',{name:'Колонки таблицы'}).isVisible());await dialog.getByRole('checkbox',{name:'Контакт',exact:true}).uncheck();await dialog.getByRole('button',{name:'Закрепить: Ответственный'}).click();await dialog.getByRole('button',{name:'Готово',exact:true}).click();assert(!(await root.locator('thead').innerText()).includes('Контакт'));
 const resize=root.getByRole('separator',{name:'Изменить ширину: Название'});const before=await root.locator('thead th').nth(1).boundingBox();await resize.focus();await page.keyboard.press('ArrowRight');const after=await root.locator('thead th').nth(1).boundingBox();assert(after.width>before.width);
 await root.getByRole('button',{name:'Представление',exact:true}).click();await root.getByText('Сохранить текущий вид',{exact:true}).click();await dialog.getByRole('textbox',{name:'Название'}).fill('Мой контроль');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await root.getByRole('button',{name:'Представление',exact:true}).click();assert(await root.getByText('Мой контроль',{exact:true}).isVisible());await page.keyboard.press('Escape');
 await root.getByRole('checkbox',{name:'Выбрать страницу'}).check();assert(await root.getByText(/Выбрано:/).isVisible());assert(await root.getByRole('button',{name:/Выбрать все .* результатов/}).isVisible());await root.getByRole('button',{name:/Выбрать все .* результатов/}).click();await root.getByRole('button',{name:'Редактировать',exact:true}).click();assert(await dialog.getByRole('heading',{name:'Массовое редактирование'}).isVisible());await dialog.getByRole('button',{name:'Отмена',exact:true}).click();
 assert(await root.getByRole('button',{name:'Экспорт',exact:true}).isVisible());assert(await root.getByRole('button',{name:'Импорт',exact:true}).isVisible());assert(await root.getByRole('button',{name:'Добавить запись',exact:true}).isVisible());
 await root.getByRole('button',{name:'Добавить запись',exact:true}).click();await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();assert(await dialog.getByRole('alert').isVisible());await dialog.getByRole('textbox',{name:'Название записи',exact:true}).fill('Созданная условная запись');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();assert.equal(await dialog.count(),0);
 await catalog.getByRole('button',{name:'Доски',exact:true}).click();const card=root.locator('.pattern-board-card').first();await card.locator('select').selectOption('done');assert.equal(await root.locator('.pattern-board-column').last().locator('.pattern-board-card').count(),1);await card.locator('.pattern-cell-open').click();assert(await dialog.isVisible());await page.keyboard.press('Escape');assert.equal(await dialog.count(),0);
 await catalog.getByRole('button',{name:'Карточки',exact:true}).click();assert(await root.locator('.pattern-entity-summary').isVisible());await root.getByRole('button',{name:'Связанные записи',exact:true}).click();assert.equal(await root.locator('.pattern-entity-summary').count(),0);assert(await root.locator('.pattern-entity-full table').isVisible());
 await catalog.getByRole('button',{name:'Аналитика',exact:true}).click();await root.getByRole('combobox',{name:'Период аналитики'}).selectOption('week');assert.equal(await root.locator('.pattern-metrics>div').first().locator('strong').innerText(),'5');
 await catalog.getByRole('button',{name:'Спецэкраны',exact:true}).click();const oldMonth=await root.locator('.pattern-month strong').innerText();await root.getByRole('button',{name:'Следующий месяц',exact:true}).click();assert.notEqual(await root.locator('.pattern-month strong').innerText(),oldMonth);
 for(const theme of ['light','dark'])for(const label of ['Таблицы','Доски','Карточки','Формы и панели','Аналитика','Спецэкраны','Элементы','Карта внедрения']){await catalog.getByRole('button',{name:label,exact:true}).click();await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);assert(await root.isVisible());await page.screenshot({path:dir+'/'+theme+'-'+label.replaceAll(' ','_')+'.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))}
 for(const width of [1920,1024,768,390]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(250);for(const label of ['Таблицы','Карточки','Элементы']){await catalog.getByRole('button',{name:label,exact:true}).click();const bounds=await root.boundingBox();assert(bounds.x+bounds.width<=width+1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:dir+'/'+width+'-'+label+'.png'})}}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'passed',checks:'registry-v2/search/dropdown/advanced-filter/2-level-group/drawer-columns/resize/saved-view/mass-actions/header-actions/create/board/entity/analytics/special/themes/responsive',errors}));
}finally{await browser.close()}
