import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { chromium } from "playwright";
const base=process.env.BASE_URL??"http://127.0.0.1:3000";
const artifacts=process.env.QA_ARTIFACT_DIR??"/tmp/operis-registry-qa";
await mkdir(artifacts,{recursive:true});
const browser=await chromium.launch({headless:true});
try {
const context=await browser.newContext({viewport:{width:1440,height:800},acceptDownloads:true});await context.addCookies([{name:'oo_workspace_mode',value:'demo',url:base},{name:'oo_demo_role',value:'director',url:base}]);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`${base}/workers`,{waitUntil:'networkidle'});const r=page.locator('.operis-worker-registry');assert.equal(await r.locator('tbody tr').count(),20);assert.equal(await page.locator('[data-nextjs-dialog]').count(),0);const checks=['loads/no hydration errors','20 rows in natural page scroll'];
async function selectChoice(label,value){await r.getByRole('button',{name:label,exact:true}).click();await r.getByRole('option',{name:value,exact:true}).click();}
await r.getByRole('button',{name:'Быстрый фильтр по объекту'}).click();await page.screenshot({path:`${artifacts}/object-choice.png`});await page.keyboard.press('ArrowDown');await page.keyboard.press('Escape');assert(await r.getByRole('button',{name:'Быстрый фильтр по объекту'}).evaluate(node=>node===document.activeElement));
await r.getByRole('button',{name:'Фильтры',exact:false}).click();const settings=r.locator('#worker-registry-settings');assert.equal(await settings.evaluate(node=>getComputedStyle(node).position),'relative');assert((await settings.boundingBox()).y+(await settings.boundingBox()).height<=(await r.locator('.operis-registry-table-wrap').boundingBox()).y);await page.screenshot({path:`${artifacts}/inline-filters.png`});await r.getByRole('button',{name:'Закрыть настройки'}).click();
await selectChoice('Быстрый фильтр по объекту','РЦ Северный');assert((await r.locator('tbody .operis-person').count())>0);await selectChoice('Быстрый фильтр по объекту','Все объекты');checks.push('anchored searchable object choice');
await r.getByRole('button',{name:'Группировка',exact:true}).click();await selectChoice('Первый уровень','Менеджер');await selectChoice('Второй уровень','Объект');await r.getByRole('button',{name:'Закрыть настройки'}).click();assert((await r.locator('.operis-group-row').count())>2);const firstGroup=r.locator('.operis-group-row button').first();await firstGroup.click();assert.equal(await firstGroup.getAttribute('aria-expanded'),'false');await firstGroup.click();await page.screenshot({path:`${artifacts}/grouped.png`});checks.push('two levels / SVG collapse');
await r.getByRole('button',{name:'Колонки',exact:true}).click();await r.getByLabel('Телефон',{exact:true}).check();await r.getByRole('button',{name:'Закрепить: Телефон'}).click();await r.getByRole('button',{name:'Закрыть настройки'}).click();assert((await r.locator('th').allTextContents()).some(x=>x.includes('Телефон')));const resize=r.locator('.operis-column-resize').first();const bounds=await resize.boundingBox();await page.mouse.move(bounds.x+3,bounds.y+6);await page.mouse.down();await page.mouse.move(bounds.x+53,bounds.y+6);await page.mouse.up();checks.push('column visibility / pin / resize');
await r.getByRole('button',{name:'Основной',exact:false}).click();await r.getByRole('button',{name:'Сохранить текущий вид…',exact:true}).click();await r.getByLabel('Сохранить текущий вид').fill('Проверка команды');await r.getByRole('button',{name:'Сохранить',exact:true}).click();await page.reload({waitUntil:'networkidle'});assert((await r.getByRole('button',{name:'Проверка команды',exact:false}).count())>0);await r.getByRole('button',{name:'Проверка команды',exact:false}).click();await r.getByRole('button',{name:'Удалить вид Проверка команды'}).click();await page.keyboard.press('Escape');checks.push('custom view persists / deletes');
await r.getByLabel('Поиск сотрудников').fill('Ермаков');assert.equal(await r.locator('tbody .operis-person').count(),1);await r.getByLabel('Выбрать страницу').check();assert((await r.locator('.operis-selection-bar').count())===1);const download=page.waitForEvent('download');await r.getByRole('button',{name:'Экспорт выбранных'}).click();assert.equal((await download).suggestedFilename(),'operis-workers.csv');await r.getByLabel('Поиск сотрудников').fill('невозможныйрезультат123');assert.equal(await r.locator('.operis-selection-bar').count(),0);assert(await r.getByText('Сотрудники не найдены').isVisible());await r.getByRole('button',{name:'Сбросить поиск и фильтры'}).click();checks.push('search / empty result / selection export / hidden selection cleared');
await r.locator('.operis-person').first().click();let drawer=page.getByRole('dialog');assert.equal(Math.round((await drawer.boundingBox()).width),560);await page.screenshot({path:`${artifacts}/quick-view.png`});const details=await drawer.getByRole('link',{name:'Подробнее'}).getAttribute('href');assert(/^\/workers\//.test(details));await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);await r.getByRole('button',{name:'Добавить сотрудника'}).click();drawer=page.getByRole('dialog');assert.equal(Math.round((await drawer.boundingBox()).width),560);await drawer.getByRole('button',{name:'Создать сотрудника'}).click();assert(await drawer.getByText('Укажите ФИО').isVisible());await page.screenshot({path:`${artifacts}/create.png`});await page.keyboard.press('Escape');checks.push('quick / create same 560px / validation / Escape');
await r.getByRole('button',{name:'Основной',exact:false}).click();await r.getByRole('button',{name:'Графики и смены',exact:true}).click();assert((await r.locator('th').allTextContents()).some(x=>x.includes('Сегодня')));await r.locator('[aria-label^="Действия:"]').first().click();assert(await r.getByRole('link',{name:'Открыть карточку',exact:true}).isVisible());assert((await r.getByRole('link',{name:'Расчёты',exact:true}).getAttribute('href')).endsWith('tab=accruals'));checks.push('schedule preset / row menu valid routes');
await context.addCookies([{name:'oo_demo_role',value:'recruiter',url:base}]);await page.goto(`${base}/workers`,{waitUntil:'networkidle'});assert.equal(await r.getByRole('button',{name:'Добавить сотрудника'}).count(),0);await r.getByRole('button',{name:'Колонки',exact:true}).click();assert.equal(await r.getByLabel('Начислено',{exact:true}).count(),0);await r.getByRole('button',{name:'Закрыть настройки'}).click();await r.getByRole('button',{name:'Основной',exact:false}).click();assert.equal(await r.getByRole('button',{name:'Расчёты',exact:true}).count(),0);await page.keyboard.press('Escape');checks.push('recruiter cannot create/import or expose financial columns/preset');
await page.goto(`${base}/references/operis-ui-standard.html`,{waitUntil:'networkidle'});await page.getByRole('button',{name:'＋ Добавить сотрудника'}).click();assert.equal(Math.round((await page.getByRole('dialog').boundingBox()).width),560);await page.keyboard.press('Escape');checks.push('offline standard HTML demo drawer');assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,errors}));} finally { await browser.close(); }
