import { notFound } from "next/navigation";
import { requireActor } from "@/lib/auth/server";
import { getCommercialProposalDetail, proposalPresentation } from "@/lib/commercial/proposal-document";
import { ProposalPrintButton } from "@/components/ProposalPrintButton";
import { rub } from "@/lib/ui/format";

const unitLabels:Record<string,string>={hour:"чел./час",shift:"чел./смена",unit:"единица",worker_month:"чел./месяц",project_month:"проект/месяц",project_fixed:"проект",mixed:"сдельно",piece:"за единицу",piecework:"сдельно"};

export default async function ProposalPrintPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const actor=await requireActor();const proposal=await getCommercialProposalDetail(actor,id);if(!proposal)notFound();
  const content=proposal.content;const roles=content.roles??[];const presentation=proposalPresentation(content);const manager=content.manager;
  const showNet=presentation.priceDisplay!=="gross_only";const showGross=presentation.priceDisplay!=="net_only";
  return <main className="proposal-print-page" style={{"--accent":presentation.accent} as React.CSSProperties}>
    <style>{`
      body{background:#eef1f4;margin:0;font-family:Arial,Helvetica,sans-serif;color:#202426}.proposal-print-page{--accent:#183d34;max-width:920px;min-height:1180px;margin:28px auto;background:#fff;box-shadow:0 8px 32px rgba(0,0,0,.08);padding:42px 50px 34px}.proposal-print-toolbar{display:flex;justify-content:flex-end;margin-bottom:26px}.proposal-print-button{border:1px solid #cfd5dc;background:#fff;padding:9px 14px;border-radius:6px;font-weight:600;cursor:pointer}.print-head{display:flex;align-items:flex-start;justify-content:space-between;padding-bottom:13px;border-bottom:2px solid #d8dcda}.print-head strong{display:block;font-size:11px;letter-spacing:.08em}.print-head span{display:block;margin-top:4px;color:#777;font-size:10px}.print-head>div:last-child{text-align:right}.print-title{padding:58px 0 30px}.print-title h1{max-width:690px;margin:0;font-family:Georgia,'Times New Roman',serif;font-size:42px;line-height:1.08;letter-spacing:-.025em}.print-title p{max-width:730px;margin:20px 0 0;color:#686d6a;font-size:13px;line-height:1.55}.print-section{margin-top:16px}.print-section h2{margin:0 0 5px;color:#33413d;font-size:11px;letter-spacing:.025em}.print-rule{height:3px;margin-bottom:7px;background:var(--accent)}.print-table{width:100%;border-collapse:collapse}.print-table th{padding:10px 12px;background:var(--accent);color:#fff;font-size:11px;text-align:left}.print-table td{padding:10px 12px;border-bottom:1px solid #eceeed;font-size:12px}.print-table td:first-child{font-weight:700}.print-note{margin:7px 0 0;color:#858a87;font-size:9px;text-align:right}.print-options{margin-top:24px}.print-options h2{padding-bottom:7px;border-bottom:1px solid #dfe2e0}.print-option-grid{display:grid;grid-template-columns:1fr 1fr}.print-option-grid div{padding:9px 12px;border-bottom:1px solid #e5e7e6;background:#f5f6f5;font-size:10px}.print-option-grid b{margin-right:8px;color:#5e6965}.print-text{margin:7px 0;color:#555d59;font-size:11px;line-height:1.55;white-space:pre-wrap}.print-cta{margin-top:22px;padding:13px 15px;background:var(--accent);color:#fff;font-family:Georgia,'Times New Roman',serif;font-size:16px;font-weight:700}.print-contact{margin-top:12px;display:flex;justify-content:center;flex-wrap:wrap;gap:7px 18px;color:#707672;font-size:9px}.print-contact strong{color:#343a37}.print-footer{margin-top:auto;padding-top:36px;color:#a0a4a2;font-size:8px;text-align:center}
      @media print{body{background:#fff}.proposal-print-page{box-shadow:none;margin:0;max-width:none;min-height:auto;padding:14mm 14mm 10mm}.proposal-print-toolbar{display:none}@page{size:A4;margin:0}}
    `}</style>
    <div className="proposal-print-toolbar"><ProposalPrintButton/></div>
    <header className="print-head"><div><strong>КОММЕРЧЕСКОЕ ПРЕДЛОЖЕНИЕ</strong><span>КП №{proposal.version}</span></div><div><strong>{content.company??proposal.client}</strong><span>{proposal.createdAt}</span></div></header>
    <div className="print-title"><h1>{presentation.documentTitle}</h1>{presentation.intro&&<p>{presentation.intro}</p>}</div>
    <section className="print-section"><h2>СТОИМОСТЬ УСЛУГ</h2><div className="print-rule"/><table className="print-table"><thead><tr><th>Специальность</th><th>Количество</th><th>Единица расчёта</th>{showNet&&<th>Без НДС</th>}{showGross&&<th>С НДС</th>}</tr></thead><tbody>{roles.map(role=><tr key={role.scenarioId}><td>{role.role}</td><td>{role.count}</td><td>{unitLabels[role.unit]??role.unit}</td>{showNet&&<td>{rub(role.rateNet)}</td>}{showGross&&<td>{rub(role.rateGross)}</td>}</tr>)}</tbody></table><div className="print-note">{showGross&&content.vatPct?`Ставка с НДС рассчитана по ставке ${content.vatPct}%. `:""}Стоимость указана в выбранной единице расчёта.</div></section>
    {presentation.showIncluded&&!!content.included?.length&&<section className="print-options"><h2>В СТОИМОСТЬ ВКЛЮЧЕНО</h2><div className="print-option-grid">{content.included.map((item,index)=><div key={`${item}-${index}`}><b>{String(index+1).padStart(2,"0")}</b>{item}</div>)}</div></section>}
    {presentation.showClientProvides&&!!content.clientProvides?.length&&<section className="print-options"><h2>ПРЕДОСТАВЛЯЕТ ЗАКАЗЧИК</h2><div className="print-option-grid">{content.clientProvides.map((item,index)=><div key={`${item}-${index}`}><b>{String(index+1).padStart(2,"0")}</b>{item}</div>)}</div></section>}
    {presentation.showTerms&&content.terms&&<section className="print-options"><h2>УСЛОВИЯ СОТРУДНИЧЕСТВА</h2><p className="print-text">{content.terms}</p>{content.additionalConditions&&<p className="print-text">{content.additionalConditions}</p>}{content.comment&&<p className="print-text">{content.comment}</p>}</section>}
    {presentation.showCta&&presentation.cta&&<div className="print-cta">{presentation.cta}</div>}
    {presentation.showManager&&manager&&<div className="print-contact"><span>Ответственный менеджер: <strong>{manager.name}</strong></span>{manager.phone&&<span>Телефон: <strong>{manager.phone}</strong></span>}{manager.email&&<span>Эл. почта: <strong>{manager.email}</strong></span>}{manager.telegram&&<span>Telegram: <strong>{manager.telegram}</strong></span>}</div>}
    <div className="print-footer">Коммерческое предложение · КП №{proposal.version}</div>
  </main>;
}
