import Link from "next/link";
import {requireActor} from "@/lib/auth/server";
import {listCommercialRates} from "@/lib/data/commercial-service";
import {PageHeader,Section,Status} from "@/components/UI";
import {rateViewLabels} from "@/lib/commercial/constants";
import {pct,rub} from "@/lib/ui/format";

export default async function Rates({searchParams}:{searchParams:Promise<{view?:string}>}){
 const {view:raw}=await searchParams;const view=raw==="calculation"||raw==="object_fact"?raw:"market";const actor=await requireActor();const rows=await listCommercialRates(actor);const filtered=rows.filter(row=>row.sourceKind===view);
 return <><PageHeader eyebrow="Коммерция → Экономика" title="База ставок" subtitle="Экономическая база знаний: рыночные ориентиры, наши исторические расчёты и фактические ставки объектов. Ориентир не подставляется в расчёт без решения пользователя." breadcrumbs={[{label:"Коммерция"},{label:"Экономика"},{label:"База ставок"}]} actions={<div className="segmented">{Object.entries(rateViewLabels).map(([key,label])=><Link key={key} className={view===key?"active":""} href={`/rates?view=${key}`}>{label}</Link>)}</div>}/>
 <Section><table className="data-table"><thead><tr><th>Специальность</th><th>Регион</th><th>Модель</th><th>{view==="market"?"Диапазон":view==="calculation"?"Ставка предложения":"Фактическая ставка"}</th><th>Персонал</th><th>Проживание</th>{view==="object_fact"&&<th>Факт маржи</th>}<th>Источник</th><th>Дата</th><th>Доверие</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td className="cell-title">{row.specialty}</td><td>{row.region}</td><td>{row.employmentModel}</td><td className="num">{view==="market"?`${rub(row.amountMin)}–${rub(row.amountMax)} / ${row.unit}`:view==="calculation"?(row.clientOfferRate!=null?rub(row.clientOfferRate):"—"):(row.actualObjectRate!=null?rub(row.actualObjectRate):"—")}</td><td>{row.workforceMode==="rotation"?"Вахта":row.workforceMode==="local"?"Местный":"—"}<span className="cell-sub">{row.workerPay!=null?`Сотруднику ${rub(row.workerPay)}`:row.grossNet}</span></td><td>{row.housingIncluded==null?"—":row.housingIncluded?"Включено":"Не включено"}</td>{view==="object_fact"&&<td className="num">{row.actualMarginPct!=null?pct(row.actualMarginPct):"—"}</td>}<td>{row.source}<span className="cell-sub">{row.comment??row.seasonality??""}</span></td><td>{row.sourceDate}</td><td><Status tone={row.confidence==="verified"?"good":"warn"}>{row.confidence}</Status></td></tr>)}</tbody></table>{!filtered.length&&<div style={{padding:20,color:"var(--muted)"}}>Для этого источника пока нет записей.</div>}</Section></>;
}
