import {NextResponse} from "next/server";
import {z} from "zod";
import {getCurrentActor} from "@/lib/auth/server";
import {AccessDeniedError,requireCapability} from "@/lib/access/server";
import {canReadRow} from "@/lib/core/access.mjs";
import {withTenant} from "@/lib/db/client";

const roleSchema=z.object({specialtyId:z.string().uuid().nullable().optional(),title:z.string().trim().min(2).max(240),count:z.number().int().positive().nullable().optional(),volume:z.number().positive().nullable().optional(),billingUnit:z.enum(["unknown","hour","shift","worker_month","unit","piecework","project","mixed"]),targetClientRate:z.number().nonnegative().nullable().optional(),notes:z.string().trim().max(2000).nullable().optional()});
const deleteSchema=z.object({roleId:z.string().uuid()});
type Scope={organizationId:string;ownerUserId:string|null;createdByUserId:string;teamId:string|null;regionId:string|null;clientId:string|null};
async function editable(actor:NonNullable<Awaited<ReturnType<typeof getCurrentActor>>>,id:string,sql:any){const [row]=await sql<Scope[]>`SELECT organization_id "organizationId",owner_user_id "ownerUserId",created_by_user_id "createdByUserId",assigned_team_id "teamId",region_id "regionId",client_company_id "clientId" FROM tenders WHERE id=${id}::uuid`;if(!row||!canReadRow(actor.access,"sales.tender.edit",row,actor))throw new AccessDeniedError("sales.tender.edit");}

export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"sales.tender.edit");if(actor.demo)return NextResponse.json({error:"Демонстрационные данные доступны только для чтения"},{status:409});const {id}=await params;const body=roleSchema.parse(await request.json());const row=await withTenant(actor.organizationId,actor.userId,async sql=>{await editable(actor,id,sql);const [created]=await sql<Array<{id:string}>>`INSERT INTO tender_roles(organization_id,tender_id,specialty_id,title,count_required,volume,billing_unit,target_client_rate,notes) VALUES(${actor.organizationId}::uuid,${id}::uuid,${body.specialtyId??null}::uuid,${body.title},${body.count??null},${body.volume??null},${body.billingUnit},${body.targetClientRate??null},${body.notes??null}) RETURNING id`;await sql`UPDATE tenders SET updated_at=now() WHERE id=${id}::uuid`;return created;});return NextResponse.json(row,{status:201});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте позицию"},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});return NextResponse.json({error:error instanceof Error?error.message:"Internal error"},{status:500});}}

export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"sales.tender.edit");if(actor.demo)return NextResponse.json({error:"Демонстрационные данные доступны только для чтения"},{status:409});const {id}=await params;const body=deleteSchema.parse(await request.json());await withTenant(actor.organizationId,actor.userId,async sql=>{await editable(actor,id,sql);const [used]=await sql`SELECT id FROM calculation_scenarios WHERE tender_role_id=${body.roleId}::uuid LIMIT 1`;if(used)throw new Error("По позиции уже есть расчёты. Удалять её нельзя");await sql`DELETE FROM tender_roles WHERE id=${body.roleId}::uuid AND tender_id=${id}::uuid`;await sql`UPDATE tenders SET updated_at=now() WHERE id=${id}::uuid`;});return NextResponse.json({ok:true});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Некорректная позиция"},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});return NextResponse.json({error:error instanceof Error?error.message:"Internal error"},{status:500});}}
