import { NextResponse } from "next/server";
import { z } from "zod";
import { AccessDeniedError, requireCapability } from "@/lib/access/server";
import { getCurrentActor } from "@/lib/auth/server";
import { withTenant } from "@/lib/db/client";

const create=z.object({changeSetId:z.string().uuid(),operation:z.enum(["move_unit","move_position","unassign"]),entityId:z.string().uuid(),targetId:z.string().uuid().nullable().optional(),reason:z.string().trim().min(3).max(500)});
const remove=z.object({id:z.string().uuid()});
async function authorize(){const actor=await getCurrentActor();if(!actor)throw new Error("UNAUTHORIZED");requireCapability(actor,"organization.unit.manage");if(actor.demo)throw new Error("DEMO");return actor}
export async function POST(request:Request){try{const actor=await authorize();const body=create.parse(await request.json());const id=await withTenant(actor.organizationId,actor.userId,async sql=>{const [set]=await sql<Array<{status:string}>>`SELECT status FROM organization_change_sets WHERE id=${body.changeSetId}::uuid FOR UPDATE`;if(!set)throw new Error("NOT_FOUND");if(set.status!=="draft")throw new Error("LOCKED");let entityType:string,changeType:string,previous:unknown,proposed:Record<string,unknown>;
if(body.operation==="move_unit"){const [row]=await sql.unsafe<Array<{id:string;parentId:string|null;name:string}>>('SELECT id,parent_id "parentId",name FROM organization_units WHERE id=$1::uuid',[body.entityId]);if(!row||!body.targetId)throw new Error("INVALID");entityType="organization_unit";changeType="move";previous={parentId:row.parentId,name:row.name};proposed={parentId:body.targetId};}
else if(body.operation==="move_position"){const [row]=await sql.unsafe<Array<{id:string;organizationUnitId:string;name:string}>>('SELECT id,organization_unit_id "organizationUnitId",name FROM staff_positions WHERE id=$1::uuid',[body.entityId]);if(!row||!body.targetId)throw new Error("INVALID");entityType="staff_position";changeType="move";previous={organizationUnitId:row.organizationUnitId,name:row.name};proposed={organizationUnitId:body.targetId};}
else{const [row]=await sql.unsafe<Array<{id:string;membershipId:string;staffPositionId:string}>>('SELECT id,membership_id "membershipId",staff_position_id "staffPositionId" FROM position_assignments WHERE id=$1::uuid AND status<>\'ended\'',[body.entityId]);if(!row)throw new Error("INVALID");entityType="position_assignment";changeType="unassign";previous=row;proposed={reason:body.reason};}
const [item]=await sql.unsafe<Array<{id:string}>>('INSERT INTO organization_change_items(organization_id,change_set_id,entity_type,change_type,entity_id,previous_value,proposed_value,impact_summary) VALUES($1::uuid,$2::uuid,$3,$4,$5::uuid,$6::jsonb,$7::jsonb,$8::jsonb) RETURNING id',[actor.organizationId,body.changeSetId,entityType,changeType,body.entityId,JSON.stringify(previous),JSON.stringify(proposed),JSON.stringify({reason:body.reason})]);return item.id});return NextResponse.json({ok:true,id},{status:201})}catch(error){return fail(error)}}
export async function DELETE(request:Request){try{const actor=await authorize();const body=remove.parse(await request.json());const rows=await withTenant(actor.organizationId,actor.userId,sql=>sql.unsafe<Array<{id:string}>>('DELETE FROM organization_change_items ci USING organization_change_sets cs WHERE ci.id=$1::uuid AND cs.id=ci.change_set_id AND cs.status=\'draft\' RETURNING ci.id',[body.id]));if(!rows.length)throw new Error("LOCKED");return NextResponse.json({ok:true})}catch(error){return fail(error)}}
function fail(error:unknown){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте операцию"},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});if(error instanceof Error&&error.message==="UNAUTHORIZED")return NextResponse.json({error:"Требуется вход"},{status:401});if(error instanceof Error&&error.message==="DEMO")return NextResponse.json({error:"В демонстрационном режиме изменения не сохраняются"},{status:409});if(error instanceof Error&&error.message==="NOT_FOUND")return NextResponse.json({error:"Пакет не найден"},{status:404});if(error instanceof Error&&error.message==="LOCKED")return NextResponse.json({error:"Изменять можно только черновик"},{status:409});if(error instanceof Error&&error.message==="INVALID")return NextResponse.json({error:"Объект операции не найден"},{status:400});console.error(error);return NextResponse.json({error:"Не удалось изменить пакет"},{status:500})}
