import {NextResponse} from "next/server";
import {z} from "zod";
import {getCurrentActor} from "@/lib/auth/server";
import {requireCapability,AccessDeniedError} from "@/lib/access/server";
import {canReadRow} from "@/lib/core/access.mjs";
import {withTenant} from "@/lib/db/client";
const schema=z.object({requestId:z.string().uuid(),scenarioIds:z.array(z.string().uuid()).min(1).max(40),validUntil:z.string().date().nullable().optional(),additionalTerms:z.string().trim().max(4000).optional()});

export async function POST(request:Request){
 try{
  const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"sales.proposal.create");requireCapability(actor,"sales.request.read");if(actor.demo)return NextResponse.json({error:"Демонстрационный набор данных доступен только для чтения."},{status:409});const body=schema.parse(await request.json());
  const proposal=await withTenant(actor.organizationId,actor.userId,async sql=>sql.begin(async tx=>{
   const [requestRow]=await tx<Array<{id:string;organizationId:string;title:string;clientId:string|null;ownerUserId:string|null;createdByUserId:string;teamId:string|null;regionId:string|null;schedule:Record<string,unknown>;vatMode:string|null}>>`SELECT id,organization_id "organizationId",title,client_company_id "clientId",owner_user_id "ownerUserId",created_by_user_id "createdByUserId",assigned_team_id "teamId",region_id "regionId",schedule_json schedule,vat_mode "vatMode" FROM requests WHERE id=${body.requestId}::uuid`;if(!requestRow)return null;if(!canReadRow(actor.access,"sales.request.read",requestRow,actor))throw new AccessDeniedError("sales.request.read");
   const scenarios=await tx<Array<{id:string;status:string;role:string;count:number;rateExVat:number;rateWithVat:number;monthlyRevenue:number}>>`SELECT cs.id,cs.status,COALESCE(s.name,rr.specialty_name,'Позиция') role,COALESCE(rr.count_required,1)::int count,COALESCE((cs.result_snapshot->>'clientRateExVat')::numeric,(cs.result_snapshot->>'clientRateHourly')::numeric,0) "rateExVat",COALESCE((cs.result_snapshot->>'clientRateWithVat')::numeric,(cs.result_snapshot->>'clientRateHourly')::numeric,0) "rateWithVat",COALESCE((cs.result_snapshot->>'monthlyRevenueWithVat')::numeric,(cs.result_snapshot->>'monthlyRevenue')::numeric,0) "monthlyRevenue" FROM calculation_scenarios cs JOIN calculations c ON c.id=cs.calculation_id LEFT JOIN request_roles rr ON rr.id=cs.request_role_id LEFT JOIN specialties s ON s.id=rr.specialty_id WHERE cs.id=ANY(${body.scenarioIds}::uuid[]) AND c.request_id=${body.requestId}::uuid`;
   if(scenarios.length!==body.scenarioIds.length)throw new Error("SCENARIO_CONTEXT");if(scenarios.some(item=>item.status!=="accepted"))throw new Error("SCENARIO_NOT_ACCEPTED");
   const [last]=await tx<Array<{version:number;id:string}>>`SELECT version,id FROM proposals WHERE request_id=${body.requestId}::uuid ORDER BY version DESC LIMIT 1`;const version=(last?.version??0)+1;
   const clientPayload={requestTitle:requestRow.title,vatMode:requestRow.vatMode,positions:scenarios.map(item=>({name:item.role,count:item.count,rateExVat:Number(item.rateExVat),rateWithVat:Number(item.rateWithVat),unit:"₽/ч"})),schedule:requestRow.schedule,additionalTerms:body.additionalTerms||null};const total=scenarios.reduce((sum,item)=>sum+Number(item.monthlyRevenue||0),0);
   const [created]=await tx<Array<{id:string;version:number;status:string}>>`INSERT INTO proposals(organization_id,request_id,version,status,scenario_ids,total_value,client_payload,valid_until,supersedes_proposal_id,created_by_user_id) VALUES(${actor.organizationId}::uuid,${body.requestId}::uuid,${version},'draft',${body.scenarioIds}::uuid[],${total},${sql.json(clientPayload)},${body.validUntil??null}::date,${last?.id??null}::uuid,${actor.userId}::uuid) RETURNING id,version,status`;
   await tx`UPDATE requests SET commercial_stage='proposal_prepared',updated_at=now() WHERE id=${body.requestId}::uuid`;
   await tx`INSERT INTO activity_events(organization_id,actor_user_id,entity_type,entity_id,verb,summary,metadata) VALUES(${actor.organizationId}::uuid,${actor.userId}::uuid,'request',${body.requestId}::uuid,'proposal.created',${`Создано коммерческое предложение v${version}`},${sql.json({requestId:body.requestId,proposalId:created.id,version,scenarioIds:body.scenarioIds})})`;
   return created;
  }));if(!proposal)return NextResponse.json({error:"Заявка не найдена"},{status:404});return NextResponse.json(proposal,{status:201});
 }catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте параметры КП",issues:error.issues},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Forbidden"},{status:403});if(error instanceof Error){const messages:Record<string,string>={SCENARIO_CONTEXT:"Один или несколько сценариев не относятся к заявке",SCENARIO_NOT_ACCEPTED:"КП можно создать только из согласованных сценариев"};if(messages[error.message])return NextResponse.json({error:messages[error.message]},{status:409});}console.error(error);return NextResponse.json({error:"Внутренняя ошибка"},{status:500});}
}
