"use client";

import { FormEvent, useState } from "react";
import { Plus, UserMinus, X } from "lucide-react";
import { useRouter } from "next/navigation";
import type { CompanyEmployeeRow, PositionAssignmentRow, StaffPositionRow } from "@/lib/organization/types";

export function AssignmentActions({ position, assignments, employees, canManage, demo }: { position: StaffPositionRow; assignments: PositionAssignmentRow[]; employees: CompanyEmployeeRow[]; canManage: boolean; demo: boolean }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const router = useRouter();
  if (!canManage) return null;
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/organization/assignments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ staffPositionId: position.id, membershipId: data.get("membershipId"), assignmentType: data.get("assignmentType"), fte: Number(data.get("fte")), effectiveFrom: data.get("effectiveFrom"), effectiveTo: data.get("effectiveTo") || null, reason: data.get("reason"), allowOverallocation: data.get("allowOverallocation") === "on" }) }); const body = await response.json(); setBusy(false); if (!response.ok) { setMessage(body.error ?? "Не удалось назначить сотрудника"); return; } setOpen(false); router.refresh(); }
  async function end(item: PositionAssignmentRow) { const reason = window.prompt(`Причина освобождения позиции сотрудником ${item.employeeName}`); if (!reason) return; const effectiveTo = new Date().toISOString().slice(0, 10); setBusy(true); const response = await fetch("/api/organization/assignments", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: item.id, effectiveTo, reason }) }); const body = await response.json(); setBusy(false); if (!response.ok) { setMessage(body.error ?? "Не удалось завершить назначение"); return; } router.refresh(); }
  return <div className="assignment-actions"><button type="button" className="button compact" onClick={() => setOpen(true)}><Plus size={14} />Назначить сотрудника</button>{assignments.map((item) => <button type="button" className="button compact danger-text" key={item.id} onClick={() => end(item)} disabled={busy || demo}><UserMinus size={14} />Освободить: {item.employeeName}</button>)}{message && <p className="form-message">{message}</p>}{open && <div className="org-modal-backdrop" role="presentation" onMouseDown={() => setOpen(false)}><section className="org-modal" role="dialog" aria-modal="true" aria-label="Новое назначение" onMouseDown={(event) => event.stopPropagation()}><header><div><strong>Назначить на позицию</strong><small>{position.name} · доступно {position.open} FTE</small></div><button type="button" className="icon-button" onClick={() => setOpen(false)} aria-label="Закрыть"><X size={16} /></button></header><form className="org-form" onSubmit={create}><label className="span-2">Сотрудник<select name="membershipId" required defaultValue=""><option value="" disabled>Выберите сотрудника</option>{employees.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.position ?? "без должности"}</option>)}</select></label><label>Тип<select name="assignmentType" defaultValue="primary"><option value="primary">Основное</option><option value="additional">Дополнительное</option><option value="acting">Исполнение обязанностей</option></select></label><label>Доля занятости<input name="fte" type="number" min="0.1" max="1" step="0.1" defaultValue="1" required /></label><label>Начало<input name="effectiveFrom" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label>Окончание<input name="effectiveTo" type="date" /></label><label className="span-2">Основание<textarea name="reason" rows={3} minLength={3} required placeholder="Перевод, совмещение, временное замещение…" /></label><label className="span-2 checkbox-line"><input name="allowOverallocation" type="checkbox" /><span>Разрешить превышение 1 FTE и ёмкости позиции (исключение будет зафиксировано)</span></label>{demo && <p className="form-message span-2">В деморежиме назначение можно просмотреть, но нельзя сохранить.</p>}{message && <p className="form-message span-2">{message}</p>}<footer className="span-2"><button type="button" className="button" onClick={() => setOpen(false)}>Отмена</button><button type="submit" className="button primary" disabled={busy || demo}>{busy ? "Сохранение…" : "Создать назначение"}</button></footer></form></section></div>}</div>;
}
