"use client";

import { FormEvent, useMemo, useState } from "react";
import type { CalculationModelOption } from "@/lib/commercial/calculation-models";
import type { ExpenseStandard, ScheduleStandard } from "@/lib/commercial/calculation-standards";

type Tab = "models"|"expenses"|"schedules"|"rules";
type FormKind = "expense"|"schedule"|null;
const tabs:[Tab,string,string][] = [["models","Модели оформления","Тип занятости и налоговая логика"],["expenses","Расходы","Затраты на сотрудника, роль и проект"],["schedules","Графики","Смены, часы и оплачиваемые перерывы"],["rules","Финансовые правила","Резерв, маржа, НДС и округление"]];
const pct=(v:unknown)=>Number.isFinite(Number(v))?`${Number(v)}%`:"—";
const baseLabels:Record<ExpenseStandard["base"],string>={per_hour:"₽ / час",per_shift:"₽ / смена",per_worker_month:"₽ / сотр. / мес.",per_worker_period:"на сотрудника",percent_of_worker_pay:"% выплаты",role_month:"₽ / позицию / мес.",role_fixed:"разово на позицию",project_month:"₽ / проект / мес.",project_fixed:"разово на проект",per_unit:"₽ / единицу"};
const scopeLabels={worker:"Сотрудник",role:"Позиция",project:"Проект"};
const now=new Date().toISOString().slice(0,10);

export function CalculationStandardsWorkspace({models,expenses:initialExpenses,schedules:initialSchedules,canManage}:{models:CalculationModelOption[];expenses:ExpenseStandard[];schedules:ScheduleStandard[];canManage:boolean}){
  const [tab,setTab]=useState<Tab>("models"),[query,setQuery]=useState(""),[selected,setSelected]=useState(models[0]?.id??"");
  const [expenses,setExpenses]=useState(initialExpenses),[schedules,setSchedules]=useState(initialSchedules),[form,setForm]=useState<FormKind>(null),[message,setMessage]=useState("");
  const visible=useMemo(()=>models.filter(m=>m.name.toLowerCase().includes(query.toLowerCase())),[models,query]);
  const active=models.find(m=>m.id===selected)||visible[0]||models[0];
  const demo=initialExpenses.some(item=>item.demo)||initialSchedules.some(item=>item.demo);
  async function save(event:FormEvent<HTMLFormElement>){
    event.preventDefault();const data=new FormData(event.currentTarget);const kind=data.get("kind") as "expense"|"schedule";const name=String(data.get("name")||"").trim();
    const base={kind,action:"create",code:String(data.get("code")||"standard"),name,active:true,effectiveFrom:String(data.get("effectiveFrom")||now),effectiveTo:null,notes:null};
    const payload=kind==="expense"?{...base,groupName:String(data.get("groupName")||"Прочие расходы"),amount:Number(data.get("amount")||0),base:String(data.get("base")||"per_worker_month"),scope:String(data.get("scope")||"worker"),amortizationMonths:data.get("amortizationMonths")?Number(data.get("amortizationMonths")):null,defaultEnabled:data.get("defaultEnabled")==="on"}:{...base,pattern:String(data.get("pattern")||""),shiftHours:Number(data.get("shiftHours")||0),breakHours:Number(data.get("breakHours")||0),breakPaid:data.get("breakPaid")==="on",shiftsPerMonth:Number(data.get("shiftsPerMonth")||0)};
    setMessage("Сохраняем…");
    const response=await fetch("/api/standards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();
    if(!response.ok){setMessage(result.error||"Не удалось сохранить норматив");return;}
    if(kind==="expense")setExpenses(current=>[result,...current.filter(item=>item.code!==result.code)]);else setSchedules(current=>[result,...current.filter(item=>item.code!==result.code)]);
    setForm(null);setMessage("Норматив сохранён как новая версия.");
  }
  const action=<button className="button primary" type="button" disabled={!canManage} title={!canManage?"У вашей роли нет права изменять нормативы":""} onClick={()=>{setForm(tab==="schedules"?"schedule":"expense");setMessage("");}}>Добавить {tab==="schedules"?"график":"расход"}</button>;
  return <div className="standards-workspace">
    <div className="summary-strip"><span>Моделей <strong>{models.length}</strong></span><span>Расходов <strong>{expenses.length}</strong></span><span>Графиков <strong>{schedules.length}</strong></span><span className={demo?"summary-warning":""}>{demo?<>Демо-данные <strong>только чтение</strong></>:<>Версия <strong>сохраняется</strong></>}</span></div>
    <div className="standards-tabs" role="tablist">{tabs.map(([id,label,note])=><button key={id} className={`standards-tab ${tab===id?"is-active":""}`} onClick={()=>{setTab(id);setForm(null);setMessage("");}} role="tab" aria-selected={tab===id}><strong>{label}</strong><small>{note}</small></button>)}</div>
    {message&&<p className="calculation-save-message">{message}</p>}
    {tab==="models"&&<div className="standards-grid"><section className="section"><div className="section-head"><div><h2>Модели оформления</h2><p>Выбираются в расчёте на дату экономики.</p></div></div><div className="standards-toolbar"><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск модели"/><span className="muted">Актуальные</span></div><div className="standards-model-list">{visible.map(m=><button key={m.id} className={`standards-model ${active?.id===m.id?"is-selected":""}`} onClick={()=>setSelected(m.id)}><span><strong>{m.name}</strong><small>{m.code} · версия {m.ruleVersion??"—"}</small></span><em>{m.rules.legalParametersVerified?"Проверено":"Демо"}</em></button>)}</div></section><section className="section standards-detail"><div className="section-head"><div><h2>{active?.name??"Модель не выбрана"}</h2><p>Параметры текущей версии и источник данных.</p></div></div>{active&&<><div className="standards-detail-meta"><span>Код <strong>{active.code}</strong></span><span>Версия <strong>{active.ruleVersion??"—"}</strong></span><span>Действует с <strong>{active.ruleEffectiveFrom??"—"}</strong></span></div><div className="standards-rule-cards"><div><small>Обязательные начисления</small><strong>{pct(active.rules.mandatoryChargePct)}</strong></div><div><small>Резерв риска</small><strong>{pct(active.rules.riskReservePct)}</strong></div><div><small>Минимальная маржа</small><strong>{pct(active.rules.minimumMarginPct)}</strong></div><div><small>НДС</small><strong>{pct(active.rules.vatPct)}</strong></div></div><div className="standards-source"><strong>{active.rules.legalParametersVerified?"Параметры проверены":"Демонстрационные параметры"}</strong><p>{active.ruleSource??"Источник не указан."}</p></div></>}</section></div>}
    {tab==="expenses"&&<section className="section"><div className="section-head"><div><h2>Группы расходов</h2><p>Активная версия автоматически попадает в новые расчёты. Ручное значение в сценарии остаётся отдельным снимком.</p></div>{action}</div>{form==="expense"&&<ExpenseForm onCancel={()=>setForm(null)} onSubmit={save}/>}<div className="request-table-wrap"><table className="data-table"><thead><tr><th>Наименование</th><th>Группа</th><th>База</th><th>Контур</th><th>Версия</th><th>Действует</th></tr></thead><tbody>{expenses.length?expenses.map(item=><tr key={item.id}><td><strong>{item.name}</strong><span className="cell-sub">{item.defaultEnabled?"Включён по умолчанию":"По выбору в расчёте"}</span></td><td>{item.groupName}</td><td>{baseLabels[item.base]}</td><td>{scopeLabels[item.scope]}</td><td>v{item.version}</td><td>{item.effectiveFrom}</td></tr>):<tr><td colSpan={6} className="muted">Нет активных расходов на выбранную дату.</td></tr>}</tbody></table></div></section>}
    {tab==="schedules"&&<section className="section"><div className="section-head"><div><h2>Шаблоны графиков</h2><p>График задаёт оплачиваемые часы и количество смен в расчётном месяце.</p></div>{action}</div>{form==="schedule"&&<ScheduleForm onCancel={()=>setForm(null)} onSubmit={save}/>}<div className="request-table-wrap"><table className="data-table"><thead><tr><th>Шаблон</th><th>Паттерн</th><th>Смена</th><th>Норма</th><th>Перерыв</th><th>Версия</th></tr></thead><tbody>{schedules.length?schedules.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.pattern}</td><td>{item.shiftHours} ч</td><td>{item.shiftsPerMonth} смены</td><td>{item.breakHours} ч · {item.breakPaid?"оплачивается":"не оплачивается"}</td><td>v{item.version}</td></tr>):<tr><td colSpan={6} className="muted">Нет активных графиков на выбранную дату.</td></tr>}</tbody></table></div></section>}
    {tab==="rules"&&<section className="section"><div className="section-head"><div><h2>Финансовые правила</h2><p>Параметры попадают в снимок каждого сценария.</p></div></div><div className="standards-rule-table"><div><span>Режим цены</span><strong>Целевая маржа / прибыль / лимит клиента</strong><small>Выбирается в сценарии</small></div><div><span>Округление</span><strong>До 1 ₽</strong><small>После полной себестоимости</small></div><div><span>НДС</span><strong>Отдельно от ставки клиента</strong><small>Показывается явно в предложении</small></div><div><span>Снимок правил</span><strong>На дату экономики</strong><small>Старая версия не меняется</small></div></div></section>}
  </div>;
}

function ExpenseForm({onCancel,onSubmit}:{onCancel:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="calculation-inline-form" onSubmit={onSubmit}><input type="hidden" name="kind" value="expense"/><label>Наименование<input className="input" name="name" required placeholder="Например, проживание"/></label><label>Код<input className="input" name="code" required placeholder="housing" pattern="[a-z0-9_-]+"/></label><label>Группа<input className="input" name="groupName" required defaultValue="Регулярное обеспечение"/></label><label>Сумма<input className="input" name="amount" type="number" min="0" step="0.01" defaultValue="0"/></label><label>База<select name="base" defaultValue="per_worker_month"><option value="per_hour">₽ / час</option><option value="per_shift">₽ / смена</option><option value="per_worker_month">₽ / сотр. / месяц</option><option value="per_worker_period">на сотрудника</option><option value="role_month">₽ / позицию / месяц</option><option value="project_month">₽ / проект / месяц</option><option value="project_fixed">разово на проект</option><option value="per_unit">₽ / единицу</option></select></label><label>Контур<select name="scope"><option value="worker">Сотрудник</option><option value="role">Позиция</option><option value="project">Проект</option></select></label><label>Дата действия<input className="input" name="effectiveFrom" type="date" defaultValue={now} required/></label><label>Амортизация, мес.<input className="input" name="amortizationMonths" type="number" min="0.1" step="0.1"/></label><label className="calculation-checkbox"><input name="defaultEnabled" type="checkbox"/> Включать по умолчанию</label><div className="calculation-inline-actions"><button className="button primary" type="submit">Сохранить версию</button><button className="button" type="button" onClick={onCancel}>Отмена</button></div></form>}
function ScheduleForm({onCancel,onSubmit}:{onCancel:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="calculation-inline-form" onSubmit={onSubmit}><input type="hidden" name="kind" value="schedule"/><label>Название<input className="input" name="name" required placeholder="Например, Вахта 30/30"/></label><label>Код<input className="input" name="code" required placeholder="watch_3030" pattern="[a-z0-9_-]+"/></label><label>Паттерн<input className="input" name="pattern" required placeholder="30/30"/></label><label>Смена, ч<input className="input" name="shiftHours" type="number" min="0.1" step="0.1" defaultValue="11" required/></label><label>Перерыв, ч<input className="input" name="breakHours" type="number" min="0" step="0.1" defaultValue="1" required/></label><label>Смен в месяц<input className="input" name="shiftsPerMonth" type="number" min="0.1" step="0.1" defaultValue="15" required/></label><label>Дата действия<input className="input" name="effectiveFrom" type="date" defaultValue={now} required/></label><label className="calculation-checkbox"><input name="breakPaid" type="checkbox"/> Перерыв оплачивается</label><div className="calculation-inline-actions"><button className="button primary" type="submit">Сохранить версию</button><button className="button" type="button" onClick={onCancel}>Отмена</button></div></form>}
