"use client";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Copy, Download, Plus, Save, Trash2 } from "lucide-react";
import { calculateScenario } from "@/lib/core/calculator.mjs";
import { demoModelHourlyDefaults, minimumRecommendedMarginPct } from "@/lib/core/calculation-defaults.mjs";
import { pct, rub } from "@/lib/ui/format";

type Base = "per_hour" | "per_shift" | "per_worker_month" | "project_month";
type Cost = { id:string; group:string; label:string; amount:number; base:Base; enabled:boolean };
type ModelConfig = { id:string; code:string; name:string; ruleVersionId:string|null; rules:Record<string,unknown>|null };
type RequestRolePrefill = { id:string; name:string; count:number; salaryTarget?:number|null; paidHours?:number|null; presenceHours?:number|null; scheduleType?:string|null };
type RequestPrefill = { id:string; title:string; regionId?:string|null; schedule?:Record<string,unknown>; provision?:Record<string,unknown>; limits?:Record<string,unknown>; roles?:RequestRolePrefill[] };
type ConfigResponse = { demo:boolean; models:ModelConfig[]; request:RequestPrefill|null };

const groups=["Налоги и обязательные начисления","Регулярное обеспечение","Транспорт и проживание","СИЗ и медицина","Подбор и управление","Прочие расходы"];
const baseCosts:Cost[]=[
  {id:"housing",group:groups[2],label:"Проживание",amount:0,base:"per_shift",enabled:false},
  {id:"travel",group:groups[2],label:"Проезд и логистика",amount:0,base:"per_hour",enabled:false},
  {id:"ppe",group:groups[3],label:"СИЗ и спецодежда",amount:0,base:"per_worker_month",enabled:false},
  {id:"medical",group:groups[3],label:"Медицина",amount:0,base:"per_worker_month",enabled:false},
  {id:"recruit",group:groups[4],label:"Подбор и запуск",amount:0,base:"project_month",enabled:false},
  {id:"manager",group:groups[4],label:"Управление объектом",amount:0,base:"project_month",enabled:false},
];
const fallbackModelLabels:Record<string,string>={employment:"Трудовой договор",gph:"ГПХ",npd:"НПД / самозанятый",custom:"Модель компании"};

export function CalculatorWorkspace({requestId}:{requestId?:string}){
  const [config,setConfig]=useState<ConfigResponse|null>(null);const [modelCode,setModelCode]=useState("employment");const [selectedRoleId,setSelectedRoleId]=useState<string|undefined>();
  const [mode,setMode]=useState<"target_margin"|"client_limit">("target_margin");const [clientLimit,setClientLimit]=useState(700);const [clientLimitVatMode,setClientLimitVatMode]=useState<"with_vat"|"without_vat">("with_vat");
  const [worker,setWorker]=useState(390);const [workers,setWorkers]=useState(24);const [hours,setHours]=useState(242);const [shiftHours,setShiftHours]=useState(11);const [margin,setMargin]=useState(18);const [costs,setCosts]=useState(baseCosts);
  const [scenarioName,setScenarioName]=useState("Базовый сценарий");const [calculationId,setCalculationId]=useState<string|undefined>();const [savedVersion,setSavedVersion]=useState<number|undefined>();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");

  useEffect(()=>{let active=true;fetch(`/api/calculations${requestId?`?request=${encodeURIComponent(requestId)}`:""}`).then(r=>r.json()).then((data:ConfigResponse)=>{if(!active)return;setConfig(data);if(data.models[0])setModelCode(data.models[0].code);if(data.request){const roles=data.request.roles??[];if(roles.length){setWorkers(roles.reduce((sum,r)=>sum+Number(r.count||0),0));setSelectedRoleId(roles[0].id);}const limits=data.request.limits??{};const known=Number(limits.maxClientRate??limits.desiredClientRate??0);if(known>0){setClientLimit(known);setMode("client_limit");}if(limits.vatMode==="without_vat"||limits.vatMode==="with_vat")setClientLimitVatMode(limits.vatMode as "with_vat"|"without_vat");setScenarioName(`${data.request.title} — базовый сценарий`);setCosts(prev=>prefillProvision(prev,data.request?.provision));}}).catch(()=>setMessage("Не удалось загрузить активные правила расчёта."));return()=>{active=false}},[requestId]);

  const model=config?.models.find(item=>item.code===modelCode);const ruleInfo=useMemo(()=>readRule(model,config?.demo??false),[model,config?.demo]);
  const normalized=useMemo(()=>costs.map(cost=>({...cost,hourlyAmount:cost.base==="per_hour"?cost.amount:cost.base==="per_shift"?cost.amount/Math.max(1,shiftHours):cost.base==="per_worker_month"?cost.amount/Math.max(1,hours):cost.amount})),[costs,hours,shiftHours]);
  const employee=useMemo(()=>[{id:"model-rule",label:"Начисления выбранной модели",enabled:true,hourlyAmount:ruleInfo.hourlyAmount},...normalized.filter(item=>item.base!=="project_month")],[normalized,ruleInfo.hourlyAmount]);
  const project=useMemo(()=>normalized.filter(item=>item.base==="project_month"),[normalized]);
  const clientRateWithoutVat=mode==="client_limit"?(clientLimitVatMode==="with_vat"&&ruleInfo.vatRatePct!==null?clientLimit/(1+ruleInfo.vatRatePct/100):clientLimit):undefined;
  const result=useMemo(()=>calculateScenario({workerNetHourly:worker,workers,hoursPerWorker:hours,targetMarginPct:margin,clientRateHourly:clientRateWithoutVat,employeeCosts:employee,projectCosts:project}),[worker,workers,hours,margin,clientRateWithoutVat,employee,project]);
  const rateWithVat=ruleInfo.vatRatePct===null?null:result.clientRateHourly*(1+ruleInfo.vatRatePct/100);const marginDeviation=result.marginPct-minimumRecommendedMarginPct;
  const requestRoles=config?.request?.roles??[];

  function update(id:string,patch:Partial<Cost>){setCosts(value=>value.map(cost=>cost.id===id?{...cost,...patch}:cost));setSavedVersion(undefined)}
  function add(group:string){setCosts(value=>[...value,{id:crypto.randomUUID(),group,label:"Новая статья",amount:0,base:"per_hour",enabled:true}]);setSavedVersion(undefined)}
  function duplicate(cost:Cost){setCosts(value=>[...value,{...cost,id:crypto.randomUUID(),label:`${cost.label} — копия`}]);setSavedVersion(undefined)}
  async function saveScenario(){
    if(!model||config?.demo){setMessage(config?.demo?"Демо-режим: сценарий можно рассчитать, но серверное сохранение отключено.":"Не выбрана активная модель расчёта.");return;}
    setBusy(true);setMessage("");try{const response=await fetch("/api/calculations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({calculationId,requestId,requestRoleId:selectedRoleId,modelId:model.id,ruleVersionId:model.ruleVersionId??undefined,name:scenarioName,title:config?.request?.title??scenarioName,calculationMode:mode,clientLimit:mode==="client_limit"?clientLimit:undefined,clientLimitVatMode:mode==="client_limit"?clientLimitVatMode:undefined,inputs:{workerNetHourly:worker,workers,hoursPerWorker:hours,paidHoursPerShift:shiftHours,targetMarginPct:margin,requestId:requestId??null},costs:normalized.map(({hourlyAmount,...cost})=>({...cost,hourlyAmount})),result,sourceSnapshot:config?.request??{}})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Не удалось сохранить сценарий");setCalculationId(data.calculationId);setSavedVersion(data.scenarioNumber);setMessage(`Сценарий сохранён как версия ${data.scenarioNumber}.`);}catch(e){setMessage(e instanceof Error?e.message:"Не удалось сохранить сценарий");}finally{setBusy(false)}
  }
  function duplicateScenario(){setCalculationId(undefined);setSavedVersion(undefined);setScenarioName(`${scenarioName} — копия`);setMessage("Создана независимая копия исходных параметров. При сохранении она получит собственный расчёт.")}
  function exportSummary(){const lines=[["Показатель","Значение"],["Модель",model?.name??fallbackModelLabels[modelCode]??modelCode],["Режим",mode==="target_margin"?"От целевой маржи":"От лимита клиента"],["Сотруднику, ₽/ч",worker],["Себестоимость, ₽/ч",result.totalCostHourly],["Клиент без НДС, ₽/ч",result.clientRateHourly],["Клиент с НДС, ₽/ч",rateWithVat??"НДС не настроен"],["Маржа, %",result.marginPct],["Прибыль / месяц",result.monthlyContribution]];const csv=lines.map(row=>row.map(value=>`"${value}"`).join(";")).join("\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));link.download="расчёт-сценария.csv";link.click();URL.revokeObjectURL(link.href)}

  return <div className="calc-layout"><section className="section">
    <div className="scenario-tabs">{(config?.models??Object.entries(fallbackModelLabels).map(([code,name])=>({id:code,code,name,ruleVersionId:null,rules:null}))).map(item=><button key={item.code} type="button" className={modelCode===item.code?"active":""} onClick={()=>{setModelCode(item.code);setSavedVersion(undefined)}}>{item.name}</button>)}</div>
    {!ruleInfo.verified&&<div className="compliance-note"><AlertTriangle size={15}/><span>{config?.demo?"Демонстрационные начисления синтетические и не являются нормативом.":"Для выбранной модели нет подтверждённой активной версии экономических правил. Перед согласованием настройте нормативы."}</span></div>}
    <details className="calc-group" open><summary><span>Способ расчёта</span><span>{mode==="target_margin"?"От маржи":"От лимита"}</span></summary><div className="scenario-tabs"><button type="button" className={mode==="target_margin"?"active":""} onClick={()=>setMode("target_margin")}>От целевой маржи</button><button type="button" className={mode==="client_limit"?"active":""} onClick={()=>setMode("client_limit")}>От лимита клиента</button></div>{mode==="target_margin"?<CalcInput label="Целевая маржа" value={margin} onChange={v=>{setMargin(v);setSavedVersion(undefined)}} unit="%"/>:<><CalcInput label="Лимит клиента" value={clientLimit} onChange={v=>{setClientLimit(v);setSavedVersion(undefined)}} unit="₽/ч"/><div className="calc-row"><span>✓</span><span>Лимит указан</span><select value={clientLimitVatMode} onChange={e=>setClientLimitVatMode(e.target.value as "with_vat"|"without_vat")}><option value="with_vat">с НДС</option><option value="without_vat">без НДС</option></select><span/></div></>}</details>
    <details className="calc-group" open><summary><span>Выплата сотруднику и объём</span><span>{rub(worker)}/ч</span></summary>{requestRoles.length>0&&<div className="calc-row"><span>✓</span><span>Позиция заявки</span><select value={selectedRoleId} onChange={e=>{const id=e.target.value;setSelectedRoleId(id);const role=requestRoles.find(r=>r.id===id);if(role){setWorkers(role.count);if(role.paidHours)setShiftHours(Number(role.paidHours));}setSavedVersion(undefined)}}>{requestRoles.map(role=><option key={role.id} value={role.id}>{role.name} · {role.count} чел.</option>)}</select><span/></div>}<CalcInput label="Ставка на руки" value={worker} onChange={v=>{setWorker(v);setSavedVersion(undefined)}} unit="₽/ч"/><CalcInput label="Количество сотрудников" value={workers} onChange={v=>{setWorkers(v);setSavedVersion(undefined)}} unit="чел."/><CalcInput label="Часов на сотрудника / месяц" value={hours} onChange={v=>{setHours(v);setSavedVersion(undefined)}} unit="ч"/><CalcInput label="Оплачиваемых часов / смену" value={shiftHours} onChange={v=>{setShiftHours(v);setSavedVersion(undefined)}} unit="ч"/></details>
    {groups.map(group=>{const items=costs.filter(cost=>cost.group===group);return <details className="calc-group" open key={group}><summary><span>{group}</span><span>{group===groups[0]?rub(ruleInfo.hourlyAmount)+"/ч":rub(items.filter(item=>item.enabled).reduce((sum,item)=>sum+(normalized.find(value=>value.id===item.id)?.hourlyAmount??0),0))+"/ч"}</span></summary>{group===groups[0]&&<div className="calc-row"><span>✓</span><span>Начисления выбранной модели</span><strong>{rub(ruleInfo.hourlyAmount)}</strong><span>₽/ч</span></div>}{items.map(cost=><div className="calc-row calc-row-full" key={cost.id}><input type="checkbox" checked={cost.enabled} onChange={event=>update(cost.id,{enabled:event.target.checked})} aria-label={`Включить ${cost.label}`}/><input className="expense-name" value={cost.label} onChange={event=>update(cost.id,{label:event.target.value})}/><input type="number" value={cost.amount} onChange={event=>update(cost.id,{amount:Number(event.target.value)})}/><select value={cost.base} onChange={event=>update(cost.id,{base:event.target.value as Base})}><option value="per_hour">₽/ч</option><option value="per_shift">₽/смену</option><option value="per_worker_month">₽/чел./мес</option><option value="project_month">₽/проект/мес</option></select><button type="button" onClick={()=>duplicate(cost)} aria-label="Дублировать"><Copy size={14}/></button><button type="button" onClick={()=>setCosts(value=>value.filter(item=>item.id!==cost.id))} aria-label="Удалить"><Trash2 size={14}/></button></div>)}{group!==groups[0]&&<button type="button" className="add-expense" onClick={()=>add(group)}><Plus size={14}/> Добавить статью</button>}</details>})}
  </section><aside className="section calc-summary"><div className="calc-result"><div className="eyebrow">Сценарий · {model?.name??fallbackModelLabels[modelCode]}</div><input value={scenarioName} onChange={e=>{setScenarioName(e.target.value);setSavedVersion(undefined)}} aria-label="Название сценария"/><div className="big">{rub(result.clientRateHourly)}<small> / ч без НДС</small></div><div className="calc-kv"><span>Сотруднику на руки</span><strong>{rub(worker)}</strong></div><div className="calc-kv"><span>Обязательные начисления</span><strong>{rub(ruleInfo.hourlyAmount)}</strong></div><div className="calc-kv"><span>Себестоимость / ч</span><strong>{rub(result.totalCostHourly)}</strong></div><div className="calc-kv"><span>Клиент без НДС</span><strong>{rub(result.clientRateHourly)}</strong></div><div className="calc-kv"><span>НДС</span><strong>{ruleInfo.vatRatePct===null?"Не настроен":pct(ruleInfo.vatRatePct)}</strong></div><div className="calc-kv"><span>Клиент с НДС</span><strong>{rateWithVat===null?"—":rub(rateWithVat)}</strong></div><div className="calc-kv"><span>Прибыль / ч</span><strong>{rub(result.marginHourly)}</strong></div><div className="calc-kv"><span>Маржинальность</span><strong>{pct(result.marginPct)}</strong></div><div className="calc-kv"><span>Отклонение от ориентира</span><strong>{marginDeviation>=0?"+":""}{pct(marginDeviation)}</strong></div><div className="calc-kv"><span>Выручка / месяц</span><strong>{rub(result.monthlyRevenue)}</strong></div><div className="calc-kv"><span>Прибыль / месяц</span><strong>{rub(result.monthlyContribution)}</strong></div><button className="button primary" style={{width:"100%",marginTop:16}} type="button" disabled={busy||Boolean(savedVersion)} onClick={saveScenario}><Save size={14}/> {savedVersion?`Сохранена версия ${savedVersion}`:"Сохранить сценарий"}</button><button className="button" style={{width:"100%",marginTop:8}} type="button" disabled={busy} onClick={saveScenario}>Сохранить как новый сценарий</button><button className="button" style={{width:"100%",marginTop:8}} type="button" onClick={duplicateScenario}><Copy size={14}/> Дублировать сценарий</button><button className="button" style={{width:"100%",marginTop:8}} type="button" onClick={exportSummary}><Download size={14}/> Экспортировать сводку</button>{message&&<p className="calc-disclaimer">{message}</p>}<p className="calc-disclaimer">Каждое серверное сохранение создаёт новую историческую версию. Согласованные и использованные версии не перезаписываются.</p></div></aside></div>;
}

function CalcInput({label,value,onChange,unit}:{label:string;value:number;onChange:(value:number)=>void;unit:string}){return <div className="calc-row"><span>✓</span><span>{label}</span><input type="number" value={value} onChange={event=>onChange(Number(event.target.value))}/><span>{unit}</span></div>}
function readRule(model:ModelConfig|undefined,demo:boolean){const rules=model?.rules??{};const hourly=numberFrom(rules,"hourlyAmount")??numberFrom(rules,"employeeHourlyAmount")??(demo?Number((demoModelHourlyDefaults as Record<string,number>)[model?.code??"employment"]??0):0);const vat=numberFrom(rules,"vatRatePct");const verified=rules.legalParametersVerified===true;return {hourlyAmount:hourly,vatRatePct:vat,verified};}
function numberFrom(value:Record<string,unknown>,key:string){const raw=value[key];return typeof raw==="number"&&Number.isFinite(raw)?raw:null}
function prefillProvision(costs:Cost[],provision?:Record<string,unknown>){if(!provision)return costs;const mapping:Record<string,string>={housing:"housing",travel:"travel",shuttle:"travel",ppe:"ppe",workwear:"ppe",medical:"medical",medicalBook:"medical"};return costs.map(cost=>{const entries=Object.entries(mapping).filter(([,id])=>id===cost.id).map(([key])=>provision[key]).filter(Boolean) as Array<Record<string,unknown>>;const owned=entries.find(item=>item.provider==="us"&&typeof item.amount==="number");return owned?{...cost,amount:Number(owned.amount),enabled:true}:cost})}
