"use client";
import { useMemo, useState } from "react";

type Model = { id:string; name:string; code:string; ruleVersion:number|null; ruleSource:string|null; ruleEffectiveFrom?:string|null; rules:Record<string,unknown> };
type Tab = "models"|"expenses"|"schedules"|"rules";
const tabs:[Tab,string,string][]=[["models","Модели оформления","Тип занятости и налоговая логика"],["expenses","Расходы","Затраты на сотрудника, роль и проект"],["schedules","Графики","Смены, часы и оплачиваемые перерывы"],["rules","Финансовые правила","Резерв, маржа, НДС и округление"]];
const expenses=[["Проживание","project_month","Проект","Активный"],["Транспорт до объекта","per_shift","Сотрудник","Активный"],["Медосмотр и оформление","per_worker_period","Сотрудник","Черновик"],["Резерв замены","percent_of_worker_pay","Проект","Активный"]];
const schedules=[["5/2 · дневная","8 ч","21,7 смены","Перерыв 1 ч · не оплачивается"],["Вахта 15/15","11 ч","15 смен","Перерыв 1 ч · оплачивается"],["Сменная 2/2","12 ч","15,2 смены","Перерыв 1 ч · не оплачивается"]];
const pct=(v:unknown)=>Number.isFinite(Number(v))?\`${Number(v)}%\`:"—";
export function CalculationStandardsWorkspace({models}:{models:Model[]}){
 const [tab,setTab]=useState<Tab>("models"),[query,setQuery]=useState(""),[selected,setSelected]=useState(models[0]?.id??"");
 const visible=useMemo(()=>models.filter(m=>m.name.toLowerCase().includes(query.toLowerCase())),[models,query]);
 const active=models.find(m=>m.id===selected)||visible[0]||models[0];
 return <div className="standards-workspace">
  <div className="summary-strip"><span>Моделей <strong>{models.length}</strong></span><span>Версий на контроле <strong>{models.filter(m=>m.ruleVersion).length}</strong></span><span>Дата применения <strong>из расчёта</strong></span><span className="summary-warning">Демо-правила <strong>помечены</strong></span></div>
  <div className="standards-tabs" role="tablist">{tabs.map(([id,label,note])=><button key={id} className={`standards-tab ${tab===id?"is-active":""}`} onClick={()=>setTab(id)} role="tab" aria-selected={tab===id}><strong>{label}</strong><small>{note}</small></button>)}</div>
  {tab==="models"&&<div className="standards-grid"><section className="section"><div className="section-head"><div><h2>Модели оформления</h2><p>Версия выбирается в расчёте на дату экономики.</p></div><button className="button primary" type="button">Добавить модель</button></div><div className="standards-toolbar"><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск модели"/><span className="muted">Актуальные</span></div><div className="standards-model-list">{visible.map(m=><button key={m.id} className={`standards-model ${active?.id===m.id?"is-selected":""}`} onClick={()=>setSelected(m.id)}><span><strong>{m.name}</strong><small>{m.code} · версия {m.ruleVersion??"—"}</small></span><em>{m.rules.legalParametersVerified?"Проверено":"Демо"}</em></button>)}{!visible.length&&<p className="muted standards-empty">Ничего не найдено.</p>}</div></section><section className="section standards-detail"><div className="section-head"><div><h2>{active?.name??"Модель не выбрана"}</h2><p>Параметры текущей версии и источник данных.</p></div><button className="button" type="button">Создать новую версию</button></div>{active&&<><div className="standards-detail-meta"><span>Код <strong>{active.code}</strong></span><span>Версия <strong>{active.ruleVersion??"—"}</strong></span><span>Действует с <strong>{active.ruleEffectiveFrom??"—"}</strong></span></div><div className="standards-rule-cards"><div><small>Обязательные начисления</small><strong>{pct(active.rules.mandatoryChargePct)}</strong></div><div><small>Резерв риска</small><strong>{pct(active.rules.riskReservePct)}</strong></div><div><small>Минимальная маржа</small><strong>{pct(active.rules.minimumMarginPct)}</strong></div><div><small>НДС</small><strong>{pct(active.rules.vatPct)}</strong></div></div><div className="standards-source"><strong>{active.rules.legalParametersVerified?"Параметры проверены":"Демонстрационные параметры"}</strong><p>{active.ruleSource??"Источник не указан."}</p></div></>}</section></div>}
  {tab==="expenses"&&<section className="section"><div className="section-head"><div><h2>Группы расходов</h2><p>Расходы разделены по уровню применения и базе начисления.</p></div><button className="button primary" type="button">Добавить расход</button></div><table className="data-table"><thead><tr><th>Наименование</th><th>База</th><th>Контур</th><th>Состояние</th></tr></thead><tbody>{expenses.map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></section>}
  {tab==="schedules"&&<section className="section"><div className="section-head"><div><h2>Шаблоны графиков</h2><p>Расписание задаёт оплачиваемые часы и количество смен в месяце.</p></div><button className="button primary" type="button">Добавить график</button></div><table className="data-table"><thead><tr><th>Шаблон</th><th>Смена</th><th>Норма</th><th>Перерыв</th></tr></thead><tbody>{schedules.map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></section>}
  {tab==="rules"&&<section className="section"><div className="section-head"><div><h2>Финансовые правила</h2><p>Параметры попадают в снимок каждого сценария.</p></div><button className="button" type="button">История изменений</button></div><div className="standards-rule-table"><div><span>Режим цены</span><strong>Целевая маржа / лимит клиента</strong><small>Выбирается в сценарии</small></div><div><span>Округление</span><strong>До 1 ₽</strong><small>После полной себестоимости</small></div><div><span>НДС</span><strong>Отдельно от ставки клиента</strong><small>Показывается явно в предложении</small></div><div><span>Снимок правил</span><strong>На дату экономики</strong><small>Старая версия не меняется</small></div></div></section>}
 </div>;
}
