"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Status } from "@/components/UI";
import type { RecruitingApplicationRow } from "@/lib/recruiting/service";
import { contactChannelLabels } from "@/lib/recruiting/model";

const storageKey="operis.recruiting.applications.v1";

export function CandidatesWorkspace({rows,demo}:{rows:RecruitingApplicationRow[];demo:boolean}){
 const [localRows,setLocalRows]=useState<RecruitingApplicationRow[]>([]);const [query,setQuery]=useState("");const [stage,setStage]=useState("all");
 useEffect(()=>{if(!demo)return;try{const raw=localStorage.getItem(storageKey);if(raw)setLocalRows(JSON.parse(raw));}catch{}},[demo]);
 const all=useMemo(()=>[...localRows,...rows.filter(row=>!localRows.some(local=>local.applicationId===row.applicationId))],[localRows,rows]);
 const candidates=useMemo(()=>{const map=new Map<string,{latest:RecruitingApplicationRow;count:number;objects:Set<string>;needs:Set<string>}>();for(const row of all){const current=map.get(row.candidateId);if(!current)map.set(row.candidateId,{latest:row,count:1,objects:new Set(row.object?[row.object]:[]),needs:new Set([row.need])});else{current.count++;if(row.object)current.objects.add(row.object);current.needs.add(row.need);}}return [...map.values()]},[all]);
 const filtered=candidates.filter(item=>{if(stage!=="all"&&item.latest.stage!==stage)return false;if(!query.trim())return true;const row=item.latest;return `${row.fullName} ${row.phone??""} ${row.email??""} ${row.source??""} ${[...item.objects].join(" ")} ${[...item.needs].join(" ")}`.toLowerCase().includes(query.trim().toLowerCase())});
 return <div className="recruiting-workspace">
  <div className="recruiting-summary"><div><span>Людей в базе</span><strong>{candidates.length}</strong></div><div><span>Активно в подборе</span><strong>{candidates.filter(x=>!["started","rejected","no_show"].includes(x.latest.stage)).length}</strong></div><div><span>Вышли</span><strong>{candidates.filter(x=>x.latest.stage==="started").length}</strong></div><div><span>Повторные обращения</span><strong>{candidates.filter(x=>x.count>1).length}</strong></div></div>
  <div className="recruiting-toolbar"><div className="recruiting-toolbar-left"><div className="segmented-control"><button className={stage==="all"?"active":""} onClick={()=>setStage("all")}>Все</button><button className={stage==="new"?"active":""} onClick={()=>setStage("new")}>Новые</button><button className={stage==="preparation"?"active":""} onClick={()=>setStage("preparation")}>Подготовка</button><button className={stage==="ready"?"active":""} onClick={()=>setStage("ready")}>Готовы</button><button className={stage==="started"?"active":""} onClick={()=>setStage("started")}>Вышли</button></div></div><div className="recruiting-toolbar-actions"><input className="request-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ФИО, телефон, источник, объект"/><Link className="button primary" href="/recruiting">+ Добавить через воронку</Link></div></div>
  <div className="section section-flush"><div className="request-table-wrap"><table className="data-table"><thead><tr><th>Кандидат</th><th>Контакт</th><th>Источник</th><th>Текущая потребность</th><th>Этап</th><th>Ответственный</th><th>История</th></tr></thead><tbody>{filtered.map(({latest,count,objects})=><tr key={latest.candidateId}><td><Link className="cell-title" href={`/candidates/${latest.candidateId}`}>{latest.fullName}</Link><span className="cell-sub">{latest.city??"Город не указан"}</span></td><td>{latest.phone??latest.email??"—"}<span className="cell-sub">{latest.preferredChannel?`предпочтительно: ${contactChannelLabels[latest.preferredChannel]??latest.preferredChannel}`:""}</span></td><td>{latest.source??"—"}<span className="cell-sub">{latest.sourceCampaign??latest.sourceChannel??""}</span></td><td>{latest.need}<span className="cell-sub">{latest.object??"без объекта"}</span></td><td><Status tone={latest.stage==="started"?"good":["rejected","no_show"].includes(latest.stage)?"bad":"info"}>{latest.stageLabel}</Status></td><td>{latest.owner??"Не назначен"}<span className="cell-sub">{latest.manager?`менеджер / мастер: ${latest.manager}`:""}</span></td><td>{count} {count===1?"заявка":"заявки"}<span className="cell-sub">{objects.size} {objects.size===1?"объект":"объекта"}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-inline">Кандидатов по выбранным условиям нет</div>}</div></div>
 </div>
}
