"use client";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";

type Scenario={id:string;name:string;status:string;clientRate:number|string;marginPct:number|string;monthlyContribution:number|string};
type Approval={id:string;scenarioId:string;scenario:string;status:string;comment?:string|null};
type Proposal={id:string;version:number;status:string};
type Props={requestId:string;scenarios:Scenario[];approvals:Approval[];proposals:Proposal[];canRequestApproval:boolean;canDecide:boolean;canCreateProposal:boolean;canSendProposal:boolean;canAcceptProposal:boolean;canComment:boolean};
const commentTypes={comment:"Комментарий",call:"Звонок",client_clarification:"Уточнение клиента",decision:"Решение",internal_note:"Внутреннее примечание"};
export function CommercialWorkflowActions(props:Props){
  const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [scenarioId,setScenarioId]=useState(props.scenarios.find(x=>x.status!=="accepted")?.id??props.scenarios[0]?.id??"");const [proposalScenarioId,setProposalScenarioId]=useState(props.scenarios.find(x=>x.status==="accepted")?.id??"");const [commentType,setCommentType]=useState("comment");const [commentBody,setCommentBody]=useState("");const pending=useMemo(()=>props.approvals.filter(x=>x.status==="pending"),[props.approvals]);
  async function act(payload:Record<string,unknown>){setBusy(true);setError("");setMessage("");try{const response=await fetch(`/api/requests/${props.requestId}/commercial`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Не удалось выполнить действие");setMessage("Действие сохранено.");router.refresh();return data}catch(e){setError(e instanceof Error?e.message:"Не удалось выполнить действие")}finally{setBusy(false)}}
  return <div className="stack-list" style={{padding:12}}>
    {props.canRequestApproval&&props.scenarios.length>0&&<div className="stack-item" style={{alignItems:"end"}}><label style={{flex:1}}><span className="cell-sub">Сценарий для согласования</span><select value={scenarioId} onChange={e=>setScenarioId(e.target.value)}>{props.scenarios.filter(x=>x.status!=="accepted").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="button" disabled={busy||!scenarioId} onClick={()=>act({action:"approval_request",scenarioId})}>Отправить на согласование</button></div>}
    {props.canDecide&&pending.map(approval=><div className="stack-item" key={approval.id}><div><strong>{approval.scenario}</strong><small>Ожидает решения руководителя</small></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button className="button primary" disabled={busy} onClick={()=>act({action:"approval_decision",approvalId:approval.id,decision:"approved"})}>Согласовать</button><button className="button" disabled={busy} onClick={()=>act({action:"approval_decision",approvalId:approval.id,decision:"revision_requested",comment:"Возвращено на доработку"})}>Вернуть на доработку</button><button className="button" disabled={busy} onClick={()=>act({action:"approval_decision",approvalId:approval.id,decision:"rejected"})}>Отклонить</button></div></div>)}
    {props.canCreateProposal&&props.scenarios.some(x=>x.status==="accepted")&&<div className="stack-item" style={{alignItems:"end"}}><label style={{flex:1}}><span className="cell-sub">Согласованный сценарий для новой версии КП</span><select value={proposalScenarioId} onChange={e=>setProposalScenarioId(e.target.value)}>{props.scenarios.filter(x=>x.status==="accepted").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="button" disabled={busy||!proposalScenarioId} onClick={()=>act({action:"proposal_create",scenarioIds:[proposalScenarioId],terms:{}})}>Создать новую версию КП</button></div>}
    {props.proposals.map(proposal=><div className="stack-item" key={proposal.id}><div><strong>КП v{proposal.version}</strong><small>{proposal.status==="accepted"?"Принято клиентом":proposal.status==="sent"?"Отправлено":"Подготовлено"}</small></div><div style={{display:"flex",gap:6}}>{props.canSendProposal&&!['sent','accepted'].includes(proposal.status)&&<button className="button" disabled={busy} onClick={()=>act({action:"proposal_send",proposalId:proposal.id})}>Зафиксировать отправку</button>}{props.canAcceptProposal&&proposal.status==="sent"&&<button className="button primary" disabled={busy} onClick={()=>act({action:"proposal_accept",proposalId:proposal.id})}>Принято клиентом</button>}</div></div>)}
    {props.canComment&&<div className="stack-item" style={{alignItems:"end"}}><label><span className="cell-sub">Тип записи</span><select value={commentType} onChange={e=>setCommentType(e.target.value)}>{Object.entries(commentTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label style={{flex:1}}><span className="cell-sub">Комментарий</span><textarea rows={2} value={commentBody} onChange={e=>setCommentBody(e.target.value)} placeholder="Зафиксировать звонок, уточнение, решение или внутреннее примечание"/></label><button className="button" disabled={busy||!commentBody.trim()} onClick={async()=>{await act({action:"comment",entityType:"request",entityId:props.requestId,commentType,body:commentBody});setCommentBody("")}}>Добавить</button></div>}
    {error&&<div className="compliance-note">{error}</div>}{message&&<div className="cell-sub">{message}</div>}
  </div>;
}
