"use client";
import {useMemo,useState} from "react";
import {AlertTriangle,Copy,Plus,Save,Trash2} from "lucide-react";
import {calculateCommercialScenario,normalizeCost} from "@/lib/core/commercial-calculator.mjs";
import type {CalculatorModelRule,CommercialRequestRow,ProvisionRow} from "@/lib/commercial/types";
import {pct,rub} from "@/lib/ui/format";

type Base="per_hour"|"per_shift"|"per_worker_month"|"project_month";
type Cost={id:string;group:string;label:string;amount:number;base:Base;enabled:boolean};
const groups=["Регулярное обеспечение","Транспорт и проживание","СИЗ и медицина","Подбор и управление","Прочие расходы"];

export function CommercialCalculatorWorkspace({rules,request,provisions=[],demo}:{rules:CalculatorModelRule[];request?:CommercialRequestRow|null;provisions?:ProvisionRow[];demo:boolean}){
 const firstRule=rules[0];const [model,setModel]=useState(firstRule?.code??"employment");const rule=rules.find(item=>item.code===model)??firstRule;
 const [roleId,setRoleId]=useState(request?.roles[0]?.id??"");const selectedRole=request?.roles.find(role=>role.id===roleId)??request?.roles[0];
 const [roleName,setRoleName]=useState(selectedRole?.name??"");const [scenarioName,setScenarioName]=useState(request?`${selectedRole?.name??"Сценарий"} · базовый вариант`:"Самостоятельный сценарий");
 const [worker,setWorker]=useState(Number(selectedRole?.salaryTarget??request?.proposedWorkerPay??390));const [workers,setWorkers]=useState(selectedRole?.count??request?.totalHeadcount??1);const [hours,setHours]=useState(242);const [shiftHours,setShiftHours]=useState(Number(selectedRole?.paidHours??11));
 const [mode,setMode]=useState<"target_margin"|"client_limit">(request?.maxClientRate?"client_limit":"target_margin");const [margin,setMargin]=useState(rule?.recommendedMarginPct??18);const [clientLimit,setClientLimit]=useState(Number(request?.maxClientRate??700));const [limitWithVat,setLimitWithVat]=useState(request?.clientRateVatMode!=="without_vat");
 const [costs,setCosts]=useState<Cost[]>(()=>initialCosts(firstRule,provisions));const [calculationId,setCalculationId]=useState<string|null>(null);const [scenarioId,setScenarioId]=useState<string|null>(null);const [scenarioNumber,setScenarioNumber]=useState<number|null>(null);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
 const employeeCosts=useMemo(()=>costs.filter(item=>item.base!=="project_month").map(item=>({...item,hourlyAmount:normalizeCost(item.amount,item.base,{hoursPerWorker:hours,shiftHours})})),[costs,hours,shiftHours]);
 const projectCosts=useMemo(()=>costs.filter(item=>item.base==="project_month").map(item=>({...item,hourlyAmount:item.amount})),[costs]);
 const result=useMemo(()=>calculateCommercialScenario({workerNetHourly:worker,workers,hoursPerWorker:hours,mandatoryChargePct:rule?.mandatoryChargePct??0,employeeCosts,projectCosts,targetMarginPct:margin,priceMode:mode,clientRate:clientLimit,clientRateIncludesVat:limitWithVat,vatRatePct:rule?.vatRatePct??0,recommendedMarginPct:rule?.recommendedMarginPct??0,minimumMarginPct:rule?.minimumMarginPct??0,maxClientRate:request?.maxClientRate,maxClientRateIncludesVat:request?.clientRateVatMode!=="without_vat"}),[worker,workers,hours,rule,employeeCosts,projectCosts,margin,mode,clientLimit,limitWithVat,request]);
 function update(id:string,patch:Partial<Cost>){setCosts(current=>current.map(item=>item.id===id?{...item,...patch}:item))}
 function add(group:string){setCosts(current=>[...current,{id:crypto.randomUUID(),group,label:"Новая статья",amount:0,base:"per_hour",enabled:true}])}
 function duplicateCost(cost:Cost){setCosts(current=>[...current,{...cost,id:crypto.randomUUID(),label:`${cost.label} — копия`}])}
 function selectRole(id:string){setRoleId(id);const role=request?.roles.find(item=>item.id===id);if(role){setRoleName(role.name);setWorkers(role.count);if(role.salaryTarget!=null)setWorker(Number(role.salaryTarget));if(role.paidHours!=null)setShiftHours(Number(role.paidHours));setScenarioName(`${role.name} · новый сценарий`)}}
 async function save(saveMode:"update"|"new"|"duplicate"){
  if(demo){setMessage("В демонстрационном режиме сохранение отключено.");return}setSaving(true);setMessage("");try{const response=await fetch("/api/calculations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({calculationId,scenarioId:saveMode==="update"?scenarioId:null,requestId:request?.id??null,requestRoleId:roleId||null,sourceKind:request?"request":"standalone",title:request?`Расчёт · ${request.number}`:scenarioName,modelCode:model,ruleVersionId:rule?.ruleVersionId??null,name:saveMode==="duplicate"?`${scenarioName} — копия`:scenarioName,saveMode,inputs:{requestId:request?.id??null,roleName,workerNetHourly:worker,workers,hoursPerWorker:hours,shiftHours,priceMode:mode,targetMarginPct:margin,clientRate:clientLimit,clientRateIncludesVat:limitWithVat,modelRule:{code:model,ruleVersionId:rule?.ruleVersionId??null}},costs,result})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Не удалось сохранить сценарий");setCalculationId(data.calculationId);setScenarioId(data.id);setScenarioNumber(data.scenarioNumber);setMessage(`Сохранён сценарий v${data.scenarioNumber}.`) }catch(error){setMessage(error instanceof Error?error.message:"Не удалось сохранить сценарий")}finally{setSaving(false)}}
 if(!rule)return <section className="section"><div className="empty"><strong>Нет моделей расчёта</strong><span>Добавьте действующую версию модели и правил.</span></div></section>;
 return <div className="calc-layout"><section className="section"><div className="scenario-tabs">{rules.map(item=><button key={item.code} type="button" className={model===item.code?"active":""} onClick={()=>{setModel(item.code);setMargin(item.recommendedMarginPct)}}>{item.label}</button>)}</div><div className="compliance-note"><AlertTriangle size={15}/><span>{rule.verified?`Используется зафиксированная версия правил ${rule.ruleVersionId}.`:`Версия правил «${rule.label}» не подтверждена. Значения показаны как демонстрационная/непроверенная конфигурация и требуют проверки перед согласованием.`}</span></div>
 {request&&<details className="calc-group" open><summary><span>Контекст заявки</span><span>{request.number}</span></summary><div style={{padding:"10px 14px",display:"grid",gap:8}}><label>Позиция <select value={roleId} onChange={e=>selectRole(e.target.value)}>{request.roles.map(role=><option key={role.id} value={role.id}>{role.name} · {role.count} чел.</option>)}</select></label><span className="cell-sub">{request.siteName??request.location} · лимит клиента {request.maxClientRate!=null?rub(request.maxClientRate):"не указан"}</span></div></details>}
 {!request&&<details className="calc-group" open><summary><span>Самостоятельный расчёт</span><span>Без заявки</span></summary><div style={{padding:"10px 14px"}}><label>Позиция <input value={roleName} onChange={e=>setRoleName(e.target.value)} placeholder="Специальность / рабочее название"/></label></div></details>}
 <details className="calc-group" open><summary><span>Выплата сотруднику и объём</span><span>{rub(worker)}/ч</span></summary><CalcInput label="Сотруднику на руки" value={worker} onChange={setWorker} unit="₽/ч"/><CalcInput label="Количество сотрудников" value={workers} onChange={setWorkers} unit="чел."/><CalcInput label="Часов на сотрудника / месяц" value={hours} onChange={setHours} unit="ч"/><CalcInput label="Оплачиваемых часов / смену" value={shiftHours} onChange={setShiftHours} unit="ч"/><div className="calc-row"><span>✓</span><span>Обязательные начисления по версии модели</span><strong className="num">{pct(rule.mandatoryChargePct)}</strong><span>{rub(result.mandatoryChargesHourly)}/ч</span></div></details>
 {groups.map(group=>{const items=costs.filter(item=>item.group===group);return <details className="calc-group" open key={group}><summary><span>{group}</span><span>{items.filter(item=>item.enabled).length} статей</span></summary>{items.map(cost=><div className="calc-row calc-row-full" key={cost.id}><input type="checkbox" checked={cost.enabled} onChange={e=>update(cost.id,{enabled:e.target.checked})} aria-label={`Включить ${cost.label}`}/><input className="expense-name" value={cost.label} onChange={e=>update(cost.id,{label:e.target.value})}/><input type="number" value={cost.amount} onChange={e=>update(cost.id,{amount:Number(e.target.value)})}/><select value={cost.base} onChange={e=>update(cost.id,{base:e.target.value as Base})}><option value="per_hour">₽/ч</option><option value="per_shift">₽/смену</option><option value="per_worker_month">₽/чел./мес</option><option value="project_month">₽/проект/мес</option></select><button type="button" onClick={()=>duplicateCost(cost)} aria-label="Дублировать"><Copy size={14}/></button><button type="button" onClick={()=>setCosts(current=>current.filter(item=>item.id!==cost.id))} aria-label="Удалить"><Trash2 size={14}/></button></div>)}<button type="button" className="add-expense" onClick={()=>add(group)}><Plus size={14}/> Добавить статью</button></details>})}
 </section><aside className="section calc-summary"><div className="calc-result"><div className="eyebrow">Сценарий{scenarioNumber?` v${scenarioNumber}`:""} · {rule.label}</div><input value={scenarioName} onChange={e=>setScenarioName(e.target.value)} aria-label="Название сценария" style={{width:"100%",marginBottom:12}}/><div className="segmented" style={{marginBottom:12}}><button type="button" className={mode==="target_margin"?"active":""} onClick={()=>setMode("target_margin")}>От целевой маржи</button><button type="button" className={mode==="client_limit"?"active":""} onClick={()=>setMode("client_limit")}>От лимита клиента</button></div>{mode==="target_margin"?<label className="margin-control">Целевая маржа <input type="number" value={margin} min="0" max="95" onChange={e=>setMargin(Number(e.target.value))}/>%</label>:<><label className="margin-control">Лимит клиента <input type="number" value={clientLimit} min="0" onChange={e=>setClientLimit(Number(e.target.value))}/> ₽/ч</label><label style={{display:"flex",gap:7,alignItems:"center",fontSize:11,marginBottom:12}}><input type="checkbox" checked={limitWithVat} onChange={e=>setLimitWithVat(e.target.checked)}/> Лимит указан с НДС</label></>}
 <div className="big">{rub(result.clientRateWithVat)}<small> / ч с НДС</small></div><div className="calc-kv"><span>Себестоимость / ч</span><strong>{rub(result.totalCostHourly)}</strong></div><div className="calc-kv"><span>Цена без НДС</span><strong>{rub(result.clientRateExVat)}</strong></div><div className="calc-kv"><span>НДС / ч</span><strong>{rub(result.vatHourly)}</strong></div><div className="calc-kv"><span>Прибыль / ч</span><strong>{rub(result.profitHourly)}</strong></div><div className="calc-kv"><span>Маржинальность</span><strong>{pct(result.marginPct)}</strong></div><div className="calc-kv"><span>Отклонение от рекомендуемой</span><strong>{pct(result.marginDeviationPct)}</strong></div><div className="calc-kv"><span>Выручка / месяц без НДС</span><strong>{rub(result.monthlyRevenue)}</strong></div><div className="calc-kv"><span>Прибыль / месяц</span><strong>{rub(result.monthlyContribution)}</strong></div>{result.exceedsLimitBy>0&&<div className="compliance-panel"><strong>Превышение лимита</strong><span>{rub(result.exceedsLimitBy)} / ч</span></div>}{result.belowMinimumMargin&&<div className="compliance-panel"><strong>Ниже минимальной маржи</strong><span>Требуется проверка и согласование по правилам компании.</span></div>}
 <div style={{display:"grid",gap:7,marginTop:14}}><button className="button primary" type="button" disabled={saving||demo} onClick={()=>save("update")}><Save size={14}/> Сохранить сценарий</button><button className="button" type="button" disabled={saving||demo} onClick={()=>save("new")}>Сохранить как новый сценарий</button><button className="button" type="button" disabled={saving||demo} onClick={()=>save("duplicate")}><Copy size={14}/> Дублировать сценарий</button></div>{message&&<p className="calc-disclaimer">{message}</p>}<p className="calc-disclaimer">В расчёте сохраняется ID версии правил. Принятая версия сценария остаётся неизменяемой.</p></div></aside></div>;
}
function CalcInput({label,value,onChange,unit}:{label:string;value:number;onChange:(value:number)=>void;unit:string}){return <div className="calc-row"><span>✓</span><span>{label}</span><input type="number" value={value} onChange={e=>onChange(Number(e.target.value))}/><span>{unit}</span></div>}
function initialCosts(rule:CalculatorModelRule|undefined,provisions:ProvisionRow[]):Cost[]{const d=rule?.defaults??{housingPerShift:0,transportPerHour:0,workwearPerWorkerMonth:0,ppePerWorkerMonth:0,medicalPerWorkerMonth:0,recruitmentProjectMonth:0,managementProjectMonth:0};const provision=(code:string,fallback:number)=>{const item=provisions.find(row=>row.code===code&&row.provider==="ours");return {amount:Number(item?.amount??fallback),enabled:Boolean(item)};};const housing=provision("housing",d.housingPerShift),transport=provision("shuttle",d.transportPerHour),workwear=provision("workwear",d.workwearPerWorkerMonth),ppe=provision("ppe",d.ppePerWorkerMonth),medical=provision("medical",d.medicalPerWorkerMonth);return [{id:"housing",group:groups[1],label:"Проживание",amount:housing.amount,base:"per_shift",enabled:housing.enabled},{id:"transport",group:groups[1],label:"Транспорт / развозка",amount:transport.amount,base:"per_hour",enabled:transport.enabled},{id:"workwear",group:groups[2],label:"Спецодежда",amount:workwear.amount,base:"per_worker_month",enabled:workwear.enabled},{id:"ppe",group:groups[2],label:"СИЗ",amount:ppe.amount,base:"per_worker_month",enabled:ppe.enabled},{id:"medical",group:groups[2],label:"Медицина",amount:medical.amount,base:"per_worker_month",enabled:medical.enabled},{id:"recruit",group:groups[3],label:"Подбор и запуск",amount:d.recruitmentProjectMonth,base:"project_month",enabled:d.recruitmentProjectMonth>0},{id:"manager",group:groups[3],label:"Управление объектом",amount:d.managementProjectMonth,base:"project_month",enabled:d.managementProjectMonth>0}]}
