"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {Plus,X} from "lucide-react";
import type {CompanyDocumentRow} from "@/lib/tenders/company-documents";

type Entity={id:string;name:string};
const statusLabels:Record<string,string>={active:"Актуален",needs_update:"Нужно обновить",missing:"Отсутствует",archived:"Архив"};
const categoryLabels:Record<string,string>={corporate:"Учредительные",tax:"Налоговые",authority:"Полномочия",experience:"Опыт и договоры",license:"Лицензии и допуски",financial:"Финансовые",other:"Прочее"};
function empty(){return {id:"",name:"",category:"corporate",legalEntityId:"",documentNumber:"",sourceUrl:"",status:"active",validFrom:"",expiresAt:"",notes:""};}
function daysLeft(value:string|null){if(!value)return null;const d=new Date(value);if(Number.isNaN(d.getTime()))return null;return Math.ceil((d.getTime()-Date.now())/86400000);}
export function CompanyDocumentsWorkspace({rows,legalEntities,canManage}:{rows:CompanyDocumentRow[];legalEntities:Entity[];canManage:boolean}){
  const router=useRouter();const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");const [open,setOpen]=useState(false);const [form,setForm]=useState(empty());const [state,setState]=useState("");
  const filtered=useMemo(()=>rows.filter(r=>(filter==="all"||r.status===filter)&&`${r.name} ${r.legalEntity??""} ${r.category}`.toLowerCase().includes(query.toLowerCase())),[rows,filter,query]);
  const expiring=rows.filter(r=>{const d=daysLeft(r.expiresAt);return d!=null&&d>=0&&d<=30;}).length;
  function edit(row?:CompanyDocumentRow){setForm(row?{id:row.id,name:row.name,category:row.category,legalEntityId:row.legalEntityId??"",documentNumber:row.documentNumber??"",sourceUrl:row.sourceUrl??"",status:row.status,validFrom:row.validFrom??"",expiresAt:row.expiresAt??"",notes:row.notes??""}:empty());setState("");setOpen(true);}
  async function save(){setState("Сохранение…");const payload={name:form.name,category:form.category,legalEntityId:form.legalEntityId||null,documentNumber:form.documentNumber||null,sourceUrl:form.sourceUrl||null,status:form.status,validFrom:form.validFrom||null,expiresAt:form.expiresAt||null,notes:form.notes||null};const response=await fetch(form.id?`/api/company-documents/${form.id}`:"/api/company-documents",{method:form.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const json=await response.json().catch(()=>({}));if(!response.ok){setState(json.error??"Не удалось сохранить документ");return;}setOpen(false);router.refresh();}
  return <div className="company-documents-workspace">
    <div className="request-final-command-strip"><div><span>Документов</span><strong>{rows.length}</strong><small>рабочая библиотека</small></div><div><span>Актуальны</span><strong>{rows.filter(r=>r.status==="active").length}</strong><small>готовы к использованию</small></div><div><span>Нужно обновить</span><strong>{rows.filter(r=>r.status==="needs_update").length}</strong><small>требуют внимания</small></div><div><span>Истекают ≤ 30 дней</span><strong>{expiring}</strong><small>проверить сроки</small></div></div>
    <div className="requests-toolbar"><div className="requests-toolbar-left"><div className="segmented-control"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Все</button><button className={filter==="active"?"active":""} onClick={()=>setFilter("active")}>Актуальные</button><button className={filter==="needs_update"?"active":""} onClick={()=>setFilter("needs_update")}>Обновить</button><button className={filter==="missing"?"active":""} onClick={()=>setFilter("missing")}>Отсутствуют</button></div></div><div className="requests-toolbar-actions"><input className="request-search" placeholder="Поиск по документам" value={query} onChange={e=>setQuery(e.target.value)}/>{canManage&&<button className="button primary" onClick={()=>edit()}><Plus size={14}/> Добавить документ</button>}</div></div>
    <div className="request-table-wrap"><table className="data-table request-registry-table"><thead><tr><th>Документ</th><th>Юрлицо</th><th>Категория</th><th>Срок</th><th>Статус</th><th>Тендеры</th><th></th></tr></thead><tbody>{filtered.length?filtered.map(row=>{const left=daysLeft(row.expiresAt);return <tr key={row.id}><td><strong className="cell-title">{row.name}</strong><span className="cell-sub">{row.documentNumber?`№ ${row.documentNumber}`:`Обновлено ${row.updatedAt}`}</span></td><td>{row.legalEntity??"Общий документ"}</td><td>{categoryLabels[row.category]??row.category}</td><td>{row.expiresAt?new Date(row.expiresAt).toLocaleDateString("ru-RU"):"Бессрочно"}{left!=null&&left<=30&&<span className="cell-sub">осталось {Math.max(0,left)} дн.</span>}</td><td><span className={`status ${row.status==="active"?"status-good":row.status==="missing"?"status-bad":"status-warn"}`}><i/>{statusLabels[row.status]??row.status}</span></td><td>{row.usageCount}</td><td>{row.sourceUrl&&<a className="button ghost" href={row.sourceUrl} target="_blank" rel="noreferrer">Открыть</a>} {canManage&&<button className="button ghost" onClick={()=>edit(row)}>Изменить</button>}</td></tr>}):<tr><td colSpan={7}><div className="empty-inline">Документов в этом разделе нет</div></td></tr>}</tbody></table></div>
    {open&&<div className="drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><aside className="drawer company-document-drawer"><div className="drawer-head"><div><strong>{form.id?"Редактировать документ":"Новый документ компании"}</strong><span>Сохраняйте актуальность и сроки отдельно для каждого юрлица.</span></div><button className="icon-button" onClick={()=>setOpen(false)}><X size={16}/></button></div><div className="drawer-body"><div className="form-grid two"><label className="span-2"><span>Название *</span><input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label><span>Категория</span><select value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))}>{Object.entries(categoryLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label><span>Юрлицо</span><select value={form.legalEntityId} onChange={e=>setForm(v=>({...v,legalEntityId:e.target.value}))}><option value="">Общий документ</option>{legalEntities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Номер документа</span><input value={form.documentNumber} onChange={e=>setForm(v=>({...v,documentNumber:e.target.value}))}/></label><label><span>Статус</span><select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value}))}>{Object.entries(statusLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label><span>Действует с</span><input type="date" value={form.validFrom} onChange={e=>setForm(v=>({...v,validFrom:e.target.value}))}/></label><label><span>Действует до</span><input type="date" value={form.expiresAt} onChange={e=>setForm(v=>({...v,expiresAt:e.target.value}))}/></label><label className="span-2"><span>Ссылка на файл / хранилище</span><input type="url" value={form.sourceUrl} onChange={e=>setForm(v=>({...v,sourceUrl:e.target.value}))}/></label><label className="span-2"><span>Комментарий</span><textarea rows={4} value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></label></div>{state&&<p className="muted">{state}</p>}</div><div className="drawer-footer"><button className="button" onClick={()=>setOpen(false)}>Отмена</button><button className="button primary" disabled={!form.name.trim()} onClick={save}>Сохранить</button></div></aside></div>}
  </div>;
}
