"use client";
import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, CheckSquare, Columns3, Search, Square, X } from "lucide-react";
export type GridColumn<T> = { key: keyof T & string; label: string; render?: (row:T)=>React.ReactNode; numeric?: boolean; sticky?: boolean; searchable?: boolean; width?: number };
export function DataGrid<T extends { id:string }>({ rows, columns, emptyText="По выбранным условиям записей нет", searchPlaceholder="Поиск по реестру", onRowClick, rowHref }: { rows:T[]; columns:GridColumn<T>[]; emptyText?:string; searchPlaceholder?:string; onRowClick?:(row:T)=>void; rowHref?:(row:T)=>string }) {
  const [query,setQuery]=useState(""); const [sort,setSort]=useState<{key:string;direction:"asc"|"desc"}|null>(null); const [hidden,setHidden]=useState<string[]>([]); const [selected,setSelected]=useState<string[]>([]); const [showColumns,setShowColumns]=useState(false);
  const visible=columns.filter((column)=>!hidden.includes(column.key));
  const filtered=useMemo(()=>{const normalized=query.trim().toLowerCase();const source=normalized?rows.filter(row=>columns.some(column=>column.searchable!==false&&String(row[column.key]??"").toLowerCase().includes(normalized))):rows;if(!sort)return source;return [...source].sort((a,b)=>{const av=a[sort.key as keyof T],bv=b[sort.key as keyof T];const result=typeof av==="number"&&typeof bv==="number"?av-bv:String(av??"").localeCompare(String(bv??""),"ru");return sort.direction==="asc"?result:-result})},[rows,columns,query,sort]);
  const allSelected=filtered.length>0&&filtered.every(row=>selected.includes(row.id));
  function toggleSort(key:string){setSort(current=>current?.key===key?current.direction==="asc"?{key,direction:"desc"}:null:{key,direction:"asc"})}
  function openRow(row:T){const href=rowHref?.(row);if(href)window.location.assign(href);else onRowClick?.(row)}
  return <div className="data-grid"><div className="grid-toolbar"><label className="grid-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={searchPlaceholder}/>{query&&<button type="button" onClick={()=>setQuery("")} aria-label="Очистить"><X size={14}/></button>}</label><div className="grid-toolbar-meta">{selected.length>0?<strong>Выбрано: {selected.length}</strong>:<span>{filtered.length} записей</span>}<div className="column-picker"><button className="button" type="button" onClick={()=>setShowColumns(x=>!x)}><Columns3 size={14}/> Колонки</button>{showColumns&&<div>{columns.map(column=><label key={column.key}><input type="checkbox" checked={!hidden.includes(column.key)} onChange={()=>setHidden(x=>x.includes(column.key)?x.filter(k=>k!==column.key):[...x,column.key])}/>{column.label}</label>)}</div>}</div></div></div><div className="grid-scroll"><table className="data-table production-grid"><thead><tr><th className="select-cell"><button type="button" onClick={()=>setSelected(allSelected?[]:filtered.map(row=>row.id))} aria-label="Выбрать все">{allSelected?<CheckSquare size={15}/>:<Square size={15}/>}</button></th>{visible.map(column=><th key={column.key} className={`${column.numeric?"num":""} ${column.sticky?"sticky-col":""}`} style={{width:column.width}}><button type="button" onClick={()=>toggleSort(column.key)}>{column.label}{sort?.key===column.key&&(sort.direction==="asc"?<ArrowUp size={13}/>:<ArrowDown size={13}/>)}</button></th>)}</tr></thead><tbody>{filtered.map(row=><tr key={row.id} className={selected.includes(row.id)?"selected":""} onDoubleClick={()=>openRow(row)}><td className="select-cell"><button type="button" onClick={()=>setSelected(x=>x.includes(row.id)?x.filter(id=>id!==row.id):[...x,row.id])} aria-label="Выбрать строку">{selected.includes(row.id)?<CheckSquare size={15}/>:<Square size={15}/>}</button></td>{visible.map(column=><td key={column.key} className={`${column.numeric?"num":""} ${column.sticky?"sticky-col":""}`} onClick={()=>column.sticky&&openRow(row)}>{column.render?column.render(row):String(row[column.key]??"—")}</td>)}</tr>)}</tbody></table>{filtered.length===0&&<div className="grid-empty">{emptyText}</div>}</div></div>;
}
