"use client";
import { useEffect, useMemo, useState } from "react";
import { ChevronDown, ChevronRight, MoreHorizontal, Network, Search, X } from "lucide-react";
import { buildOrganizationTree, organizationUnitLabels } from "@/lib/core/organization.mjs";
import type { CompanyEmployeeRow, OrganizationUnitRow, StaffPositionRow } from "@/lib/organization/types";
import { Status } from "@/components/UI";
type TreeUnit = OrganizationUnitRow & { children: TreeUnit[] };

export function DepartmentRegistry({ units, employees, staffPositions }: { units: OrganizationUnitRow[]; employees: CompanyEmployeeRow[]; staffPositions: StaffPositionRow[] }) {
  const initialUnit = () => typeof window === "undefined" ? null : new URL(window.location.href).searchParams.get("unit");
  const [query, setQuery] = useState(""); const [kind, setKind] = useState("all"); const [region, setRegion] = useState("all"); const [selectedBranch, setSelectedBranch] = useState<string | null>(null); const [selected, setSelected] = useState<OrganizationUnitRow | null>(() => units.find((item) => item.id === initialUnit()) ?? null); const [collapsed, setCollapsed] = useState<Set<string>>(new Set());
  const roots = useMemo(() => buildOrganizationTree(units) as TreeUnit[], [units]); const regions = [...new Set(units.map((item) => item.region).filter(Boolean))] as string[];
  useEffect(() => { const url = new URL(window.location.href); if (selected) url.searchParams.set("unit", selected.id); else url.searchParams.delete("unit"); window.history.replaceState(null, "", url); }, [selected]);
  const branchIds = useMemo(() => { if (!selectedBranch) return null; const found = new Set([selectedBranch]); let changed = true; while (changed) { changed = false; for (const item of units) if (item.parentId && found.has(item.parentId) && !found.has(item.id)) { found.add(item.id); changed = true; } } return found; }, [selectedBranch, units]);
  const rows = units.filter((item) => (!branchIds || branchIds.has(item.id)) && (!query || [item.name, item.code, item.manager, item.region].join(" ").toLowerCase().includes(query.toLowerCase())) && (kind === "all" || item.kind === kind) && (region === "all" || item.region === region));
  function render(unit: TreeUnit): React.ReactNode { const closed = collapsed.has(unit.id); return <li key={unit.id}><button type="button" className={selectedBranch === unit.id ? "active" : ""} onClick={() => setSelectedBranch(unit.id)}><span className="tree-toggle" onClick={(event) => { event.stopPropagation(); if (!unit.children.length) return; setCollapsed((value) => { const next = new Set(value); if (next.has(unit.id)) next.delete(unit.id); else next.add(unit.id); return next; }); }}>{unit.children.length ? closed ? <ChevronRight size={13} /> : <ChevronDown size={13} /> : null}</span><Network size={13} /><span>{unit.name}</span><i>{unit.childCount ?? unit.children.length}</i></button>{!closed && unit.children.length > 0 && <ul>{unit.children.map(render)}</ul>}</li>; }
  return <div className="department-workspace"><div className="department-toolbar"><label className="toolbar-search"><Search size={15} /><span className="sr-only">Поиск подразделения</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Название, код или руководитель" /></label><select value={kind} onChange={(event) => setKind(event.target.value)} aria-label="Тип"><option value="all">Все типы</option>{Object.entries(organizationUnitLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={region} onChange={(event) => setRegion(event.target.value)} aria-label="Регион"><option value="all">Все регионы</option>{regions.map((item) => <option key={item}>{item}</option>)}</select><button type="button" className="button compact" onClick={() => setSelectedBranch(null)}>Вся структура</button></div>
    <div className="department-layout"><nav className="department-tree" aria-label="Иерархия подразделений"><strong>Структура компании</strong><ul>{roots.map(render)}</ul></nav><div className="grid-scroll"><table className="data-table department-table"><thead><tr><th>Название</th><th>Тип</th><th>Родитель</th><th>Регион</th><th>Руководитель</th><th>Сотрудники</th><th>Команды</th><th>Позиции</th><th>Вакансии</th><th>Статус</th><th aria-label="Действия" /></tr></thead><tbody>{rows.map((item) => <tr key={item.id} className={selected?.id === item.id ? "selected" : ""} onClick={() => setSelected(item)} tabIndex={0} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelected(item); } }}><td><span className="cell-title">{item.name}</span><span className="cell-sub">{item.code}</span></td><td>{organizationUnitLabels[item.kind] ?? item.kind}</td><td>{units.find((parent) => parent.id === item.parentId)?.name ?? "—"}</td><td>{item.region ?? "—"}</td><td>{item.manager ?? "Не назначен"}</td><td className="num">{item.employeeCount}</td><td className="num">{units.filter((child) => child.parentId === item.id && ["team", "project_group", "object_team"].includes(child.kind)).length}</td><td className="num">{item.staffPositionCount ?? staffPositions.filter((position) => position.orgUnitId === item.id).length}</td><td className="num">{item.vacancyCount ?? staffPositions.filter((position) => position.orgUnitId === item.id).reduce((sum, position) => sum + position.open, 0)}</td><td><Status tone={item.active ? "good" : "neutral"}>{item.active ? "Действует" : "Архив"}</Status></td><td><button type="button" className="icon-button" onClick={(event) => { event.stopPropagation(); setSelected(item); }} aria-label={`Действия: ${item.name}`}><MoreHorizontal size={15} /></button></td></tr>)}</tbody></table>{rows.length === 0 && <div className="registry-empty"><strong>В выбранной ветке нет элементов</strong><span>Измените фильтры или выберите всю структуру.</span></div>}</div></div>
    {selected && <aside className="department-drawer"><header><div><Network size={20} /><span><h2>{selected.name}</h2><p>{organizationUnitLabels[selected.kind]}</p></span></div><button type="button" className="icon-button" onClick={() => setSelected(null)} aria-label="Закрыть карточку"><X size={16} /></button></header><dl><Fact label="Родитель" value={units.find((item) => item.id === selected.parentId)?.name ?? "Верхний уровень"} /><Fact label="Руководитель" value={selected.manager ?? "Не назначен"} /><Fact label="Регион" value={selected.region ?? "Вся компания"} /><Fact label="Действует" value={selected.active ? "Да" : "Нет"} /></dl><section><h3>Дочерние единицы</h3><div className="drawer-list">{units.filter((item) => item.parentId === selected.id).map((item) => <div key={item.id}><strong>{item.name}</strong><small>{organizationUnitLabels[item.kind]}</small></div>)}</div></section><section><h3>Сотрудники</h3><div className="drawer-list">{employees.filter((item) => item.orgUnitId === selected.id).map((item) => <div key={item.id}><strong>{item.name}</strong><small>{item.primaryStaffPosition ?? item.position ?? "Без позиции"}</small></div>)}</div></section><section><h3>Структурный статус</h3><p>{selected.managerMembershipId ? "Руководитель назначен; единица доступна для маршрутизации задач и ответственности." : "Руководитель не назначен. Правила эскалации должны использовать резервную роль."}</p></section></aside>}
  </div>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
