"use client";
import { useMemo, useState } from "react";
import { Mail, Phone, Search } from "lucide-react";
import type { CompanyEmployeeRow } from "@/lib/organization/types";
import { Status } from "@/components/UI";

export function EmployeeDirectory({employees}:{employees:CompanyEmployeeRow[]}){
  const [query,setQuery]=useState("");const [unit,setUnit]=useState("all");const [region,setRegion]=useState("all");const [selected,setSelected]=useState<CompanyEmployeeRow|null>(null);
  const units=[...new Set(employees.map(item=>item.orgUnit).filter(Boolean))] as string[];const regions=[...new Set(employees.map(item=>item.region).filter(Boolean))] as string[];
  const rows=useMemo(()=>employees.filter(item=>{const text=[item.name,item.position,item.orgUnit,...item.roles.map(r=>r.name),...item.responsibilities].join(" ").toLowerCase();return text.includes(query.toLowerCase())&&(unit==="all"||item.orgUnit===unit)&&(region==="all"||item.region===region)}),[employees,query,unit,region]);
  return <div className="directory-workspace"><div className="registry-toolbar"><label className="toolbar-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Имя, должность, роль или ответственность"/></label><select value={unit} onChange={e=>setUnit(e.target.value)} aria-label="Подразделение"><option value="all">Все подразделения</option>{units.map(item=><option key={item}>{item}</option>)}</select><select value={region} onChange={e=>setRegion(e.target.value)} aria-label="Регион"><option value="all">Все регионы</option>{regions.map(item=><option key={item}>{item}</option>)}</select><span className="toolbar-count">{rows.length} из {employees.length}</span></div><div className="directory-layout"><div className="grid-scroll"><table className="data-table employee-table"><thead><tr><th>Сотрудник</th><th>Должность</th><th>Подразделение</th><th>Регион</th><th>Отвечает</th><th>Контакты</th><th>Статус</th></tr></thead><tbody>{rows.map(item=><tr key={item.id} onClick={()=>setSelected(item)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setSelected(item)}}} tabIndex={0} aria-label={`Открыть карточку ${item.name}`} className={selected?.id===item.id?"selected":""}><td><span className="cell-title">{item.name}</span><span className="cell-sub">{item.roles.map(r=>r.name).join(" · ")||"Основная должность"}</span></td><td>{item.position??"—"}</td><td>{item.orgUnit??"—"}</td><td>{item.region??"Вся компания"}</td><td>{item.responsibilities.slice(0,2).join(" · ")||"—"}</td><td><span className="contact-line"><Phone size={12}/>{item.phone??"—"}</span><span className="contact-line"><Mail size={12}/>{item.email??"—"}</span></td><td><Status tone={item.status==="active"?"good":"warn"}>{item.status}</Status></td></tr>)}</tbody></table></div>{selected&&<aside className="directory-detail" aria-label={`Карточка сотрудника ${selected.name}`}><h2>{selected.name}</h2><p>{selected.position} · {selected.orgUnit}</p><dl><div><dt>Руководитель</dt><dd>{selected.manager??"Не назначен"}</dd></div><div><dt>Процессные роли</dt><dd>{selected.roles.map(r=>r.name).join(", ")||"Нет"}</dd></div></dl><h3>Зона ответственности</h3><ul>{selected.responsibilities.map(item=><li key={item}>{item}</li>)}</ul></aside>}</div></div>;
}
