"use client";

import { useEffect, useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Mail, MoreHorizontal, Phone, Search, ShieldCheck, X } from "lucide-react";
import type { AccessSourceRow, CompanyEmployeeRow, PositionAssignmentRow } from "@/lib/organization/types";
import { Status } from "@/components/UI";

type Tab = "overview" | "assignments" | "roles" | "access" | "objects" | "history";
const statusLabels: Record<string, string> = { active: "Активен", invited: "Приглашён", suspended: "Неактивен" };
const scopeLabels: Record<string, string> = { all_org: "Вся компания", self: "Свои записи", org_unit: "Подразделение", region: "Регион", team: "Команда", objects: "Объекты", clients: "Клиенты", assigned_to_me: "Назначено мне", own_created: "Создано мной" };
const sourceLabels: Record<string, string> = { role_template: "Шаблон доступа", job_profile: "Профиль должности", process_role: "Процессная роль", individual: "Индивидуально" };

export function EmployeeDirectory({ employees, assignments }: { employees: CompanyEmployeeRow[]; assignments: PositionAssignmentRow[] }) {
  const params = () => typeof window === "undefined" ? null : new URL(window.location.href).searchParams;
  const [query, setQuery] = useState(() => params()?.get("q") ?? ""); const [unit, setUnit] = useState(() => params()?.get("unit") ?? "all"); const [region, setRegion] = useState(() => params()?.get("region") ?? "all"); const [status, setStatus] = useState("all");
  const [sort, setSort] = useState<"name" | "unit" | "status">("name"); const [page, setPage] = useState(1); const [selected, setSelected] = useState<CompanyEmployeeRow | null>(() => { const id = params()?.get("employee"); return employees.find((item) => item.id === id) ?? null; }); const [tab, setTab] = useState<Tab>("overview"); const pageSize = 20;
  useEffect(() => { const url = new URL(window.location.href); if (query) url.searchParams.set("q", query); else url.searchParams.delete("q"); if (unit !== "all") url.searchParams.set("unit", unit); else url.searchParams.delete("unit"); if (region !== "all") url.searchParams.set("region", region); else url.searchParams.delete("region"); if (selected) url.searchParams.set("employee", selected.id); else url.searchParams.delete("employee"); window.history.replaceState(null, "", url); }, [query, unit, region, selected]);
  const units = [...new Set(employees.map((item) => item.orgUnit).filter(Boolean))] as string[]; const regions = [...new Set(employees.map((item) => item.region).filter(Boolean))] as string[];
  const filtered = useMemo(() => employees.filter((item) => (!query || [item.name, item.email, item.phone, item.position, item.primaryStaffPosition, item.manager].join(" ").toLowerCase().includes(query.toLowerCase())) && (unit === "all" || item.orgUnit === unit) && (region === "all" || item.region === region) && (status === "all" || item.status === status)).sort((a, b) => sort === "unit" ? (a.orgUnit ?? "").localeCompare(b.orgUnit ?? "", "ru") : sort === "status" ? a.status.localeCompare(b.status) : a.name.localeCompare(b.name, "ru")), [employees, query, unit, region, status, sort]);
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const rows = filtered.slice((page - 1) * pageSize, page * pageSize);
  function choose(item: CompanyEmployeeRow) { setSelected(item); setTab("overview"); }
  return <div className="directory-workspace">
    <div className="registry-toolbar"><label className="toolbar-search"><Search size={15} /><span className="sr-only">Поиск сотрудников</span><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="ФИО, позиция, email или руководитель" /></label><select value={unit} onChange={(event) => { setUnit(event.target.value); setPage(1); }} aria-label="Подразделение"><option value="all">Все подразделения</option>{units.map((item) => <option key={item}>{item}</option>)}</select><select value={region} onChange={(event) => { setRegion(event.target.value); setPage(1); }} aria-label="Регион"><option value="all">Все регионы</option>{regions.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} aria-label="Статус"><option value="all">Все статусы</option><option value="active">Активные</option><option value="invited">Приглашённые</option><option value="suspended">Неактивные</option></select><select value={sort} onChange={(event) => { setSort(event.target.value as typeof sort); setPage(1); }} aria-label="Сортировка"><option value="name">По имени</option><option value="unit">По подразделению</option><option value="status">По статусу</option></select><span className="toolbar-count">{filtered.length} из {employees.length}</span></div>
    <div className="grid-scroll"><table className="data-table employee-table"><thead><tr><th>Сотрудник</th><th>Основная штатная позиция</th><th>Подразделение</th><th>Регион</th><th>Руководитель</th><th>Доп. назначения</th><th>Процессные роли</th><th>Объекты</th><th>Статус</th><th aria-label="Действия" /></tr></thead><tbody>{rows.map((item) => <tr key={item.id} onClick={() => choose(item)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); choose(item); } }} tabIndex={0} aria-label={`Открыть карточку ${item.name}`} className={selected?.id === item.id ? "selected" : ""}><td><span className="cell-title">{item.name}</span><span className="cell-sub">{item.email ?? "Email не указан"}</span></td><td>{item.primaryStaffPosition ?? item.position ?? "—"}</td><td>{item.orgUnit ?? "—"}</td><td>{item.region ?? "Вся компания"}</td><td>{item.manager ?? "Не назначен"}</td><td className="num">{item.additionalAssignments ?? 0}</td><td><span className="cell-title">{item.roles.length}</span><span className="cell-sub">{item.roles.slice(0, 2).map((role) => role.name).join(" · ") || "Нет"}</span></td><td className="num">{item.objectCount ?? item.responsibilities.filter((value) => /объект|склад|рц/i.test(value)).length}</td><td><Status tone={item.status === "active" ? "good" : item.status === "invited" ? "info" : "neutral"}>{statusLabels[item.status] ?? item.status}</Status></td><td><button type="button" className="icon-button" onClick={(event) => { event.stopPropagation(); choose(item); }} aria-label={`Действия: ${item.name}`}><MoreHorizontal size={15} /></button></td></tr>)}</tbody></table>{rows.length === 0 && <div className="registry-empty"><strong>Сотрудники не найдены</strong><span>Измените запрос или снимите часть фильтров.</span></div>}</div>
    <footer className="registry-pagination"><span>{filtered.length ? `${(page - 1) * pageSize + 1}–${Math.min(page * pageSize, filtered.length)} из ${filtered.length}` : "0 сотрудников"}</span><div><button type="button" className="icon-button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)} aria-label="Предыдущая страница"><ChevronLeft size={15} /></button><span>{page} / {pages}</span><button type="button" className="icon-button" disabled={page >= pages} onClick={() => setPage((value) => value + 1)} aria-label="Следующая страница"><ChevronRight size={15} /></button></div></footer>
    {selected && <EmployeeDrawer employee={selected} assignments={assignments.filter((item) => item.membershipId === selected.id)} tab={tab} onTab={setTab} onClose={() => setSelected(null)} />}
  </div>;
}

function EmployeeDrawer({ employee, assignments, tab, onTab, onClose }: { employee: CompanyEmployeeRow; assignments: PositionAssignmentRow[]; tab: Tab; onTab: (tab: Tab) => void; onClose: () => void }) {
  const [access, setAccess] = useState<AccessSourceRow[] | null>(null); const [accessError, setAccessError] = useState("");
  useEffect(() => { if (tab !== "access" || access) return; let active = true; fetch(`/api/organization/employees/${employee.id}/access`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); if (active) setAccess(body.items); }).catch((error) => active && setAccessError(error.message ?? "Не удалось загрузить доступ")); return () => { active = false; }; }, [tab, employee.id, access]);
  return <aside className="employee-drawer" aria-label={`Карточка сотрудника ${employee.name}`}><header><div><span className="avatar large">{employee.name.split(" ").map((value) => value[0]).join("").slice(0, 2)}</span><span><h2>{employee.name}</h2><p>{employee.primaryStaffPosition ?? employee.position ?? "Позиция не назначена"}</p><Status tone={employee.status === "active" ? "good" : "neutral"}>{statusLabels[employee.status] ?? employee.status}</Status></span></div><button type="button" className="icon-button" onClick={onClose} aria-label="Закрыть карточку"><X size={16} /></button></header>
    <nav className="drawer-tabs" aria-label="Разделы сотрудника">{(["overview", "assignments", "roles", "access", "objects", "history"] as Tab[]).map((item) => <button type="button" key={item} className={tab === item ? "active" : ""} onClick={() => onTab(item)}>{item === "overview" ? "Обзор" : item === "assignments" ? "Назначения" : item === "roles" ? "Роли" : item === "access" ? "Доступ" : item === "objects" ? "Объекты" : "История"}</button>)}</nav>
    <div className="employee-drawer-body">{tab === "overview" && <><dl><Fact label="Подразделение" value={employee.orgUnit ?? "Не назначено"} /><Fact label="Регион" value={employee.region ?? "Вся компания"} /><Fact label="Руководитель" value={employee.manager ?? "Не назначен"} /></dl><section><h3>Контакты</h3><p className="contact-line"><Mail size={13} />{employee.email ?? "Не указан"}</p><p className="contact-line"><Phone size={13} />{employee.phone ?? "Не указан"}</p></section></>}
      {tab === "assignments" && <section><h3>Штатные назначения</h3>{assignments.length ? <div className="drawer-list">{assignments.map((item) => <div key={item.id}><strong>{item.employeeName}</strong><small>{item.assignmentType === "primary" ? "Основное" : item.assignmentType === "additional" ? "Дополнительное" : "И. о."} · {item.fte} FTE · {item.effectiveFrom} — {item.effectiveTo ?? "бессрочно"}</small></div>)}</div> : <p>Штатные назначения не созданы.</p>}</section>}
      {tab === "roles" && <><section><h3>Процессные роли</h3><div className="tag-list">{employee.roles.length ? employee.roles.map((role) => <span key={role.id}>{role.name}</span>) : <span>Нет ролей</span>}</div></section><section><h3>Фактическая ответственность</h3>{employee.responsibilities.length ? <ul>{employee.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Не назначена.</p>}</section></>}
      {tab === "access" && <section><h3>Происхождение эффективного доступа</h3>{accessError && <p className="form-message">{accessError}</p>}{access === null && !accessError && <p>Загрузка источников доступа…</p>}{access?.length === 0 && <p>В деморежиме подробные grants не загружаются. Эффективный доступ роли уже ограничивает экран.</p>}{access && access.length > 0 && <div className="access-provenance">{access.map((item, index) => <div key={`${item.capability}-${item.sourceType}-${index}`}><ShieldCheck size={14} /><span><strong>{item.label}</strong><small>{sourceLabels[item.sourceType]} · {item.sourceName} · {scopeLabels[item.scopeType ?? ""] ?? item.scopeType ?? "Без области"}</small></span><Status tone={item.effect === "deny" ? "bad" : item.sourceType === "individual" ? "warn" : "good"}>{item.effect === "deny" ? "Запрещено" : "Разрешено"}</Status></div>)}</div>}</section>}
      {tab === "objects" && <section><h3>Связанные объекты</h3><p>Связи определяются процессными ролями и областями ответственности. В карточке показано {employee.objectCount ?? employee.responsibilities.filter((value) => /объект|склад|рц/i.test(value)).length} доступных объектов.</p></section>}
      {tab === "history" && <section><h3>История сотрудника</h3><p>Переводы, назначения, роли и индивидуальные исключения фиксируются в системном журнале с автором и датой.</p></section>}</div>
  </aside>;
}

function Fact({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
