"use client";

import {createPortal} from "react-dom";
import {useMemo,useState} from "react";
import {Plus,X} from "lucide-react";
import type {InventoryItemRow,InventorySnapshot,OperationsReferenceData} from "@/lib/operations/service";
import {rub} from "@/lib/ui/format";

const categoryLabels:Record<string,string>={workwear:"Спецодежда",ppe:"СИЗ",tool:"Инструмент",equipment:"Оборудование",consumable:"Расходник",other:"Другое"};
const sizeModeLabels:Record<string,string>={none:"Без размера",clothing:"Размер одежды",shoe:"Размер обуви",manual:"Другой вариант"};
const locationLabels:Record<string,string>={office:"Офис",manager:"Запас менеджера",object:"Объект",housing:"Жильё",vehicle:"Автомобиль",other:"Другое"};
const priceSourceLabels:Record<string,string>={manual:"Нормативная цена",purchase:"По закупке",supplier:"Цена поставщика",opening:"Начальный ориентир"};

type ItemModal="create"|"edit"|"variant"|"price"|null;

export function InventoryItemsWorkspace({snapshot,canManage,demo}:{snapshot:InventorySnapshot;canManage:boolean;demo:boolean}){
  const [modal,setModal]=useState<ItemModal>(null);
  const [selected,setSelected]=useState<InventoryItemRow|null>(null);
  const [name,setName]=useState(""); const [code,setCode]=useState(""); const [category,setCategory]=useState("workwear"); const [unit,setUnit]=useState("шт");
  const [returnable,setReturnable]=useState(true); const [sizeMode,setSizeMode]=useState<"none"|"clothing"|"shoe"|"manual">("none"); const [cycle,setCycle]=useState(""); const [notes,setNotes]=useState("");
  const [variantLabel,setVariantLabel]=useState(""); const [variantCode,setVariantCode]=useState("");
  const [price,setPrice]=useState(""); const [priceDate,setPriceDate]=useState(new Date().toISOString().slice(0,10)); const [priceSource,setPriceSource]=useState("manual");
  const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const rows=useMemo(()=>snapshot.items.slice().sort((a,b)=>a.name.localeCompare(b.name,"ru")),[snapshot.items]);

  function openCreate(){setSelected(null);setName("");setCode("");setCategory("workwear");setUnit("шт");setReturnable(true);setSizeMode("none");setCycle("");setNotes("");setError("");setModal("create")}
  function openEdit(item:InventoryItemRow){setSelected(item);setName(item.name);setCode(item.code??"");setCategory(item.category);setUnit(item.unit);setReturnable(item.returnable);setSizeMode(item.sizeMode);setCycle(item.defaultReplacementCycleDays==null?"":String(item.defaultReplacementCycleDays));setNotes(item.notes??"");setError("");setModal("edit")}
  function openVariant(item:InventoryItemRow){setSelected(item);setVariantLabel("");setVariantCode("");setError("");setModal("variant")}
  function openPrice(item:InventoryItemRow){setSelected(item);setPrice(item.currentPrice==null?"":String(item.currentPrice));setPriceDate(new Date().toISOString().slice(0,10));setPriceSource("manual");setError("");setModal("price")}

  async function request(url:string,body:unknown,method="POST"){
    if(demo){setError("Изменения в демо-режиме недоступны");return false}
    const response=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const json=await response.json().catch(()=>({}));
    if(!response.ok)throw new Error(json.error??"Операция не выполнена");window.location.reload();return true;
  }
  async function saveItem(){setBusy(true);setError("");try{const payload={name,code:code||null,category,unit,returnable,tracksVariant:sizeMode!=="none",sizeMode,defaultReplacementCycleDays:cycle?Number(cycle):null,notes:notes||null};if(modal==="create")await request("/api/assets/items",payload);else if(selected)await request("/api/assets/items/"+selected.id,{action:"update",...payload},"PATCH")}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить товар")}finally{setBusy(false)}}
  async function saveVariant(){if(!selected)return;setBusy(true);setError("");try{await request("/api/assets/items/"+selected.id,{action:"add_variant",label:variantLabel,code:variantCode||null},"PATCH")}catch(e){setError(e instanceof Error?e.message:"Не удалось добавить размер")}finally{setBusy(false)}}
  async function savePrice(){if(!selected)return;setBusy(true);setError("");try{await request("/api/assets/items/"+selected.id,{action:"add_price",unitCost:Number(price),effectiveFrom:priceDate,variantId:null,source:priceSource,partnerId:null,notes:null},"PATCH")}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить стоимость")}finally{setBusy(false)}}

  return <section className="section section-flush inventory-directory-section">
    <div className="section-head"><div><h2>Товары и материалы</h2><p>Единая номенклатура компании: параметры учёта, размеры, период выдачи и нормативная стоимость.</p></div>{canManage&&<button className="button primary" type="button" onClick={openCreate}><Plus size={14}/> Добавить товар</button>}</div>
    <div className="request-table-wrap"><table className="data-table inventory-items-table"><thead><tr><th>Товар</th><th>Категория</th><th>Учёт</th><th>Период выдачи</th><th>Текущая стоимость</th><th>Размеры / варианты</th><th>Годно на складе</th>{canManage&&<th>Действия</th>}</tr></thead>
      <tbody>{rows.map(item=>{const variants=snapshot.variants.filter(row=>row.itemId===item.id&&row.active);const usable=snapshot.balances.filter(row=>row.itemId===item.id).reduce((sum,row)=>sum+row.usableQuantity,0);return <tr key={item.id}>
        <td><strong className="cell-title">{item.name}</strong><span className="cell-sub">{item.code??item.unit}</span></td><td>{categoryLabels[item.category]??"Другое"}</td>
        <td>{item.returnable?"Возвратное имущество":"Расходуется"}<span className="cell-sub">{sizeModeLabels[item.sizeMode]??"Без размера"}</span></td>
        <td>{item.defaultReplacementCycleDays?item.defaultReplacementCycleDays+" дн.":"Не задан"}<span className="cell-sub">{item.category==="consumable"?"повторная выдача":"нормативный период"}</span></td>
        <td className="num">{item.currentPrice==null?"—":rub(item.currentPrice)}{item.currentPriceEffectiveFrom&&<span className="cell-sub">с {formatDate(item.currentPriceEffectiveFrom)}</span>}</td>
        <td>{variants.length?variants.slice(0,6).map(row=>row.label).join(", "):item.tracksVariant?"Не заведены":"Не требуется"}{variants.length>6&&<span className="cell-sub">ещё {variants.length-6}</span>}</td><td className="num">{usable} {item.unit}</td>
        {canManage&&<td><div className="inventory-directory-actions"><button className="table-link" onClick={()=>openEdit(item)}>Изменить</button>{item.tracksVariant&&<button className="table-link" onClick={()=>openVariant(item)}>Добавить размер</button>}<button className="table-link" onClick={()=>openPrice(item)}>Новая цена</button></div></td>}
      </tr>})}</tbody></table>{!rows.length&&<div className="empty-inline">Номенклатура ещё не создана.</div>}</div>

    {(modal==="create"||modal==="edit")&&<AssetModal title={modal==="create"?"Новый товар":"Параметры товара"} text="Эти данные используются складом, комплектами по профессиям и расчётным контуром." onClose={()=>setModal(null)} footer={<><button className="button" onClick={()=>setModal(null)}>Отмена</button><button className="button primary" disabled={busy||name.trim().length<2||!unit.trim()} onClick={()=>void saveItem()}>{modal==="create"?"Создать":"Сохранить"}</button></>}>
      <div className="form-grid two"><label className="span-2"><span>Название</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Код</span><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Необязательно"/></label><label><span>Категория</span><select value={category} onChange={e=>{const value=e.target.value;setCategory(value);if(value==="consumable")setReturnable(false)}}>{Object.entries(categoryLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Единица учёта</span><input value={unit} onChange={e=>setUnit(e.target.value)} placeholder="шт, пар, компл."/></label><label><span>Размерный учёт</span><select value={sizeMode} onChange={e=>setSizeMode(e.target.value as typeof sizeMode)}>{Object.entries(sizeModeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Период повторной выдачи, дней</span><input type="number" min="1" max="3650" value={cycle} onChange={e=>setCycle(e.target.value)} placeholder="Например 180"/></label><label className="operations-check"><input type="checkbox" checked={returnable} onChange={e=>setReturnable(e.target.checked)}/><span>Возвратное имущество</span></label><label className="span-2"><span>Комментарий</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Особенности учёта или выдачи"/></label></div>{error&&<div className="recruiting-error">{error}</div>}
    </AssetModal>}
    {modal==="variant"&&selected&&<AssetModal title="Размер или вариант" text={selected.name} onClose={()=>setModal(null)} footer={<><button className="button" onClick={()=>setModal(null)}>Отмена</button><button className="button primary" disabled={busy||!variantLabel.trim()} onClick={()=>void saveVariant()}>Добавить</button></>}><div className="form-grid two"><label><span>Размер / вариант</span><input value={variantLabel} onChange={e=>setVariantLabel(e.target.value)} placeholder="Например 43 или 52"/></label><label><span>Код</span><input value={variantCode} onChange={e=>setVariantCode(e.target.value)} placeholder="Необязательно"/></label></div>{error&&<div className="recruiting-error">{error}</div>}</AssetModal>}
    {modal==="price"&&selected&&<AssetModal title="Новая стоимость" text={selected.name+" · цена сохраняется исторически и действует с выбранной даты."} onClose={()=>setModal(null)} footer={<><button className="button" onClick={()=>setModal(null)}>Отмена</button><button className="button primary" disabled={busy||price===""||!priceDate} onClick={()=>void savePrice()}>Сохранить цену</button></>}><div className="form-grid two"><label><span>Стоимость за {selected.unit}</span><input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label><span>Действует с</span><input type="date" value={priceDate} onChange={e=>setPriceDate(e.target.value)}/></label><label className="span-2"><span>Источник</span><select value={priceSource} onChange={e=>setPriceSource(e.target.value)}>{Object.entries(priceSourceLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{error&&<div className="recruiting-error">{error}</div>}</AssetModal>}
  </section>;
}

export function StorageLocationsWorkspace({snapshot,options,canManage,demo,managerId,objectId}:{snapshot:InventorySnapshot;options:OperationsReferenceData;canManage:boolean;demo:boolean;managerId:string;objectId:string}){
  const [show,setShow]=useState(false);const [name,setName]=useState("");const [kind,setKind]=useState("manager");const [locationObjectId,setLocationObjectId]=useState(objectId);const [description,setDescription]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const rows=useMemo(()=>snapshot.locations.filter(row=>(!managerId||row.ownerUserId===managerId)&&(!objectId||row.objectId===objectId)),[snapshot.locations,managerId,objectId]);
  async function save(){setBusy(true);setError("");try{if(demo){setError("Изменения в демо-режиме недоступны");return}const response=await fetch("/api/assets/locations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,kind,objectId:kind==="object"?locationObjectId||null:null,description:description||null})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось создать место хранения");window.location.reload()}catch(e){setError(e instanceof Error?e.message:"Не удалось создать место хранения")}finally{setBusy(false)}}
  return <section className="section section-flush inventory-directory-section">
    <div className="section-head"><div><h2>Места хранения</h2><p>Офисный склад, запасы менеджеров, объекты, автомобили и другие точки хранения.</p></div>{canManage&&<button className="button primary" type="button" onClick={()=>{setError("");setShow(true)}}><Plus size={14}/> Добавить место</button>}</div>
    <div className="request-table-wrap"><table className="data-table inventory-locations-table"><thead><tr><th>Место хранения</th><th>Тип</th><th>Ответственный</th><th>Объект</th><th>Позиций</th><th>Годно к выдаче</th><th>Обслуживание / ремонт</th><th>Контроль запаса</th></tr></thead><tbody>{rows.map(location=>{const balances=snapshot.balances.filter(row=>row.locationId===location.id);const usable=balances.reduce((sum,row)=>sum+row.usableQuantity,0);const service=balances.reduce((sum,row)=>sum+row.serviceQuantity+row.repairQuantity,0);const low=balances.filter(row=>row.minQuantity>0&&row.usableQuantity<=row.minQuantity).length;return <tr key={location.id}><td><strong className="cell-title">{location.name}</strong><span className="cell-sub">{location.description??"—"}</span></td><td>{locationLabels[location.kind]??"Другое"}</td><td>{location.responsible??"—"}</td><td>{location.object??"—"}</td><td className="num">{balances.length}</td><td className="num">{usable}</td><td className="num">{service}</td><td>{low?low+" поз. ниже минимума":"Отклонений нет"}</td></tr>})}</tbody></table>{!rows.length&&<div className="empty-inline">Места хранения по выбранному контуру не найдены.</div>}</div>
    {show&&<AssetModal title="Место хранения" text="Создайте реальную точку, где физически хранится имущество компании." onClose={()=>setShow(false)} footer={<><button className="button" onClick={()=>setShow(false)}>Отмена</button><button className="button primary" disabled={busy||name.trim().length<2} onClick={()=>void save()}>Создать</button></>}><div className="form-grid two"><label className="span-2"><span>Название</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Например, склад офиса или запас менеджера"/></label><label><span>Тип</span><select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(locationLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{kind==="object"&&<label><span>Объект</span><select value={locationObjectId} onChange={e=>setLocationObjectId(e.target.value)}><option value="">Выберите</option>{options.objects.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>}<label className="span-2"><span>Комментарий</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Адрес, зона хранения или пояснение"/></label></div>{error&&<div className="recruiting-error">{error}</div>}</AssetModal>}
  </section>;
}

function AssetModal({title,text,onClose,footer,children}:{title:string;text?:string;onClose:()=>void;footer:React.ReactNode;children:React.ReactNode}){return <Portal><div className="recruiting-modal inventory-modal" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><div className="recruiting-modal-card inventory-modal-card"><div className="recruiting-modal-head"><div><h2>{title}</h2>{text&&<p>{text}</p>}</div><button className="icon-button" onClick={onClose}><X size={17}/></button></div><div className="candidate-import-body inventory-modal-body">{children}</div><div className="recruiting-modal-footer">{footer}</div></div></div></Portal>}
function Portal({children}:{children:React.ReactNode}){return typeof document==="undefined"?null:createPortal(children,document.body)}
function formatDate(value:string){const date=new Date(value+"T00:00:00");return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("ru-RU").format(date)}
