"use client";

import {useState} from "react";
import {useRouter} from "next/navigation";
import {Plus,X} from "lucide-react";
import type {IncidentRow,WorkerRow} from "@/lib/data/service";
import {rub} from "@/lib/ui/format";
import {Status} from "@/components/UI";

const typeLabels:Record<string,string>={discipline:"Дисциплина",attendance:"Выход / посещаемость",quality:"Качество",safety:"Охрана труда",property:"Имущество",client:"Требование заказчика",other:"Другое"};
const severityLabels:Record<string,string>={normal:"Обычный",medium:"Средний",high:"Высокий",critical:"Критический"};
const statusLabels:Record<string,string>={open:"Открыт",in_progress:"В работе",resolved:"Разрешён",closed:"Закрыт"};
const financialLabels:Record<string,string>={none:"Нет",proposed:"Предложено",approved:"Согласовано",rejected:"Отклонено",applied:"Применено"};
const financialKindLabels:Record<string,string>={worker_adjustment:"Корректировка сотруднику",company_expense:"Расход компании",client_claim:"Претензия клиенту"};

export function ObjectQualityWorkspace({objectId,rows,workers,canEdit,canFinance,demo}:{objectId:string;rows:IncidentRow[];workers:WorkerRow[];canEdit:boolean;canFinance:boolean;demo:boolean}){
 const router=useRouter();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [state,setState]=useState("");const [scope,setScope]=useState<"active"|"all"|"closed">("active");const [workerId,setWorkerId]=useState("");const [type,setType]=useState("discipline");const [severity,setSeverity]=useState("normal");const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [occurredAt,setOccurredAt]=useState(()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16));const [amount,setAmount]=useState("");const [financialKind,setFinancialKind]=useState("worker_adjustment");const [basis,setBasis]=useState("");const filteredRows=rows.filter(row=>scope==="all"||scope==="active"?!["resolved","closed"].includes(row.status):["resolved","closed"].includes(row.status));
 async function create(){if(amount&&financialKind==="worker_adjustment"&&!workerId){setState("Для корректировки сотруднику сначала выберите сотрудника");return}setBusy(true);setState("");try{if(demo){setState("В демо-режиме изменения не сохраняются");return}const response=await fetch("/api/incidents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({objectId,workerId:workerId||null,incidentType:type,severity,title,description,occurredAt:new Date(occurredAt).toISOString(),financialEffectAmount:amount?Number(amount):null,financialEffectKind:amount?financialKind:null,financialEffectBasis:basis||null})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось создать инцидент");setOpen(false);router.refresh()}catch(e){setState(e instanceof Error?e.message:"Не удалось создать инцидент")}finally{setBusy(false)}}
 async function close(id:string){setBusy(true);try{if(demo){setState("В демо-режиме изменения не сохраняются");return}const response=await fetch(`/api/incidents/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:"resolved",resolution:"Закрыто менеджером объекта"})});if(!response.ok){const json=await response.json().catch(()=>({}));throw new Error(json.error??"Не удалось закрыть инцидент")}router.refresh()}catch(e){setState(e instanceof Error?e.message:"Не удалось закрыть инцидент")}finally{setBusy(false)}}
 async function financialAction(id:string,status:"approved"|"rejected"|"applied"){setBusy(true);setState("");try{if(demo){setState("В демо-режиме изменения не сохраняются");return}const response=await fetch(`/api/incidents/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({financialEffectStatus:status})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось обновить финансовое последствие");router.refresh()}catch(e){setState(e instanceof Error?e.message:"Не удалось обновить финансовое последствие")}finally{setBusy(false)}}
 return <div className="object-quality-workspace">
   <div className="object-quality-toolbar"><div className="segmented-control"><button className={scope==="active"?"active":""} onClick={()=>setScope("active")}>Открытые</button><button className={scope==="all"?"active":""} onClick={()=>setScope("all")}>Все</button><button className={scope==="closed"?"active":""} onClick={()=>setScope("closed")}>Закрытые</button></div>{canEdit&&<button className="button primary" onClick={()=>setOpen(true)}><Plus size={14}/> Зафиксировать инцидент</button>}</div>
   {state&&!open&&<div className="object-staffing-message">{state}</div>}
   <div className="request-table-wrap"><table className="data-table object-quality-table"><thead><tr><th>Инцидент</th><th>Дата</th><th>Сотрудник</th><th>Тип</th><th>Финансовое последствие</th><th>Ответственный</th><th>Статус</th><th></th></tr></thead><tbody>{filteredRows.map(row=><tr key={row.id}><td><strong className="cell-title">{row.title}</strong><span className="cell-sub">{row.description}</span></td><td>{row.occurredAt}</td><td>{row.worker??"—"}</td><td>{typeLabels[row.type]??"Другое"}<span className="cell-sub">{severityLabels[row.severity]??"Обычный"}</span></td><td>{Number(row.financialEffectAmount??0)>0?<div className="incident-finance-cell"><strong>{rub(Number(row.financialEffectAmount))}</strong><span>{financialKindLabels[row.financialEffectKind??"worker_adjustment"]??"Финансовое последствие"}</span><small>{financialLabels[row.financialEffectStatus??"proposed"]}</small>{canFinance&&row.financialEffectStatus==="proposed"&&<div className="incident-finance-actions"><button className="button ghost" disabled={busy} onClick={()=>void financialAction(row.id,"approved")}>Согласовать</button><button className="button ghost" disabled={busy} onClick={()=>void financialAction(row.id,"rejected")}>Отклонить</button></div>}{canFinance&&row.financialEffectStatus==="approved"&&row.financialEffectKind!=="client_claim"&&<button className="button ghost" disabled={busy} onClick={()=>void financialAction(row.id,"applied")}>Применить</button>}</div>:"—"}</td><td>{row.responsible??"—"}</td><td><Status tone={row.status==="resolved"||row.status==="closed"?"good":row.severity==="critical"?"bad":row.severity==="high"?"warn":"info"}>{statusLabels[row.status]??"Открыт"}</Status></td><td>{canEdit&&!["resolved","closed"].includes(row.status)&&<button className="button ghost" disabled={busy} onClick={()=>void close(row.id)}>Закрыть</button>}</td></tr>)}{!filteredRows.length&&<tr><td colSpan={8}><div className="empty-inline">{scope==="active"?"Открытых инцидентов нет":"Инцидентов по выбранному фильтру нет"}</div></td></tr>}</tbody></table></div>
   {open&&<div className="drawer-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><aside className="drawer object-quality-drawer"><div className="drawer-head"><div><strong>Новый инцидент</strong><span>Финансовое последствие фиксируется как предложение и не удерживается автоматически.</span></div><button className="icon-button" onClick={()=>setOpen(false)}><X size={16}/></button></div><div className="drawer-body"><div className="form-grid two"><label><span>Сотрудник</span><select value={workerId} onChange={e=>setWorkerId(e.target.value)}><option value="">Без сотрудника</option>{workers.map(worker=><option key={worker.id} value={worker.id}>{worker.fullName} · {worker.specialty??"без специальности"}</option>)}</select></label><label><span>Дата и время</span><input type="datetime-local" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)}/></label><label><span>Тип</span><select value={type} onChange={e=>setType(e.target.value)}>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Приоритет</span><select value={severity} onChange={e=>setSeverity(e.target.value)}>{Object.entries(severityLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="span-2"><span>Название *</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Например: невыход без предупреждения"/></label><label className="span-2"><span>Описание *</span><textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Что произошло и что нужно сделать"/></label><label><span>Предлагаемая сумма, ₽</span><input type="number" min="0" step="100" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Необязательно"/></label><label><span>Куда относится</span><select value={financialKind} onChange={e=>setFinancialKind(e.target.value)} disabled={!amount}><option value="worker_adjustment">Корректировка сотруднику</option><option value="company_expense">Расход компании</option><option value="client_claim">Претензия клиенту</option></select></label><label className="span-2"><span>Основание</span><input value={basis} onChange={e=>setBasis(e.target.value)} placeholder="Правило / договор / комментарий"/></label></div>{state&&<p className="form-error">{state}</p>}</div><div className="drawer-footer"><button className="button" onClick={()=>setOpen(false)}>Отмена</button><button className="button primary" disabled={busy||!title.trim()||!description.trim()} onClick={()=>void create()}>{busy?"Сохраняю…":"Зафиксировать"}</button></div></aside></div>}
 </div>
}