"use client";

import {useMemo,useState} from "react";
import Link from "next/link";
import type {AccrualRow,FinanceRow,IncidentRow,PaymentRow} from "@/lib/data/service";
import type {DailyPaymentProgressRow} from "@/lib/operations/service";
import {rub,pct} from "@/lib/ui/format";

type Mode="due"|"daily"|"history"|"economics";
type PaymentKind="salary"|"advance"|"other";
type PaymentMethod="transfer"|"cash"|"other";
const sourceLabels:Record<string,string>={finance:"Финансовый контур",object_manager:"Менеджер объекта",integration:"Интеграция",legacy:"Исторические данные"};
const reconciliationLabels:Record<string,string>={unreconciled:"Не сверено",confirmed:"Сверено",conflict:"Есть расхождение"};
const methodLabels:Record<string,string>={transfer:"Перевод",cash:"Наличные",other:"Другое"};
const paymentStatusLabels:Record<string,string>={planned:"Запланировано",approved:"Согласовано",paid:"Выплачено",rejected:"Отклонено",cancelled:"Отменено"};
export function ObjectFinanceWorkspace({objectId,pnl,accruals,payments,daily,incidents,objectDefaultDailyPaymentShifts,canConfirmDaily,canRecordPayment,canReconcilePayments,canEditWorker,demo}:{objectId:string;pnl:FinanceRow|null;accruals:AccrualRow[];payments:PaymentRow[];daily:DailyPaymentProgressRow[];incidents:IncidentRow[];objectDefaultDailyPaymentShifts:number;canConfirmDaily:boolean;canRecordPayment:boolean;canReconcilePayments:boolean;canEditWorker:boolean;demo:boolean}){
  const [mode,setMode]=useState<Mode>("due");const [rows,setRows]=useState(daily);const [busy,setBusy]=useState("");const [message,setMessage]=useState("");const today=new Date().toISOString().slice(0,10);const [paymentDate,setPaymentDate]=useState(today);const [reference,setReference]=useState("");const [paymentKind,setPaymentKind]=useState<PaymentKind>("salary");const [paymentMethod,setPaymentMethod]=useState<PaymentMethod>("transfer");const [batchAmounts,setBatchAmounts]=useState<Record<string,string>>({});const [defaultDailyLimit,setDefaultDailyLimit]=useState(objectDefaultDailyPaymentShifts);const [applyDailyToActive,setApplyDailyToActive]=useState(false);
  const meaningfulPayments=useMemo(()=>payments.filter(row=>Number(row.amount||0)>0),[payments]);const accrued=accruals.reduce((sum,row)=>sum+Number(row.total||0),0),paid=meaningfulPayments.filter(row=>row.status==="paid").reduce((sum,row)=>sum+Number(row.amount||0),0),balance=accrued-paid;const unreconciledPayments=meaningfulPayments.filter(row=>row.status==="paid"&&row.reconciliationStatus==="unreconciled"),unreconciledAmount=unreconciledPayments.reduce((sum,row)=>sum+Number(row.amount||0),0);const historyPayments=[...meaningfulPayments].sort((a,b)=>(b.dateIso??"").localeCompare(a.dateIso??"")||a.worker.localeCompare(b.worker,"ru"));
  const people=useMemo(()=>{const map=new Map<string,{workerId:string;worker:string;accrued:number;paid:number;planned:number;lastDate:string;dailyLimit:number}>();for(const row of accruals){const item=map.get(row.workerId)??{workerId:row.workerId,worker:row.worker,accrued:0,paid:0,planned:0,lastDate:"",dailyLimit:0};item.accrued+=Number(row.total||0);map.set(row.workerId,item)}for(const row of meaningfulPayments){const item=map.get(row.workerId)??{workerId:row.workerId,worker:row.worker,accrued:0,paid:0,planned:0,lastDate:"",dailyLimit:0};if(row.status==="paid"){item.paid+=Number(row.amount||0);if((row.dateIso??"")>item.lastDate)item.lastDate=row.dateIso??""}else if(row.status==="planned")item.planned+=Number(row.amount||0);map.set(row.workerId,item)}for(const row of rows){const item=map.get(row.workerId)??{workerId:row.workerId,worker:row.worker,accrued:0,paid:0,planned:0,lastDate:"",dailyLimit:0};item.dailyLimit=row.shiftLimit;map.set(row.workerId,item)}return [...map.values()].sort((a,b)=>a.worker.localeCompare(b.worker,"ru"))},[accruals,meaningfulPayments,rows]);
  const proposed=incidents.filter(row=>Number(row.financialEffectAmount??0)>0&&!["rejected","applied"].includes(row.financialEffectStatus??"proposed"));const dailyDates=[...new Set(rows.flatMap(worker=>worker.shifts.map(shift=>shift.workDate)))].sort().reverse();const [dailyDate,setDailyDate]=useState(()=>dailyDates[0]??today);const dayRows=rows.flatMap(worker=>{const shiftIndex=worker.shifts.findIndex(shift=>shift.workDate===dailyDate);if(shiftIndex<0)return[];return [{worker,shift:worker.shifts[shiftIndex],shiftIndex:shiftIndex+1}]}).sort((a,b)=>a.worker.worker.localeCompare(b.worker.worker,"ru"));
  function fillBalances(){setBatchAmounts(Object.fromEntries(people.filter(p=>p.accrued-p.paid>0).map(p=>[p.workerId,String(Math.max(p.accrued-p.paid,0))])))}
  async function recordPayments(){const items=people.map(p=>({workerId:p.workerId,amount:Number(batchAmounts[p.workerId]||0),paymentDate,reference:reference||null})).filter(x=>x.amount>0);if(!items.length){setMessage("Укажите хотя бы одну сумму");return}if(!window.confirm(`Сохранить ${items.length} выплат на ${formatDate(paymentDate)}?`))return;setBusy("batch");setMessage("");try{const response=await fetch(`/api/objects/${objectId}/payments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows:items,paymentKind,paymentMethod})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось сохранить выплаты");setMessage(`Сохранено выплат: ${items.length}. Факт учтён и ожидает сверки с финансовым контуром.`);setBatchAmounts({});if(!demo)window.location.reload()}catch(e){setMessage(e instanceof Error?e.message:"Не удалось сохранить выплаты")}finally{setBusy("")}}
  async function toggleDaily(workerId:string,workDate:string,paidState:boolean,amount:number){const key=`${workerId}:${workDate}`;setBusy(key);setMessage("");try{const response=await fetch(`/api/objects/${objectId}/daily-payments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workerId,workDate,amount,paid:paidState})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось сохранить выплату");setRows(current=>current.map(worker=>worker.workerId!==workerId?worker:{...worker,shifts:worker.shifts.map(shift=>shift.workDate!==workDate?shift:{...shift,paymentStatus:paidState?"paid":"planned",paymentAmount:amount,paymentDate:paidState?workDate:shift.paymentDate})}));setMessage(paidState?"Выплата подтверждена":"Подтверждение снято")}catch(e){setMessage(e instanceof Error?e.message:"Не удалось сохранить выплату")}finally{setBusy("")}}
  async function updateLimit(workerId:string,value:number){if(!canEditWorker)return;setBusy(`limit:${workerId}`);try{const response=await fetch(`/api/workers/${workerId}/assignment-settings`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({dailyPaymentShifts:value})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось изменить схему");setRows(current=>current.map(row=>row.workerId===workerId?{...row,shiftLimit:value,remaining:Math.max(value-row.workedCount,0)}:row));setMessage("Индивидуальная схема сотрудника обновлена");if(!demo)window.location.reload()}catch(e){setMessage(e instanceof Error?e.message:"Не удалось изменить схему")}finally{setBusy("")}}
  async function saveObjectDailyPolicy(){if(!canRecordPayment)return;setBusy("policy");setMessage("");try{const response=await fetch(`/api/objects/${objectId}/daily-payment-policy`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({defaultDailyPaymentShifts:defaultDailyLimit,applyToActive:applyDailyToActive})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось сохранить схему");if(applyDailyToActive)setRows(current=>current.map(row=>({...row,shiftLimit:defaultDailyLimit,remaining:Math.max(defaultDailyLimit-row.workedCount,0)})));setApplyDailyToActive(false);setMessage(applyDailyToActive?`Схема сохранена и применена к текущим сотрудникам: ${json.updatedAssignments??0}`:"Схема сохранена для новых назначений");if(!demo)window.location.reload()}catch(e){setMessage(e instanceof Error?e.message:"Не удалось сохранить схему")}finally{setBusy("")}}
  async function markDayPaid(){const items=dayRows.filter(item=>item.shift.paymentStatus!=="paid").map(item=>({workerId:item.worker.workerId,workDate:item.shift.workDate,amount:item.shift.suggestedAmount,paid:true}));if(!items.length){setMessage("За выбранную дату все выплаты уже отмечены");return}if(!window.confirm(`Отметить выплаченными ${items.length} выплат за ${formatDate(dailyDate)}?`))return;setBusy("daily-batch");setMessage("");try{const response=await fetch(`/api/objects/${objectId}/daily-payments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows:items})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось отметить выплаты");const keys=new Set(items.map(item=>`${item.workerId}:${item.workDate}`));setRows(current=>current.map(worker=>({...worker,shifts:worker.shifts.map(shift=>keys.has(`${worker.workerId}:${shift.workDate}`)?{...shift,paymentStatus:"paid",paymentAmount:shift.suggestedAmount,paymentDate:shift.workDate}:shift)})));setMessage(`Отмечено выплат: ${items.length}`)}catch(e){setMessage(e instanceof Error?e.message:"Не удалось отметить выплаты")}finally{setBusy("")}}
  async function reconcile(row:PaymentRow,status:"confirmed"|"conflict"){setBusy(`reconcile:${row.kind}:${row.id}`);setMessage("");try{const response=await fetch(`/api/objects/${objectId}/payments/reconcile`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({paymentId:row.id,kind:row.kind,status})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось обновить сверку");setMessage(status==="confirmed"?"Выплата подтверждена финансовым контуром":"По выплате отмечено расхождение");if(!demo)window.location.reload()}catch(e){setMessage(e instanceof Error?e.message:"Не удалось обновить сверку")}finally{setBusy("")}}
  return <div className="object-finance-workspace">
    <div className="object-finance-tabs"><button className={mode==="due"?"active":""} onClick={()=>setMode("due")}>К выплате</button><button className={mode==="daily"?"active":""} onClick={()=>setMode("daily")}>Ежедневные выплаты</button><button className={mode==="history"?"active":""} onClick={()=>setMode("history")}>История выплат</button><button className={mode==="economics"?"active":""} onClick={()=>setMode("economics")}>Экономика объекта</button></div>
    <div className="metrics-grid object-finance-metrics"><div className="metric"><span>Начислено</span><strong>{rub(accrued)}</strong><small>по текущим начислениям</small></div><div className="metric"><span>Выплачено</span><strong>{rub(paid)}</strong><small>подтверждённый факт</small></div><div className="metric"><span>{balance>=0?"К выплате":"Аванс / переплата"}</span><strong>{rub(Math.abs(balance))}</strong><small>{balance>=0?"без учёта запланированных":"превышение выплат над начислением"}</small></div><div className="metric"><span>На сверке</span><strong>{rub(unreconciledAmount)}</strong><small>{unreconciledPayments.length?`${unreconciledPayments.length} ${paymentWord(unreconciledPayments.length)}`:"расхождений нет"}</small></div></div>{message&&<div className="object-staffing-message">{message}</div>}
    {mode==="due"&&<>
      {canRecordPayment&&<div className="object-payment-entry">
        <div className="object-payment-entry-row">
          <div className="object-payment-entry-grid">
            <label>Тип выплаты<select value={paymentKind} onChange={e=>setPaymentKind(e.target.value as PaymentKind)}><option value="salary">Зарплата</option><option value="advance">Аванс</option><option value="other">Другая выплата</option></select></label>
            <label>Дата выплаты<input type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></label>
            <label>Способ<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value as PaymentMethod)}><option value="transfer">Перевод</option><option value="cash">Наличные</option><option value="other">Другое</option></select></label>
            <label className="object-payment-reference">Период / основание<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Например, зарплата 01–15.09 или аванс"/></label>
          </div>
          <div className="object-payment-entry-actions"><button className="button" type="button" onClick={fillBalances}>Заполнить остатки</button><button className="button" type="button" onClick={()=>setBatchAmounts({})}>Очистить</button><button className="button primary" type="button" disabled={busy==="batch"} onClick={()=>void recordPayments()}>{busy==="batch"?"Сохраняю…":"Сохранить выплаты"}</button></div>
        </div>
        <p className="object-finance-hint">Выплата, внесённая менеджером объекта, сразу учитывается в остатке сотрудника и остаётся «Не сверено», пока её не подтвердит финансовый контур.</p>
      </div>}
      <div className="request-table-wrap"><table className="data-table object-payment-batch"><thead><tr><th>Сотрудник</th><th>Начислено</th><th>Выплачено</th><th>Запланировано</th><th>Остаток</th><th>Последняя выплата</th><th>Ежедневная схема</th><th>Не сверено</th>{canRecordPayment&&<th>Получил сейчас</th>}</tr></thead><tbody>{people.map(row=>{const workerBalance=row.accrued-row.paid;const unrec=payments.filter(payment=>payment.workerId===row.workerId&&payment.status==="paid"&&payment.reconciliationStatus==="unreconciled").reduce((sum,payment)=>sum+Number(payment.amount||0),0);return <tr key={row.workerId}><td><Link className="cell-title" href={`/workers/${row.workerId}?tab=payments`}>{row.worker}</Link></td><td className="num">{rub(row.accrued)}</td><td className="num">{rub(row.paid)}</td><td className="num">{row.planned?rub(row.planned):"—"}</td><td className="num"><strong>{workerBalance>=0?rub(workerBalance):`Аванс ${rub(Math.abs(workerBalance))}`}</strong></td><td>{row.lastDate?formatDate(row.lastDate):"—"}</td><td>{row.dailyLimit?`первые ${row.dailyLimit} смен`:"Обычный цикл"}</td><td>{unrec?rub(unrec):"—"}</td>{canRecordPayment&&<td><input type="number" min="0" step="100" value={batchAmounts[row.workerId]??""} onChange={e=>setBatchAmounts(current=>({...current,[row.workerId]:e.target.value}))} placeholder="0"/></td>}</tr>})}</tbody></table></div>
    </>}
    {mode==="history"&&<div className="request-table-wrap"><table className="data-table object-payment-history-table"><thead><tr><th>Дата</th><th>Сотрудник</th><th>Тип</th><th>Сумма</th><th>Статус выплаты</th><th>Способ</th><th>Источник</th><th>Сверка</th><th>Основание</th>{canReconcilePayments&&<th></th>}</tr></thead><tbody>{historyPayments.map(row=><tr key={`${row.kind}:${row.id}`}><td>{row.date??"—"}</td><td>{row.worker}</td><td>{row.kind==="payment"?"Зарплата":row.purpose==="daily_shift"?"Ежедневная":row.purpose==="advance"?"Аванс":"Другая"}</td><td className="num">{rub(row.amount)}</td><td>{paymentStatusLabels[row.status]??"Неизвестно"}</td><td>{row.paymentMethod?methodLabels[row.paymentMethod]??"Другое":"—"}</td><td>{sourceLabels[row.recordSource??"legacy"]??"Источник не указан"}</td><td>{row.status==="paid"?<span className={`object-finance-reconciliation ${row.reconciliationStatus==="confirmed"?"is-confirmed":row.reconciliationStatus==="conflict"?"is-conflict":"is-pending"}`}>{reconciliationLabels[row.reconciliationStatus??"confirmed"]??"Сверено"}</span>:<span className="object-finance-muted">—</span>}</td><td>{paymentReferenceLabel(row.reference)}</td>{canReconcilePayments&&<td>{row.status==="paid"&&row.reconciliationStatus==="unreconciled"?<div className="object-reconcile-actions"><button className="button ghost" disabled={busy.startsWith("reconcile:")} onClick={()=>void reconcile(row,"confirmed")}>Сверено</button><button className="button ghost object-finance-conflict-action" disabled={busy.startsWith("reconcile:")} onClick={()=>void reconcile(row,"conflict")}>Расхождение</button></div>:""}</td>}</tr>)}</tbody></table></div>}
    {mode==="daily"&&<>
      <div className="object-daily-policy">
        <div><strong>Схема объекта</strong><span>Количество первых отработанных смен, которые по умолчанию оплачиваются ежедневно новым сотрудникам.</span></div>
        <label><span>Первые смены</span><input type="number" min="0" max="31" value={defaultDailyLimit} onChange={e=>setDefaultDailyLimit(Math.max(0,Math.min(31,Number(e.target.value)||0)))}/></label>
        {canRecordPayment&&<label className="object-finance-check"><input type="checkbox" checked={applyDailyToActive} onChange={e=>setApplyDailyToActive(e.target.checked)}/><span>Применить к текущим сотрудникам</span></label>}
        {canRecordPayment&&<button className="button primary" disabled={busy==="policy"} onClick={()=>void saveObjectDailyPolicy()}>Сохранить схему</button>}
      </div>
      <div className="object-daily-toolbar">
        <label>Дата<select value={dailyDate} onChange={e=>setDailyDate(e.target.value)}>{dailyDates.map(value=><option key={value} value={value}>{formatDate(value)}</option>)}</select></label>
        <span>{dayRows.length?`Выплат за день: ${dayRows.length}`:"Нет первых смен за выбранную дату"}</span>
        {canConfirmDaily&&dayRows.length>0&&<button className="button primary" disabled={busy==="daily-batch"} onClick={()=>void markDayPaid()}>{busy==="daily-batch"?"Сохраняю…":`Отметить все за ${formatDateShort(dailyDate)}`}</button>}
      </div>
      <div className="request-table-wrap"><table className="data-table object-daily-payment-date"><thead><tr><th>Сотрудник</th><th>Смена по схеме</th><th>Часы</th><th>Сумма</th><th>Статус</th></tr></thead><tbody>{dayRows.map(({worker,shift,shiftIndex})=>{const paidState=shift.paymentStatus==="paid",amount=shift.paymentAmount??shift.suggestedAmount,key=`${worker.workerId}:${shift.workDate}`;return <tr key={key}><td><Link className="cell-title" href={`/workers/${worker.workerId}`}>{worker.worker}</Link><span className="cell-sub">{worker.specialty??"—"}</span></td><td>{shiftIndex} из {worker.shiftLimit}</td><td>{shift.dayHours?`день ${shift.dayHours} ч`:""}{shift.dayHours&&shift.nightHours?" · ":""}{shift.nightHours?`ночь ${shift.nightHours} ч`:""}</td><td className="num">{rub(amount)}</td><td>{canConfirmDaily?<label className="object-daily-paid-check"><input type="checkbox" checked={paidState} disabled={busy===key} onChange={e=>void toggleDaily(worker.workerId,shift.workDate,e.target.checked,shift.suggestedAmount)}/><span>{paidState?"Выплачено":"Отметить выплату"}</span></label>:<span>{paidState?"Выплачено":"Не подтверждено"}</span>}</td></tr>})}{!dayRows.length&&<tr><td colSpan={5}><div className="empty-inline">На эту дату нет смен, входящих в схему ежедневных выплат</div></td></tr>}</tbody></table></div>
      <details className="object-daily-worker-settings"><summary>Индивидуальные исключения по сотрудникам</summary><div className="request-table-wrap"><table className="data-table"><thead><tr><th>Сотрудник</th><th>Специальность</th><th>Первые смены</th><th>Отработано в схеме</th></tr></thead><tbody>{rows.map(worker=><tr key={worker.workerId}><td className="cell-title">{worker.worker}</td><td>{worker.specialty??"—"}</td><td>{canEditWorker?<div className="object-daily-limit"><input type="number" min="0" max="31" value={worker.shiftLimit} disabled={busy===`limit:${worker.workerId}`} onChange={e=>setRows(current=>current.map(row=>row.workerId===worker.workerId?{...row,shiftLimit:Number(e.target.value)}:row))}/><button className="button" onClick={()=>void updateLimit(worker.workerId,worker.shiftLimit)}>✓</button></div>:`${worker.shiftLimit} смен`}</td><td>{worker.shifts.length} из {worker.shiftLimit}</td></tr>)}</tbody></table></div></details>
    </>}
    {mode==="economics"&&<>
      {pnl?<div className="object-finance-pnl"><div><span>Выручка</span><strong>{rub(pnl.revenue)}</strong></div><div><span>Персонал</span><strong>{rub(pnl.workerCost)}</strong></div><div><span>Расходы объекта</span><strong>{rub(pnl.expenses)}</strong></div><div><span>Вклад в прибыль</span><strong>{rub(pnl.contribution)}</strong></div><div><span>Маржа</span><strong>{pct(pnl.marginPct)}</strong></div></div>:<div className="empty-inline">Для объекта пока нет рассчитанной экономики.</div>}
      {proposed.length>0&&<div className="object-finance-effects"><div className="section-head"><div><h2>Финансовые последствия инцидентов</h2><p>Не меняют начисления до согласования и применения финансовой ролью.</p></div></div>{proposed.map(row=><div className="stack-item" key={row.id}><div><strong>{row.worker??"Объект"} · {row.title}</strong><small>{row.financialEffectBasis??"Основание не указано"}</small></div><strong>{rub(Number(row.financialEffectAmount))}</strong></div>)}</div>}
    </>}
  </div>
}
function formatDate(value:string){return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(new Date(value+"T00:00:00Z"))}function formatDateShort(value:string){return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",timeZone:"UTC"}).format(new Date(value+"T00:00:00Z"))}function paymentWord(value:number){const n=Math.abs(value)%100,d=n%10;return n>10&&n<20?"выплат":d===1?"выплата":d>=2&&d<=4?"выплаты":"выплат"}function paymentReferenceLabel(value:string|null|undefined){if(!value)return"—";return value.trim().toUpperCase()==="DEMO"?"Демо":value}