"use client";

import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {Plus,X} from "lucide-react";
import type {ObjectDocumentRow} from "@/lib/operations/service";

const categories:Record<string,string>={client_instruction:"Регламенты заказчика",access:"Пропускной режим",ppe:"СИЗ и форма",safety:"Охрана труда",act:"Акты",template:"Рабочие формы",client:"Прочие документы заказчика",other:"Прочее"};
type LinkedDocument={id:string;label:string;meta:string;href:string};
const statuses:Record<string,string>={active:"Актуален",needs_update:"Нужно обновить",archived:"Архив"};
const emptyForm=()=>({id:"",name:"",category:"client_instruction",documentNumber:"",documentDate:"",versionLabel:"",sourceUrl:"",status:"active",validFrom:"",expiresAt:"",notes:""});
function daysLeft(value:string|null){if(!value)return null;const date=new Date(value+"T00:00:00Z");return Math.ceil((date.getTime()-Date.now())/86400000)}

export function ObjectDocumentsWorkspace({objectId,rows,linked,canEdit,demo}:{objectId:string;rows:ObjectDocumentRow[];linked:LinkedDocument[];canEdit:boolean;demo:boolean}){
  const router=useRouter();const [query,setQuery]=useState("");const [category,setCategory]=useState("all");const [open,setOpen]=useState(false);const [form,setForm]=useState(emptyForm());const [state,setState]=useState("");
  const filtered=useMemo(()=>rows.filter(row=>(category==="all"||row.category===category)&&`${row.name} ${row.documentNumber??""} ${row.notes??""}`.toLowerCase().includes(query.toLowerCase())),[rows,query,category]);
  const attention=rows.filter(row=>{const days=daysLeft(row.expiresAt);return row.status==="needs_update"||(days!=null&&days>=0&&days<=30&&row.status!=="archived")}).sort((a,b)=>(daysLeft(a.expiresAt)??9999)-(daysLeft(b.expiresAt)??9999));
  function edit(row?:ObjectDocumentRow){setForm(row?{id:row.id,name:row.name,category:row.category,documentNumber:row.documentNumber??"",documentDate:row.documentDate??"",versionLabel:row.versionLabel??"",sourceUrl:row.sourceUrl??"",status:row.status,validFrom:row.validFrom??"",expiresAt:row.expiresAt??"",notes:row.notes??""}:emptyForm());setState("");setOpen(true)}
  async function save(){setState("Сохранение…");if(demo){setState("В демо-режиме изменения не сохраняются");return}const payload={name:form.name,category:form.category,documentNumber:form.documentNumber||null,documentDate:form.documentDate||null,versionLabel:form.versionLabel||null,sourceUrl:form.sourceUrl||null,status:form.status,validFrom:form.validFrom||null,expiresAt:form.expiresAt||null,notes:form.notes||null};const url=form.id?`/api/objects/${objectId}/documents/${form.id}`:`/api/objects/${objectId}/documents`;const response=await fetch(url,{method:form.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const json=await response.json().catch(()=>({}));if(!response.ok){setState(json.error??"Не удалось сохранить документ");return}setOpen(false);router.refresh()}
  return <div className="object-documents-workspace">
    {attention.length>0&&<div className="object-document-attention"><div><strong>Требует внимания</strong><span>Актуальность рабочих документов объекта</span></div><div>{attention.slice(0,4).map(row=>{const left=daysLeft(row.expiresAt);return <button type="button" key={row.id} onClick={()=>edit(row)}><strong>{row.name}</strong><span>{row.status==="needs_update"?"Нужно обновить":left==null?"Проверить документ":`Истекает через ${Math.max(0,left)} дн.`}</span></button>})}</div></div>}
    {linked.length>0&&<div className="object-linked-documents"><div className="section-head"><div><h2>Связанные документы</h2><p>Источник открывается в своей сущности. Здесь не создаются копии договоров, заявок и КП.</p></div></div><div>{linked.map(row=><a key={row.id} href={row.href}><strong>{row.label}</strong><span>{row.meta}</span></a>)}</div></div>}
    <div className="object-document-toolbar"><input placeholder="Поиск по рабочим документам" value={query} onChange={e=>setQuery(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Все категории</option>{Object.entries(categories).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{canEdit&&<button className="button primary" onClick={()=>edit()}><Plus size={14}/> Добавить документ</button>}</div>
    <div className="request-table-wrap"><table className="data-table"><thead><tr><th>Документ</th><th>Категория</th><th>Версия / дата</th><th>Срок</th><th>Статус</th><th></th></tr></thead><tbody>{filtered.map(row=>{const left=daysLeft(row.expiresAt);return <tr key={row.id}><td><strong className="cell-title">{row.name}</strong><span className="cell-sub">{row.documentNumber?`№ ${row.documentNumber}`:row.notes??`Обновлено ${row.updatedAt}`}</span></td><td>{categories[row.category]??"Прочее"}</td><td>{row.versionLabel?`v${row.versionLabel}`:"—"}<span className="cell-sub">{row.documentDate?new Intl.DateTimeFormat("ru-RU").format(new Date(row.documentDate+"T00:00:00Z")):`Добавил ${row.createdBy} · ${row.createdAt}`}</span></td><td>{row.expiresAt?new Intl.DateTimeFormat("ru-RU").format(new Date(row.expiresAt+"T00:00:00Z")):"Бессрочно"}{left!=null&&left>=0&&left<=30&&<span className="cell-sub">осталось {left} дн.</span>}</td><td><span className={`status ${row.status==="active"?"status-good":row.status==="archived"?"status-neutral":"status-warn"}`}><i/>{statuses[row.status]??"Актуален"}</span></td><td className="object-document-actions">{row.sourceUrl&&<a className="button ghost" href={row.sourceUrl} target="_blank" rel="noreferrer">Открыть</a>}{canEdit&&<button className="button ghost" onClick={()=>edit(row)}>Изменить</button>}</td></tr>})}{!filtered.length&&<tr><td colSpan={6}><div className="empty-inline">Документов по выбранному фильтру нет</div></td></tr>}</tbody></table></div>
    {open&&<div className="drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><aside className="drawer object-document-drawer"><div className="drawer-head"><div><strong>{form.id?"Редактировать документ":"Новый документ объекта"}</strong><span>Только рабочие документы этого объекта. Личные документы сотрудников сюда не попадают.</span></div><button className="icon-button" onClick={()=>setOpen(false)}><X size={16}/></button></div><div className="drawer-body"><div className="form-grid two"><label className="span-2"><span>Название *</span><input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label><span>Категория</span><select value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))}>{Object.entries(categories).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Статус</span><select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value}))}>{Object.entries(statuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Номер</span><input value={form.documentNumber} onChange={e=>setForm(v=>({...v,documentNumber:e.target.value}))}/></label><label><span>Версия</span><input value={form.versionLabel} onChange={e=>setForm(v=>({...v,versionLabel:e.target.value}))} placeholder="Например, 2.1"/></label><label><span>Дата документа</span><input type="date" value={form.documentDate} onChange={e=>setForm(v=>({...v,documentDate:e.target.value}))}/></label><label><span>Действует с</span><input type="date" value={form.validFrom} onChange={e=>setForm(v=>({...v,validFrom:e.target.value}))}/></label><label><span>Действует до</span><input type="date" value={form.expiresAt} onChange={e=>setForm(v=>({...v,expiresAt:e.target.value}))}/></label><label className="span-2"><span>Ссылка на файл / хранилище</span><input type="url" value={form.sourceUrl} onChange={e=>setForm(v=>({...v,sourceUrl:e.target.value}))} placeholder="https://…"/></label><label className="span-2"><span>Комментарий</span><textarea rows={4} value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></label></div>{state&&<p className="muted">{state}</p>}</div><div className="drawer-footer"><button className="button" onClick={()=>setOpen(false)}>Отмена</button><button className="button primary" disabled={!form.name.trim()} onClick={()=>void save()}>Сохранить</button></div></aside></div>}
  </div>
}