"use client";

import {useMemo,useState} from "react";
import Link from "next/link";
import type {AccrualRow,FinanceRow,IncidentRow,PaymentRow} from "@/lib/data/service";
import type {DailyPaymentProgressRow} from "@/lib/operations/service";
import {rub,pct} from "@/lib/ui/format";
import {Status} from "@/components/UI";

const paymentStatusLabels:Record<string,string>={planned:"Запланировано",paid:"Выплачено",cancelled:"Отменено",failed:"Ошибка"};
const accrualStatusLabels:Record<string,string>={draft:"Расчёт",approved:"Согласовано",closed:"Закрыто"};
const financialLabels:Record<string,string>={proposed:"На согласовании",approved:"Согласовано",rejected:"Отклонено",applied:"Применено"};

type Mode="summary"|"payments"|"daily";
export function ObjectFinanceWorkspace({objectId,pnl,accruals,payments,daily,incidents,canConfirmDaily}:{objectId:string;pnl:FinanceRow|null;accruals:AccrualRow[];payments:PaymentRow[];daily:DailyPaymentProgressRow[];incidents:IncidentRow[];canConfirmDaily:boolean}){
  const [mode,setMode]=useState<Mode>("summary");const [rows,setRows]=useState(daily);const [busy,setBusy]=useState("");const [message,setMessage]=useState("");
  const [amounts,setAmounts]=useState<Record<string,string>>(()=>Object.fromEntries(daily.flatMap(worker=>worker.shifts.map(shift=>[`${worker.workerId}:${shift.workDate}`,String(shift.paymentAmount ?? shift.suggestedAmount ?? 0)]))));
  const accrued=accruals.reduce((sum,row)=>sum+Number(row.total||0),0);const paid=payments.filter(row=>row.status==="paid").reduce((sum,row)=>sum+Number(row.amount||0),0);const balance=accrued-paid;
  const people=useMemo(()=>{const map=new Map<string,{workerId:string;worker:string;accrued:number;paid:number;planned:number;lastDate:string;dailyLimit:number}>();for(const row of accruals){const item=map.get(row.workerId)??{workerId:row.workerId,worker:row.worker,accrued:0,paid:0,planned:0,lastDate:"",dailyLimit:0};item.accrued+=Number(row.total||0);map.set(row.workerId,item)}for(const row of payments){const item=map.get(row.workerId)??{workerId:row.workerId,worker:row.worker,accrued:0,paid:0,planned:0,lastDate:"",dailyLimit:0};if(row.status==="paid")item.paid+=Number(row.amount||0);else if(row.status==="planned")item.planned+=Number(row.amount||0);if((row.dateIso??"")>item.lastDate)item.lastDate=row.dateIso??"";map.set(row.workerId,item)}for(const row of rows){const item=map.get(row.workerId)??{workerId:row.workerId,worker:row.worker,accrued:0,paid:0,planned:0,lastDate:"",dailyLimit:0};item.dailyLimit=row.shiftLimit;map.set(row.workerId,item)}return [...map.values()].sort((a,b)=>a.worker.localeCompare(b.worker,"ru"))},[accruals,payments,rows]);
  const proposed=incidents.filter(row=>Number(row.financialEffectAmount??0)>0&&!['rejected','applied'].includes(row.financialEffectStatus??'proposed'));
  async function toggleDaily(workerId:string,workDate:string,paidState:boolean){const key=`${workerId}:${workDate}`;const amount=Number(amounts[key]||0);if(!amount){setMessage("Укажите сумму выплаты");return}setBusy(key);setMessage("");try{const response=await fetch(`/api/objects/${objectId}/daily-payments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workerId,workDate,amount,paid:paidState})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось сохранить выплату");setRows(current=>current.map(worker=>worker.workerId!==workerId?worker:{...worker,shifts:worker.shifts.map(shift=>shift.workDate!==workDate?shift:{...shift,paymentStatus:paidState?"paid":"planned",paymentAmount:amount,paymentDate:paidState?workDate:shift.paymentDate})}));setMessage(paidState?"Выплата отмечена как полученная":"Подтверждение выплаты снято")}catch(e){setMessage(e instanceof Error?e.message:"Не удалось сохранить выплату")}finally{setBusy("")}}
  return <div className="object-finance-workspace">
    <div className="object-finance-tabs"><button className={mode==="summary"?"active":""} onClick={()=>setMode("summary")}>Сводка</button><button className={mode==="payments"?"active":""} onClick={()=>setMode("payments")}>Выплаты сотрудникам</button><button className={mode==="daily"?"active":""} onClick={()=>setMode("daily")}>Первые смены</button></div>
    <div className="metrics-grid object-finance-metrics"><div className="metric"><span>Начислено сотрудникам</span><strong>{rub(accrued)}</strong></div><div className="metric"><span>Выплачено</span><strong>{rub(paid)}</strong></div><div className="metric"><span>Остаток</span><strong>{rub(balance)}</strong></div><div className="metric"><span>{pnl?"Маржа объекта":"Ежедневные схемы"}</span><strong>{pnl?pct(pnl.marginPct):daily.length}</strong></div></div>
    {message&&<div className="object-staffing-message">{message}</div>}
    {mode==="summary"&&<>
      {pnl&&<div className="object-finance-pnl"><div><span>Выручка</span><strong>{rub(pnl.revenue)}</strong></div><div><span>Персонал</span><strong>{rub(pnl.workerCost)}</strong></div><div><span>Расходы объекта</span><strong>{rub(pnl.expenses)}</strong></div><div><span>Вклад в прибыль</span><strong>{rub(pnl.contribution)}</strong></div></div>}
      <div className="request-table-wrap"><table className="data-table object-finance-people"><thead><tr><th>Сотрудник</th><th>Начислено</th><th>Выплачено</th><th>Остаток</th><th>Последняя выплата</th><th>Первые смены</th></tr></thead><tbody>{people.map(row=><tr key={row.workerId}><td><Link className="cell-title" href={`/workers/${row.workerId}?tab=payments`}>{row.worker}</Link></td><td className="num">{rub(row.accrued)}</td><td className="num">{rub(row.paid)}</td><td className="num"><strong>{rub(row.accrued-row.paid)}</strong>{row.planned>0&&<span className="cell-sub">запланировано {rub(row.planned)}</span>}</td><td>{row.lastDate?formatDate(row.lastDate):"—"}</td><td>{row.dailyLimit?`первые ${row.dailyLimit} смен` : "Обычный цикл"}</td></tr>)}{!people.length&&<tr><td colSpan={6}><div className="empty-inline">Финансовых операций по сотрудникам пока нет</div></td></tr>}</tbody></table></div>
      {proposed.length>0&&<div className="object-finance-effects"><div className="section-head"><div><h2>Финансовые последствия по инцидентам</h2><p>Менеджер фиксирует предложение. Удержание не попадает в начисление без отдельного согласования.</p></div></div>{proposed.map(row=><div className="stack-item" key={row.id}><div><strong>{row.worker??"Без сотрудника"} · {row.title}</strong><small>{row.financialEffectBasis??"Основание не указано"}</small></div><div className="object-finance-effect-value"><strong>{rub(Number(row.financialEffectAmount))}</strong><span>{financialLabels[row.financialEffectStatus??"proposed"]}</span></div></div>)}</div>}
    </>}
    {mode==="payments"&&<div className="request-table-wrap"><table className="data-table"><thead><tr><th>Дата</th><th>Сотрудник</th><th>Тип</th><th>Сумма</th><th>Основание</th><th>Статус</th></tr></thead><tbody>{payments.map(row=><tr key={`${row.kind}:${row.id}`}><td>{row.date??"—"}</td><td><Link className="cell-title" href={`/workers/${row.workerId}?tab=payments`}>{row.worker}</Link></td><td>{row.kind==="payment"?"Зарплатная выплата":row.purpose==="daily_shift"?"Ежедневная выплата":"Аванс"}{row.workDate&&<span className="cell-sub">смена {formatDate(row.workDate)}</span>}</td><td className="num">{rub(row.amount)}</td><td>{row.reference??"—"}</td><td><Status tone={row.status==="paid"?"good":row.status==="planned"?"warn":"neutral"}>{paymentStatusLabels[row.status]??"В работе"}</Status></td></tr>)}{!payments.length&&<tr><td colSpan={6}><div className="empty-inline">Выплат по объекту пока нет</div></td></tr>}</tbody></table></div>}
    {mode==="daily"&&<div className="object-daily-payment-list">{rows.map(worker=><article className="object-daily-payment-card" key={worker.workerId}><header><div><Link href={`/workers/${worker.workerId}`}>{worker.worker}</Link><span>{worker.specialty??"Специальность не указана"}</span></div><div><strong>{worker.workedCount} / {worker.shiftLimit}</strong><span>первых смен отработано</span></div></header><div className="object-daily-payment-shifts">{worker.shifts.map((shift,index)=>{const key=`${worker.workerId}:${shift.workDate}`;const isPaid=shift.paymentStatus==="paid";return <div key={shift.workDate}><span className="object-daily-index">{index+1}</span><div><strong>{formatDate(shift.workDate)}</strong><span>{shift.hours} ч · план {rub(shift.suggestedAmount)}</span></div><input type="number" min="0" step="100" value={amounts[key]??""} onChange={e=>setAmounts(current=>({...current,[key]:e.target.value}))}/><label className="object-daily-check"><input type="checkbox" checked={isPaid} disabled={!canConfirmDaily||busy===key} onChange={e=>void toggleDaily(worker.workerId,shift.workDate,e.target.checked)}/><span>{isPaid?"Получено":"Не подтверждено"}</span></label></div>})}{!worker.shifts.length&&<div className="empty-inline">Фактически отработанных смен пока нет</div>}</div>{worker.remaining>0&&<footer>По схеме осталось {worker.remaining} из {worker.shiftLimit} первых смен</footer>}</article>)}{!rows.length&&<div className="empty-inline">На объекте нет сотрудников со схемой ежедневных выплат первых смен</div>}</div>}
  </div>
}
function formatDate(value:string){return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(new Date(value+"T00:00:00Z"))}