"use client";

import {useMemo,useState} from "react";
import Link from "next/link";
import type {AccrualRow,FinanceRow,IncidentRow,PaymentRow} from "@/lib/data/service";
import type {DailyPaymentProgressRow} from "@/lib/operations/service";
import {rub,pct} from "@/lib/ui/format";

type Mode="summary"|"payments"|"daily";
export function ObjectFinanceWorkspace({objectId,pnl,accruals,payments,daily,incidents,canConfirmDaily,canRecordPayment,canEditWorker,demo}:{objectId:string;pnl:FinanceRow|null;accruals:AccrualRow[];payments:PaymentRow[];daily:DailyPaymentProgressRow[];incidents:IncidentRow[];canConfirmDaily:boolean;canRecordPayment:boolean;canEditWorker:boolean;demo:boolean}){
  const [mode,setMode]=useState<Mode>("summary");const [rows,setRows]=useState(daily);const [busy,setBusy]=useState("");const [message,setMessage]=useState("");const today=new Date().toISOString().slice(0,10);const [paymentDate,setPaymentDate]=useState(today);const [reference,setReference]=useState("");const [batchAmounts,setBatchAmounts]=useState<Record<string,string>>({});
  const accrued=accruals.reduce((sum,row)=>sum+Number(row.total||0),0),paid=payments.filter(row=>row.status==="paid").reduce((sum,row)=>sum+Number(row.amount||0),0),balance=accrued-paid;
  const people=useMemo(()=>{const map=new Map<string,{workerId:string;worker:string;accrued:number;paid:number;planned:number;lastDate:string;dailyLimit:number}>();for(const row of accruals){const item=map.get(row.workerId)??{workerId:row.workerId,worker:row.worker,accrued:0,paid:0,planned:0,lastDate:"",dailyLimit:0};item.accrued+=Number(row.total||0);map.set(row.workerId,item)}for(const row of payments){const item=map.get(row.workerId)??{workerId:row.workerId,worker:row.worker,accrued:0,paid:0,planned:0,lastDate:"",dailyLimit:0};if(row.status==="paid")item.paid+=Number(row.amount||0);else if(row.status==="planned")item.planned+=Number(row.amount||0);if((row.dateIso??"")>item.lastDate)item.lastDate=row.dateIso??"";map.set(row.workerId,item)}for(const row of rows){const item=map.get(row.workerId)??{workerId:row.workerId,worker:row.worker,accrued:0,paid:0,planned:0,lastDate:"",dailyLimit:0};item.dailyLimit=row.shiftLimit;map.set(row.workerId,item)}return [...map.values()].sort((a,b)=>a.worker.localeCompare(b.worker,"ru"))},[accruals,payments,rows]);
  const proposed=incidents.filter(row=>Number(row.financialEffectAmount??0)>0&&!["rejected","applied"].includes(row.financialEffectStatus??"proposed"));const maxDaily=Math.min(10,Math.max(0,...rows.map(row=>row.shiftLimit)));
  function fillBalances(){setBatchAmounts(Object.fromEntries(people.filter(p=>p.accrued-p.paid>0).map(p=>[p.workerId,String(Math.max(p.accrued-p.paid,0))])))}
  async function recordPayments(){const items=people.map(p=>({workerId:p.workerId,amount:Number(batchAmounts[p.workerId]||0),paymentDate,reference:reference||null})).filter(x=>x.amount>0);if(!items.length){setMessage("Укажите хотя бы одну сумму");return}if(!window.confirm(`Сохранить ${items.length} выплат на ${formatDate(paymentDate)}?`))return;setBusy("batch");setMessage("");try{const response=await fetch(`/api/objects/${objectId}/payments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows:items})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось сохранить выплаты");setMessage(`Сохранено выплат: ${items.length}`);setBatchAmounts({});if(!demo)window.location.reload()}catch(e){setMessage(e instanceof Error?e.message:"Не удалось сохранить выплаты")}finally{setBusy("")}}
  async function toggleDaily(workerId:string,workDate:string,paidState:boolean,amount:number){const key=`${workerId}:${workDate}`;setBusy(key);setMessage("");try{const response=await fetch(`/api/objects/${objectId}/daily-payments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workerId,workDate,amount,paid:paidState})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось сохранить выплату");setRows(current=>current.map(worker=>worker.workerId!==workerId?worker:{...worker,shifts:worker.shifts.map(shift=>shift.workDate!==workDate?shift:{...shift,paymentStatus:paidState?"paid":"planned",paymentAmount:amount,paymentDate:paidState?workDate:shift.paymentDate})}));setMessage(paidState?"Выплата подтверждена":"Подтверждение снято")}catch(e){setMessage(e instanceof Error?e.message:"Не удалось сохранить выплату")}finally{setBusy("")}}
  async function updateLimit(workerId:string,value:number){if(!canEditWorker)return;setBusy(`limit:${workerId}`);try{const response=await fetch(`/api/workers/${workerId}/assignment-settings`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({dailyPaymentShifts:value})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось изменить схему");setRows(current=>current.map(row=>row.workerId===workerId?{...row,shiftLimit:value,remaining:Math.max(value-row.workedCount,0)}:row));setMessage("Количество первых смен обновлено")}catch(e){setMessage(e instanceof Error?e.message:"Не удалось изменить схему")}finally{setBusy("")}}
  return <div className="object-finance-workspace">
    <div className="object-finance-tabs"><button className={mode==="summary"?"active":""} onClick={()=>setMode("summary")}>Сводка</button><button className={mode==="payments"?"active":""} onClick={()=>setMode("payments")}>Выплаты сотрудникам</button><button className={mode==="daily"?"active":""} onClick={()=>setMode("daily")}>Первые смены</button></div>
    <div className="metrics-grid object-finance-metrics"><div className="metric"><span>Начислено сотрудникам</span><strong>{rub(accrued)}</strong></div><div className="metric"><span>Выплачено</span><strong>{rub(paid)}</strong></div><div className="metric"><span>Остаток</span><strong>{rub(balance)}</strong></div><div className="metric"><span>{pnl?"Маржа объекта":"Схемы первых выплат"}</span><strong>{pnl?pct(pnl.marginPct):daily.length}</strong></div></div>{message&&<div className="object-staffing-message">{message}</div>}
    {mode==="summary"&&<>{pnl&&<div className="object-finance-pnl"><div><span>Выручка</span><strong>{rub(pnl.revenue)}</strong></div><div><span>Персонал</span><strong>{rub(pnl.workerCost)}</strong></div><div><span>Расходы объекта</span><strong>{rub(pnl.expenses)}</strong></div><div><span>Вклад в прибыль</span><strong>{rub(pnl.contribution)}</strong></div></div>}<div className="request-table-wrap"><table className="data-table"><thead><tr><th>Сотрудник</th><th>Начислено</th><th>Выплачено</th><th>Остаток</th><th>Последняя выплата</th><th>Первые смены</th></tr></thead><tbody>{people.map(row=><tr key={row.workerId}><td><Link className="cell-title" href={`/workers/${row.workerId}?tab=payments`}>{row.worker}</Link></td><td className="num">{rub(row.accrued)}</td><td className="num">{rub(row.paid)}</td><td className="num"><strong>{rub(row.accrued-row.paid)}</strong></td><td>{row.lastDate?formatDate(row.lastDate):"—"}</td><td>{row.dailyLimit?`первые ${row.dailyLimit} смен`:"Обычный цикл"}</td></tr>)}</tbody></table></div>{proposed.length>0&&<div className="object-finance-effects"><div className="section-head"><div><h2>Предлагаемые финансовые последствия</h2><p>Не уменьшают начисление без отдельного согласования.</p></div></div>{proposed.map(row=><div className="stack-item" key={row.id}><div><strong>{row.worker??"Без сотрудника"} · {row.title}</strong><small>{row.financialEffectBasis??"Основание не указано"}</small></div><strong>{rub(Number(row.financialEffectAmount))}</strong></div>)}</div>}</>}
    {mode==="payments"&&<><div className="object-payment-entry"><div><label>Дата выплаты<input type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></label><label>Основание / период<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Например, зарплата 01–15.09"/></label></div>{canRecordPayment&&<div className="page-actions"><button className="button" onClick={fillBalances}>Заполнить остатки</button><button className="button primary" disabled={busy==="batch"} onClick={()=>void recordPayments()}>Сохранить выплаты</button></div>}</div><div className="request-table-wrap"><table className="data-table object-payment-batch"><thead><tr><th>Сотрудник</th><th>Начислено</th><th>Выплачено</th><th>Остаток</th><th>Получил сейчас</th></tr></thead><tbody>{people.map(row=><tr key={row.workerId}><td className="cell-title">{row.worker}</td><td className="num">{rub(row.accrued)}</td><td className="num">{rub(row.paid)}</td><td className="num">{rub(Math.max(row.accrued-row.paid,0))}</td><td>{canRecordPayment?<input type="number" min="0" step="100" value={batchAmounts[row.workerId]??""} onChange={e=>setBatchAmounts(current=>({...current,[row.workerId]:e.target.value}))} placeholder="0"/>:"—"}</td></tr>)}</tbody></table></div><details className="object-payment-history"><summary>История выплат · {payments.length}</summary><div className="request-table-wrap"><table className="data-table"><thead><tr><th>Дата</th><th>Сотрудник</th><th>Тип</th><th>Сумма</th><th>Основание</th></tr></thead><tbody>{payments.map(row=><tr key={`${row.kind}:${row.id}`}><td>{row.date??"—"}</td><td>{row.worker}</td><td>{row.kind==="payment"?"Зарплата":row.purpose==="daily_shift"?"Первая смена":"Аванс"}</td><td className="num">{rub(row.amount)}</td><td>{row.reference??"—"}</td></tr>)}</tbody></table></div></details></>}
    {mode==="daily"&&<div className="request-table-wrap"><table className="data-table object-daily-payment-matrix"><thead><tr><th className="sticky-col">Сотрудник</th><th>Схема</th>{Array.from({length:maxDaily},(_,i)=><th key={i}>Смена {i+1}</th>)}<th>Итого</th></tr></thead><tbody>{rows.map(worker=><tr key={worker.workerId}><td className="sticky-col"><Link className="cell-title" href={`/workers/${worker.workerId}`}>{worker.worker}</Link><span className="cell-sub">{worker.specialty??"—"}</span></td><td>{canEditWorker?<div className="object-daily-limit"><input type="number" min="0" max="31" value={worker.shiftLimit} disabled={busy===`limit:${worker.workerId}`} onChange={e=>setRows(current=>current.map(row=>row.workerId===worker.workerId?{...row,shiftLimit:Number(e.target.value)}:row))}/><button className="button" onClick={()=>void updateLimit(worker.workerId,worker.shiftLimit)}>✓</button></div>:`${worker.shiftLimit} смен`}</td>{Array.from({length:maxDaily},(_,i)=>{const shift=worker.shifts[i];if(i>=worker.shiftLimit)return <td key={i} className="object-daily-empty">—</td>;if(!shift)return <td key={i}><span className="cell-sub">Ещё не отработана</span></td>;const paidState=shift.paymentStatus==="paid",amount=shift.paymentAmount??shift.suggestedAmount,key=`${worker.workerId}:${shift.workDate}`;return <td key={i} className="object-daily-cell"><strong>{formatDateShort(shift.workDate)}</strong><span>{shift.dayHours?`Д ${shift.dayHours}ч`:""}{shift.dayHours&&shift.nightHours?" · ":""}{shift.nightHours?`Н ${shift.nightHours}ч`:""}</span><span>{rub(amount)}</span>{canConfirmDaily?<label><input type="checkbox" checked={paidState} disabled={busy===key} onChange={e=>void toggleDaily(worker.workerId,shift.workDate,e.target.checked,shift.suggestedAmount)}/>{paidState?"Получил":"Отметить"}</label>:<small>{paidState?"Получил":"Не подтверждено"}</small>}</td>})}<td><strong>{worker.shifts.filter(s=>s.paymentStatus==="paid").length}/{worker.shiftLimit}</strong></td></tr>)}{!rows.length&&<tr><td colSpan={maxDaily+3}><div className="empty-inline">Нет сотрудников со схемой первых выплат</div></td></tr>}</tbody></table></div>}
  </div>
}
function formatDate(value:string){return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(new Date(value+"T00:00:00Z"))}function formatDateShort(value:string){return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",timeZone:"UTC"}).format(new Date(value+"T00:00:00Z"))}