"use client";
import { useMemo, useState } from "react";
import { ChevronDown, ChevronRight, LocateFixed, Minus, Plus, Search, Users } from "lucide-react";
import { buildOrganizationTree, organizationUnitLabels } from "@/lib/core/organization.mjs";
import type { CompanyEmployeeRow, OrganizationUnitRow } from "@/lib/organization/types";

type TreeUnit=OrganizationUnitRow&{children:TreeUnit[]};
const initials=(name:string)=>name.split(" ").map(part=>part[0]).join("").slice(0,2);

export function OrganizationChart({units,employees}:{units:OrganizationUnitRow[];employees:CompanyEmployeeRow[]}){
  const [query,setQuery]=useState("");const [kind,setKind]=useState("all");const [region,setRegion]=useState("all");const [zoom,setZoom]=useState(1);const [collapsed,setCollapsed]=useState<Set<string>>(new Set());const [selected,setSelected]=useState<CompanyEmployeeRow|null>(null);
  const roots=useMemo(()=>buildOrganizationTree(units) as TreeUnit[],[units]);const regions=[...new Set(units.map(item=>item.region).filter(Boolean))] as string[];
  const normalized=query.trim().toLowerCase();
  const employeeMatches=(employee:CompanyEmployeeRow)=>!normalized||[employee.name,employee.position,employee.orgUnit,...employee.roles.map(r=>r.name),...employee.responsibilities].join(" ").toLowerCase().includes(normalized);
  const unitVisible=(unit:TreeUnit):boolean=>{const own=(!normalized||unit.name.toLowerCase().includes(normalized)||employees.some(e=>e.orgUnitId===unit.id&&employeeMatches(e)))&&(kind==="all"||unit.kind===kind)&&(region==="all"||unit.region===region);return own||unit.children.some(unitVisible)};
  function toggle(id:string){setCollapsed(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})}
  function render(unit:TreeUnit){if(!unitVisible(unit))return null;const members=employees.filter(item=>item.orgUnitId===unit.id&&employeeMatches(item));const closed=collapsed.has(unit.id);return <li key={unit.id} className="org-tree-node"><div className="org-unit-card"><button type="button" className="org-unit-toggle" onClick={()=>toggle(unit.id)} aria-label={`${closed?"Развернуть":"Свернуть"} ${unit.name}`} aria-expanded={!closed}>{closed?<ChevronRight size={14}/>:<ChevronDown size={14}/>}</button><div><span>{organizationUnitLabels[unit.kind]??unit.kind}</span><strong>{unit.name}</strong><small>{unit.manager?"Руководитель: "+unit.manager:"Руководитель не назначен"} · {unit.employeeCount} чел.</small></div></div>{members.length>0&&<div className="org-unit-employees">{members.map(employee=><button type="button" className="org-person-card" key={employee.id} onClick={()=>setSelected(employee)}><span className="avatar">{initials(employee.name)}</span><span><strong>{employee.name}</strong><small>{employee.position??"Должность не назначена"}</small></span>{employee.roles.length>0&&<i title="Дополнительные роли">{employee.roles.length}</i>}</button>)}</div>}{!closed&&unit.children.length>0&&<ul>{unit.children.map(render)}</ul>}</li>}
  return <div className="org-chart-workspace"><div className="org-chart-toolbar"><label className="toolbar-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Сотрудник, роль или подразделение"/></label><select value={kind} onChange={e=>setKind(e.target.value)} aria-label="Тип подразделения"><option value="all">Все типы</option>{Object.entries(organizationUnitLabels).filter(([key])=>key!=="company").map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select value={region} onChange={e=>setRegion(e.target.value)} aria-label="Регион"><option value="all">Все регионы</option>{regions.map(item=><option key={item}>{item}</option>)}</select><div className="org-zoom"><button type="button" onClick={()=>setZoom(value=>Math.max(.65,value-.1))} aria-label="Уменьшить"><Minus size={14}/></button><span>{Math.round(zoom*100)}%</span><button type="button" onClick={()=>setZoom(value=>Math.min(1.35,value+.1))} aria-label="Увеличить"><Plus size={14}/></button><button type="button" onClick={()=>setZoom(1)} aria-label="Сбросить масштаб"><LocateFixed size={14}/></button></div></div><div className="org-chart-viewport"><div className="org-chart-canvas" style={{transform:"scale("+zoom+")"}}><ul className="org-tree-root">{roots.map(render)}</ul></div>{!roots.some(unitVisible)&&<div className="org-no-results"><Users size={24}/><strong>Совпадений нет</strong><span>Измените поиск или фильтры.</span></div>}</div>{selected&&<EmployeeDrawer employee={selected} onClose={()=>setSelected(null)}/>}</div>;
}

function EmployeeDrawer({employee,onClose}:{employee:CompanyEmployeeRow;onClose:()=>void}){return <aside className="org-detail-drawer" role="dialog" aria-label={`Карточка сотрудника ${employee.name}`}><header><div><span className="avatar large">{initials(employee.name)}</span><div><strong>{employee.name}</strong><small>{employee.position??"Должность не назначена"}</small></div></div><button type="button" className="button" onClick={onClose}>Закрыть</button></header><dl><div><dt>Подразделение</dt><dd>{employee.orgUnit??"Не назначено"}</dd></div><div><dt>Регион</dt><dd>{employee.region??"Вся компания"}</dd></div><div><dt>Руководитель</dt><dd>{employee.manager??"Не назначен"}</dd></div><div><dt>Контакты</dt><dd>{employee.phone??"—"}<br/>{employee.email??"—"}</dd></div></dl><section><h3>Процессные роли</h3>{employee.roles.length?<div className="tag-list">{employee.roles.map(role=><span key={role.id}>{role.name}</span>)}</div>:<p>Дополнительных ролей нет.</p>}</section><section><h3>Зона ответственности</h3><ul>{employee.responsibilities.map(item=><li key={item}>{item}</li>)}</ul></section></aside>}
