"use client";
import { FormEvent, useState } from "react";
import { Plus, X } from "lucide-react";
import { useRouter } from "next/navigation";
import type { CompanyEmployeeRow, OrganizationUnitRow, PositionRow, ProcessRoleRow } from "@/lib/organization/types";

type Kind="unit"|"position"|"role"|"employee";
export function OrganizationCreatePanel({kind,canManage,demo,units=[],positions=[],roles=[],employees=[]}:{kind:Kind;canManage:boolean;demo:boolean;units?:OrganizationUnitRow[];positions?:PositionRow[];roles?:ProcessRoleRow[];employees?:CompanyEmployeeRow[]}){
  const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const router=useRouter();
  if(!canManage)return null;
  const labels={unit:"Добавить подразделение",position:"Создать должность",role:"Создать роль",employee:"Добавить сотрудника"};
  const paths={unit:"units",position:"positions",role:"roles",employee:"employees"};
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const data=new FormData(event.currentTarget);const body:Record<string,unknown>=Object.fromEntries(data.entries());if(kind==="position")for(const key of ["duties","responsibilities","processes"])body[key]=String(body[key]??"").split("\n").map(value=>value.trim()).filter(Boolean);if(kind==="employee")body.processRoleIds=data.getAll("processRoleIds");for(const key of ["parentId","managerMembershipId","positionId","orgUnitId"])if(body[key]==="")delete body[key];const response=await fetch("/api/organization/"+paths[kind],{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setBusy(false);if(!response.ok){setMessage(result.error??"Не удалось сохранить");return}setOpen(false);router.refresh()}
  return <><button type="button" className="button primary" onClick={()=>setOpen(true)}><Plus size={14}/>{labels[kind]}</button>{open&&<div className="org-modal-backdrop" role="presentation" onMouseDown={()=>setOpen(false)}><section className="org-modal" role="dialog" aria-modal="true" aria-label={labels[kind]} onMouseDown={event=>event.stopPropagation()}><header><div><strong>{labels[kind]}</strong><small>{demo?"Предпросмотр формы: демоданные не изменяются":"Изменения сохраняются в журнале организации"}</small></div><button type="button" className="icon-button" onClick={()=>setOpen(false)} aria-label="Закрыть"><X size={16}/></button></header><form onSubmit={submit} className="org-form">
    {(kind==="unit"||kind==="position"||kind==="role")&&<label>Код<input name="code" required pattern="[a-z0-9-]+" placeholder="operations-moscow"/></label>}
    <label>{kind==="employee"?"Имя сотрудника":"Название"}<input name="name" required placeholder={kind==="employee"?"Иван Петров":"Операции · Москва"}/></label>
    {kind==="unit"&&<><label>Тип<select name="kind" defaultValue="department"><option value="department">Подразделение</option><option value="region">Регион</option><option value="branch">Филиал</option><option value="direction">Направление</option><option value="team">Команда</option><option value="project_group">Проектная группа</option></select></label><label>Родительская единица<select name="parentId" defaultValue=""><option value="">Корневой уровень</option>{units.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Руководитель<select name="managerMembershipId" defaultValue=""><option value="">Не назначен</option>{employees.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></>}
    {kind==="position"&&<><label className="span-2">Цель должности<textarea name="purpose" rows={3}/></label><label className="span-2">Описание<textarea name="description" rows={3}/></label><label className="span-2">Обязанности, по одной в строке<textarea name="duties" rows={4}/></label><label className="span-2">Ответственность, по одной в строке<textarea name="responsibilities" rows={4}/></label><label className="span-2">Участие в процессах, по одному в строке<textarea name="processes" rows={3}/></label></>}
    {kind==="role"&&<><label className="span-2">Зона ответственности<textarea name="responsibility" rows={3}/></label><label className="span-2">Описание<textarea name="description" rows={3}/></label></>}
    {kind==="employee"&&<><label>Электронная почта<input name="email" type="email" required/></label><label>Телефон<input name="phone" type="tel"/></label><label>Должность<select name="positionId" defaultValue=""><option value="">Не назначена</option>{positions.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Подразделение<select name="orgUnitId" defaultValue=""><option value="">Не назначено</option>{units.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Руководитель<select name="managerMembershipId" defaultValue=""><option value="">Не назначен</option>{employees.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{roles.length>0&&<fieldset className="span-2 role-choice"><legend>Дополнительные процессные роли</legend>{roles.map(role=><label key={role.id}><input type="checkbox" name="processRoleIds" value={role.id}/><span><strong>{role.name}</strong><small>{role.responsibility??role.description??"Функция в процессе"}</small></span></label>)}</fieldset>}</>}
    {message&&<p className="form-message span-2">{message}</p>}<footer className="span-2"><button type="button" className="button" onClick={()=>setOpen(false)}>Отмена</button><button className="button primary" disabled={busy}>{busy?"Сохранение…":"Сохранить"}</button></footer>
  </form></section></div>}</>;
}
