"use client";
import Link from "next/link";
import dynamic from "next/dynamic";
import { useState } from "react";
import { ChartNoAxesCombined, Eye } from "lucide-react";
import type { PortfolioData, PortfolioObject } from "@/lib/data/portfolio";
import { SalesDrawer, SalesEmpty, SalesMetrics, SalesSearch, SalesSegments } from "@/components/sales/SalesUI";
import { Status } from "@/components/UI";
import { num, pct, rub } from "@/lib/ui/format";
const PortfolioChart = dynamic(() => import("@/components/PortfolioChart").then(module => module.PortfolioChart), { loading: () => <p>Загрузка графика…</p> });
const dateLabel = (date?: string | null) => date ? (/^\d{4}-\d{2}-\d{2}$/.test(date) ? date.split("-").reverse().join(".") : date) : "—";
const periodLabel = (row: PortfolioObject) => row.finance?.periodStart && row.finance.periodEnd ? `${dateLabel(row.finance.periodStart)} – ${dateLabel(row.finance.periodEnd)}` : "Период не указан";

export function PortfolioWorkspace({ data, view }: { data: PortfolioData; view: string }) {
  const { rows, upcoming, permissions } = data;
  const [query, setQuery] = useState(""); const [region, setRegion] = useState(""); const [owner, setOwner] = useState("");
  const [bucket, setBucket] = useState("all"); const [selected, setSelected] = useState<PortfolioObject | null>(null); const [chart, setChart] = useState(false);
  const scoped = rows.filter(row => (!region || row.region === region) && (!owner || (row.ownerUserId ?? "unassigned") === owner) && `${row.name} ${row.code} ${row.client} ${row.ownerName ?? ""}`.toLocaleLowerCase("ru").includes(query.trim().toLocaleLowerCase("ru")));
  const visible = scoped.filter(row => bucket === "attention" ? row.signals.length > 0 : bucket === "launch" ? row.status === "launch" : true);
  const required = scoped.reduce((sum, row) => sum + row.required, 0);
  const filled = scoped.reduce((sum, row) => sum + row.filled, 0);
  const reset = () => { setQuery(""); setRegion(""); setOwner(""); setBucket("all"); };
  const financeRows = visible.filter(row => row.finance);
  const linkTab = (row: PortfolioObject, tab: string) => `/objects/${row.id}?tab=${tab === "needs" && !permissions.needs ? "overview" : tab}`;
  return <>
    <SalesMetrics label="Сводка по доступным объектам" items={[
      { label: "Объекты", value: scoped.length, note: "по выбранным фильтрам" },
      { label: "Требуют внимания", value: <button className="portfolio-metric-link" onClick={() => setBucket("attention")}>{scoped.filter(row => row.signals.length).length}</button>, note: "зафиксированные отклонения" },
      { label: "В запуске", value: <button className="portfolio-metric-link" onClick={() => setBucket("launch")}>{scoped.filter(row => row.status === "launch").length}</button>, note: "объекты на этапе запуска" },
      { label: "Комплектация", value: required ? pct(100 * filled / required) : "—", note: required ? `${num(filled)} из ${num(required)} человек` : "потребность не задана" },
    ]}/>
    <div className="sales-toolbar"><nav className="sales-segments portfolio-views" aria-label="Представление портфеля"><Link href="/analytics" aria-current={view === "portfolio" ? "page" : undefined}>Портфель</Link><Link href="/analytics?view=comparison" aria-current={view === "comparison" ? "page" : undefined}>Сравнение объектов</Link><Link href="/analytics?view=workforce" aria-current={view === "workforce" ? "page" : undefined}>Подбор и персонал</Link></nav>{permissions.finance && view !== "workforce" && <button className="button" aria-pressed={chart} onClick={() => setChart(value => !value)}><ChartNoAxesCombined size={16}/>{chart ? "Скрыть график" : "Финансовый график"}</button>}</div>
    <div className="sales-filterbar"><SalesSegments label="Отбор объектов" value={bucket} onChange={setBucket} items={[{ value: "all", label: "Все объекты" }, { value: "attention", label: "Требуют внимания" }, { value: "launch", label: "В запуске" }]}/><select aria-label="Регион объектов" value={region} onChange={event => setRegion(event.target.value)}><option value="">Все регионы</option>{[...new Set(rows.map(row => row.region))].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Ответственный за объект" value={owner} onChange={event => setOwner(event.target.value)}><option value="">Все ответственные</option>{[...new Map(rows.map(row => [row.ownerUserId ?? "unassigned", row.ownerName ?? (row.ownerUserId ? "Имя не указано" : "Не назначен")])).entries()].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><SalesSearch value={query} onChange={setQuery} placeholder="Объект, клиент или код"/>{(query || region || owner || bucket !== "all") && <button className="button" onClick={reset}>Сбросить</button>}</div>
    <p className="portfolio-data-note">{data.demo ? "Демонстрационные данные. " : ""}Показано {visible.length} из {rows.length} доступных объектов. Численность взята из потребностей. Табели и финансовый факт показаны за последний доступный период каждого объекта; периоды могут различаться.</p>
    {chart && permissions.finance && view !== "workforce" && <section className="section"><div className="section-head"><div><h2>Финансовый факт по объектам</h2><p>Последний доступный снимок каждого объекта. Общий итог по разным периодам не рассчитывается.</p></div></div>{financeRows.length ? <PortfolioChart rows={financeRows.map(row => ({ object: `${row.name} · ${periodLabel(row)}`, revenue: Number(row.finance!.revenue), contribution: Number(row.finance!.contribution) }))}/> : <SalesEmpty title="Нет финансовых данных" text="Для выбранных объектов нет доступных снимков финансового факта."/>}</section>}
    {!permissions.objects ? <SalesEmpty title="Нет доступа к объектам" text="Для просмотра портфеля требуется доступ к реестру объектов."/> : !visible.length ? <SalesEmpty title={rows.length ? "Объекты не найдены" : "Нет доступных объектов"} text={rows.length ? "Измените поиск или фильтры." : "Сводка появится после создания объектов в доступном вам контуре."} onReset={rows.length ? reset : undefined}/> : <div className="portfolio-table-scroll" role="region" aria-label="Сводная таблица объектов" tabIndex={0}><table className="data-table portfolio-table"><thead><tr><th>Объект / клиент</th><th>Ответственный / этап</th><th>Комплектация</th>{view === "workforce" ? <><th>Сотрудники</th><th>Кандидаты</th></> : <><th>Клиентский табель</th>{permissions.finance && <><th>Выручка / вклад</th><th>Маржа / период</th></>}</>}<th>Требует внимания</th><th><span className="sr-only">Просмотр</span></th></tr></thead><tbody>{visible.map(row => <tr key={row.id}>
      <td><Link className="cell-title" href={`/objects/${row.id}`}>{row.name}</Link><span className="cell-sub">{row.client} · {row.code}</span><span className="cell-sub">{row.region}</span></td>
      <td>{row.ownerName ?? (row.ownerUserId ? "Имя не указано" : "Не назначен")}<div className="portfolio-cell-status"><Status tone={row.status === "launch" ? "info" : "neutral"}>{row.status}</Status></div>{row.status === "launch" && <span className="cell-sub">Старт: {dateLabel(row.targetStart)}</span>}</td>
      <td>{row.staffing.coverage === null ? <span className="cell-sub">Потребность не задана</span> : <><strong>{row.filled} / {row.required}</strong><span className="cell-sub">{row.staffing.coverage}% · дефицит {row.staffing.deficit}</span><div className="progress portfolio-progress"><span style={{ width: `${Math.min(100, Math.max(0, row.staffing.coverage))}%` }}/></div></>}</td>
      {view === "workforce" ? <><td className="num">{row.workerCount ?? "Нет доступа"}</td><td className="num">{row.candidateCount ?? "Нет доступа"}</td></> : <><td>{!permissions.timesheets ? <span className="cell-sub">Нет доступа</span> : row.timesheet ? <><Status tone="neutral">{row.timesheet.status}</Status><span className="cell-sub">{row.timesheet.period}</span></> : <span className="cell-sub">Нет данных</span>}</td>{permissions.finance && <><td className="num">{row.finance ? <>{rub(row.finance.revenue)}<span className="cell-sub">Вклад: {rub(row.finance.contribution)}</span></> : "—"}</td><td>{row.finance ? <><strong>{pct(row.finance.marginPct)}</strong><span className="cell-sub">{periodLabel(row)}</span></> : <span className="cell-sub">Нет данных</span>}</td></>}</>}
      <td><div className="portfolio-signals">{row.signals.length ? row.signals.map(signal => signal.tab === "timesheets" ? <button key={signal.tab} className="portfolio-signal" onClick={() => setSelected(row)}>{signal.label}</button> : <Link key={signal.tab} className={`portfolio-signal tone-${signal.tone}`} href={linkTab(row, signal.tab)}>{signal.label}</Link>) : <span className="cell-sub">Нет выявленных отклонений</span>}</div></td>
      <td><button className="icon-button" aria-label={`Сводка: ${row.name}`} onClick={() => setSelected(row)}><Eye size={16}/></button></td>
    </tr>)}</tbody></table></div>}
    {view === "workforce" && <p className="portfolio-data-note">Сотрудники и кандидаты посчитаны в пределах ваших прав. Назначение сотрудника не подтверждает фактический выход на смену.</p>}
    {view === "workforce" && permissions.candidates && <section className="section"><div className="section-head"><div><h2>Воронка подбора</h2><p>Все доступные кандидаты. Фильтры таблицы объектов не применяются.</p></div></div>{data.candidateStages.length ? <div className="stack-list">{data.candidateStages.map(item => <div className="stack-item" key={item.stage}><Status>{item.stage}</Status><strong>{item.count}</strong></div>)}</div> : <SalesEmpty title="Нет доступных кандидатов" text="Воронка появится после добавления кандидатов в доступный контур."/>}</section>}
    {view === "portfolio" && permissions.requests && <section className="section portfolio-upcoming"><div className="section-head"><div><h2>Заявки с датой старта</h2><p>Коммерческая подготовка. Эти количества не складываются с потребностями объектов.</p></div><Link className="button" href="/requests">Все заявки</Link></div>{upcoming.length ? <div className="portfolio-table-scroll"><table className="data-table"><thead><tr><th>Заявка / клиент</th><th>Этап</th><th>Старт</th><th>Потребность</th></tr></thead><tbody>{upcoming.map(row => <tr key={row.id}><td><Link className="cell-title" href={`/requests/${row.id}`}>{row.title}</Link><span className="cell-sub">{row.client}</span></td><td>{row.stage}</td><td>{dateLabel(row.start)}</td><td className="num">{row.headcount} чел.</td></tr>)}</tbody></table></div> : <SalesEmpty title="Заявок с датой старта нет" text="Здесь появятся доступные незакрытые заявки с указанной датой."/>}</section>}
    {selected && <SalesDrawer title={selected.name} subtitle={`${selected.client} · ${selected.region}`} onClose={() => setSelected(null)} footer={<Link className="button primary" href={`/objects/${selected.id}`}>Открыть объект</Link>}><dl className="portfolio-detail"><dt>Ответственный</dt><dd>{selected.ownerName ?? "Не указан"}</dd><dt>Этап</dt><dd><Status>{selected.status}</Status></dd><dt>Старт</dt><dd>{dateLabel(selected.targetStart)}</dd><dt>Комплектация</dt><dd>{selected.required ? `${selected.filled} из ${selected.required}` : "Потребность не задана"}</dd><dt>Клиентский табель</dt><dd>{permissions.timesheets ? selected.timesheet ? <><Status>{selected.timesheet.status}</Status><span className="cell-sub">{selected.timesheet.period}</span></> : "Нет данных" : "Нет доступа"}</dd>{permissions.finance && <><dt>Финансовый факт</dt><dd>{selected.finance ? <>{rub(selected.finance.revenue)} выручка<span className="cell-sub">Вклад: {rub(selected.finance.contribution)} · {pct(selected.finance.marginPct)}</span><span className="cell-sub">{periodLabel(selected)}</span></> : "Нет данных"}</dd></>}</dl><h3>Следующие действия</h3><div className="portfolio-signals">{selected.signals.filter(signal => signal.tab !== "timesheets").map(signal => <Link className="button" key={signal.tab} href={linkTab(selected, signal.tab)}>{signal.label}</Link>)}{selected.timesheet && <p className="portfolio-data-note">Статус клиентского табеля: <Status>{selected.timesheet.status}</Status>. Подробная сверка выполняется в модуле табелей.</p>}{!selected.signals.length && <p className="portfolio-data-note">В доступных данных отклонения не выявлены.</p>}</div></SalesDrawer>}
  </>;
}
