"use client";
import { useEffect,useState } from "react";

type Specialty={id:string;name:string};
type Role={specialtyId:string;count:number;qualification?:string;experience?:string;salaryTarget?:number;salaryUnit?:string;scheduleType?:string;paidHours?:number;presenceHours?:number;requirements?:Record<string,unknown>};
type FormData={title:string;contactName:string;contactPosition:string;contactPhone:string;contactEmail:string;siteName:string;location:string;city:string;transportAccess:string;nearestTransport:string;logisticsComment:string;startDate:string;durationText:string;projectIndefinite:boolean;schedule:Record<string,unknown>;staffingRequirements:Record<string,unknown>;provision:Record<string,{provider:"client"|"us"|"not_required";amount?:number;unit?:string;comment?:string}>;commercialLimits:Record<string,unknown>;roles:Role[]};
type Payload={mode:string;requestId:string|null;request:Partial<FormData>|null;specialties:Specialty[]};
const provisionLabels:Record<string,string>={workwear:"Спецодежда",ppe:"СИЗ",food:"Питание",housing:"Проживание",shuttle:"Развозка",travel:"Проезд иногородних",medical:"Медосмотр",medicalBook:"Медкнижка",training:"Обучение",permits:"Допуски",tools:"Инструменты",other:"Другие расходы"};
const blank:FormData={title:"",contactName:"",contactPosition:"",contactPhone:"",contactEmail:"",siteName:"",location:"",city:"",transportAccess:"",nearestTransport:"",logisticsComment:"",startDate:"",durationText:"",projectIndefinite:false,schedule:{},staffingRequirements:{},provision:{},commercialLimits:{},roles:[]};

export function PublicRequestForm({token}:{token:string}){
  const [form,setForm]=useState<FormData>(blank);const [specialties,setSpecialties]=useState<Specialty[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [sent,setSent]=useState(false);
  useEffect(()=>{fetch(`/api/public/requests/${token}`,{cache:"no-store"}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);return data as Payload}).then(data=>{setSpecialties(data.specialties??[]);setForm({...blank,...(data.request??{}),roles:Array.isArray(data.request?.roles)?data.request.roles:[],provision:data.request?.provision??{},commercialLimits:data.request?.commercialLimits??{},schedule:data.request?.schedule??{},staffingRequirements:data.request?.staffingRequirements??{}})}).catch(e=>setError(e instanceof Error?e.message:"Форма недоступна")).finally(()=>setLoading(false))},[token]);
  function field<K extends keyof FormData>(key:K,value:FormData[K]){setForm(current=>({...current,[key]:value}))}
  function addRole(){if(!specialties[0])return;field("roles",[...form.roles,{specialtyId:specialties[0].id,count:1}])}
  function rolePatch(index:number,patch:Partial<Role>){field("roles",form.roles.map((role,i)=>i===index?{...role,...patch}:role))}
  function provision(key:string,provider:"client"|"us"|"not_required"){field("provision",{...form.provision,[key]:{...(form.provision[key]??{}),provider}})}
  async function submit(){setError("");try{const response=await fetch(`/api/public/requests/${token}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(clean(form))});const data=await response.json();if(!response.ok)throw new Error(data.error||"Не удалось отправить форму");setSent(true)}catch(e){setError(e instanceof Error?e.message:"Не удалось отправить форму")}}
  if(loading)return <div className="section" style={{maxWidth:980,margin:"40px auto",padding:24}}>Загрузка формы…</div>;
  if(error&&!form.title)return <div className="section" style={{maxWidth:760,margin:"40px auto",padding:24}}><h1>Ссылка недоступна</h1><p>{error}</p></div>;
  if(sent)return <div className="section" style={{maxWidth:760,margin:"40px auto",padding:24}}><h1>Данные отправлены</h1><p>Менеджер получил обновлённые условия заявки. Внутренние расчёты и служебная информация в этой форме не отображаются.</p></div>;
  return <main style={{maxWidth:1100,margin:"0 auto",padding:"28px 18px 56px"}}><header style={{marginBottom:18}}><div className="eyebrow">Анкета заказчика</div><h1 style={{margin:"6px 0"}}>Условия потребности в персонале</h1><p style={{maxWidth:760}}>Заполните известные данные. Необязательные поля можно оставить пустыми — менеджер уточнит их позже.</p></header>
    <div className="workspace-grid"><section className="section"><div className="section-head"><h2>Заказчик и площадка</h2></div><div style={{padding:16,display:"grid",gap:10}}><Text label="Рабочее название заявки" value={form.title} onChange={v=>field("title",v)} required/><div className="workspace-grid"><Text label="Контактное лицо" value={form.contactName} onChange={v=>field("contactName",v)}/><Text label="Должность" value={form.contactPosition} onChange={v=>field("contactPosition",v)}/><Text label="Телефон" value={form.contactPhone} onChange={v=>field("contactPhone",v)}/><Text label="Email" value={form.contactEmail} onChange={v=>field("contactEmail",v)} type="email"/></div><Text label="Название площадки" value={form.siteName} onChange={v=>field("siteName",v)}/><Text label="Адрес" value={form.location} onChange={v=>field("location",v)}/><div className="workspace-grid"><Text label="Город" value={form.city} onChange={v=>field("city",v)}/><Text label="Ближайший транспорт / метро" value={form.nearestTransport} onChange={v=>field("nearestTransport",v)}/></div><Text label="Транспортная доступность" value={form.transportAccess} onChange={v=>field("transportAccess",v)}/><Text label="Комментарий по логистике" value={form.logisticsComment} onChange={v=>field("logisticsComment",v)}/></div></section>
      <section className="section"><div className="section-head"><h2>Срок и коммерческие ориентиры</h2></div><div style={{padding:16,display:"grid",gap:10}}><div className="workspace-grid"><Text label="Дата старта" value={form.startDate} onChange={v=>field("startDate",v)} type="date"/><Text label="Срок проекта" value={form.durationText} onChange={v=>field("durationText",v)}/></div><label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={form.projectIndefinite} onChange={e=>field("projectIndefinite",e.target.checked)}/> Бессрочный проект</label><NumberField label="Желаемая ставка клиента, ₽/ч" value={Number(form.commercialLimits.desiredClientRate??0)} onChange={v=>field("commercialLimits",{...form.commercialLimits,desiredClientRate:v})}/><NumberField label="Максимальная ставка клиента, ₽/ч" value={Number(form.commercialLimits.maxClientRate??0)} onChange={v=>field("commercialLimits",{...form.commercialLimits,maxClientRate:v})}/><label><span className="cell-sub">Ставка указана</span><select value={String(form.commercialLimits.vatMode??"with_vat")} onChange={e=>field("commercialLimits",{...form.commercialLimits,vatMode:e.target.value})}><option value="with_vat">с НДС</option><option value="without_vat">без НДС</option></select></label></div></section></div>
    <section className="section" style={{marginTop:16}}><div className="section-head"><h2>Позиции</h2><button className="button" type="button" onClick={addRole}>Добавить специальность</button></div><div className="stack-list">{form.roles.length?form.roles.map((role,index)=><div className="stack-item" key={`${role.specialtyId}-${index}`} style={{alignItems:"start"}}><div style={{display:"grid",gridTemplateColumns:"minmax(180px,2fr) 100px minmax(150px,1fr) minmax(150px,1fr)",gap:8,width:"100%"}}><label><span className="cell-sub">Специальность</span><select value={role.specialtyId} onChange={e=>rolePatch(index,{specialtyId:e.target.value})}>{specialties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><NumberField label="Количество" value={role.count} onChange={v=>rolePatch(index,{count:Math.max(1,Math.round(v))})}/><Text label="Квалификация" value={role.qualification??""} onChange={v=>rolePatch(index,{qualification:v})}/><Text label="Опыт" value={role.experience??""} onChange={v=>rolePatch(index,{experience:v})}/><label><span className="cell-sub">График</span><select value={role.scheduleType??"5/2"} onChange={e=>rolePatch(index,{scheduleType:e.target.value})}><option>5/2</option><option>6/1</option><option>2/2</option><option value="watch">Вахта</option><option value="other">Другое</option></select></label><NumberField label="Часы присутствия" value={Number(role.presenceHours??0)} onChange={v=>rolePatch(index,{presenceHours:v})}/><NumberField label="Оплачиваемые часы" value={Number(role.paidHours??0)} onChange={v=>rolePatch(index,{paidHours:v})}/><NumberField label="Зарплатный ориентир" value={Number(role.salaryTarget??0)} onChange={v=>rolePatch(index,{salaryTarget:v})}/></div><button className="button" type="button" onClick={()=>field("roles",form.roles.filter((_,i)=>i!==index))}>Удалить</button></div>):<div className="stack-item"><span>Добавьте одну или несколько специальностей. Отдельная заявка на каждую профессию не требуется.</span></div>}</div></section>
    <section className="section" style={{marginTop:16}}><div className="section-head"><h2>Что предоставляется</h2></div><table className="data-table"><thead><tr><th>Условие</th><th>Кто предоставляет</th><th>Стоимость, если обеспечивает исполнитель</th></tr></thead><tbody>{Object.entries(provisionLabels).map(([key,label])=>{const item=form.provision[key]??{provider:"not_required" as const};return <tr key={key}><td className="cell-title">{label}</td><td><select value={item.provider} onChange={e=>provision(key,e.target.value as "client"|"us"|"not_required")}><option value="client">Заказчик</option><option value="us">Исполнитель</option><option value="not_required">Не требуется</option></select></td><td>{item.provider==="us"?<input type="number" min="0" value={item.amount??0} onChange={e=>field("provision",{...form.provision,[key]:{...item,amount:Number(e.target.value),unit:"₽"}})}/>:"—"}</td></tr>})}</tbody></table></section>
    {error&&<div className="compliance-note" style={{marginTop:16}}>{error}</div>}<div style={{display:"flex",justifyContent:"flex-end",marginTop:18}}><button className="button primary" type="button" onClick={submit}>Отправить данные менеджеру</button></div>
  </main>;
}
function Text({label,value,onChange,type="text",required=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean}){return <label><span className="cell-sub">{label}{required?" *":""}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label><span className="cell-sub">{label}</span><input type="number" min="0" value={value||""} onChange={e=>onChange(Number(e.target.value))}/></label>}
function clean(form:FormData){const result={...form};return Object.fromEntries(Object.entries(result).filter(([,value])=>value!==""))}
