"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ExternalLink, Phone, UserRound, X } from "lucide-react";
import { KeyValue, Status } from "@/components/UI";
import type { RecruitingApplicationRow, RecruitingNeedRow } from "@/lib/recruiting/service";
import { recruitingStageLabels, recruitingStages, type RecruitingStage } from "@/lib/recruiting/model";

type Props={rows:RecruitingApplicationRow[];needs:RecruitingNeedRow[];demo:boolean;canCreate:boolean;initialNeed?:string|null;initialObject?:string|null;initialSpecialty?:string|null;initialRecruiter?:string|null};
type CandidateForm={needId:string;fullName:string;phone:string;email:string;preferredChannel:string;telegram:string;whatsapp:string;city:string;source:string;sourceChannel:string;sourceCampaign:string;sourceReference:string;nextAction:string};
const blank:CandidateForm={needId:"",fullName:"",phone:"",email:"",preferredChannel:"phone",telegram:"",whatsapp:"",city:"",source:"Авито",sourceChannel:"",sourceCampaign:"",sourceReference:"",nextAction:""};
const storageKey="operis.recruiting.applications.v1";

export function RecruitingFunnelWorkspace({rows,needs,demo,canCreate,initialNeed,initialObject,initialSpecialty,initialRecruiter}:Props){
 const router=useRouter();const [query,setQuery]=useState("");const [needFilter,setNeedFilter]=useState(initialNeed??"all");const [objectFilter,setObjectFilter]=useState(initialObject??"all");const [specialtyFilter,setSpecialtyFilter]=useState(initialSpecialty??"all");const [recruiterFilter,setRecruiterFilter]=useState(initialRecruiter??"all");const [selected,setSelected]=useState<RecruitingApplicationRow|null>(null);const [showCreate,setShowCreate]=useState(false);const [form,setForm]=useState<CandidateForm>({...blank,needId:initialNeed??""});const [busy,setBusy]=useState("");const [error,setError]=useState("");const [localRows,setLocalRows]=useState<RecruitingApplicationRow[]>([]);
 useEffect(()=>{if(!demo)return;let frame=0;try{const raw=localStorage.getItem(storageKey);if(raw){const parsed=JSON.parse(raw) as RecruitingApplicationRow[];frame=requestAnimationFrame(()=>setLocalRows(parsed));}}catch{}return()=>{if(frame)cancelAnimationFrame(frame)}},[demo]);
 useEffect(()=>{const params=new URLSearchParams();if(needFilter!=="all")params.set("need",needFilter);if(objectFilter!=="all")params.set("object",objectFilter);if(specialtyFilter!=="all")params.set("specialty",specialtyFilter);if(recruiterFilter!=="all")params.set("recruiter",recruiterFilter);const qs=params.toString();router.replace(qs?`/recruiting?${qs}`:"/recruiting",{scroll:false})},[needFilter,objectFilter,specialtyFilter,recruiterFilter,router]);
 const allRows=useMemo(()=>[...localRows,...rows.filter(row=>!localRows.some(local=>local.applicationId===row.applicationId))],[localRows,rows]);
 const needById=useMemo(()=>new Map(needs.map(item=>[item.id,item])),[needs]);const objectOptions=useMemo(()=>Array.from(new Map(needs.filter(item=>item.objectId&&item.object).map(item=>[item.objectId!,item.object!])).entries()),[needs]);const specialtyOptions=useMemo(()=>Array.from(new Map(needs.map(item=>[item.specialtyId,item.specialty])).entries()),[needs]);const recruiterOptions=useMemo(()=>Array.from(new Map(needs.flatMap(item=>item.recruiters.map(recruiter=>[recruiter.userId,recruiter.name] as const))).entries()),[needs]);
 const filtered=useMemo(()=>allRows.filter(row=>{const need=needById.get(row.needId);if(needFilter!=="all"&&row.needId!==needFilter)return false;if(objectFilter!=="all"&&row.objectId!==objectFilter)return false;if(specialtyFilter!=="all"&&need?.specialtyId!==specialtyFilter)return false;if(recruiterFilter!=="all"&&!row.assigneeUserIds.includes(recruiterFilter)&&row.ownerUserId!==recruiterFilter)return false;if(!query.trim())return true;return `${row.fullName} ${row.phone??""} ${row.need} ${row.object??""} ${row.source??""}`.toLocaleLowerCase("ru").includes(query.trim().toLocaleLowerCase("ru"))}),[allRows,needById,needFilter,objectFilter,specialtyFilter,recruiterFilter,query]);
 const active=filtered.filter(row=>!["rejected","no_show"].includes(row.stage));const terminals=filtered.filter(row=>["rejected","no_show"].includes(row.stage));const hasContext=needFilter!=="all"||objectFilter!=="all"||specialtyFilter!=="all"||recruiterFilter!=="all";
 async function changeStage(row:RecruitingApplicationRow,stage:RecruitingStage){if(stage===row.stage)return;let reason:string|undefined;if(["rejected","no_show"].includes(stage)){reason=window.prompt(stage==="rejected"?"Причина отказа":"Почему кандидат не вышел")?.trim()||undefined;if(!reason)return;}setBusy(row.applicationId);setError("");try{if(demo){const updated:RecruitingApplicationRow={...row,stage,stageLabel:recruitingStageLabels[stage],rejectionReason:reason??null,actualStartAt:stage==="started"?new Date().toISOString():row.actualStartAt};const next=[updated,...localRows.filter(item=>item.applicationId!==row.applicationId)];setLocalRows(next);localStorage.setItem(storageKey,JSON.stringify(next));setSelected(updated);}else{const response=await fetch(`/api/candidates/${row.candidateId}/stage`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({applicationId:row.applicationId,stage,reason})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось изменить этап");router.refresh();setSelected(null);}}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить этап");}finally{setBusy("")}}
 async function createCandidate(event:React.FormEvent){event.preventDefault();setError("");const need=needs.find(item=>item.id===form.needId);if(!need){setError("Выберите потребность");return;}if(!form.phone&&!form.email){setError("Укажите телефон или email");return;}setBusy("create");try{if(demo){const stage:RecruitingStage="new";const created:RecruitingApplicationRow={applicationId:crypto.randomUUID(),candidateId:crypto.randomUUID(),organizationId:need.organizationId,fullName:form.fullName,phone:form.phone||null,email:form.email||null,preferredChannel:form.preferredChannel||null,telegram:form.telegram||null,whatsapp:form.whatsapp||null,city:form.city||null,source:form.source||"Ручной ввод",sourceChannel:form.sourceChannel||null,sourceCampaign:form.sourceCampaign||null,sourceReference:form.sourceReference||null,stage,stageLabel:recruitingStageLabels[stage],needId:need.id,need:need.title,objectId:need.objectId,object:need.object,regionId:need.regionId,clientId:need.clientId,ownerUserId:need.ownerUserId,owner:need.owner,managerUserId:need.managerUserId,manager:need.manager,assigneeUserIds:need.assigneeUserIds,nextAction:form.nextAction||null,plannedStartDate:null,actualStartAt:null,rejectionReason:null,conditions:need.conditions};const next=[created,...localRows];setLocalRows(next);localStorage.setItem(storageKey,JSON.stringify(next));}else{const response=await fetch("/api/candidates",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fullName:form.fullName,phone:form.phone||null,email:form.email||null,preferredChannel:form.preferredChannel||null,telegram:form.telegram||null,whatsapp:form.whatsapp||null,city:form.city||null,source:form.source||null,sourceChannel:form.sourceChannel||null,sourceCampaign:form.sourceCampaign||null,sourceReference:form.sourceReference||null,needId:form.needId,nextActionAt:form.nextAction?new Date(form.nextAction).toISOString():null})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось добавить кандидата");router.refresh();}setShowCreate(false);setForm({...blank,needId:needFilter==="all"?"":needFilter});}catch(e){setError(e instanceof Error?e.message:"Не удалось добавить кандидата");}finally{setBusy("")}}
 return <div className="recruiting-workspace">
  <div className="recruiting-summary"><div><span>В работе</span><strong>{active.length}</strong></div><div><span>На согласовании</span><strong>{active.filter(x=>x.stage==="manager_review").length}</strong></div><div><span>Готовы к выходу</span><strong>{active.filter(x=>x.stage==="ready").length}</strong></div><div><span>Фактически вышли</span><strong>{filtered.filter(x=>x.stage==="started").length}</strong></div></div>
  {hasContext&&<div className="recruiting-filter-context"><div><strong>Воронка отфильтрована из потребностей</strong><span>{needFilter!=="all"?(needById.get(needFilter)?.title??"Потребность"):objectFilter!=="all"?(objectOptions.find(([id])=>id===objectFilter)?.[1]??"Объект"):"Выбранный контур"}</span></div><Link className="button" href="/needs">← Потребности</Link></div>}
  <div className="recruiting-toolbar"><div className="recruiting-toolbar-left recruiting-funnel-filters"><select className="request-search" value={needFilter} onChange={e=>setNeedFilter(e.target.value)}><option value="all">Все потребности</option>{needs.filter(x=>["open","in_progress","paused"].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.title} · {x.object??x.region??"без объекта"}</option>)}</select><select className="request-search" value={objectFilter} onChange={e=>setObjectFilter(e.target.value)}><option value="all">Все объекты</option>{objectOptions.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select className="request-search" value={specialtyFilter} onChange={e=>setSpecialtyFilter(e.target.value)}><option value="all">Все специальности</option>{specialtyOptions.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select className="request-search" value={recruiterFilter} onChange={e=>setRecruiterFilter(e.target.value)}><option value="all">Все рекрутеры</option>{recruiterOptions.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div><div className="recruiting-toolbar-actions"><input className="request-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Кандидат, телефон, объект, источник"/>{canCreate&&<button className="button primary" onClick={()=>setShowCreate(true)}>+ Добавить кандидата</button>}</div></div>
  {error&&<div className="recruiting-error">{error}</div>}
  <div className="recruiting-funnel-scroll"><div className="recruiting-funnel">{recruitingStages.map(stage=><section className="recruiting-column" key={stage}><header><span>{recruitingStageLabels[stage]}</span><span>{active.filter(x=>x.stage===stage).length}</span></header><div className="recruiting-cards">{active.filter(x=>x.stage===stage).map(row=><button key={row.applicationId} className={`recruiting-card${isOverdue(row.nextAction)?" is-overdue":""}`} onClick={()=>setSelected(row)}><strong>{row.fullName}</strong><span>{row.need}{row.object?` · ${row.object}`:""}</span><div className="recruiting-card-meta"><span>{row.source??"Источник не указан"}</span><span>{row.nextAction??"Без следующего действия"}</span></div></button>)}</div></section>)}</div></div>
  {terminals.length>0&&<div className="recruiting-terminal"><strong>Выбыли из активной воронки: {terminals.length}</strong><span>Отказы: {terminals.filter(x=>x.stage==="rejected").length} · не вышли: {terminals.filter(x=>x.stage==="no_show").length}</span></div>}
  {selected&&<><div className="drawer-backdrop" onClick={()=>setSelected(null)}/><aside className="drawer"><button className="icon-button drawer-close" onClick={()=>setSelected(null)} aria-label="Закрыть"><X size={17}/></button><div className="eyebrow">Кандидат · {selected.source??"источник не указан"}</div><h2>{selected.fullName}</h2><Status tone={selected.stage==="started"?"good":["rejected","no_show"].includes(selected.stage)?"bad":"info"}>{selected.stageLabel}</Status><div className="drawer-content"><KeyValue label="Контакт" value={<span><Phone size={13}/> {selected.phone??selected.email??"Не указан"}</span>}/><KeyValue label="Потребность" value={selected.need}/><KeyValue label="Объект" value={selected.object??"Без объекта"}/><KeyValue label="Рекрутер" value={selected.owner??"Не назначен"}/><KeyValue label="Следующее действие" value={selected.nextAction??"Не запланировано"}/><section className="section" style={{marginTop:14}}><div className="section-head"><div><h2>Перевести на этап</h2><p>Переход фиксируется в истории кандидата</p></div></div><div style={{padding:"0 14px 14px"}}><select style={{width:"100%"}} value={selected.stage} disabled={busy===selected.applicationId} onChange={e=>void changeStage(selected,e.target.value as RecruitingStage)}>{recruitingStages.map(stage=><option key={stage} value={stage}>{recruitingStageLabels[stage]}</option>)}<option value="rejected">Отказ</option><option value="no_show">Не вышел</option></select></div></section></div><div className="drawer-actions"><Link className="button primary" href={`/candidates/${selected.candidateId}`}><UserRound size={14}/> Полная карточка</Link>{selected.objectId&&<Link className="button" href={`/objects/${selected.objectId}?tab=recruiting`}><ExternalLink size={14}/> Объект</Link>}</div></aside></>}
  {showCreate&&<div className="recruiting-modal" onMouseDown={e=>{if(e.target===e.currentTarget)setShowCreate(false)}}><form className="recruiting-modal-card" onSubmit={createCandidate}><div className="recruiting-modal-head"><div><h2>Добавить кандидата</h2><p>Если телефон или email уже есть в базе, новая карточка человека не создаётся — добавится новая заявка.</p></div><button className="icon-button" type="button" onClick={()=>setShowCreate(false)}><X size={17}/></button></div><div className="recruiting-form">{error&&<div className="recruiting-error">{error}</div>}<div className="recruiting-form-grid"><label className="wide">Потребность<select required value={form.needId} onChange={e=>setForm(x=>({...x,needId:e.target.value}))}><option value="">Выберите потребность</option>{needs.filter(x=>["open","in_progress"].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.title} · {x.object??x.region??"без объекта"} · нужно {x.deficit}</option>)}</select></label><label>ФИО<input required value={form.fullName} onChange={e=>setForm(x=>({...x,fullName:e.target.value}))}/></label><label>Телефон<input value={form.phone} onChange={e=>setForm(x=>({...x,phone:e.target.value}))}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm(x=>({...x,email:e.target.value}))}/></label><label>Предпочтительный канал<select value={form.preferredChannel} onChange={e=>setForm(x=>({...x,preferredChannel:e.target.value}))}><option value="phone">Телефон</option><option value="whatsapp">WhatsApp</option><option value="telegram">Telegram</option><option value="email">Email</option><option value="other">Другой</option></select></label><label>Telegram<input value={form.telegram} onChange={e=>setForm(x=>({...x,telegram:e.target.value}))}/></label><label>WhatsApp<input value={form.whatsapp} onChange={e=>setForm(x=>({...x,whatsapp:e.target.value}))}/></label><label>Город<input value={form.city} onChange={e=>setForm(x=>({...x,city:e.target.value}))}/></label><label>Источник<input value={form.source} onChange={e=>setForm(x=>({...x,source:e.target.value}))} placeholder="Авито, Telegram, рекомендация"/></label><label>Канал / площадка<input value={form.sourceChannel} onChange={e=>setForm(x=>({...x,sourceChannel:e.target.value}))}/></label><label>Кампания / объявление<input value={form.sourceCampaign} onChange={e=>setForm(x=>({...x,sourceCampaign:e.target.value}))}/></label><label>Ссылка / идентификатор<input value={form.sourceReference} onChange={e=>setForm(x=>({...x,sourceReference:e.target.value}))}/></label><label>Следующее действие<input type="datetime-local" value={form.nextAction} onChange={e=>setForm(x=>({...x,nextAction:e.target.value}))}/></label></div><div className="recruiting-form-actions"><button type="button" className="button" onClick={()=>setShowCreate(false)}>Отмена</button><button className="button primary" disabled={busy==="create"}>{busy==="create"?"Сохраняю…":"Добавить кандидата"}</button></div></div></form></div>}
 </div>
}
function isOverdue(value:string|null){if(!value)return false;const m=value.match(/(\d{2})\.(\d{2})\.(\d{4})\s*(\d{2})?:?(\d{2})?/);if(!m)return false;const date=new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),Number(m[4]??23),Number(m[5]??59));return date.getTime()<Date.now()}
