"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {ContactFields,emptyContact,type ContactValues} from '@/components/sales/ContactFields';
import {SalesEditSection,useUnsavedChanges} from '@/components/sales/SalesEditSection';
import {getDemoRequest,saveDemoRequest} from '@/lib/commercial/demo-workspace-client';
import {demoClientSnapshotKey,loadDemoClientSnapshot,saveDemoClientSnapshot} from '@/components/sales/DemoClientPreview';
import {mergeContactIntake} from '@/lib/commercial/contact-snapshot';
import type {RequestIntake} from '@/lib/commercial/request-intake';
import type {ClientContactRow,ClientRow} from '@/lib/data/service';
import type {CommercialRequestDetail} from '@/lib/commercial/service';
import type {RequestBoardRow,RequestWorkspaceOptions,RequestWorkflowMeta} from '@/lib/commercial/request-workflow';
type Props={request:CommercialRequestDetail;intake:RequestIntake;demo:boolean;scope:string;options:RequestWorkspaceOptions;board?:RequestBoardRow;workflow:RequestWorkflowMeta;canEdit:boolean};
function fromContact(c:ClientContactRow):ContactValues{return {...emptyContact,fullName:c.fullName,position:c.position??'',phone:c.phone??'',email:c.email??'',telegram:c.telegram??'',whatsapp:c.whatsapp??'',maxContact:c.maxContact??'',preferredChannel:c.preferredChannel??''};}
export function RequestContactSection(props:Props){const {intake,canEdit}=props;return <SalesEditSection title="Контакт по заявке" canEdit={canEdit} editor={(done,cancel)=><Editor {...props} done={done} cancel={cancel}/>}><div className="request-entity-side-body"><div className="key-value"><span>ФИО</span><strong>{intake.contact.name||'Не указан'}</strong></div><div className="key-value"><span>Связь</span><strong>{[intake.contact.phone,intake.contact.email,...intake.contact.messengers.map(x=>x.value)].filter(Boolean).join(' · ')||'Не указана'}</strong></div></div></SalesEditSection>;}
function Editor({request,intake,demo,scope,options,board,workflow,done,cancel}:Props&{done:()=>void;cancel:()=>void}){
 const router=useRouter();const initial={...emptyContact,fullName:intake.contact.name,phone:intake.contact.phone,email:intake.contact.email,telegram:intake.contact.messengers.find(x=>x.type==='telegram')?.value??'',whatsapp:intake.contact.messengers.find(x=>x.type==='whatsapp')?.value??'',maxContact:intake.contact.messengers.find(x=>x.type==='max')?.value??''};
 const [values,setValues]=useState<ContactValues>(initial),[mode,setMode]=useState<'snapshot'|'existing'|'new'>('snapshot'),[selected,setSelected]=useState(request.contactId??''),[contacts,setContacts]=useState<ClientContactRow[]>([]),[client,setClient]=useState<ClientRow|null>(null),[canCreate,setCanCreate]=useState(false),[loading,setLoading]=useState(Boolean(request.clientId)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loadError,setLoadError]=useState('');
 const dirty=JSON.stringify(values)!==JSON.stringify(initial)||mode!=='snapshot';const canLeave=useUnsavedChanges(dirty);
 useEffect(()=>{if(!request.clientId)return;let ignore=false;const stored=demo?loadDemoClientSnapshot(scope,request.clientId):null;if(stored?.contactRows){queueMicrotask(()=>{if(!ignore){setClient(stored);setContacts(stored.contactRows??[]);}});}
 fetch(`/api/clients/${request.clientId}/contacts`).then(async response=>{const json=await response.json();if(!response.ok)throw Error(json.error??'Не удалось загрузить контакты');if(!ignore){setClient(stored??json.client);setContacts(stored?.contactRows??json.contacts);setCanCreate(Boolean(json.canEdit));}}).catch(e=>{if(!ignore)setLoadError(e.message);}).finally(()=>{if(!ignore)setLoading(false);});return()=>{ignore=true;};},[request.clientId,demo,scope]);
 function changeMode(next:'snapshot'|'existing'|'new'){setMode(next);setError('');if(next==='new')setValues({...emptyContact});else if(next==='snapshot')setValues(initial);else{const found=contacts.find(x=>x.id===selected)??contacts[0];setSelected(found?.id??'');if(found)setValues(fromContact(found));}}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;if(mode==='existing'&&!selected){setError('Выберите контакт');return;}setBusy(true);setError('');try{
  if(demo){let contactId=mode==='existing'?selected:null;let nextClient=client?loadDemoClientSnapshot(scope,client.id)??client:null;let rows:ClientContactRow[]=(nextClient as (ClientRow&{contactRows?:ClientContactRow[]})|null)?.contactRows??contacts;
   if(mode==='new'){if(!client||!canCreate)throw Error('Недостаточно прав для создания контакта');if(rows.some(c=>c.fullName.toLowerCase()===values.fullName.toLowerCase()&&((values.phone&&c.phone?.replace(/\D/g,'')===values.phone.replace(/\D/g,''))||(values.email&&c.email?.toLowerCase()===values.email.toLowerCase()))))throw Error('Такой контакт уже есть. Выберите его из списка.');contactId=crypto.randomUUID();rows=[...rows,{...client,...values,id:contactId,clientId:client.id,objectAssignments:[]}];nextClient={...client,...nextClient,contacts:rows.length,contactRows:rows,updatedAt:new Date().toISOString()} as ClientRow;}
   const previous=getDemoRequest(request.id);const nextIntake=mergeContactIntake(previous?.payload.intake??intake,values,mode==='snapshot');
   const payload={clientId:request.clientId,title:request.title,source:request.source,location:request.location,regionId:request.regionId,startDate:request.startDate?.slice(0,10)??null,durationText:request.durationText,schedule:request.schedule,lunchPaid:request.lunchPaid??false,vatMode:request.vatMode,comments:request.comments,ownerUserId:request.ownerUserId,observerUserIds:workflow.observers.map(x=>x.id),roles:request.roles.map(x=>({...x,specialtyName:x.specialty,targetClientRate:x.targetClientRate==null?null:Number(x.targetClientRate)})),...previous?.payload,contactId,intake:nextIntake};
   const snapshotKey=mode==='new'&&nextClient?demoClientSnapshotKey(scope,nextClient.id):null;const oldSnapshot=snapshotKey?sessionStorage.getItem(snapshotKey):null;
   if(mode==='new'&&nextClient&&!saveDemoClientSnapshot(scope,{...nextClient,contactRows:rows} as ClientRow,true))throw Error('Не удалось сохранить контакт клиента');
   try{saveDemoRequest(payload,{id:request.id,base:previous?.board??board,clientName:options.clients.find(x=>x.id===request.clientId)?.name,actorId:options.currentUserId});}catch(cause){if(snapshotKey){if(oldSnapshot)sessionStorage.setItem(snapshotKey,oldSnapshot);else sessionStorage.removeItem(snapshotKey);window.dispatchEvent(new Event('operis:demo-client-edit'));}throw cause;}
  }else{const response=await fetch(`/api/requests/${request.id}/contact`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({expectedUpdatedAt:request.updatedAt,mode,contactId:selected||null,values})});const json=await response.json();if(!response.ok)throw Error(json.error??'Не удалось сохранить контакт');}
  done();router.refresh();
 }catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить контакт');}finally{setBusy(false);}}
 return <form onSubmit={save}><fieldset className="sales-edit-fieldset" disabled={busy}><div className="form-grid two"><label><span>Действие</span><select value={mode} onChange={e=>changeMode(e.target.value as typeof mode)}><option value="snapshot">Контактные данные этой заявки</option>{request.clientId&&<option value="existing" disabled={loading||!contacts.length}>Выбрать контакт клиента</option>}{request.clientId&&canCreate&&<option value="new">Добавить контакт клиенту</option>}</select></label>{mode==='existing'&&<label><span>Контакт клиента *</span><select required value={selected} onChange={e=>{setSelected(e.target.value);const found=contacts.find(x=>x.id===e.target.value);if(found)setValues(fromContact(found));}}>{contacts.map(x=><option key={x.id} value={x.id}>{x.fullName}{x.position?' · '+x.position:''}</option>)}</select></label>}</div>{loading&&<p role="status">Загрузка контактов…</p>}{loadError&&<p className="muted">{loadError}. Можно сохранить контактные данные только в этой заявке.</p>}<fieldset className="sales-edit-fieldset" disabled={mode==='existing'}><ContactFields key={`${mode}:${mode==='existing'?selected:''}`} value={values} onChange={setValues} showPosition={mode==='new'}/></fieldset><p className="muted">{mode==='new'?'Контакт будет добавлен клиенту и выбран для этой заявки.':'Изменения в этой заявке не переписывают контакт клиента и старые документы.'}</p>{error&&<p role="alert" className="form-error">{error}</p>}<div className="sales-edit-footer"><button className="button" type="button" onClick={()=>{if(canLeave())cancel();}}>Отмена</button><button className="button primary" type="submit">Сохранить контакт</button></div></fieldset></form>;
}
