"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {CalendarClock,LayoutList,Columns3,Plus,Search} from "lucide-react";
import type {TenderRow} from "@/lib/tenders/service";
import {tenderDecisionLabels,tenderStageLabel,tenderStages,tenderDeadlineState,tenderBillingLabels,tenderResultLabels} from "@/lib/tenders/model";
import {rub} from "@/lib/ui/format";
import {TenderImportPanel} from "@/components/TenderImportPanel";

type View="list"|"board";type Bucket="active"|"completed";type DeadlineFilter="all"|"today"|"3d"|"7d";
function date(value:string|null){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});}
function deadlineClass(key:string){return key==="overdue"||key==="today"?"danger":key==="urgent"?"warn":"neutral";}
function activity(value:string){const d=new Date(value);if(Number.isNaN(d.getTime()))return "—";const diff=Math.floor((Date.now()-d.getTime())/86400000);return diff<=0?"Сегодня":diff===1?"Вчера":`${diff} дн. назад`;}

export function TendersWorkspace({rows,canCreate,canImport,canEdit}:{rows:TenderRow[];canCreate:boolean;canImport:boolean;canEdit:boolean}){
  const router=useRouter();const [view,setView]=useState<View>("list");const [bucket,setBucket]=useState<Bucket>("active");const [deadline,setDeadline]=useState<DeadlineFilter>("all");const [query,setQuery]=useState("");const [dragId,setDragId]=useState<string|null>(null);const [busyId,setBusyId]=useState<string|null>(null);
  const now=new Date();const active=rows.filter(r=>r.stage!=="completed");const urgent=active.filter(r=>["overdue","today","urgent"].includes(tenderDeadlineState(r.submissionDeadline,now).key));const analysis=active.filter(r=>["new","analysis","clarification"].includes(r.stage));const participating=active.filter(r=>r.decision==="participate");
  const filtered=useMemo(()=>rows.filter(row=>bucket==="completed"?row.stage==="completed":row.stage!=="completed").filter(row=>{const q=query.trim().toLowerCase();return !q||[row.title,row.customer,row.platform??"",row.procedureNumber??"",row.owner??""].some(v=>v.toLowerCase().includes(q));}).filter(row=>{if(deadline==="all")return true;const d=tenderDeadlineState(row.submissionDeadline);if(deadline==="today")return ["overdue","today"].includes(d.key);if(deadline==="3d")return ["overdue","today","urgent"].includes(d.key);return d.days!=null&&d.days<=7;}),[rows,bucket,query,deadline]);
  async function move(id:string,stage:string){if(!canEdit||stage==="completed")return;setBusyId(id);const response=await fetch(`/api/tenders/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"stage",stage})});setBusyId(null);if(response.ok)router.refresh();else{const json=await response.json().catch(()=>({}));alert(json.error??"Не удалось изменить этап");}}
  return <div className="request-baseline-registry tender-registry">
    <div className="request-final-command-strip tender-command-strip"><div><span>В работе</span><strong>{active.length}</strong><small>активных тендеров</small></div><div><span>Требуют анализа</span><strong>{analysis.length}</strong><small>новые и уточнения</small></div><div><span>Участвуем</span><strong>{participating.length}</strong><small>решение принято</small></div><div className={urgent.length?"attention":""}><span>Срок ≤ 3 дней</span><strong>{urgent.length}</strong><small>требуют внимания</small></div></div>
    <div className="requests-toolbar tender-toolbar"><div className="segmented"><button className={bucket==="active"?"active":""} onClick={()=>setBucket("active")}>Активные</button><button className={bucket==="completed"?"active":""} onClick={()=>setBucket("completed")}>Завершённые</button></div><div className="segmented"><button className={view==="list"?"active":""} onClick={()=>setView("list")}><LayoutList size={14}/> Список</button><button className={view==="board"?"active":""} onClick={()=>setView("board")}><Columns3 size={14}/> Доска</button></div><label className="request-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по тендерам"/></label><select value={deadline} onChange={e=>setDeadline(e.target.value as DeadlineFilter)}><option value="all">Все сроки</option><option value="today">Сегодня / просрочено</option><option value="3d">До 3 дней</option><option value="7d">До 7 дней</option></select><div className="toolbar-spacer"/>{canImport&&<TenderImportPanel canImport={canImport}/>} {canCreate&&<Link className="button primary" href="/tenders/new"><Plus size={14}/> Новый тендер</Link>}</div>

    {view==="list"?<div className="request-table-wrap"><table className="request-registry-table tender-table"><thead><tr><th>Тендер</th><th>Заказчик</th><th>Подача до</th><th>Осталось</th><th>Этап</th><th>Блокеры</th><th>Ответственный</th><th>Активность</th></tr></thead><tbody>{filtered.length?filtered.map(row=>{const dl=tenderDeadlineState(row.submissionDeadline);return <tr key={row.id}><td><Link href={`/tenders/${row.id}`} className="cell-title">{row.title}</Link><span className="cell-sub">{[row.platform,row.procedureNumber].filter(Boolean).join(" · ")||"Площадка не указана"}{row.initialPrice?` · ${rub(row.initialPrice)}`:""}</span></td><td>{row.customer}<span className="cell-sub">{row.sourceName??"Источник не указан"}</span></td><td><strong>{date(row.submissionDeadline)}</strong><span className="cell-sub">{row.billingUnit!=="unknown"?tenderBillingLabels[row.billingUnit]:"Формат цены не определён"}</span></td><td><span className={`tender-deadline ${deadlineClass(dl.key)}`}><CalendarClock size={13}/>{dl.label}</span></td><td><span className="status neutral">{row.stage==="completed"?(row.result?tenderResultLabels[row.result]:"Завершён"):tenderStageLabel(row.stage)}</span><span className="cell-sub">{tenderDecisionLabels[row.decision]}</span></td><td>{row.blockerCount>0?<><strong className="tender-blocker-count">{row.blockerCount}</strong><span className="cell-sub">по документам</span></>:"—"}</td><td>{row.owner??"Не назначен"}<span className="cell-sub">{row.nextActionText??"Нет следующего действия"}</span></td><td>{activity(row.updatedAt)}</td></tr>}):<tr><td colSpan={8}><div className="commercial-empty">По выбранным фильтрам тендеров нет</div></td></tr>}</tbody></table></div>:
      <div className="tender-board">{tenderStages.filter(stage=>bucket==="completed"?stage.code==="completed":stage.code!=="completed").map(stage=>{const items=filtered.filter(row=>row.stage===stage.code);return <section className="tender-board-column" key={stage.code} onDragOver={e=>{if(canEdit&&stage.code!=="completed")e.preventDefault()}} onDrop={()=>{if(dragId)void move(dragId,stage.code);setDragId(null)}}><header><strong>{stage.label}</strong><span>{items.length}</span></header><div className="tender-board-stack">{items.map(row=>{const dl=tenderDeadlineState(row.submissionDeadline);return <article key={row.id} draggable={canEdit&&row.stage!=="completed"} onDragStart={()=>setDragId(row.id)} onDragEnd={()=>setDragId(null)} className={busyId===row.id?"busy":""}><Link href={`/tenders/${row.id}`}><strong>{row.title}</strong><span>{row.customer}</span><div className="tender-card-meta"><span className={`tender-deadline ${deadlineClass(dl.key)}`}>{dl.label}</span><span>{date(row.submissionDeadline)}</span></div>{row.nextActionText&&<small>{row.nextActionText}</small>}<footer><span>{row.owner??"Не назначен"}</span>{row.blockerCount>0&&<b>{row.blockerCount} блок.</b>}</footer></Link></article>)}{!items.length&&<div className="tender-board-empty">Нет тендеров</div>}</div></section>})}</div>}
  </div>;
}
