"use client";
import {useMemo,useState,useRef} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {Check,Pencil,Plus,Send,Trash2} from "lucide-react";
import {SalesInlineForm} from "@/components/sales/SalesInlineForm";
import {useUnsavedChanges,useSalesEditSession} from "@/components/sales/SalesEditSection";
import {saveDemoTenderSnapshot} from "@/components/sales/DemoTenderPreview";
import {TenderDataEditor} from "@/components/TenderDataEditor";
import {SalesDrawer} from "@/components/sales/SalesUI";
import {formatTenderDateTime,tenderDateTimeInput,tenderDateTimeIso} from "@/lib/tenders/datetime";
import type {TenderDetail,TenderOptions,TenderRequirement,TenderRole,TenderSourceDocument} from "@/lib/tenders/service";
import {tenderAssignmentLabels,tenderBillingLabels,tenderDocumentStatusLabels,tenderStages} from "@/lib/tenders/model";

const iso=tenderDateTimeIso;
async function jsonRequest(url:string,method:string,body:unknown){const response=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось сохранить изменения");return json;}
function condition(value:unknown){return typeof value==="string"?value:"";}
const tenderBidVatModeLabels:Record<string,string>={unknown:"Не определено",with_vat:"С НДС",without_vat:"Без НДС",not_applicable:"НДС не применяется"};
const tenderBidSourceLabels:Record<string,string>={submission:"Подача",auction:"Торги",correction:"Исправление",manual:"Ручная фиксация"};
function tenderMoney(value:number|string|null|undefined){if(value==null)return "—";return new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(Number(value));}

export function TenderCoreEditor({tender,options,canEdit,canResult,canSubmit,mode="all",initialOpen=false,returnHref}:{tender:TenderDetail;options:TenderOptions;canEdit:boolean;canResult:boolean;canSubmit:boolean;mode?:"all"|"core"|"workflow";initialOpen?:boolean;returnHref?:string}){
  const router=useRouter();const [coreOpen,setCoreOpen]=useState(initialOpen);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [noBidOpen,setNoBidOpen]=useState(false);const [noBidReasonCode,setNoBidReasonCode]=useState(tender.noBidReasonCode??"");const [noBidComment,setNoBidComment]=useState(tender.noBidComment??"");
  function closeCore(){if(busy)return;setCoreOpen(false);setError("");if(initialOpen&&returnHref)router.replace(returnHref,{scroll:false});}
  async function stage(stage:string){if(stage==="submitted"&&!canSubmit||stage==="completed")return;setBusy(true);setError("");try{await jsonRequest(`/api/tenders/${tender.id}`,"PATCH",{expectedUpdatedAt:tender.updatedAt,action:"stage",stage,decision:tender.decision,result:tender.result,noBidReasonCode:tender.noBidReasonCode,noBidComment:tender.noBidComment,resultReasonCode:tender.resultReasonCode,closeReason:tender.closeReason});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}}
  async function decision(decision:string){
    if(decision==="no_bid"){setNoBidOpen(true);setNoBidReasonCode(tender.noBidReasonCode??"");setNoBidComment(tender.noBidComment??"");return}
    setBusy(true);setError("");try{await jsonRequest(`/api/tenders/${tender.id}`,"PATCH",{expectedUpdatedAt:tender.updatedAt,action:"stage",stage:tender.stage,decision,result:tender.result,noBidReasonCode:null,noBidComment:null,resultReasonCode:tender.resultReasonCode,closeReason:tender.closeReason});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}
  }
  async function saveNoBid(){if(!noBidReasonCode){setError("Выберите причину отказа от участия");return}setBusy(true);setError("");try{await jsonRequest(`/api/tenders/${tender.id}`,"PATCH",{expectedUpdatedAt:tender.updatedAt,action:"stage",stage:tender.stage,decision:"no_bid",result:tender.result,noBidReasonCode,noBidComment:noBidComment||null,resultReasonCode:tender.resultReasonCode,closeReason:tender.closeReason});setNoBidOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}}
  async function complete(result:string,reasonCode:string|null,reason:string){setBusy(true);setError("");try{await jsonRequest(`/api/tenders/${tender.id}`,"PATCH",{expectedUpdatedAt:tender.updatedAt,action:"stage",stage:"completed",decision:result==="no_bid"?"no_bid":tender.decision,result,noBidReasonCode:result==="no_bid"?reasonCode:tender.noBidReasonCode,noBidComment:result==="no_bid"?(reason||null):tender.noBidComment,resultReasonCode:result==="lost"?reasonCode:null,closeReason:reason||null});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}}
  if(!canEdit)return null;
  return <div className="tender-controls-stack">{mode!=="workflow"&&<><button className="button" type="button" onClick={()=>{setError("");setCoreOpen(true);}}><Pencil size={14}/> Быстрое редактирование</button>{coreOpen&&<TenderDataEditor tender={tender} options={options} quick onSaved={()=>{closeCore();router.refresh();}} onCancel={closeCore}/>}</>}
    {mode!=="core"&&<div className="tender-quick-controls"><label><span>Этап</span><select value={tender.stage} onChange={e=>void stage(e.target.value)} disabled={busy}>{tenderStages.filter(s=>s.code!=="completed"||tender.stage==="completed").map(s=><option key={s.code} value={s.code} disabled={s.code==="completed"||(s.code==="submitted"&&!canSubmit)}>{s.label}</option>)}</select></label><label><span>Решение</span><select value={tender.decision} onChange={e=>void decision(e.target.value)} disabled={busy}><option value="undecided">Не принято</option><option value="participate">Участвуем</option><option value="needs_clarification">Нужно уточнить</option><option value="no_bid">Не участвуем</option></select></label></div>}
    {mode!=="core"&&canResult&&<TenderResultControl current={tender.result??""} reason={tender.closeReason??""} currentReasonCode={tender.resultReasonCode??tender.noBidReasonCode??""} noBidReasons={options.noBidReasons} lossReasons={options.lossReasons} busy={busy} onComplete={complete}/>} {!coreOpen&&error&&<p className="form-error" role="alert">{error}</p>}
    {noBidOpen&&<SalesDrawer title="Не участвуем" overline="Решение по тендеру" subtitle="Выберите причину отказа. Комментарий сохранится отдельно." onClose={()=>{if(!busy)setNoBidOpen(false);}} footer={<><button type="button" className="button" disabled={busy} onClick={()=>setNoBidOpen(false)}>Отмена</button><button type="button" className="button primary" disabled={busy||!noBidReasonCode} onClick={()=>void saveNoBid()}>{busy?"Сохраняю…":"Сохранить решение"}</button></>}><div className="form-grid"><label><span>Причина</span><select value={noBidReasonCode} disabled={busy} onChange={event=>setNoBidReasonCode(event.target.value)}><option value="">Выберите причину</option>{options.noBidReasons.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label><span>Комментарий</span><textarea rows={3} disabled={busy} value={noBidComment} onChange={event=>setNoBidComment(event.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}</div></SalesDrawer>}
  </div>;
}
function TenderResultControl({current,reason,currentReasonCode,noBidReasons,lossReasons,busy,onComplete}:{current:string;reason:string;currentReasonCode:string;noBidReasons:Array<{code:string;name:string}>;lossReasons:Array<{code:string;name:string}>;busy:boolean;onComplete:(result:string,reasonCode:string|null,reason:string)=>Promise<void>}){
  const [result,setResult]=useState(current||"lost");const [note,setNote]=useState(reason);const [reasonCode,setReasonCode]=useState(currentReasonCode);
  const options=result==="lost"?lossReasons:result==="no_bid"?noBidReasons:[];
  const reasonRequired=result==="lost"||result==="no_bid";
  return <details className="tender-edit-panel"><summary>Завершить тендер</summary><div className="tender-panel-body"><label><span>Результат</span><select value={result} onChange={e=>{setResult(e.target.value);setReasonCode("")}}><option value="won">Выиграли</option><option value="lost">Проиграли</option><option value="no_bid">Не участвовали</option><option value="cancelled">Отменён заказчиком</option><option value="failed">Не состоялся</option></select></label>{reasonRequired&&<label><span>{result==="lost"?"Причина проигрыша":"Почему не участвуем"}</span><select value={reasonCode} onChange={e=>setReasonCode(e.target.value)}><option value="">Выберите причину</option>{options.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label>}<label><span>Комментарий</span><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="button" type="button" disabled={busy||(reasonRequired&&!reasonCode)} onClick={()=>void onComplete(result,reasonCode||null,note)}>Зафиксировать результат</button></div></details>
}


export function TenderRoleEditButton({tenderId,role,options,demoScope,tender}:{tenderId:string;role:TenderRole;options:TenderOptions;demoScope?:string;tender?:TenderDetail}){
  const editorBusy=Boolean(useSalesEditSession()?.active);const anchor=useRef<HTMLButtonElement>(null);const router=useRouter();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const [form,setForm]=useState({specialtyId:role.specialtyId??"",title:role.title,count:role.count==null?"":String(role.count),volume:role.volume==null?"":String(role.volume),billingUnit:role.billingUnit,targetClientRate:role.targetClientRate==null?"":String(role.targetClientRate),notes:role.notes??""});
  const initialForm={specialtyId:role.specialtyId??"",title:role.title,count:role.count==null?"":String(role.count),volume:role.volume==null?"":String(role.volume),billingUnit:role.billingUnit,targetClientRate:role.targetClientRate==null?"":String(role.targetClientRate),notes:role.notes??""};
  const dirty=JSON.stringify(form)!==JSON.stringify(initialForm);const canLeave=useUnsavedChanges(open&&dirty);
  function cancel(){if(!busy&&canLeave()){setForm(initialForm);setOpen(false);}}
  async function save(){setBusy(true);setError("");try{const body={specialtyId:form.specialtyId||null,title:form.title,count:form.count?Number(form.count):null,volume:form.volume?Number(form.volume):null,billingUnit:form.billingUnit,targetClientRate:form.targetClientRate?Number(form.targetClientRate):null,notes:form.notes||null};if(demoScope&&tender){if(!saveDemoTenderSnapshot(demoScope,{...tender,roles:tender.roles.map(x=>x.id===role.id?{...x,...body}:x),updatedAt:new Date().toISOString()} as TenderDetail))throw new Error("Не удалось сохранить позицию");}else await jsonRequest(`/api/tenders/${tenderId}/roles`,"PATCH",{roleId:role.id,specialtyId:form.specialtyId||null,title:form.title,count:form.count?Number(form.count):null,volume:form.volume?Number(form.volume):null,billingUnit:form.billingUnit,targetClientRate:form.targetClientRate?Number(form.targetClientRate):null,notes:form.notes||null});setOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}}
  return <><button ref={anchor} disabled={editorBusy} className="icon-button" type="button" aria-label={`Редактировать позицию: ${role.title}`} onClick={()=>{setForm(initialForm);setOpen(true)}}><Pencil size={14}/></button>{open&&<SalesInlineForm anchor={anchor} title="Редактировать позицию"><form onSubmit={event=>{event.preventDefault();void save();}}><fieldset className="sales-edit-fieldset" disabled={busy}><div className="form-grid two"><label><span>Специальность</span><select value={form.specialtyId} onChange={e=>{const specialty=options.specialties.find(item=>item.id===e.target.value);setForm(v=>({...v,specialtyId:e.target.value,title:specialty?.name??v.title}))}}><option value="">Без связи со справочником</option>{options.specialties.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Название</span><input required minLength={2} maxLength={180} value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label><span>Количество</span><input type="number" min="1" value={form.count} onChange={e=>setForm(v=>({...v,count:e.target.value}))}/></label><label><span>Объём</span><input type="number" min="0" step="0.001" value={form.volume} onChange={e=>setForm(v=>({...v,volume:e.target.value}))}/></label><label><span>Единица</span><select value={form.billingUnit} onChange={e=>setForm(v=>({...v,billingUnit:e.target.value}))}>{Object.entries(tenderBillingLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><span>Ориентир ставки</span><input type="number" min="0" value={form.targetClientRate} onChange={e=>setForm(v=>({...v,targetClientRate:e.target.value}))}/></label><label className="span-2"><span>Комментарий</span><textarea rows={3} value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></label>{error&&<p className="form-error" role="alert">{error}</p>}</div><div className="sales-edit-footer"><button className="button" type="button" onClick={cancel}>Отмена</button><button className="button primary" type="submit" disabled={!form.title.trim()}>{busy?"Сохраняю…":"Сохранить"}</button></div></fieldset></form></SalesInlineForm>}</>;
}

function TenderDocumentEditButton({tenderId,document}:{tenderId:string;document:TenderSourceDocument}){
  const router=useRouter();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const [form,setForm]=useState({name:document.name,documentType:document.documentType,sourceUrl:document.sourceUrl??"",notes:document.notes??""});
  async function save(){setBusy(true);setError("");try{await jsonRequest(`/api/tenders/${tenderId}/documents`,"PATCH",{documentId:document.id,name:form.name,documentType:form.documentType,sourceUrl:form.sourceUrl||null,notes:form.notes||null});setOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}}
  async function remove(){if(!window.confirm(`Удалить документ «${document.name}» из тендера?`))return;setBusy(true);setError("");try{await jsonRequest(`/api/tenders/${tenderId}/documents`,"DELETE",{documentId:document.id});setOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}}
  return <><button className="icon-button" type="button" aria-label={`Редактировать документ: ${document.name}`} onClick={()=>setOpen(true)}><Pencil size={14}/></button>{open&&<SalesDrawer title="Редактировать документ" overline="Тендер · документы" subtitle="Меняются реквизиты исходного документа. Сам документ и его версии не подменяются скрыто." onClose={()=>!busy&&setOpen(false)} footer={<><button className="button" type="button" disabled={busy} onClick={()=>setOpen(false)}>Отмена</button><button className="button tender-danger-button" type="button" disabled={busy} onClick={()=>void remove()}><Trash2 size={14}/> Удалить</button><button className="button primary" type="button" disabled={busy||!form.name.trim()} onClick={()=>void save()}>{busy?"Сохраняю…":"Сохранить"}</button></>}><div className="form-grid"><label><span>Название</span><input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label><span>Тип</span><select value={form.documentType} onChange={e=>setForm(v=>({...v,documentType:e.target.value}))}><option value="technical_spec">Техническое задание</option><option value="contract">Проект договора</option><option value="specification">Спецификация</option><option value="application_form">Форма заявки</option><option value="clarification">Разъяснение</option><option value="other">Другое</option></select></label><label><span>Ссылка</span><input type="url" value={form.sourceUrl} onChange={e=>setForm(v=>({...v,sourceUrl:e.target.value}))}/></label><label><span>Комментарий</span><textarea rows={3} value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></label>{error&&<p className="form-error" role="alert">{error}</p>}</div></SalesDrawer>}</>;
}

function TenderRequirementEditButton({tenderId,requirement,options}:{tenderId:string;requirement:TenderRequirement;options:TenderOptions}){
  const router=useRouter();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const [form,setForm]=useState({name:requirement.name,required:requirement.required,status:requirement.status,companyDocumentId:requirement.companyDocumentId??"",ownerUserId:requirement.ownerUserId??"",dueAt:tenderDateTimeInput(requirement.dueAt),notes:requirement.notes??""});
  async function save(){setBusy(true);setError("");try{await jsonRequest(`/api/tenders/${tenderId}/requirements`,"PATCH",{requirementId:requirement.id,name:form.name,category:requirement.category,required:form.required,status:form.status,companyDocumentId:form.companyDocumentId||null,ownerUserId:form.ownerUserId||null,dueAt:iso(form.dueAt),notes:form.notes||null});setOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}}
  async function remove(){if(!window.confirm(`Удалить требование «${requirement.name}»?`))return;setBusy(true);setError("");try{await jsonRequest(`/api/tenders/${tenderId}/requirements`,"DELETE",{requirementId:requirement.id});setOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}finally{setBusy(false);}}
  return <><button className="icon-button" type="button" aria-label={`Редактировать требование: ${requirement.name}`} onClick={()=>setOpen(true)}><Pencil size={14}/></button>{open&&<SalesDrawer title="Редактировать требование" overline="Тендер · документы" subtitle="Настройте требование, ответственного, срок и связь с библиотекой документов." onClose={()=>!busy&&setOpen(false)} footer={<><button className="button" type="button" disabled={busy} onClick={()=>setOpen(false)}>Отмена</button><button className="button tender-danger-button" type="button" disabled={busy} onClick={()=>void remove()}><Trash2 size={14}/> Удалить</button><button className="button primary" type="button" disabled={busy||!form.name.trim()} onClick={()=>void save()}>{busy?"Сохраняю…":"Сохранить"}</button></>}><div className="form-grid"><label><span>Требование</span><input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label className="request-check-row"><input type="checkbox" checked={form.required} onChange={e=>setForm(v=>({...v,required:e.target.checked}))}/><span>Обязательное требование</span></label><label><span>Статус</span><select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value}))}>{Object.entries(tenderDocumentStatusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><span>Документ компании</span><select value={form.companyDocumentId} onChange={e=>setForm(v=>({...v,companyDocumentId:e.target.value}))}><option value="">Не сопоставлен</option>{options.companyDocuments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Ответственный</span><select value={form.ownerUserId} onChange={e=>setForm(v=>({...v,ownerUserId:e.target.value}))}><option value="">Не назначен</option>{options.members.map(item=><option key={item.userId} value={item.userId}>{item.name}</option>)}</select></label><label><span>Срок (МСК)</span><input type="datetime-local" value={form.dueAt} onChange={e=>setForm(v=>({...v,dueAt:e.target.value}))}/></label><label><span>Комментарий</span><textarea rows={3} value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></label>{error&&<p className="form-error" role="alert">{error}</p>}</div></SalesDrawer>}</>;
}

export function TenderTeamEditor({tender,options,canEdit}:{tender:TenderDetail;options:TenderOptions;canEdit:boolean}){
  const router=useRouter();const roleCodes=Object.keys(tenderAssignmentLabels);const initial=Object.fromEntries(roleCodes.map(code=>[code,tender.assignments.find(a=>a.roleCode===code)?.userId??""]));const [values,setValues]=useState<Record<string,string>>(initial);const [state,setState]=useState("");
  async function save(){try{setState("Сохранение…");const assignments=Object.entries(values).filter(([,userId])=>userId).map(([roleCode,userId])=>({roleCode,userId}));await jsonRequest(`/api/tenders/${tender.id}/assignments`,"PUT",{assignments});setState("Сохранено");router.refresh();}catch(e){setState(e instanceof Error?e.message:"Ошибка");}}
  if(!canEdit)return <section className="section"><h3>Роли и ответственность</h3><dl className="tender-responsibility-list">{roleCodes.map(code=><div key={code}><dt>{tenderAssignmentLabels[code]}</dt><dd>{tender.assignments.filter(item=>item.roleCode===code).map(item=>item.user).join(", ")||"Не назначен"}</dd></div>)}</dl></section>;return <details className="tender-edit-panel"><summary>Роли и ответственность</summary><div className="tender-panel-body tender-team-grid">{roleCodes.map(code=><label key={code}><span>{tenderAssignmentLabels[code]}</span><select value={values[code]} onChange={e=>setValues(v=>({...v,[code]:e.target.value}))}><option value="">Не назначен</option>{options.members.map(m=><option key={m.userId} value={m.userId}>{m.name}{m.position?` · ${m.position}`:""}</option>)}</select></label>)}<button className="button" type="button" onClick={save}>Сохранить роли</button>{state&&<small>{state}</small>}</div></details>;
}

export function TenderAnalysisEditor({tender,options,canEdit}:{tender:TenderDetail;options:TenderOptions;canEdit:boolean}){
  const router=useRouter();const [summary,setSummary]=useState(tender.analysisSummary??"");const [conditions,setConditions]=useState({subject:condition(tender.conditions.subject),workFormat:condition(tender.conditions.workFormat),schedule:condition(tender.conditions.schedule),region:condition(tender.conditions.region),projectDuration:condition(tender.conditions.projectDuration),housing:condition(tender.conditions.housing),travel:condition(tender.conditions.travel),ppe:condition(tender.conditions.ppe),medical:condition(tender.conditions.medical),participantRequirements:condition(tender.conditions.participantRequirements),vatMode:condition(tender.conditions.vatMode)});const [role,setRole]=useState({specialtyId:"",title:"",count:"",volume:"",billingUnit:tender.billingUnit==="unknown"?"hour":tender.billingUnit,targetClientRate:"",notes:""});const [state,setState]=useState("");
  async function save(){try{setState("Сохранение…");await jsonRequest(`/api/tenders/${tender.id}`,"PATCH",{expectedUpdatedAt:tender.updatedAt,action:"analysis",analysisSummary:summary||null,conditions});setState("Сохранено");router.refresh();}catch(e){setState(e instanceof Error?e.message:"Ошибка");}}
  async function addRole(){try{setState("");await jsonRequest(`/api/tenders/${tender.id}/roles`,"POST",{specialtyId:role.specialtyId||null,title:role.title,count:role.count?Number(role.count):null,volume:role.volume?Number(role.volume):null,billingUnit:role.billingUnit,targetClientRate:role.targetClientRate?Number(role.targetClientRate):null,notes:role.notes||null});setRole(v=>({...v,title:"",count:"",volume:"",targetClientRate:"",notes:""}));router.refresh();}catch(e){setState(e instanceof Error?e.message:"Ошибка");}}
  async function removeRole(id:string){try{await jsonRequest(`/api/tenders/${tender.id}/roles`,"DELETE",{roleId:id});router.refresh();}catch(e){setState(e instanceof Error?e.message:"Ошибка");}}
  return <div className="tender-tab-stack"><section className="section"><h3>Аналитическое заключение</h3><p className="muted">Короткое рабочее резюме для руководителя и следующего сотрудника. Исходные документы остаются источником истины.</p>{canEdit?<><textarea className="tender-summary-editor" rows={7} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Что требуется, что понятно, что нужно уточнить, основные риски и вывод…"/><div className="form-grid two tender-analysis-fields"><label><span>Предмет закупки</span><input value={conditions.subject} onChange={e=>setConditions(v=>({...v,subject:e.target.value}))}/></label><label><span>Формат работ</span><input value={conditions.workFormat} onChange={e=>setConditions(v=>({...v,workFormat:e.target.value}))}/></label><label><span>График</span><input value={conditions.schedule} onChange={e=>setConditions(v=>({...v,schedule:e.target.value}))}/></label><label><span>Регион / место</span><input value={conditions.region} onChange={e=>setConditions(v=>({...v,region:e.target.value}))}/></label><label><span>Срок проекта</span><input value={conditions.projectDuration} onChange={e=>setConditions(v=>({...v,projectDuration:e.target.value}))}/></label><label><span>Проживание</span><input value={conditions.housing} onChange={e=>setConditions(v=>({...v,housing:e.target.value}))}/></label><label><span>Проезд / транспорт</span><input value={conditions.travel} onChange={e=>setConditions(v=>({...v,travel:e.target.value}))}/></label><label><span>СИЗ</span><input value={conditions.ppe} onChange={e=>setConditions(v=>({...v,ppe:e.target.value}))}/></label><label><span>Медицинские требования</span><input value={conditions.medical} onChange={e=>setConditions(v=>({...v,medical:e.target.value}))}/></label><label><span>НДС</span><select value={conditions.vatMode} onChange={e=>setConditions(v=>({...v,vatMode:e.target.value}))}><option value="">Не определено</option><option value="with_vat">С НДС</option><option value="without_vat">Без НДС</option><option value="not_applicable">Не применяется</option></select></label><label className="span-2"><span>Требования к участнику</span><textarea rows={3} value={conditions.participantRequirements} onChange={e=>setConditions(v=>({...v,participantRequirements:e.target.value}))}/></label></div><button className="button primary" type="button" onClick={save}>Сохранить анализ</button></>:<p>{summary||"Аналитическое заключение пока не заполнено."}</p>}{state&&<p className={state==="Сохранено"?"form-success":"muted"}>{state}</p>}</section>
    <section className="section"><h3>Позиции и объём</h3><div className="grid-scroll"><table className="data-table"><thead><tr><th>Специальность / работа</th><th>Количество</th><th>Объём</th><th>Единица</th><th>Ориентир ставки</th><th></th></tr></thead><tbody>{tender.roles.map(r=><tr key={r.id}><td><strong>{r.title}</strong>{r.notes&&<span className="cell-sub">{r.notes}</span>}</td><td>{r.count??"—"}</td><td>{r.volume??"—"}</td><td>{tenderBillingLabels[r.billingUnit]??r.billingUnit}</td><td>{r.targetClientRate??"—"}</td><td>{canEdit&&<div className="tender-row-actions"><TenderRoleEditButton tenderId={tender.id} role={r} options={options}/><button className="icon-button" type="button" aria-label={`Удалить позицию: ${r.title}`} onClick={()=>void removeRole(r.id)}><Trash2 size={14}/></button></div>}</td></tr>)}</tbody></table></div>{canEdit&&<div className="tender-add-row"><select value={role.specialtyId} onChange={e=>{const found=options.specialties.find(s=>s.id===e.target.value);setRole(v=>({...v,specialtyId:e.target.value,title:found?.name??v.title}))}}><option value="">Специальность из справочника</option>{options.specialties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={role.title} onChange={e=>setRole(v=>({...v,title:e.target.value}))} placeholder="Название позиции"/><input type="number" min="1" value={role.count} onChange={e=>setRole(v=>({...v,count:e.target.value}))} placeholder="Кол-во"/><select value={role.billingUnit} onChange={e=>setRole(v=>({...v,billingUnit:e.target.value}))}>{Object.entries(tenderBillingLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><button className="button" type="button" disabled={!role.title.trim()} onClick={()=>void addRole()}><Plus size={14}/> Добавить</button></div>}</section>
  </div>;
}

export function TenderComments({tender,canEdit}:{tender:TenderDetail;canEdit:boolean}){const router=useRouter();const [body,setBody]=useState("");const [error,setError]=useState("");async function add(){try{await jsonRequest(`/api/tenders/${tender.id}/comments`,"POST",{body});setBody("");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}}return <section className="section"><h3>Комментарии</h3>{canEdit&&<div className="tender-comment-compose"><textarea rows={3} value={body} onChange={e=>setBody(e.target.value)} placeholder="Рабочий комментарий, вывод или уточнение…"/><button className="button" type="button" disabled={!body.trim()} onClick={()=>void add()}>Добавить комментарий</button></div>}{error&&<p className="form-error">{error}</p>}<div className="tender-comments">{tender.comments.map(c=><article key={c.id}><header><strong>{c.createdBy}</strong><span>{c.createdAt}</span></header><p>{c.body}</p></article>)}{!tender.comments.length&&<p className="muted">Комментариев пока нет.</p>}</div></section>}

export function TenderDocumentsPanel({tender,options,canEdit}:{tender:TenderDetail;options:TenderOptions;canEdit:boolean}){
  const router=useRouter();const [doc,setDoc]=useState({name:"",documentType:"technical_spec",sourceUrl:"",notes:""});const [req,setReq]=useState({name:"",category:"other",companyDocumentId:"",ownerUserId:"",dueAt:"",notes:""});const [error,setError]=useState("");
  async function addDoc(){try{await jsonRequest(`/api/tenders/${tender.id}/documents`,"POST",{...doc,sourceUrl:doc.sourceUrl||null,notes:doc.notes||null});setDoc({name:"",documentType:"technical_spec",sourceUrl:"",notes:""});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}}
  async function addReq(){try{const linked=options.companyDocuments.find(d=>d.id===req.companyDocumentId);await jsonRequest(`/api/tenders/${tender.id}/requirements`,"POST",{name:req.name,category:req.category,companyDocumentId:req.companyDocumentId||null,status:linked?"available":"prepare",ownerUserId:req.ownerUserId||null,dueAt:iso(req.dueAt),notes:req.notes||null,required:true});setReq({name:"",category:"other",companyDocumentId:"",ownerUserId:"",dueAt:"",notes:""});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}}
  async function setStatus(id:string,status:string){try{await jsonRequest(`/api/tenders/${tender.id}/requirements`,"PATCH",{requirementId:id,status});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Ошибка");}}
  return <div className="tender-tab-stack"><section className="section"><h3>Документы тендера</h3><p className="muted">Техническое задание, проект договора, спецификации, формы и разъяснения заказчика.</p><div className="tender-document-list">{tender.sourceDocuments.map(d=><article key={d.id}><div><strong>{d.name}</strong><span>{({technical_spec:"Техническое задание",contract:"Проект договора",specification:"Спецификация",application_form:"Форма заявки",clarification:"Разъяснение",other:"Другое"} as Record<string,string>)[d.documentType]??"Документ"} · {d.createdAt}</span></div><div className="tender-row-actions">{d.sourceUrl?<a className="button ghost" href={d.sourceUrl} target="_blank" rel="noreferrer">Открыть</a>:<span className="muted">Файл / ссылка не прикреплены</span>}{canEdit&&<TenderDocumentEditButton tenderId={tender.id} document={d}/>}</div></article>)}{!tender.sourceDocuments.length&&<p className="muted">Документов ещё нет.</p>}</div>{canEdit&&<div className="tender-add-document"><input value={doc.name} onChange={e=>setDoc(v=>({...v,name:e.target.value}))} placeholder="Название документа"/><select value={doc.documentType} onChange={e=>setDoc(v=>({...v,documentType:e.target.value}))}><option value="technical_spec">Техническое задание</option><option value="contract">Проект договора</option><option value="specification">Спецификация</option><option value="application_form">Форма заявки</option><option value="clarification">Разъяснение</option><option value="other">Другое</option></select><input type="url" value={doc.sourceUrl} onChange={e=>setDoc(v=>({...v,sourceUrl:e.target.value}))} placeholder="Ссылка на документ"/><button className="button" disabled={!doc.name.trim()} type="button" onClick={()=>void addDoc()}><Plus size={14}/> Добавить</button></div>}</section>
    <section className="section"><h3>Документы от нашей компании</h3><p className="muted">Чек-лист требований тендера сопоставляется с общей библиотекой документов выбранного юрлица.</p><div className="grid-scroll"><table className="data-table tender-doc-checklist"><thead><tr><th></th><th>Требование</th><th>Документ компании</th><th>Статус</th><th>Ответственный</th><th>Срок</th>{canEdit&&<th aria-label="Действия"/>}</tr></thead><tbody>{tender.requirements.map(r=>{const ready=["available","ready","not_required"].includes(r.status);return <tr key={r.id}><td><input type="checkbox" aria-label={`Готовность: ${r.name}`} checked={ready} disabled={!canEdit} onChange={e=>void setStatus(r.id,e.target.checked?"ready":"prepare")}/></td><td><strong>{r.name}</strong><span className="cell-sub">{r.required?"Обязательный":"Дополнительный"}</span>{r.notes&&<span className="cell-sub">{r.notes}</span>}</td><td>{r.companyDocument??"Не сопоставлен"}{r.companyDocumentStatus&&<span className="cell-sub">{({active:"Действует",needs_update:"Требует обновления",missing:"Отсутствует",archived:"В архиве"} as Record<string,string>)[r.companyDocumentStatus]??"Статус уточняется"}</span>}{r.companyDocumentExpiresAt&&<span className="cell-sub">до {r.companyDocumentExpiresAt}</span>}</td><td>{canEdit?<select value={r.status} onChange={e=>void setStatus(r.id,e.target.value)}>{Object.entries(tenderDocumentStatusLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select>:tenderDocumentStatusLabels[r.status]??"Статус уточняется"}</td><td>{r.owner??"—"}</td><td>{r.dueAt?new Date(r.dueAt).toLocaleDateString("ru-RU"):"—"}</td>{canEdit&&<td><TenderRequirementEditButton tenderId={tender.id} requirement={r} options={options}/></td>}</tr>})}</tbody></table></div>{canEdit&&<div className="tender-requirement-create"><input value={req.name} onChange={e=>setReq(v=>({...v,name:e.target.value}))} placeholder="Требуемый документ"/><select value={req.companyDocumentId} onChange={e=>setReq(v=>({...v,companyDocumentId:e.target.value}))}><option value="">Нет в библиотеке / подготовить</option>{options.companyDocuments.filter(d=>!tender.legalEntityId||!d.legalEntityId||d.legalEntityId===tender.legalEntityId).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select value={req.ownerUserId} onChange={e=>setReq(v=>({...v,ownerUserId:e.target.value}))}><option value="">Ответственный не назначен</option>{options.members.map(m=><option key={m.userId} value={m.userId}>{m.name}</option>)}</select><input type="datetime-local" aria-label="Срок требования (МСК)" value={req.dueAt} onChange={e=>setReq(v=>({...v,dueAt:e.target.value}))}/><button className="button" type="button" disabled={!req.name.trim()} onClick={()=>void addReq()}><Plus size={14}/> Добавить требование</button></div>}<a className="button ghost" href="/organization/documents">Открыть библиотеку документов компании</a>{error&&<p className="form-error">{error}</p>}</section>
  </div>;
}

export function TenderApprovalActions({tender,canEdit}:{tender:TenderDetail;canEdit:boolean}){const router=useRouter();const [state,setState]=useState("");const pending=tender.approvals.some(a=>a.status==="pending");async function submit(processCode:string){try{setState("Отправка…");await jsonRequest("/api/approvals","POST",{subjectType:"tender",subjectId:tender.id,processCode});setState("Отправлено на согласование");router.refresh();}catch(e){setState(e instanceof Error?e.message:"Ошибка");}}if(!canEdit)return null;return <section className="section"><h3>Новое согласование</h3><p className="muted">Используется общая очередь OPERIS. Согласующий определяется правилами ответственности и организационной структурой.</p><div className="tender-approval-buttons"><button className="button" type="button" disabled={pending} onClick={()=>void submit("tender_participation")}>Согласовать участие</button><button className="button" type="button" disabled={pending} onClick={()=>void submit("tender_bid")}>Согласовать цену</button><button className="button" type="button" disabled={pending} onClick={()=>void submit("tender_submission")}>Разрешить подачу</button></div>{pending&&<p className="muted">По тендеру уже есть активное согласование.</p>}{state&&<p className="muted">{state}</p>}</section>}

export function TenderSubmissionEditor({tender,canEdit,canSubmit}:{tender:TenderDetail;canEdit:boolean;canSubmit:boolean}){
  const router=useRouter();
  const defaults=tender.submissionChecklist.length?tender.submissionChecklist:!canEdit?[]:[{id:"calculation",label:"Экономика рассчитана и согласована",done:false},{id:"decision",label:"Решение об участии согласовано",done:false},{id:"documents",label:"Пакет документов готов",done:false},{id:"price",label:"Финальная цена зафиксирована",done:false},{id:"signature",label:"Итоговые файлы подписаны",done:false},{id:"platform",label:"Комплект загружен на площадку",done:false}];
  const initialVatMode=typeof tender.conditions.vatMode==="string"&&tender.conditions.vatMode in tenderBidVatModeLabels?tender.conditions.vatMode:"unknown";
  const [checklist,setChecklist]=useState(defaults);
  const [price,setPrice]=useState(tender.finalBidValue==null?"":String(tender.finalBidValue));
  const [priceVatMode,setPriceVatMode]=useState(initialVatMode);
  const [reference,setReference]=useState(tender.bidReference??"");
  const [note,setNote]=useState(tender.submissionNote??"");
  const [state,setState]=useState("");
  const ready=checklist.filter(x=>x.done).length;
  const priceLocked=Boolean(tender.submittedAt);
  async function save(markSubmitted=false){
    try{
      setState("Сохранение…");
      await jsonRequest(`/api/tenders/${tender.id}`,"PATCH",{expectedUpdatedAt:tender.updatedAt,action:"submission",finalBidValue:price?Number(price):null,priceVatMode,bidReference:reference||null,submissionNote:note||null,checklist,markSubmitted});
      setState(markSubmitted?"Подача зафиксирована":"Сохранено");
      router.refresh();
    }catch(e){setState(e instanceof Error?e.message:"Ошибка");}
  }
  return <section className="section"><div className="tender-submission-head"><div><h3>Готовность к подаче</h3><p>{checklist.length?`${ready} из ${checklist.length} пунктов`:"Чек-лист не задан"}</p></div><strong>{checklist.length?`${Math.round(ready/checklist.length*100)}%`:"—"}</strong></div>
    {!tender.submissionChecklist.length&&canEdit&&<p className="muted">Предложен начальный чек-лист. Он сохранится после сохранения подготовки.</p>}
    <div className="tender-submit-checklist">{checklist.map(item=><label key={item.id}><input type="checkbox" checked={item.done} disabled={!canEdit} onChange={e=>setChecklist(v=>v.map(x=>x.id===item.id?{...x,done:e.target.checked}:x))}/><span>{item.label}</span></label>)}</div>
    <div className="form-grid two">
      <label><span>Финальная цена / сумма</span><input type="number" min="0" disabled={!canEdit||priceLocked} value={price} onChange={e=>setPrice(e.target.value)}/>{priceLocked&&<small className="muted">После подачи цена изменяется только через вкладку «Торги».</small>}</label>
      <label><span>НДС в цене</span><select disabled={!canEdit||priceLocked} value={priceVatMode} onChange={e=>setPriceVatMode(e.target.value)}>{Object.entries(tenderBidVatModeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
      <label><span>№ заявки / подтверждение площадки</span><input disabled={!canEdit} value={reference} onChange={e=>setReference(e.target.value)}/></label>
      <label className="span-2"><span>Комментарий по подаче</span><textarea rows={4} disabled={!canEdit} value={note} onChange={e=>setNote(e.target.value)}/></label>
    </div>
    {canEdit&&<div className="tender-submit-actions"><button className="button" type="button" onClick={()=>void save(false)}>Сохранить подготовку</button>{canSubmit&&tender.stage!=="submitted"&&tender.stage!=="awaiting_result"&&tender.stage!=="completed"&&<button className="button primary" type="button" onClick={()=>void save(true)}><Send size={14}/> Зафиксировать подачу</button>}</div>}
    {state&&<p className="muted">{state}</p>}
    {tender.submittedAt&&<p className="form-success"><Check size={14}/> Подано {formatTenderDateTime(tender.submittedAt)}{tender.submittedBy?` · ${tender.submittedBy}`:""}</p>}
  </section>;
}

export function TenderTradingPanel({tender,canSubmit,canReadEconomics}:{tender:TenderDetail;canSubmit:boolean;canReadEconomics:boolean}){
  const router=useRouter();
  const rounds=useMemo(()=>[...tender.bidRounds].sort((a,b)=>b.roundNumber-a.roundNumber),[tender.bidRounds]);
  const initialVatMode=typeof tender.conditions.vatMode==="string"&&tender.conditions.vatMode in tenderBidVatModeLabels?tender.conditions.vatMode:"unknown";
  const [form,setForm]=useState({bidValue:tender.finalBidValue==null?"":String(tender.finalBidValue),priceVatMode:initialVatMode,occurredAt:"",reference:"",note:""});
  const [state,setState]=useState("");
  const canTrade=canSubmit&&["submitted","awaiting_result"].includes(tender.stage);
  const latest=rounds[0]??null;
  const latestMargin=latest?.economics?.status==="complete"?latest.economics.marginPct:null;
  function reduction(value:number|string){const initial=Number(tender.initialPrice);const current=Number(value);return Number.isFinite(initial)&&initial>0&&Number.isFinite(current)?(initial-current)/initial*100:null;}
  const latestCut=latest?reduction(latest.bidValue):null;
  async function addRound(){
    try{
      setState("Сохранение…");
      await jsonRequest(`/api/tenders/${tender.id}/bids`,"POST",{bidValue:Number(form.bidValue),priceVatMode:form.priceVatMode,occurredAt:tenderDateTimeIso(form.occurredAt),reference:form.reference||null,note:form.note||null});
      setForm(v=>({...v,occurredAt:"",reference:"",note:""}));
      setState("Раунд зафиксирован");
      router.refresh();
    }catch(e){setState(e instanceof Error?e.message:"Ошибка");}
  }
  return <div className="tender-tab-stack">
    <section className="section">
      <h3>Торги и история цены</h3>
      <p className="muted">Каждая фактически поданная цена сохраняется отдельным неизменяемым раундом. Ошибочную запись не переписывают — добавляют новый раунд с пояснением.</p>
      {!canReadEconomics&&<p className="muted">Цена доступна по тендеру, но для просмотра себестоимости и маржи нужен доступ к расчётам экономики.</p>}
      <div className="request-entity-facts">
        <article><span>Текущая цена</span><strong>{tenderMoney(tender.finalBidValue)}</strong><small>{latest?tenderBidVatModeLabels[latest.priceVatMode]??"Режим НДС не определён":"Раундов пока нет"}</small></article>
        <article><span>Раундов</span><strong>{rounds.length}</strong><small>{latest?`Последний: ${formatTenderDateTime(latest.occurredAt)}`:"История ещё не начата"}</small></article>
        <article><span>Снижение от НМЦК</span><strong>{latestCut==null?"—":`${latestCut.toFixed(2)}%`}</strong><small>{tender.initialPrice==null?"НМЦК не указана":"По номинальной цене площадки"}</small></article>
        <article><span>Маржа последнего раунда</span><strong>{latestMargin==null?"—":`${Number(latestMargin).toFixed(2)}%`}</strong><small>{latest?.economics?.status==="incomplete"?"Недостаточно сопоставимой экономики":latestMargin==null?"Расчёт затрат не сохранён":"По сохранённому расчёту затрат"}</small></article>
      </div>
      {rounds.length?<div className="grid-scroll"><table className="data-table"><thead><tr><th>Раунд</th><th>Время</th><th>Цена</th><th>Снижение от НМЦК</th><th>Маржа</th><th>Источник</th><th>Зафиксировал</th></tr></thead><tbody>{rounds.map(round=>{const cut=reduction(round.bidValue);return <tr key={round.id}><td>№ {round.roundNumber}</td><td>{formatTenderDateTime(round.occurredAt)}</td><td><strong>{tenderMoney(round.bidValue)}</strong><span className="cell-sub">{tenderBidVatModeLabels[round.priceVatMode]??"НДС не определён"}</span></td><td>{cut==null?"—":`${cut.toFixed(2)}%`}</td><td>{round.economics?.status==="complete"&&round.economics.marginPct!=null?<><strong>{Number(round.economics.marginPct).toFixed(2)}%</strong><span className="cell-sub">Себестоимость: {tenderMoney(round.economics.totalCostNet)}</span></>:round.economics?<><span>—</span><span className="cell-sub">{round.economics.missing[0]??"Недостаточно данных"}</span></>:<span>—</span>}</td><td>{tenderBidSourceLabels[round.source]??"Раунд"}{round.reference&&<span className="cell-sub">{round.reference}</span>}{round.note&&<span className="cell-sub">{round.note}</span>}</td><td>{round.recordedBy??"Система"}</td></tr>})}</tbody></table></div>:<p className="muted">История торгов пока пуста. Первая цена будет зафиксирована при подаче или при добавлении раунда.</p>}
    </section>
    {canTrade&&<section className="section">
      <h3>Новый раунд</h3>
      <p className="muted">Маржа рассчитывается только если у всех позиций есть принятые сценарии утверждённой экономики, сопоставимый объём и единицы тарификации.</p>
      <div className="form-grid two">
        <label><span>Цена раунда</span><input type="number" min="0.01" step="0.01" value={form.bidValue} onChange={e=>setForm(v=>({...v,bidValue:e.target.value}))}/></label>
        <label><span>НДС в цене</span><select value={form.priceVatMode} onChange={e=>setForm(v=>({...v,priceVatMode:e.target.value}))}>{Object.entries(tenderBidVatModeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
        <label><span>Время раунда (МСК)</span><input type="datetime-local" value={form.occurredAt} onChange={e=>setForm(v=>({...v,occurredAt:e.target.value}))}/><small className="muted">Если не заполнить, будет использовано текущее время.</small></label>
        <label><span>Протокол / номер шага</span><input value={form.reference} onChange={e=>setForm(v=>({...v,reference:e.target.value}))} placeholder="Например, шаг 3 или номер протокола"/></label>
        <label className="span-2"><span>Комментарий</span><textarea rows={3} value={form.note} onChange={e=>setForm(v=>({...v,note:e.target.value}))} placeholder="Причина изменения цены, контекст торгов…"/></label>
      </div>
      <div className="tender-submit-actions"><button className="button primary" type="button" disabled={!form.bidValue||Number(form.bidValue)<=0} onClick={()=>void addRound()}>Зафиксировать раунд</button></div>
      {state&&<p className={state==="Раунд зафиксирован"?"form-success":"muted"}>{state}</p>}
    </section>}
    {canSubmit&&!canTrade&&tender.stage!=="completed"&&<section className="section"><p className="muted">Добавление раундов станет доступно после фиксации подачи тендера.</p></section>}
  </div>;
}

const tenderOutcomeLabels:Record<string,string>={won:"Выиграли",lost:"Проиграли",no_bid:"Не участвовали",cancelled:"Отменён заказчиком",failed:"Не состоялся"};

export function TenderResultPanel({tender,options,canLaunch}:{tender:TenderDetail;options:TenderOptions;canLaunch:boolean}){
  const router=useRouter();
  const [open,setOpen]=useState(false);
  const [busy,setBusy]=useState(false);
  const [state,setState]=useState("");
  const defaultEntity=tender.legalEntityId??(options.legalEntities.length===1?options.legalEntities[0]?.id??"":"");
  const [form,setForm]=useState({name:tender.title,code:"",targetStartDate:"",legalEntityId:defaultEntity});
  const won=tender.stage==="completed"&&tender.result==="won";

  async function launch(){
    try{
      setBusy(true);setState("");
      await jsonRequest(`/api/tenders/${tender.id}/launch`,"POST",{
        name:form.name.trim()||undefined,
        code:form.code.trim()||undefined,
        targetStartDate:form.targetStartDate||undefined,
        legalEntityId:form.legalEntityId||undefined,
      });
      setOpen(false);
      setState("Передача в запуск выполнена");
      router.refresh();
    }catch(error){
      setState(error instanceof Error?error.message:"Не удалось передать тендер в запуск");
    }finally{setBusy(false);}
  }

  return <div className="tender-tab-stack">
    <section className="section">
      <h3>Результат тендера</h3>
      <div className="request-entity-facts">
        <article><span>Результат</span><strong>{tender.result?tenderOutcomeLabels[tender.result]??"Статус уточняется":"Не зафиксирован"}</strong><small>{tender.stage==="completed"?"Тендер завершён":"Итог ещё не зафиксирован"}</small></article>
        <article><span>Финальная цена</span><strong>{tenderMoney(tender.finalBidValue)}</strong><small>{tender.bidRounds.length?`Раундов торгов: ${tender.bidRounds.length}`:"История торгов отсутствует"}</small></article>
        <article><span>Договор / запуск</span><strong>{tender.winHandoff?.started?"Передано в запуск":won?"Ожидает передачи":"—"}</strong><small>{tender.winHandoff?.started?"Создан договор и контур подготовки объекта":won?"Нужна утверждённая экономика и готовые позиции":"Доступно после победы"}</small></article>
      </div>
      {tender.closeReason&&<div className="tender-open-questions"><strong>Комментарий к результату</strong><p>{tender.closeReason}</p></div>}
    </section>

    {tender.winHandoff?.started&&<section className="section">
      <h3>Передача в договор и объект</h3>
      <p className="muted">Источник зафиксирован как выигранный тендер. Дальнейшая работа идёт в общих модулях договоров и объектов.</p>
      <div className="tender-submit-actions">
        {tender.winHandoff.contractId&&<Link className="button primary" href={`/contracts/${tender.winHandoff.contractId}`}>Открыть договор</Link>}
        {tender.winHandoff.objectId&&<Link className="button" href={`/objects/${tender.winHandoff.objectId}`}>Открыть объект</Link>}
        {!tender.winHandoff.contractId&&!tender.winHandoff.objectId&&<span className="muted">Передача выполнена. Связанные сущности скрыты текущими правами доступа.</span>}
      </div>
    </section>}

    {won&&!tender.winHandoff?.started&&<section className="section">
      <h3>Передать выигранный тендер в запуск</h3>
      <p className="muted">Будут созданы объект в подготовке, потребности, план запуска, клиентские ставки и черновик договора. Источником останется этот тендер; существующие расчёты не переписываются.</p>
      {canLaunch?<button className="button primary" type="button" onClick={()=>{setState("");setOpen(true);}}>Создать договор и подготовку объекта</button>:<p className="muted">Нет права передавать выигранный тендер в запуск.</p>}
      {state&&<p className={state==="Передача в запуск выполнена"?"form-success":"form-error"}>{state}</p>}
    </section>}

    {!won&&!tender.winHandoff?.started&&<section className="section"><p className="muted">Передача в договор и объект станет доступна после фиксации результата «Выиграли».</p></section>}

    {open&&<SalesDrawer
      title="Передать тендер в запуск"
      overline="Тендер · результат"
      subtitle="Создаётся рабочий контур запуска на основании выигранного тендера и одной утверждённой версии экономики."
      onClose={()=>{if(!busy)setOpen(false);}}
      footer={<><button className="button" type="button" disabled={busy} onClick={()=>setOpen(false)}>Отмена</button><button className="button primary" type="button" disabled={busy||!form.name.trim()||!form.legalEntityId} onClick={()=>void launch()}>{busy?"Создаю…":"Создать договор и объект"}</button></>}
    >
      <div className="form-grid">
        <label><span>Название объекта</span><input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label>
        <label><span>Код объекта</span><input value={form.code} onChange={e=>setForm(v=>({...v,code:e.target.value.toUpperCase()}))} placeholder="Можно оставить пустым"/></label>
        <label><span>Плановый старт</span><input type="date" value={form.targetStartDate} onChange={e=>setForm(v=>({...v,targetStartDate:e.target.value}))}/></label>
        <label><span>Юридическое лицо</span><select value={form.legalEntityId} onChange={e=>setForm(v=>({...v,legalEntityId:e.target.value}))}><option value="">Выберите юрлицо</option>{options.legalEntities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
        <p className="muted">Система проверит клиента, регион, специальности, количество сотрудников и полное покрытие позиций принятой экономикой. При любой ошибке транзакция будет отменена целиком.</p>
        {state&&<p className="form-error">{state}</p>}
      </div>
    </SalesDrawer>}
  </div>;
}
