"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import type {TenderOptions} from "@/lib/tenders/service";

function toIso(value:string){if(!value)return null;const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString();}
export function TenderCreateForm({options}:{options:TenderOptions}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const [form,setForm]=useState({title:"",customerName:"",clientId:"",platform:"",procedureNumber:"",sourceUrl:"",sourceName:"Ручной ввод",publicationDate:"",submissionDeadline:"",initialPrice:"",regionId:"",legalEntityId:"",comment:""});
  function set<K extends keyof typeof form>(key:K,value:(typeof form)[K]){setForm(v=>({...v,[key]:value}));}
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const response=await fetch("/api/tenders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:form.title,customerName:form.customerName||null,clientId:form.clientId||null,platform:form.platform||null,procedureNumber:form.procedureNumber||null,sourceUrl:form.sourceUrl||null,sourceName:form.sourceName||null,publicationDate:form.publicationDate||null,submissionDeadline:toIso(form.submissionDeadline),initialPrice:form.initialPrice?Number(form.initialPrice):null,regionId:form.regionId||null,legalEntityId:form.legalEntityId||null,comment:form.comment||null})});const json=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(json.error??"Не удалось создать тендер");return;}router.push(`/tenders/${json.id}`);router.refresh();}
  return <form className="tender-create-layout" onSubmit={submit}><section className="section"><div className="tender-form-section"><h3>Основные данные</h3><p>Для регистрации достаточно названия и срока подачи. Остальные условия можно заполнить после изучения документации.</p><div className="form-grid two"><label><span>Название тендера *</span><input required value={form.title} onChange={e=>set("title",e.target.value)} placeholder="Предоставление линейного персонала"/></label><label><span>Заказчик</span><input value={form.customerName} onChange={e=>set("customerName",e.target.value)} placeholder="ООО / АО / учреждение"/></label><label><span>Площадка</span><input value={form.platform} onChange={e=>set("platform",e.target.value)} placeholder="ЕИС, РТС-тендер, B2B-Center…"/></label><label><span>№ процедуры</span><input value={form.procedureNumber} onChange={e=>set("procedureNumber",e.target.value)} placeholder="Номер закупки"/></label><label className="span-2"><span>Ссылка на закупку</span><input type="url" value={form.sourceUrl} onChange={e=>set("sourceUrl",e.target.value)} placeholder="https://…"/></label><label><span>Дата публикации</span><input type="date" value={form.publicationDate} onChange={e=>set("publicationDate",e.target.value)}/></label><label><span>Окончание подачи</span><input type="datetime-local" value={form.submissionDeadline} onChange={e=>set("submissionDeadline",e.target.value)}/></label></div></div>
    <div className="tender-form-section"><h3>Дополнительная привязка</h3><div className="form-grid two"><label><span>Существующий клиент</span><select value={form.clientId} onChange={e=>set("clientId",e.target.value)}><option value="">Не связывать</option>{options.clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Регион</span><select value={form.regionId} onChange={e=>set("regionId",e.target.value)}><option value="">Не указан</option>{options.regions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Юрлицо для участия</span><select value={form.legalEntityId} onChange={e=>set("legalEntityId",e.target.value)}><option value="">Определить позже</option>{options.legalEntities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>НМЦК / начальная цена</span><input type="number" min="0" value={form.initialPrice} onChange={e=>set("initialPrice",e.target.value)} placeholder="Можно заполнить позже"/></label><label className="span-2"><span>Источник</span><input value={form.sourceName} onChange={e=>set("sourceName",e.target.value)} placeholder="Список аналитика, площадка, ручной ввод"/></label><label className="span-2"><span>Первичный комментарий</span><textarea rows={4} value={form.comment} onChange={e=>set("comment",e.target.value)} placeholder="Что уже известно или на что обратить внимание"/></label></div></div>{error&&<p className="form-error">{error}</p>}</section><aside className="section tender-create-side"><h3>После создания</h3><p>Тендер попадёт в этап «Новые». В карточке можно изучить условия, распределить роли, собрать документы, отправить расчёт на согласование и контролировать подачу.</p><button className="button primary" type="submit" disabled={busy}>{busy?"Создание…":"Создать тендер"}</button><button className="button" type="button" onClick={()=>router.push("/tenders")}>Отмена</button></aside></form>;
}
