"use client";
import {useId,useState,type FormEvent,type ReactNode} from "react";
import {useRouter} from "next/navigation";
import type {TenderRow,TenderOptions} from "@/lib/tenders/service";
import {tenderBillingLabels} from "@/lib/tenders/model";
import {tenderDateTimeInput,tenderDateTimeIso} from "@/lib/tenders/datetime";
import {SalesDrawer} from "@/components/sales/SalesUI";
import {SalesEditSection,useUnsavedChanges} from "@/components/sales/SalesEditSection";
import {loadDemoTenderSnapshot,saveDemoTenderSnapshot} from "@/components/sales/DemoTenderPreview";

type Props={tender:TenderRow;options:Pick<TenderOptions,"regions"|"legalEntities">;quick?:boolean;inline?:boolean;demoScope?:string;onSaved:()=>void;onCancel:()=>void};
export function TenderDataEditor({tender,options,quick=false,inline=false,demoScope,onSaved,onCancel}:Props){
 const router=useRouter();const formId=useId();const [dirty,setDirty]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const canLeave=useUnsavedChanges(dirty);
 function cancel(){if(!busy&&canLeave())onCancel();}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const fd=new FormData(event.currentTarget);const value=(key:string,previous:string|null|undefined)=>fd.has(key)?String(fd.get(key)??"").trim()||null:previous??null;
  const price=fd.has("initialPrice")?String(fd.get("initialPrice")??""):tender.initialPrice;
  const body={action:"core",expectedUpdatedAt:tender.updatedAt,title:value("title",tender.title),customerName:value("customerName",tender.customer),clientId:tender.clientId,platform:value("platform",tender.platform),procedureNumber:value("procedureNumber",tender.procedureNumber),sourceUrl:value("sourceUrl",tender.sourceUrl),sourceName:value("sourceName",tender.sourceName),publicationDate:value("publicationDate",tender.publicationDate),submissionDeadline:fd.has("submissionDeadline")?tenderDateTimeIso(String(fd.get("submissionDeadline")??""),tender.submissionDeadline):tender.submissionDeadline,initialPrice:price==null||price===""?null:Number(price),billingUnit:value("billingUnit",tender.billingUnit),priority:value("priority",tender.priority),potential:value("potential",tender.potential),regionId:value("regionId",tender.regionId),legalEntityId:value("legalEntityId",tender.legalEntityId),nextActionText:value("nextActionText",tender.nextActionText),nextActionAt:fd.has("nextActionAt")?tenderDateTimeIso(String(fd.get("nextActionAt")??""),tender.nextActionAt):tender.nextActionAt};
  setBusy(true);setError("");try{
   if(demoScope){const current=loadDemoTenderSnapshot(demoScope,tender.id);if(current&&current.updatedAt!==tender.updatedAt)throw new Error("Тендер уже изменён. Обновите карточку перед сохранением.");const next={...tender,...body,title:body.title??tender.title,customer:body.customerName??tender.customer,billingUnit:body.billingUnit??tender.billingUnit,priority:body.priority as TenderRow["priority"],potential:body.potential as TenderRow["potential"],updatedAt:new Date().toISOString()};if(!saveDemoTenderSnapshot(demoScope,next))throw new Error("Не удалось сохранить изменения в браузере");}
   else{const response=await fetch(`/api/tenders/${tender.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Не удалось сохранить тендер");}
   setDirty(false);onSaved();router.refresh();
  }catch(cause){setError(cause instanceof Error?cause.message:"Не удалось сохранить тендер");}finally{setBusy(false);}
 }
 const footer=<><button type="button" className="button" disabled={busy} onClick={cancel}>Отмена</button><button type="submit" form={formId} className="button primary" disabled={busy||!dirty}>{busy?"Сохраняю…":"Сохранить изменения"}</button></>;
 const form=<form id={formId} onSubmit={submit} onChange={()=>setDirty(true)}><fieldset className="sales-edit-fieldset" disabled={busy}><div className="form-grid two">
  <label className="span-2"><span>Название тендера *</span><input name="title" required minLength={3} maxLength={300} defaultValue={tender.title}/></label>
  <label><span>Подача до (МСК)</span><input name="submissionDeadline" type="datetime-local" defaultValue={tenderDateTimeInput(tender.submissionDeadline)}/></label>
  <label><span>Приоритет</span><select name="priority" defaultValue={tender.priority}><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option></select></label>
  <label className="span-2"><span>Следующее действие</span><input name="nextActionText" maxLength={1000} defaultValue={tender.nextActionText??""}/></label><label><span>Срок действия (МСК)</span><input name="nextActionAt" type="datetime-local" defaultValue={tenderDateTimeInput(tender.nextActionAt)}/></label>
  {!quick&&<><label><span>Заказчик</span><input name="customerName" disabled={Boolean(tender.clientId)} maxLength={300} defaultValue={tender.customer}/>{tender.clientId&&<small>Связан с карточкой клиента. Название изменяется там.</small>}</label><label><span>Площадка</span><input name="platform" maxLength={160} defaultValue={tender.platform??""}/></label><label><span>Номер процедуры</span><input name="procedureNumber" maxLength={180} defaultValue={tender.procedureNumber??""}/></label><label className="span-2"><span>Ссылка на закупку</span><input name="sourceUrl" type="url" maxLength={2000} defaultValue={tender.sourceUrl??""}/></label><label><span>Источник</span><input name="sourceName" maxLength={180} defaultValue={tender.sourceName??""}/></label><label><span>Дата публикации</span><input name="publicationDate" type="date" defaultValue={tender.publicationDate??""}/></label><label><span>НМЦК, ₽</span><input name="initialPrice" type="number" min="0" step="any" defaultValue={tender.initialPrice??""}/></label><label><span>Формат цены</span><select name="billingUnit" defaultValue={tender.billingUnit}>{Object.entries(tenderBillingLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><span>Потенциал</span><select name="potential" defaultValue={tender.potential}><option value="low">Низкий</option><option value="medium">Средний</option><option value="high">Высокий</option></select></label><label><span>Регион</span><select name="regionId" defaultValue={tender.regionId??""}><option value="">Не указан</option>{tender.regionId&&!options.regions.some(x=>x.id===tender.regionId)&&<option value={tender.regionId}>Текущий регион</option>}{options.regions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Юрлицо</span><select name="legalEntityId" defaultValue={tender.legalEntityId??""}><option value="">Не определено</option>{tender.legalEntityId&&!options.legalEntities.some(x=>x.id===tender.legalEntityId)&&<option value={tender.legalEntityId}>Текущее юрлицо</option>}{options.legalEntities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></>}
 </div>{error&&<p className="form-error" role="alert">{error}</p>}</fieldset>{inline&&<div className="sales-edit-footer">{footer}</div>}</form>;
 return inline?form:<SalesDrawer overline="Редактирование" title="Быстрое редактирование тендера" subtitle={tender.title} onClose={()=>!busy&&onCancel()} footer={footer}>{form}</SalesDrawer>;
}
export function TenderDataSection({children,canEdit,...props}:Omit<Props,"onSaved"|"onCancel"|"inline">&{children:ReactNode;canEdit:boolean}){
 return <SalesEditSection title="Данные закупки" canEdit={canEdit} editor={(onSaved,onCancel)=><TenderDataEditor {...props} inline onSaved={onSaved} onCancel={onCancel}/>}>{children}</SalesEditSection>;
}
