import { NextResponse } from "next/server";
import { z } from "zod";
import { AccessDeniedError, requireCapability } from "@/lib/access/server";
import { getCurrentActor } from "@/lib/auth/server";
import { withTenant } from "@/lib/db/client";

const rule=z.object({processCode:z.string().trim().min(2).max(120).regex(/^[a-z0-9._-]+$/),processName:z.string().trim().min(2).max(200),stepCode:z.string().trim().min(2).max(120).regex(/^[a-z0-9._-]+$/),stepName:z.string().trim().min(2).max(200),responsibilityType:z.enum(["owner","executor","approver","observer","fallback"]),subjectType:z.enum(["process_role","staff_position","org_unit","membership"]),subjectId:z.string().uuid(),scopeType:z.enum(["self","team","org_unit","region","objects","clients","all_org"]),scopeIds:z.array(z.string().uuid()).max(200).default([]),fallbackSubjectType:z.enum(["process_role","staff_position","org_unit","membership"]).nullable().optional(),fallbackSubjectId:z.string().uuid().nullable().optional(),effectiveFrom:z.string().date(),effectiveTo:z.string().date().nullable().optional(),active:z.boolean().default(true)}).refine(value=>(value.fallbackSubjectType==null)===(value.fallbackSubjectId==null),{message:"Резервный субъект заполнен не полностью"}).refine(value=>!value.effectiveTo||value.effectiveTo>=value.effectiveFrom,{message:"Некорректный период"});
const update=rule.extend({id:z.string().uuid()});
async function authorize(){const actor=await getCurrentActor();if(!actor)throw new Error("UNAUTHORIZED");requireCapability(actor,"organization.position.manage");if(actor.demo)throw new Error("DEMO");return actor}

export async function POST(request:Request){try{const actor=await authorize();const body=rule.parse(await request.json());const [row]=await withTenant(actor.organizationId,actor.userId,sql=>sql.unsafe<Array<{id:string}>>(`INSERT INTO responsibility_rules(organization_id,process_code,process_name,step_code,step_name,responsibility_type,subject_type,subject_id,scope_type,scope_ids,fallback_subject_type,fallback_subject_id,effective_from,effective_to,active,created_by_user_id) VALUES($1::uuid,$2,$3,$4,$5,$6,$7,$8::uuid,$9,$10::uuid[],$11,$12::uuid,$13::date,$14::date,$15,$16::uuid) RETURNING id`,[actor.organizationId,body.processCode,body.processName,body.stepCode,body.stepName,body.responsibilityType,body.subjectType,body.subjectId,body.scopeType,body.scopeIds,body.fallbackSubjectType??null,body.fallbackSubjectId??null,body.effectiveFrom,body.effectiveTo??null,body.active,actor.userId]));return NextResponse.json({ok:true,id:row.id},{status:201})}catch(error){return fail(error)}}
export async function PATCH(request:Request){try{const actor=await authorize();const body=update.parse(await request.json());const rows=await withTenant(actor.organizationId,actor.userId,sql=>sql.unsafe<Array<{id:string}>>(`UPDATE responsibility_rules SET process_code=$2,process_name=$3,step_code=$4,step_name=$5,responsibility_type=$6,subject_type=$7,subject_id=$8::uuid,scope_type=$9,scope_ids=$10::uuid[],fallback_subject_type=$11,fallback_subject_id=$12::uuid,effective_from=$13::date,effective_to=$14::date,active=$15,updated_at=now() WHERE id=$1::uuid RETURNING id`,[body.id,body.processCode,body.processName,body.stepCode,body.stepName,body.responsibilityType,body.subjectType,body.subjectId,body.scopeType,body.scopeIds,body.fallbackSubjectType??null,body.fallbackSubjectId??null,body.effectiveFrom,body.effectiveTo??null,body.active]));if(!rows.length)throw new Error("NOT_FOUND");return NextResponse.json({ok:true})}catch(error){return fail(error)}}

function fail(error:unknown){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте правило ответственности",issues:error.issues},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});if(error instanceof Error&&error.message==="UNAUTHORIZED")return NextResponse.json({error:"Требуется вход"},{status:401});if(error instanceof Error&&error.message==="DEMO")return NextResponse.json({error:"В демонстрационном режиме изменения не сохраняются"},{status:409});if(error instanceof Error&&error.message==="NOT_FOUND")return NextResponse.json({error:"Правило не найдено"},{status:404});console.error(error);return NextResponse.json({error:"Не удалось сохранить правило"},{status:500})}
