const state={route:'/tenders',theme:localStorage.getItem('operis.preview.theme')||'light',compact:localStorage.getItem('operis.preview.compact')==='1',requestView:'list',requestBucket:'active',tenderView:'list',tenderBucket:'active',tenderSearch:'',tenderDeadline:'all',selectedTender:'t1',selectedRequest:'r1',selectedClient:'c1',selectedProposal:'p1',entityTab:'Обзор'};

const sections=[
{id:'home',label:'Главная',icon:'⌂',groups:[{label:'Рабочее пространство',items:[['Командный центр','/'],['Мои задачи','/tasks']]},{label:'Команда',items:[['Задачи команды','/team/tasks','База'],['Согласования','/approvals']]}]},
{id:'commerce',label:'Коммерция',icon:'▣',groups:[{label:'Продажи',items:[['Заявки','/requests'],['Клиенты','/clients'],['Коммерческие предложения','/proposals'],['Тендеры','/tenders']]},{label:'Экономика',items:[['Расчёты','/calculations'],['База ставок','/rates'],['Нормативы','/standards','База']]},{label:'Договорная работа',items:[['Договоры','/contracts','База']]}]},
{id:'people',label:'Люди',icon:'♙',groups:[{label:'Подбор',items:[['Потребности','/needs'],['Воронка подбора','/recruiting'],['Кандидаты','/candidates']]},{label:'Подготовка выхода',items:[['Готовность к выходу','/onboarding/readiness','База'],['Оформление','/onboarding/employment','База'],['Документы и допуски','/compliance'],['Проезд и прибытие','/onboarding/travel','База']]},{label:'Персонал',items:[['Сотрудники','/workers']]}]},
{id:'operations',label:'Операции',icon:'⚙',groups:[{label:'Объекты',items:[['Реестр объектов','/objects'],['План запуска','/launches'],['План комплектации','/staffing-plan','База'],['Смены','/shifts'],['Табели и сверка','/timesheets']]},{label:'Обеспечение',items:[['Жильё','/supply/housing','База'],['Транспорт','/supply/transport','База'],['Закупки','/procurement','База'],['Имущество и СИЗ','/assets','База'],['Поставщики','/suppliers','База']]},{label:'Качество',items:[['Инциденты','/incidents'],['Претензии и SLA','/claims','База']]}]},
{id:'finance',label:'Финансы',icon:'₽',groups:[{label:'Персонал',items:[['Начисления','/accruals'],['Выплаты','/payments']]},{label:'Клиенты',items:[['Биллинг','/billing','База'],['Дебиторская задолженность','/receivables','База']]},{label:'Экономика',items:[['Операционные расходы','/expenses','База'],['Прибыли и убытки','/finance'],['План / факт / прогноз','/finance/plan-fact','База']]}]},
{id:'analytics',label:'Аналитика',icon:'◫',groups:[{label:'Руководство',items:[['Портфель','/analytics'],['KPI','/analytics/kpi','База'],['Риски и сигналы','/analytics/risks','База']]},{label:'Направления',items:[['Коммерция','/analytics/commerce','База'],['Подбор и персонал','/analytics?view=workforce'],['Операции','/analytics?view=comparison'],['Финансы','/analytics/finance','База']]}]},
{id:'control',label:'Контроль',icon:'◉',groups:[{label:'Системный контроль',items:[['Журнал действий','/activity'],['Документы и сроки','/control/documents','База'],['Допуски','/control/admissions','База']]}]},
{id:'organization',label:'Организация',icon:'▦',groups:[{label:'Структура',items:[['Оргструктура','/organization/structure'],['Сотрудники компании','/organization/staff'],['Должности и роли','/organization/positions'],['Подразделения и регионы','/organization/departments']]},{label:'Работа компании',items:[['Рабочие процессы','/organization/processes','База'],['SLA и эскалации','/organization/sla','База'],['KPI и мотивация','/organization/kpi','База'],['Замещения','/organization/substitutions','База']]},{label:'Документы',items:[['Документы компании','/organization/documents']]}]},
{id:'admin',label:'Администрирование',icon:'⚙',groups:[{label:'Доступ',items:[['Пользователи и права','/admin/access']]},{label:'Настройки',items:[['Справочники','/admin/directories'],['Модули компании','/admin/modules','База'],['Интеграции','/admin/integrations','База'],['Шаблоны документов','/admin/document-templates'],['Юридические лица','/admin/legal-entities']]}]}
];
const titleMap=Object.fromEntries(sections.flatMap(s=>s.groups.flatMap(g=>g.items.map(i=>[i[1].split('?')[0],{title:i[0],section:s.label,group:g.label}]))));

const requests=[
{id:'r1',title:'Линейный персонал · Руднево',client:'ООО «ДАСКАР»',location:'Москва · Руднево',headcount:26,roles:'Комплектовщик 16 · Грузчик 10',stage:'Расчёт',owner:'Сергей',proposal:'№2',sent:1,start:'15.09.2026',activity:'Обновлено сегодня',source:'Эл. почта'},
{id:'r2',title:'Контакт-центр · удалённо',client:'ООО «Контакт Сервис»',location:'Екатеринбург / удалённо',headcount:60,roles:'Оператор 60',stage:'КП у клиента',owner:'Сергей',proposal:'№3',sent:2,start:'20.09.2026',activity:'Без изменений 2 дня',source:'Повторное обращение'},
{id:'r3',title:'AQUATON · производство',client:'AQUATON',location:'Воротынск',headcount:31,roles:'Упаковщик 18 · Разнорабочий 13',stage:'Готово к расчёту',owner:'Сергей',proposal:'—',sent:0,start:'18.09.2026',activity:'Обновлено вчера',source:'Телефон'},
{id:'r4',title:'Возрождение · склад',client:'ООО «Возрождение»',location:'Москва',headcount:20,roles:'Комплектовщик 20',stage:'Согласовано',owner:'Сергей',proposal:'№1',sent:1,start:'12.09.2026',activity:'Обновлено сегодня',source:'Сайт'}
];
const clients=[
{id:'c1',name:'ООО «ДАСКАР»',status:'Активный',contacts:'Анастасия · +7 977 685-55-40',requests:3,objects:1,contour:'Москва · производство'},
{id:'c2',name:'AQUATON',status:'Активный',contacts:'Отдел персонала',requests:2,objects:1,contour:'Калужская область'},
{id:'c3',name:'ООО «Контакт Сервис»',status:'Активный',contacts:'Анна · коммерческий контакт',requests:4,objects:0,contour:'Удалённый контакт-центр'},
{id:'c4',name:'ООО «Возрождение»',status:'Активный',contacts:'Иван Петров',requests:1,objects:1,contour:'Москва'}
];
const proposals=[
{id:'p1',title:'КП №2 · Линейный персонал',client:'ООО «ДАСКАР»',amount:2140000,status:'У клиента',positions:2,created:'08.09.2026',activity:'Сегодня',request:'Линейный персонал · Руднево'},
{id:'p2',title:'КП №3 · Контакт-центр',client:'ООО «Контакт Сервис»',amount:4960000,status:'Переговоры',positions:1,created:'07.09.2026',activity:'Вчера',request:'Контакт-центр · удалённо'},
{id:'p3',title:'КП №1 · Комплектовщики',client:'ООО «Возрождение»',amount:1780000,status:'Принято клиентом',positions:1,created:'03.09.2026',activity:'Сегодня',request:'Возрождение · склад'}
];
const tenders=[
{id:'t1',title:'Предоставление персонала на склад и производство',customer:'АО «Пуратос»',platform:'Bidzaar',number:'369-138',deadline:'2026-09-11T15:15:00+03:00',price:12600000,stage:'Подготовка',decision:'Участвуем',potential:'Высокий',owner:'Сергей',roles:'Комплектовщик · Грузчик',calc:'2 сценария',summary:'Экономика предварительно проходит. Требуется закрыть комплект документов и согласовать финальную ставку.',questions:'Проверить обеспечение заявки, гарантированный объём и финальные требования к подаче.',region:'Подольск, Московская область',billing:'чел./час',volume:'Плавающий объём',guarantee:'Не подтверждён',payment:'По фактически отработанным часам',bidSecurity:'Уточнить',contractSecurity:'Уточнить'},
{id:'t2',title:'Услуги по подбору и предоставлению персонала',customer:'ООО «РДВ-Софт»',platform:'Сбербанк-АСТ',number:'SBR028-2606090043',deadline:'2026-11-16T16:00:00+03:00',price:0,stage:'Анализ',decision:'Не принято',potential:'Средний',owner:'Сергей',roles:'Не определены',calc:'Нет',summary:'Требуется определить объём, модель тарификации и требования к участнику.',questions:'Уточнить гарантированный объём и сроки предоставления персонала.',region:'Москва',billing:'Не определено',volume:'Не определён',guarantee:'Не определён',payment:'Не изучено',bidSecurity:'Не изучено',contractSecurity:'Не изучено'},
{id:'t3',title:'Аутсорсинг персонала: упаковка готовой продукции и РЦ',customer:'ГК РОСТ',platform:'Bidzaar',number:'213-531',deadline:'2027-01-31T18:00:00+03:00',price:0,stage:'Анализ',decision:'Участвуем',potential:'Высокий',owner:'Сергей',roles:'Упаковщик · Разнорабочий',calc:'1 сценарий',summary:'Подходит по профилю. Нужно определить распределение объектов и коммерческую модель.',questions:'Проверить географию объектов и объём по сменам.',region:'Санкт-Петербург',billing:'чел./час',volume:'По заявкам',guarantee:'Нет данных',payment:'По табелю',bidSecurity:'Нет данных',contractSecurity:'Нет данных'},
{id:'t4',title:'Предоставление персонала для производственной площадки',customer:'АО «Силовые машины»',platform:'ТЭК-Торг',number:'ЗП6082432',deadline:'2026-09-08T10:53:00+03:00',price:0,stage:'Анализ',decision:'Не принято',potential:'Средний',owner:'Сергей',roles:'Производственный персонал',calc:'Нет',summary:'Требуется первичная квалификация и проверка требований.',questions:'Проверить допуски, квалификацию и пакет участника.',region:'Санкт-Петербург',billing:'Не определено',volume:'Не определён',guarantee:'Не определён',payment:'Не изучено',bidSecurity:'Не изучено',contractSecurity:'Не изучено'},
{id:'t5',title:'Аутстаффинг в логистических центрах РЦ',customer:'АО «Тандер»',platform:'B2B-Center',number:'4583194',deadline:'2026-09-08T15:00:00+03:00',price:0,stage:'Новый',decision:'Не принято',potential:'Высокий',owner:'Не назначен',roles:'Складской персонал',calc:'Нет',summary:'Новая закупка, требуется первичный разбор.',questions:'',region:'Краснодарский край',billing:'чел./час',volume:'Не определён',guarantee:'Не определён',payment:'Не изучено',bidSecurity:'Не изучено',contractSecurity:'Не изучено'},
{id:'t6',title:'Предоставление труда работников (аутстафф)',customer:'ООО «Сберобразование»',platform:'Сбербанк-АСТ',number:'SBR028-2608240122',deadline:'2026-09-01T09:00:00+03:00',price:9800000,stage:'Завершён',decision:'Не участвовали',potential:'Средний',owner:'Сергей',roles:'Линейный персонал',calc:'1 сценарий',summary:'Закупка завершена.',questions:'',region:'Москва',billing:'фиксированная сумма',volume:'По ТЗ',guarantee:'По договору',payment:'По договору',bidSecurity:'Не требовалось',contractSecurity:'Не требовалось'}
];
const calculations=[
{id:'calc1',source:'Заявка №r1',name:'Комплектовщик · базовый',net:132000,rate:650,rateVat:793,margin:'17,6%',status:'Основной'},
{id:'calc2',source:'Тендер №t1',name:'Грузчик · тендер',net:125000,rate:620,rateVat:756,margin:'16,9%',status:'Сценарий'},
{id:'calc3',source:'Быстрый расчёт',name:'Разнорабочий · предварительный',net:110000,rate:570,rateVat:695,margin:'15,8%',status:'Черновик'}
];

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(v){return v?new Intl.NumberFormat('ru-RU').format(v)+' ₽':'—';}
function header(title,subtitle,crumb=''){return `<div class="breadcrumbs"><span>${crumb||'OPERIS'}</span></div><div class="page-header"><div><div class="eyebrow">${esc(crumb||'РАБОЧИЙ КОНТУР')}</div><h1>${esc(title)}</h1>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div></div>`;}
function stageBadge(v){return `<span class="status status-neutral"><i></i>${esc(v)}</span>`;}
function summaryStrip(items){return `<div class="preview-summary-strip">${items.map(x=>`<div><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong>${x[2]?`<small>${esc(x[2])}</small>`:''}</div>`).join('')}</div>`;}
function entityTabs(labels,active){return `<div class="preview-entity-tabs">${labels.map(x=>`<button class="${x===active?'active':''}" onclick="setEntityTab('${x.replace(/'/g,"\\'")}')">${esc(x)}</button>`).join('')}</div>`;}
function setEntityTab(tab){state.entityTab=tab;render();}

function buildNav(){const nav=document.getElementById('nav');nav.innerHTML=sections.map(s=>`<div class="nav-section"><button class="nav-section-button ${sectionActive(s)?'is-current':''}" onclick="toggleSection('${s.id}')"><span class="preview-nav-icon">${s.icon}</span><span>${esc(s.label)}</span><span class="preview-chevron">⌄</span></button><div class="nav-section-body" data-section="${s.id}">${s.groups.map(g=>`<div class="nav-subgroup"><button type="button"><span>${esc(g.label)}</span></button><div>${g.items.map(i=>`<a href="#${i[1]}" class="${routeActive(i[1])?'active':''}"><span>${esc(i[0])}</span>${i[2]?`<small class="preview-foundation-badge">${i[2]}</small>`:''}</a>`).join('')}</div></div>`).join('')}</div></div>`).join('');}
function sectionActive(s){return s.groups.some(g=>g.items.some(i=>routeActive(i[1])));}
function routeActive(href){const p=href.split('?')[0];return state.route===p||state.route.startsWith(p+'/')||(p==='/'&&state.route==='/');}
function toggleSection(id){const el=document.querySelector(`[data-section="${id}"]`);if(el)el.hidden=!el.hidden;}

function renderHome(){return header('Командный центр','Единая рабочая точка: коммерция, подбор, объекты, финансы и контроль.','ГЛАВНАЯ')+summaryStrip([['Требуют внимания','7','сроки и блокеры'],['Активные заявки','3','в работе'],['Тендеры','5','активных'],['Согласования','4','ожидают решения']])+`<div class="preview-detail-grid"><section class="section"><div class="section-head"><div><h2>Приоритеты сегодня</h2><p>То, что требует управленческого действия.</p></div></div><div class="stack-list"><div class="stack-item"><div><strong>Тендер Пуратос · подача через 2 дня</strong><small>Закрыть документы и согласовать финальную ставку</small></div><span class="status status-warn"><i></i>Срок</span></div><div class="stack-item"><div><strong>КП №2 · ООО «ДАСКАР»</strong><small>Клиент ожидает уточнение по ставке</small></div><span class="status status-info"><i></i>КП</span></div><div class="stack-item"><div><strong>AQUATON · потребность 31 чел.</strong><small>Подготовить базовый расчёт</small></div><span class="status status-neutral"><i></i>Расчёт</span></div></div></section><aside class="section preview-side-rail"><div class="section-head"><div><h2>Контур</h2><p>Оперативная сводка.</p></div></div><div style="padding:0 14px">${kv('Активные тендеры','5')}${kv('Потребность','117 чел.')}${kv('КП у клиентов','2')}${kv('Объекты','3')}</div></aside></div>`;}
function kv(a,b){return `<div class="preview-kv"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`;}

function renderRequests(){const active=requests.filter(r=>r.stage!=='Согласовано');const total=active.reduce((s,r)=>s+r.headcount,0);let body=header('Заявки','Прямые запросы заказчиков: потребность, расчёт, КП и согласование.','КОММЕРЦИЯ → ПРОДАЖИ')+summaryStrip([['Активные заявки',String(active.length),'сейчас в работе'],['Потребность',String(total),'человек по активным заявкам'],['Отправки КП','4','за всё время'],['Согласовано','67%','из завершённых исходов']]);body+=`<div class="requests-toolbar requests-toolbar-polished"><div class="requests-toolbar-left"><div class="segmented-control request-view-switcher">${['list','board','analytics'].map((m,i)=>`<button class="${state.requestView===m?'active':''}" onclick="setRequestView('${m}')">${['Список','Доска','Аналитика'][i]}</button>`).join('')}</div><div class="segmented-control request-bucket-switcher"><button class="active">Активные</button><button>Завершённые</button><button>Архив</button></div></div><div class="requests-toolbar-actions"><input class="request-search" placeholder="Поиск по заявкам"><button class="button">Поделиться формой</button><button class="button primary">+ Новая заявка</button></div></div>`;
if(state.requestView==='board')body+=renderRequestBoard();else if(state.requestView==='analytics')body+=renderRequestAnalytics();else body+=`<div class="request-table-wrap"><table class="data-table request-registry-table"><thead><tr><th>Заявка</th><th>Потребность</th><th>Этап</th><th>Ответственный</th><th>КП</th><th>Старт</th><th>Активность</th></tr></thead><tbody>${requests.map(r=>`<tr><td><span class="preview-title-link" onclick="openRequest('${r.id}')">${esc(r.title)}</span><span class="cell-sub">${esc(r.client)} · ${esc(r.location)}</span></td><td><strong>${r.headcount} чел.</strong><span class="cell-sub">${esc(r.roles)}</span></td><td>${stageBadge(r.stage)}</td><td>${esc(r.owner)}<span class="cell-sub">${esc(r.source)}</span></td><td>${esc(r.proposal)}<span class="cell-sub">${r.sent?`отправлено: ${r.sent}`:'ещё не отправлялось'}</span></td><td>${esc(r.start)}</td><td>${esc(r.activity)}</td></tr>`).join('')}</tbody></table></div>`;return body;}
function setRequestView(v){state.requestView=v;render();}
function renderRequestBoard(){const stages=['Новая','Готово к расчёту','Расчёт','КП у клиента','Согласовано'];return `<div class="request-kanban request-board-polished request-baseline-board">${stages.map(s=>`<section class="request-kanban-column request-board-column"><header><div>${stageBadge(s)} <span class="request-board-count">${requests.filter(r=>r.stage===s).length}</span></div></header><div class="request-kanban-cards">${requests.filter(r=>r.stage===s).map(r=>`<article class="request-kanban-card request-board-card request-baseline-card"><div class="request-board-card-head"><span class="preview-title-link" onclick="openRequest('${r.id}')"><strong>${esc(r.title)}</strong></span><span>⋯</span></div><div class="request-board-client">${esc(r.client)}<small>${esc(r.location)}</small></div><div class="request-board-facts"><span>${r.headcount} чел.</span><span>${esc(r.roles.split(' · ')[0])}</span>${r.proposal!=='—'?`<span>КП ${esc(r.proposal)}</span>`:''}</div><div class="request-baseline-activity"><span>${esc(r.owner)}</span><strong>${esc(r.activity)}</strong></div></article>`).join('')}</div></section>`).join('')}</div>`;}
function renderRequestAnalytics(){return `<div class="request-analytics-grid request-analytics-polished request-baseline-analytics"><section class="request-analytics-panel"><header><strong>Распределение заявок</strong><small>Текущий объём по этапам.</small></header><div class="preview-analytics-bars">${[['Новая',1],['Готово к расчёту',1],['Расчёт',1],['КП у клиента',1],['Согласовано',1]].map(x=>`<div class="preview-bar-row"><span>${x[0]}</span><div class="preview-bar"><span style="width:${x[1]*65}%"></span></div><strong>${x[1]}</strong></div>`).join('')}</div></section><section class="request-analytics-panel"><header><strong>Коммерческий результат</strong><small>Только завершённые исходы.</small></header><div class="preview-card-grid"><div class="preview-card"><span>Согласовано</span><strong>2</strong><p>Завершённые положительные исходы</p></div><div class="preview-card"><span>Не согласовано</span><strong>1</strong><p>Основная причина: цена</p></div><div class="preview-card"><span>Конверсия</span><strong>67%</strong><p>Из завершённых исходов</p></div></div></section></div>`;}
function openRequest(id){state.selectedRequest=id;state.entityTab='Обзор';state.route='/requests/'+id;location.hash=state.route;render();}
function renderRequestDetail(){const r=requests.find(x=>x.id===state.selectedRequest)||requests[0];const tabs=['Обзор','Позиции','Расчёты','КП','Согласование','История'];let body=header(r.title,`${r.client} · ${r.location}`,'КОММЕРЦИЯ → ЗАЯВКИ')+entityTabs(tabs,state.entityTab);if(state.entityTab==='Обзор')body+=summaryStrip([['Этап',r.stage],['Потребность',`${r.headcount} чел.`],['Ответственный',r.owner],['КП',r.proposal]])+`<div class="preview-detail-grid"><section class="section"><div class="section-head"><div><h2>Ключевые условия</h2><p>Оперативная сводка заявки.</p></div></div><div style="padding:12px 14px" class="preview-facts"><div class="preview-fact"><span>Позиции</span><strong>${esc(r.roles)}</strong></div><div class="preview-fact"><span>Старт</span><strong>${esc(r.start)}</strong></div><div class="preview-fact"><span>Источник</span><strong>${esc(r.source)}</strong></div><div class="preview-fact"><span>Проживание</span><strong>Включить в нашу цену</strong></div><div class="preview-fact"><span>Медосмотр</span><strong>Заказчик</strong></div><div class="preview-fact"><span>Инструменты</span><strong>Заказчик</strong></div></div></section><aside class="section preview-side-rail"><div class="section-head"><div><h2>Рабочий контекст</h2></div></div><div style="padding:0 14px">${kv('Этап',r.stage)}${kv('Ответственный',r.owner)}${kv('Активность',r.activity)}${kv('КП',r.proposal)}</div></aside></div>`;else body+=entityPlaceholder(state.entityTab,r.title);return body;}

function renderClients(){return header('Клиенты','Единый реестр заказчиков и связанного коммерческого контура.','КОММЕРЦИЯ → ПРОДАЖИ')+summaryStrip([['Клиенты','4'],['Активные','4'],['Заявки','10'],['Объекты','3']])+`<div class="preview-toolbar"><div class="segmented-control"><button class="active">Все</button><button>Активные</button></div><input placeholder="Поиск по клиентам"><div class="preview-spacer"></div><button class="button primary">+ Новый клиент</button></div><div class="preview-generic-table"><table class="data-table"><thead><tr><th>Клиент</th><th>Статус</th><th>Контакты</th><th>Заявки</th><th>Объекты</th><th>Контур</th></tr></thead><tbody>${clients.map(c=>`<tr><td><span class="preview-title-link" onclick="openClient('${c.id}')">${esc(c.name)}</span></td><td>${stageBadge(c.status)}</td><td>${esc(c.contacts)}</td><td>${c.requests}</td><td>${c.objects}</td><td>${esc(c.contour)}</td></tr>`).join('')}</tbody></table></div>`;}
function openClient(id){state.selectedClient=id;state.entityTab='Обзор';state.route='/clients/'+id;location.hash=state.route;render();}
function renderClientDetail(){const c=clients.find(x=>x.id===state.selectedClient)||clients[0];const tabs=['Обзор','Контакты','Заявки','Расчёты','КП','Объекты','Документы','Финансы','Журнал действий'];let body=header(c.name,c.contour,'КОММЕРЦИЯ → КЛИЕНТЫ')+entityTabs(tabs,state.entityTab);if(state.entityTab==='Обзор')body+=summaryStrip([['Статус',c.status],['Заявки',String(c.requests)],['Объекты',String(c.objects)],['Контакт',c.contacts.split(' · ')[0]]])+`<div class="preview-detail-grid"><section class="section"><div class="section-head"><div><h2>Карточка клиента</h2><p>Основные данные и коммерческий контур.</p></div></div><div style="padding:12px 14px" class="preview-facts"><div class="preview-fact"><span>Компания</span><strong>${esc(c.name)}</strong></div><div class="preview-fact"><span>Контакты</span><strong>${esc(c.contacts)}</strong></div><div class="preview-fact"><span>Контур</span><strong>${esc(c.contour)}</strong></div></div></section><aside class="section preview-side-rail"><div class="section-head"><div><h2>Активность</h2></div></div><div style="padding:0 14px">${kv('Последняя заявка','Сегодня')}${kv('КП у клиента','1')}${kv('Активные объекты',String(c.objects))}</div></aside></div>`;else body+=entityPlaceholder(state.entityTab,c.name);return body;}

function renderProposals(){return header('Коммерческие предложения','Реестр КП, документ, согласование и история отправок.','КОММЕРЦИЯ → ПРОДАЖИ')+summaryStrip([['КП в работе','2'],['У клиента','1'],['Принято','1'],['Активный расчётный объём','8,9 млн ₽']])+`<div class="preview-toolbar"><div class="segmented-control"><button class="active">Все</button><button>Черновики</button><button>Согласование</button><button>У клиента</button><button>Завершённые</button></div><input placeholder="Поиск по КП"><div class="preview-spacer"></div><button class="button primary">+ Новое КП</button></div><div class="preview-generic-table"><table class="data-table"><thead><tr><th>Коммерческое предложение</th><th>Клиент</th><th>Сумма</th><th>Этап</th><th>Позиции</th><th>Создано</th><th>Активность</th></tr></thead><tbody>${proposals.map(p=>`<tr><td><span class="preview-title-link" onclick="openProposal('${p.id}')">${esc(p.title)}</span><span class="cell-sub">${esc(p.request)}</span></td><td>${esc(p.client)}</td><td><strong>${money(p.amount)}</strong></td><td>${stageBadge(p.status)}</td><td>${p.positions}</td><td>${esc(p.created)}</td><td>${esc(p.activity)}</td></tr>`).join('')}</tbody></table></div>`;}
function openProposal(id){state.selectedProposal=id;state.entityTab='Обзор';state.route='/proposals/'+id;location.hash=state.route;render();}
function renderProposalDetail(){const p=proposals.find(x=>x.id===state.selectedProposal)||proposals[0];const tabs=['Обзор','Документ','Согласование','История'];let body=header(p.title,`${p.client} · ${p.request}`,'КОММЕРЦИЯ → КП')+entityTabs(tabs,state.entityTab);if(state.entityTab==='Обзор')body+=summaryStrip([['Этап',p.status],['Версия',p.title.match(/№\d+/)?.[0]||'№1'],['Позиции',String(p.positions)],['Объём',money(p.amount)]])+`<div class="preview-detail-grid"><section class="section"><div class="section-head"><div><h2>Коммерческий контур</h2></div></div><div style="padding:12px 14px" class="preview-facts"><div class="preview-fact"><span>Клиент</span><strong>${esc(p.client)}</strong></div><div class="preview-fact"><span>Заявка</span><strong>${esc(p.request)}</strong></div><div class="preview-fact"><span>Сумма</span><strong>${money(p.amount)}</strong></div><div class="preview-fact"><span>НДС</span><strong>С НДС</strong></div><div class="preview-fact"><span>Ставка</span><strong>часовая</strong></div><div class="preview-fact"><span>Контакт</span><strong>Сергей · менеджер</strong></div></div></section><aside class="section preview-side-rail"><div class="section-head"><div><h2>Состояние</h2></div></div><div style="padding:0 14px">${kv('Этап',p.status)}${kv('Создано',p.created)}${kv('Активность',p.activity)}</div></aside></div>`;else if(state.entityTab==='Документ')body+=renderProposalPaper(p);else body+=entityPlaceholder(state.entityTab,p.title);return body;}
function renderProposalPaper(p){return `<div class="preview-toolbar"><span class="preview-muted">Шаблон: Основное КП</span><div class="preview-spacer"></div><button class="button">Изменить шаблон</button><button class="button">Настроить документ</button><button class="button primary">Скачать PDF</button></div><div class="preview-paper"><h2>Коммерческое предложение</h2><p>Оказание услуг по предоставлению персонала</p><div class="paper-meta"><span>Заказчик: <strong>${esc(p.client)}</strong></span><span>Объект: <strong>${esc(p.request)}</strong></span><span>Контакт: Сергей</span><span>Эл. почта: manager@company.ru</span></div><table><thead><tr><th>Специальность</th><th>Кол-во</th><th>Ставка без НДС</th><th>Ставка с НДС</th></tr></thead><tbody><tr><td>Комплектовщик</td><td>16</td><td>650 ₽/ч</td><td>793 ₽/ч</td></tr><tr><td>Грузчик</td><td>10</td><td>620 ₽/ч</td><td>756 ₽/ч</td></tr></tbody></table><p><strong>Стоимость услуг определяется по фактически отработанным человеко-часам.</strong></p><p style="color:#5f6b75;font-size:12px">Дополнительные блоки «В стоимость включено» и «Заказчик предоставляет» добавляются только при необходимости.</p></div>`;}

function renderTenders(){const rows=tenders.filter(t=>state.tenderBucket==='active'?t.stage!=='Завершён':t.stage==='Завершён').filter(t=>{const q=state.tenderSearch.trim().toLowerCase();return !q||`${t.title} ${t.customer} ${t.platform} ${t.number}`.toLowerCase().includes(q);}).filter(t=>{if(state.tenderDeadline==='all')return true;const d=daysLeft(t.deadline);return d<=Number(state.tenderDeadline);});const active=tenders.filter(t=>t.stage!=='Завершён');let body=header('Тендеры','Рабочий реестр закупок: импорт, анализ, расчёт, согласование, документы и подача.','КОММЕРЦИЯ → ПРОДАЖИ')+summaryStrip([['Новые',String(active.filter(t=>t.stage==='Новый').length),'требуют первичного разбора'],['На анализе',String(active.filter(t=>t.stage==='Анализ').length),'изучаем условия'],['Участвуем',String(active.filter(t=>t.decision==='Участвуем').length),'решение принято'],['Срок ≤ 3 дней',String(active.filter(t=>daysLeft(t.deadline)<=3).length),'требуют внимания']]);body+=`<div class="preview-toolbar"><div class="segmented-control"><button class="${state.tenderBucket==='active'?'active':''}" onclick="setTenderBucket('active')">Активные</button><button class="${state.tenderBucket==='completed'?'active':''}" onclick="setTenderBucket('completed')">Завершённые</button></div><div class="segmented-control"><button class="${state.tenderView==='list'?'active':''}" onclick="setTenderView('list')">Список</button><button class="${state.tenderView==='board'?'active':''}" onclick="setTenderView('board')">Доска</button></div><input value="${esc(state.tenderSearch)}" oninput="setTenderSearch(this.value)" placeholder="Поиск по тендерам"><select onchange="setTenderDeadline(this.value)"><option value="all" ${state.tenderDeadline==='all'?'selected':''}>Все сроки</option><option value="3" ${state.tenderDeadline==='3'?'selected':''}>До 3 дней</option><option value="7" ${state.tenderDeadline==='7'?'selected':''}>До 7 дней</option></select><div class="preview-spacer"></div><button class="button" onclick="exportTenders()">Выгрузить Excel</button><button class="button" onclick="document.getElementById('excelInput').click()">Загрузить Excel</button><button class="button primary" onclick="openTenderDrawer()">+ Добавить тендер</button></div>`;body+=state.tenderView==='board'?renderTenderBoard(rows):renderTenderList(rows);return body;}
function setTenderBucket(v){state.tenderBucket=v;render();}function setTenderView(v){state.tenderView=v;render();}function setTenderSearch(v){state.tenderSearch=v;render();}function setTenderDeadline(v){state.tenderDeadline=v;render();}
function renderTenderList(rows){return `<div class="request-table-wrap"><table class="data-table request-registry-table tender-table"><thead><tr><th>Тендер</th><th>Заказчик</th><th>Подача до</th><th>Осталось</th><th>Цена / контекст</th><th>Этап</th><th>Ответственный</th><th>Расчёты</th></tr></thead><tbody>${rows.map(t=>`<tr><td><span class="preview-title-link" onclick="openTender('${t.id}')">${esc(t.title)}</span><span class="cell-sub">${esc(t.platform)} · ${esc(t.number)}</span></td><td>${esc(t.customer)}<span class="cell-sub">${esc(t.roles)}</span></td><td><strong>${new Date(t.deadline).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</strong><span class="cell-sub">${esc(t.region)}</span></td><td><span class="${daysLeft(t.deadline)<=0?'preview-danger':daysLeft(t.deadline)<=3?'preview-warn':'preview-muted'} preview-deadline">${deadlineText(t.deadline)}</span></td><td><strong>${money(t.price)}</strong><span class="cell-sub">${esc(t.billing)} · потенциал ${esc(t.potential.toLowerCase())}</span></td><td>${stageBadge(t.stage)}<span class="cell-sub">${esc(t.decision)}</span></td><td>${esc(t.owner)}<span class="cell-sub">Следующее: изучить / подготовить</span></td><td>${esc(t.calc)}</td></tr>`).join('')}</tbody></table></div>`;}
function renderTenderBoard(rows){const stages=['Новый','Анализ','Расчёт','Согласование','Подготовка','Подано','Ожидаем результат'];return `<div class="preview-board">${stages.map(s=>`<section class="preview-column"><header><strong>${s}</strong><span>${rows.filter(t=>t.stage===s).length}</span></header><div class="preview-stack">${rows.filter(t=>t.stage===s).map(t=>`<article class="preview-board-card" onclick="openTender('${t.id}')"><strong>${esc(t.title)}</strong><small>${esc(t.customer)}</small><small class="${daysLeft(t.deadline)<=3?'preview-warn':''}">${deadlineText(t.deadline)} · ${esc(t.platform)}</small><footer><span>${esc(t.owner)}</span><span>${esc(t.potential)}</span></footer></article>`).join('')}</div></section>`).join('')}</div>`;}
function daysLeft(v){return Math.ceil((new Date(v).getTime()-Date.now())/86400000);}function deadlineText(v){const d=daysLeft(v);if(d<0)return `просрочено ${Math.abs(d)} дн.`;if(d===0)return 'сегодня';if(d===1)return '1 день';return `${d} дн.`;}
function openTender(id){state.selectedTender=id;state.entityTab='Обзор';state.route='/tenders/'+id;location.hash=state.route;render();}
function renderTenderDetail(){const t=tenders.find(x=>x.id===state.selectedTender)||tenders[0];const tabs=['Обзор','Анализ','Документы','Расчёты','Согласования','Подача','История'];let body=header(t.title,`${t.customer} · ${t.platform} · ${t.number}`,'КОММЕРЦИЯ → ТЕНДЕРЫ')+entityTabs(tabs,state.entityTab);if(state.entityTab==='Обзор')body+=summaryStrip([['Этап',t.stage],['Подача до',new Date(t.deadline).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})],['Осталось',deadlineText(t.deadline)],['Решение',t.decision]])+`<div class="preview-detail-grid"><section class="section"><div class="section-head"><div><h2>Ключевые условия</h2><p>Сводка после анализа тендера.</p></div></div><div style="padding:12px 14px" class="preview-facts">${fact('Регион',t.region)}${fact('Формат цены',t.billing)}${fact('Объём',t.volume)}${fact('Гарантированный объём',t.guarantee)}${fact('Условия оплаты',t.payment)}${fact('НМЦК',money(t.price))}</div><div style="padding:0 14px 14px"><div class="preview-card"><span>Заключение аналитика</span><strong>${esc(t.summary)}</strong><p>${esc(t.questions||'Критичных открытых вопросов нет.')}</p></div></div></section><aside class="section preview-side-rail"><div class="section-head"><div><h2>Работа</h2></div></div><div style="padding:0 14px">${kv('Ответственный',t.owner)}${kv('Потенциал',t.potential)}${kv('Расчёты',t.calc)}${kv('Следующее действие','Подготовить пакет')}</div></aside></div>`;else if(state.entityTab==='Анализ')body+=renderTenderAnalysis(t);else if(state.entityTab==='Документы')body+=renderTenderDocs(t);else if(state.entityTab==='Расчёты')body+=renderTenderCalcs(t);else if(state.entityTab==='Согласования')body+=renderTenderApprovals(t);else if(state.entityTab==='Подача')body+=renderTenderSubmission(t);else body+=entityPlaceholder('История',t.title);return body;}
function fact(a,b){return `<div class="preview-fact"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`;}
function renderTenderAnalysis(t){return `<div class="preview-detail-grid"><section class="section"><div class="section-head"><div><h2>Анализ тендера</h2><p>Данные для решения Go / No-Go и расчёта.</p></div><button class="button">Редактировать</button></div><div style="padding:12px 14px" class="preview-facts">${fact('Предмет закупки',t.roles)}${fact('Формат работ',t.billing)}${fact('Регион',t.region)}${fact('Гарантированный объём',t.guarantee)}${fact('Объём',t.volume)}${fact('Условия оплаты',t.payment)}${fact('Обеспечение заявки',t.bidSecurity)}${fact('Обеспечение договора',t.contractSecurity)}${fact('НДС','Уточнить по документации')}</div><div style="padding:0 14px 14px"><div class="preview-card"><span>Риски и открытые вопросы</span><strong>${esc(t.questions||'Не выявлены')}</strong><p>Итог: ${esc(t.summary)}</p></div></div></section><aside class="section preview-side-rail"><div class="section-head"><div><h2>Решение</h2></div></div><div style="padding:12px 14px"><div class="preview-card"><span>Текущая рекомендация</span><strong>${esc(t.decision)}</strong><p>Потенциал: ${esc(t.potential)}</p></div><div class="preview-actions" style="margin-top:10px"><button class="button primary">Участвуем</button><button class="button">Нужно уточнить</button><button class="button">Не участвуем</button></div></div></aside></div>`;}
function renderTenderDocs(t){return `<div class="preview-detail-grid"><section class="section"><div class="section-head"><div><h2>Документы тендера</h2><p>Исходные файлы и разъяснения.</p></div><button class="button">+ Добавить документ</button></div><div style="padding:12px 14px" class="preview-docs"><div class="preview-doc"><strong>Техническое задание.pdf</strong><span>ТЗ</span></div><div class="preview-doc"><strong>Проект договора.docx</strong><span>Договор</span></div><div class="preview-doc"><strong>Спецификация.xlsx</strong><span>Спецификация</span></div></div></section><section class="section"><div class="section-head"><div><h2>Документы компании</h2><p>Чек-лист именно для этой закупки.</p></div></div><div class="preview-generic-table" style="border:0;border-radius:0"><table class="data-table"><thead><tr><th>Документ</th><th>Статус</th><th>Ответственный</th></tr></thead><tbody><tr><td>Устав</td><td>${stageBadge('Готов')}</td><td>—</td></tr><tr><td>Выписка ЕГРЮЛ</td><td>${stageBadge('Готов')}</td><td>—</td></tr><tr><td>Справка ФНС</td><td>${stageBadge('Нужно обновить')}</td><td>Анна</td></tr><tr><td>Аналогичный договор</td><td>${stageBadge('Проверить')}</td><td>Сергей</td></tr></tbody></table></div></section></div>`;}
function renderTenderCalcs(t){return `<div class="section"><div class="section-head"><div><h2>Связанные расчёты</h2><p>Тендер использует общий калькулятор OPERIS напрямую, без промежуточной заявки.</p></div><button class="button primary" onclick="go('/calculations')">+ Создать расчёт</button></div><div class="preview-generic-table" style="border:0"><table class="data-table"><thead><tr><th>Сценарий</th><th>Ставка без НДС</th><th>С НДС</th><th>Маржа</th><th>Статус</th></tr></thead><tbody><tr><td>Комплектовщик · базовый</td><td>650 ₽/ч</td><td>793 ₽/ч</td><td>17,6%</td><td>${stageBadge('Основной')}</td></tr><tr><td>Грузчик · резерв</td><td>620 ₽/ч</td><td>756 ₽/ч</td><td>16,9%</td><td>${stageBadge('Сценарий')}</td></tr></tbody></table></div></div>`;}
function renderTenderApprovals(t){return `<div class="preview-card-grid"><div class="preview-card"><span>Решение об участии</span><strong>${esc(t.decision)}</strong><p>Согласующий: руководитель направления</p><button class="button" style="margin-top:10px">Передать на согласование</button></div><div class="preview-card"><span>Цена</span><strong>${t.calc}</strong><p>Финальная ставка ещё не зафиксирована</p><button class="button" style="margin-top:10px">Согласовать цену</button></div><div class="preview-card"><span>Разрешение подачи</span><strong>Не запрошено</strong><p>Доступно после готовности документов</p><button class="button" style="margin-top:10px">Запросить</button></div></div>`;}
function renderTenderSubmission(t){return `<div class="preview-detail-grid"><section class="section"><div class="section-head"><div><h2>Готовность к подаче</h2><p>Рабочий чек-лист перед отправкой на площадку.</p></div></div><div style="padding:14px"><div class="preview-progress"><span style="width:75%"></span></div><div class="preview-docs" style="margin-top:12px"><div class="preview-doc"><strong>Цена рассчитана</strong><span class="preview-good">Готово</span></div><div class="preview-doc"><strong>Решение об участии</strong><span class="preview-good">Согласовано</span></div><div class="preview-doc"><strong>Документы компании</strong><span class="preview-warn">3 / 4</span></div><div class="preview-doc"><strong>Разрешение подачи</strong><span>Не получено</span></div></div></div></section><aside class="section preview-side-rail"><div class="section-head"><div><h2>Подача</h2></div></div><div style="padding:12px 14px"><button class="button primary" style="width:100%">Зафиксировать подачу</button><p class="preview-muted" style="font-size:11px">Дата, кто подал, финальная цена, номер заявки и комментарий.</p></div></aside></div>`;}
function openTenderDrawer(){document.getElementById('drawer').classList.add('is-open');}function closeDrawer(){document.getElementById('drawer').classList.remove('is-open');}
function saveTender(){const title=document.getElementById('newTitle').value.trim();if(!title)return;const id='t'+(tenders.length+1);tenders.unshift({id,title,customer:document.getElementById('newCustomer').value||'Заказчик не указан',platform:document.getElementById('newPlatform').value||'Площадка не указана',number:document.getElementById('newNumber').value||'—',deadline:document.getElementById('newDeadline').value?new Date(document.getElementById('newDeadline').value).toISOString():new Date(Date.now()+7*86400000).toISOString(),price:Number(document.getElementById('newPrice').value)||0,stage:'Новый',decision:'Не принято',potential:document.getElementById('newPotential').value,owner:'Не назначен',roles:'Не определены',calc:'Нет',summary:document.getElementById('newComment').value||'Требуется первичный анализ.',questions:'',region:'Не указано',billing:'Не определено',volume:'Не определён',guarantee:'Не определён',payment:'Не изучено',bidSecurity:'Не изучено',contractSecurity:'Не изучено'});closeDrawer();render();}
function exportTenders(){const data=tenders.map(t=>({'Название':t.title,'Заказчик':t.customer,'Площадка':t.platform,'Номер':t.number,'Срок':new Date(t.deadline).toLocaleString('ru-RU'),'Цена':t.price,'Этап':t.stage,'Решение':t.decision}));const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Тендеры');XLSX.writeFile(wb,'OPERIS_тендеры_preview.xlsx');}

function renderCalculations(){return header('Расчёты','Общий калькулятор OPERIS: из заявки, из тендера или быстрый самостоятельный расчёт.','КОММЕРЦИЯ → ЭКОНОМИКА')+`<div class="preview-toolbar"><div class="segmented-control"><button class="active">Все расчёты</button><button>Быстрые</button><button>Из заявок</button><button>Из тендеров</button></div><div class="preview-spacer"></div><button class="button primary">+ Быстрый расчёт</button></div><div class="preview-generic-table"><table class="data-table"><thead><tr><th>Расчёт</th><th>Источник</th><th>На руки</th><th>Ставка без НДС</th><th>С НДС</th><th>Маржа</th><th>Статус</th></tr></thead><tbody>${calculations.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.source)}</td><td>${money(c.net)}</td><td>${c.rate} ₽/ч</td><td>${c.rateVat} ₽/ч</td><td>${esc(c.margin)}</td><td>${stageBadge(c.status)}</td></tr>`).join('')}</tbody></table></div>`;}
function renderCompanyDocs(){return header('Документы компании','Общая библиотека документов юридических лиц для тендеров и других процессов.','ОРГАНИЗАЦИЯ → ДОКУМЕНТЫ')+summaryStrip([['Документы','18'],['Актуальные','14'],['Истекают','2'],['Нужно обновить','2']])+`<div class="preview-toolbar"><input placeholder="Поиск по документам"><select><option>Все юрлица</option><option>ООО «Р-Кадры»</option></select><div class="preview-spacer"></div><button class="button primary">+ Добавить документ</button></div><div class="preview-generic-table"><table class="data-table"><thead><tr><th>Документ</th><th>Юрлицо</th><th>Действует до</th><th>Статус</th><th>Использование</th></tr></thead><tbody><tr><td><strong>Устав</strong></td><td>ООО «Р-Кадры»</td><td>—</td><td>${stageBadge('Актуален')}</td><td>Тендеры</td></tr><tr><td><strong>Выписка ЕГРЮЛ</strong></td><td>ООО «Р-Кадры»</td><td>—</td><td>${stageBadge('Актуален')}</td><td>Тендеры</td></tr><tr><td><strong>Справка ФНС</strong></td><td>ООО «Р-Кадры»</td><td>30.09.2026</td><td>${stageBadge('Истекает')}</td><td>Тендеры</td></tr></tbody></table></div>`;}
function renderGeneric(){const meta=titleMap[state.route]||{title:state.route.split('/').filter(Boolean).pop()||'Раздел',section:'OPERIS',group:'Рабочий контур'};return header(meta.title,'Раздел присутствует в текущей архитектуре OPERIS. В preview показан общий visual baseline без серверной логики.',`${meta.section} → ${meta.group}`)+`<div class="preview-card-grid"><div class="preview-card"><span>Статус</span><strong>Рабочий контур</strong><p>Сохранена навигация и текущий визуальный язык.</p></div><div class="preview-card"><span>Данные</span><strong>Preview</strong><p>Серверная БД в GitHub Pages не используется.</p></div><div class="preview-card"><span>Production</span><strong>Next.js + PostgreSQL</strong><p>Полная логика остаётся в основном приложении.</p></div></div>`;}
function entityPlaceholder(tab,title){return `<div class="section"><div class="section-head"><div><h2>${esc(tab)}</h2><p>${esc(title)}</p></div></div><div class="preview-foundation"><div><strong>${esc(tab)}</strong><span>В preview сохранён отдельный раздел сущности. Детальная серверная логика остаётся в production OPERIS.</span></div></div></div>`;}

function render(){document.documentElement.dataset.theme=state.theme;document.getElementById('sidebar').classList.toggle('sidebar-compact',state.compact);document.getElementById('topbar').classList.toggle('topbar-compact',state.compact);buildNav();let html;if(state.route==='/')html=renderHome();else if(state.route==='/requests')html=renderRequests();else if(state.route.startsWith('/requests/'))html=renderRequestDetail();else if(state.route==='/clients')html=renderClients();else if(state.route.startsWith('/clients/'))html=renderClientDetail();else if(state.route==='/proposals')html=renderProposals();else if(state.route.startsWith('/proposals/'))html=renderProposalDetail();else if(state.route==='/tenders')html=renderTenders();else if(state.route.startsWith('/tenders/'))html=renderTenderDetail();else if(state.route==='/calculations')html=renderCalculations();else if(state.route==='/organization/documents')html=renderCompanyDocs();else html=renderGeneric();document.getElementById('page').innerHTML=html;document.getElementById('topContext').textContent=`Рабочий контур · ${titleMap[state.route]?.title||state.route.split('/').filter(Boolean)[0]||'Главная'}`;}
function go(path){state.route=path.split('?')[0]||'/';state.entityTab='Обзор';location.hash=path;render();}
function syncRoute(){const h=decodeURIComponent(location.hash.slice(1)||'/tenders');state.route=h.split('?')[0]||'/';if(state.route.startsWith('/tenders/'))state.selectedTender=state.route.split('/')[2];if(state.route.startsWith('/requests/'))state.selectedRequest=state.route.split('/')[2];if(state.route.startsWith('/clients/'))state.selectedClient=state.route.split('/')[2];if(state.route.startsWith('/proposals/'))state.selectedProposal=state.route.split('/')[2];state.entityTab='Обзор';render();}
window.addEventListener('hashchange',syncRoute);document.getElementById('themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('operis.preview.theme',state.theme);render();};document.getElementById('collapse').onclick=()=>{state.compact=!state.compact;localStorage.setItem('operis.preview.compact',state.compact?'1':'0');render();};document.getElementById('drawer').addEventListener('mousedown',e=>{if(e.target===e.currentTarget)closeDrawer();});document.getElementById('quickSearch').onclick=()=>openCommand();
function openCommand(){const q=prompt('Быстрый переход: введите название раздела');if(!q)return;const all=sections.flatMap(s=>s.groups.flatMap(g=>g.items.map(i=>({label:i[0],path:i[1]}))));const hit=all.find(i=>i.label.toLowerCase().includes(q.toLowerCase()));if(hit)go(hit.path);}
document.getElementById('excelInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});if(rows.length)alert(`Файл прочитан. Найдено строк: ${rows.length}. В production OPERIS перед импортом откроется сопоставление колонок и проверка дублей.`);else alert('В файле не найдено строк.');}catch{alert('Не удалось прочитать файл.');}e.target.value='';});
syncRoute();