import {NextResponse} from "next/server";
import {z} from "zod";
import type {Sql} from "postgres";
import {getCurrentActor} from "@/lib/auth/server";
import {AccessDeniedError,requireCapability} from "@/lib/access/server";
import {canReadRow} from "@/lib/core/access.mjs";
import {withTenant} from "@/lib/db/client";

const createSchema=z.object({name:z.string().trim().min(2).max(300),documentType:z.string().trim().min(2).max(80),sourceUrl:z.string().url().max(2000).nullable().optional(),notes:z.string().trim().max(2000).nullable().optional()});
const deleteSchema=z.object({documentId:z.string().uuid()});
type Scope={organizationId:string;ownerUserId:string|null;createdByUserId:string;teamId:string|null;regionId:string|null;clientId:string|null};
async function assertEditable(actor:NonNullable<Awaited<ReturnType<typeof getCurrentActor>>>,id:string,sql:Sql){const [row]=await sql<Scope[]>`SELECT organization_id "organizationId",owner_user_id "ownerUserId",created_by_user_id "createdByUserId",assigned_team_id "teamId",region_id "regionId",client_company_id "clientId" FROM tenders WHERE id=${id}::uuid`;if(!row||!canReadRow(actor.access,"sales.tender.edit",row,actor))throw new AccessDeniedError("sales.tender.edit");}

export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"sales.tender.edit");if(actor.demo)return NextResponse.json({error:"Демонстрационные данные доступны только для чтения"},{status:409});const {id}=await params;const body=createSchema.parse(await request.json());const row=await withTenant(actor.organizationId,actor.userId,async sql=>{await assertEditable(actor,id,sql);const [created]=await sql<Array<{id:string}>>`INSERT INTO tender_source_documents(organization_id,tender_id,name,document_type,source_url,notes,created_by_user_id) VALUES(${actor.organizationId}::uuid,${id}::uuid,${body.name},${body.documentType},${body.sourceUrl??null},${body.notes??null},${actor.userId}::uuid) RETURNING id`;await sql`UPDATE tenders SET updated_at=now() WHERE id=${id}::uuid`;return created;});return NextResponse.json(row,{status:201});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте документ"},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});return NextResponse.json({error:error instanceof Error?error.message:"Internal error"},{status:500});}}

export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"sales.tender.edit");if(actor.demo)return NextResponse.json({error:"Демонстрационные данные доступны только для чтения"},{status:409});const {id}=await params;const body=deleteSchema.parse(await request.json());await withTenant(actor.organizationId,actor.userId,async sql=>{await assertEditable(actor,id,sql);await sql`DELETE FROM tender_source_documents WHERE id=${body.documentId}::uuid AND tender_id=${id}::uuid`;await sql`UPDATE tenders SET updated_at=now() WHERE id=${id}::uuid`;});return NextResponse.json({ok:true});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Некорректный документ"},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});return NextResponse.json({error:error instanceof Error?error.message:"Internal error"},{status:500});}}
