import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentActor } from "@/lib/auth/server";
import { AccessDeniedError, requireCapability } from "@/lib/access/server";
import { hasCapability,canReadRow } from "@/lib/core/access.mjs";
import { withTenant } from "@/lib/db/client";
import { getCommercialRequest } from "@/lib/commercial/service";
import { normalizeRequestIntake,toJsonValue } from "@/lib/commercial/request-intake";

const roleSchema=z.object({id:z.string().uuid().optional(),specialtyId:z.string().uuid().nullable().optional(),specialtyName:z.string().trim().min(2).max(160),count:z.number().int().positive().max(5000),schedule:z.record(z.string(),z.json()).default({}),requirements:z.record(z.string(),z.json()).default({}),targetClientRate:z.number().nonnegative().nullable().default(null)});
const schema=z.object({clientId:z.string().uuid().nullable().default(null),title:z.string().trim().min(3).max(240),source:z.string().trim().min(1).max(120),location:z.string().trim().max(500),regionId:z.string().uuid().nullable().default(null),startDate:z.string().date().nullable().default(null),durationText:z.string().trim().max(160).nullable().default(null),schedule:z.record(z.string(),z.json()).default({}),intake:z.record(z.string(),z.json()).default({}),lunchPaid:z.boolean(),vatMode:z.string().trim().max(40).nullable(),comments:z.string().trim().max(5000).nullable(),ownerUserId:z.string().uuid().nullable(),observerUserIds:z.array(z.string().uuid()).max(30).default([]),roles:z.array(roleSchema).max(250).default([])});
function canAssign(actor:NonNullable<Awaited<ReturnType<typeof getCurrentActor>>>){return actor.roleCode==="director"||hasCapability(actor.access,"organization.manage")||hasCapability(actor.access,"sales.request.archive");}
function rule(intake:ReturnType<typeof normalizeRequestIntake>,key:"housing"|"travel"|"shuttle"|"workwear"|"ppe"|"medical"|"medbook"|"tools"){return intake.provision[key].provider;}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Unauthorized"},{status:401});requireCapability(actor,"sales.request.edit");if(actor.demo)return NextResponse.json({error:"Демонстрационные данные доступны только для чтения"},{status:409});const {id}=await params;const body=schema.parse(await request.json());const intake=normalizeRequestIntake(body.intake);const current=await getCommercialRequest(actor,id);if(!current)return NextResponse.json({error:"Заявка не найдена"},{status:404});if(!canReadRow(actor.access,"sales.request.edit",current,actor))throw new AccessDeniedError("sales.request.edit");if(current.archivedAt)throw new Error("Сначала восстановите заявку из архива");if(["accepted","launched"].includes(current.status))throw new Error("Принятая заявка зафиксирована. Изменения вносятся до согласования КП");const ownerUserId=body.ownerUserId??actor.userId;if(ownerUserId!==current.ownerUserId&&ownerUserId!==actor.userId&&!canAssign(actor))throw new AccessDeniedError("sales.request.assign");
  await withTenant(actor.organizationId,actor.userId,async(sql)=>sql.begin(async(tx)=>{if(body.clientId){const [client]=await tx<Array<{id:string}>>`SELECT id FROM client_companies WHERE id=${body.clientId}::uuid`;if(!client)throw new Error("Клиент не найден в текущей организации");}if(body.regionId){const [region]=await tx<Array<{id:string}>>`SELECT id FROM regions WHERE id=${body.regionId}::uuid`;if(!region)throw new Error("Регион не найден в текущей организации");}const [owner]=await tx<Array<{id:string}>>`SELECT user_id id FROM organization_memberships WHERE organization_id=${actor.organizationId}::uuid AND user_id=${ownerUserId}::uuid AND status='active'`;if(!owner)throw new Error("Ответственный не состоит в текущей организации");
    await tx`UPDATE requests SET client_company_id=${body.clientId}::uuid,title=${body.title},source=${body.source},location_text=${body.location},region_id=${body.regionId}::uuid,expected_start_date=${body.startDate}::date,duration_text=${body.durationText},schedule_json=${sql.json(toJsonValue(body.schedule))},intake_json=${sql.json(toJsonValue(intake))},lunch_paid=${body.lunchPaid},vat_mode=${body.vatMode},housing_rule=${rule(intake,"housing")},travel_rule=${rule(intake,"travel")},shuttle_rule=${rule(intake,"shuttle")},ppe_rule=${`${rule(intake,"workwear")} / ${rule(intake,"ppe")}`},medical_rule=${`${rule(intake,"medical")} / ${rule(intake,"medbook")}`},citizenship_rule=${intake.compliance.workerCategories.join(", ")},tools_rule=${rule(intake,"tools")},comments=${body.comments},owner_user_id=${ownerUserId}::uuid,updated_at=now() WHERE id=${id}::uuid`;
    const linkedIds=await tx<Array<{id:string}>>`SELECT DISTINCT request_role_id id FROM calculation_scenarios cs JOIN calculations c ON c.id=cs.calculation_id WHERE c.request_id=${id}::uuid`;const supplied=new Set(body.roles.flatMap((role)=>role.id?[role.id]:[]));
    for(const role of body.roles){let specialtyId=role.specialtyId??null;if(specialtyId){const [specialty]=await tx<Array<{id:string}>>`SELECT id FROM specialties WHERE id=${specialtyId}::uuid AND active`;if(!specialty)specialtyId=null;}if(!specialtyId){const [existing]=await tx<Array<{id:string}>>`SELECT id FROM specialties WHERE active AND lower(name)=lower(${role.specialtyName}) LIMIT 1`;if(existing)specialtyId=existing.id;else{const [created]=await tx<Array<{id:string}>>`INSERT INTO specialties(organization_id,code,name) VALUES(${actor.organizationId}::uuid,${`custom-${randomUUID().slice(0,8)}`},${role.specialtyName}) RETURNING id`;specialtyId=created.id;}}if(role.id){const old=current.roles.find((item)=>item.id===role.id);if(old&&linkedIds.some((item)=>item.id===role.id)&&old.specialtyId!==specialtyId)throw new Error("Нельзя менять специальность позиции после создания расчёта. Добавьте новую позицию");await tx`UPDATE request_roles SET specialty_id=${specialtyId}::uuid,count_required=${role.count},schedule_json=${sql.json(toJsonValue(role.schedule))},requirements_json=${sql.json(toJsonValue(role.requirements))},target_client_rate=${role.targetClientRate} WHERE id=${role.id}::uuid AND request_id=${id}::uuid`;}else await tx`INSERT INTO request_roles(organization_id,request_id,specialty_id,count_required,schedule_json,requirements_json,target_client_rate) VALUES(${actor.organizationId}::uuid,${id}::uuid,${specialtyId}::uuid,${role.count},${sql.json(toJsonValue(role.schedule))},${sql.json(toJsonValue(role.requirements))},${role.targetClientRate})`;}
    for(const old of current.roles){if(supplied.has(old.id))continue;if(linkedIds.some((item)=>item.id===old.id))throw new Error("Нельзя удалить позицию, по которой уже существует расчёт");await tx`DELETE FROM request_roles WHERE id=${old.id}::uuid AND request_id=${id}::uuid`;}
    await tx`DELETE FROM request_observers WHERE request_id=${id}::uuid`;for(const userId of [...new Set(body.observerUserIds)].filter((observerId)=>observerId!==ownerUserId)){const [member]=await tx<Array<{id:string}>>`SELECT user_id id FROM organization_memberships WHERE organization_id=${actor.organizationId}::uuid AND user_id=${userId}::uuid AND status='active'`;if(member)await tx`INSERT INTO request_observers(organization_id,request_id,user_id,added_by_user_id) VALUES(${actor.organizationId}::uuid,${id}::uuid,${userId}::uuid,${actor.userId}::uuid)`;}
  }));return NextResponse.json({id});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Проверьте заполнение полей",issues:error.issues},{status:400});if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});console.error(error);return NextResponse.json({error:error instanceof Error?error.message:"Internal error"},{status:500});}}
