import Link from "next/link";
import { notFound } from "next/navigation";
import { requireActor } from "@/lib/auth/server";
import { listCandidates,listFinance,listNeeds,listObjects,listShifts,listWorkers } from "@/lib/data/service";
import { hasCapability } from "@/lib/core/access.mjs";
import { Empty,EntityTabs,KeyValue,Metric,PageHeader,Section,Status } from "@/components/UI";
import { pct,rub } from "@/lib/ui/format";

const labels:Record<string,string>={overview:"Обзор",needs:"Потребности",recruiting:"Подбор",people:"Люди",shifts:"Смены",timesheets:"Табели",incidents:"Инциденты",documents:"Документы",expenses:"Расходы",finance:"Финансы",activity:"Журнал действий"};
export default async function ObjectWorkspace({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{tab?:string}>}) {
 const {id}=await params;const {tab:rawTab}=await searchParams;const tab=rawTab&&labels[rawTab]?rawTab:"overview";const actor=await requireActor();const objects=await listObjects(actor);const object=objects.find(row=>row.id===id);if(!object)notFound();
 const [needs,workers,shifts,finance,candidates]=await Promise.all([
  hasCapability(actor.access,"operations.need.read")?listNeeds(actor):Promise.resolve([]),hasCapability(actor.access,"worker.read")?listWorkers(actor):Promise.resolve([]),hasCapability(actor.access,"operations.shift.read")?listShifts(actor):Promise.resolve([]),hasCapability(actor.access,"finance.pnl.read")?listFinance(actor):Promise.resolve([]),hasCapability(actor.access,"recruiting.candidate.read")?listCandidates(actor):Promise.resolve([]),
 ]);
 const objectNeeds=needs.filter(x=>x.objectId===id),objectWorkers=workers.filter(x=>x.objectId===id),objectShifts=shifts.filter(x=>x.objectId===id),objectCandidates=candidates.filter(x=>x.objectId===id),objFinance=finance.find(x=>x.objectId===id);const margin=object.marginForecast??objFinance?.marginPct;
 const tabs=Object.entries(labels).filter(([key])=>key!=="finance"||hasCapability(actor.access,"finance.pnl.read")).map(([key,label])=>({label,href:`/objects/${id}?tab=${key}`,count:key==="needs"?objectNeeds.length:key==="people"?objectWorkers.length:key==="recruiting"?objectCandidates.length:key==="shifts"?objectShifts.length:undefined}));
 return <><PageHeader eyebrow={`Объект · ${object.code}`} title={object.name} subtitle={`${object.client} · ${object.region}`} breadcrumbs={[{label:"Операции"},{label:"Объекты",href:"/objects"},{label:object.name}]}/><div className="object-hero"><div><Status tone={object.risk==="critical"?"bad":object.risk==="high"?"warn":"good"}>{object.status}</Status><div className="object-meta"><div><span>Клиент</span><strong>{object.client}</strong></div><div><span>Регион</span><strong>{object.region}</strong></div><div><span>Старт</span><strong>{object.targetStart??"—"}</strong></div><div><span>Дефицит</span><strong>{object.deficit}</strong></div><div><span>Прогнозная маржа</span><strong>{margin!=null?pct(margin):"—"}</strong></div></div></div><div className="health"><strong>{object.coverage}%</strong><span>укомплектованность</span></div></div><EntityTabs items={tabs} active={labels[tab]}/>
 {tab==="overview"&&<><div className="metrics-grid"><Metric label="Потребность" value={object.required}/><Metric label="Назначено" value={object.filled}/><Metric label="Дефицит" value={object.deficit} tone={object.deficit?"bad":"good"}/><Metric label="Прогнозная маржа" value={margin!=null?pct(margin):"—"} tone={margin!=null&&Number(margin)<15?"warn":"good"}/></div><div className="workspace-grid"><div><Section title="Требует внимания" note="Операционные исключения и ближайшие действия"><div className="stack-list">{object.deficit>0&&<div className="stack-item"><div><strong className="priority-critical">Не закрыт плановый состав</strong><small>{object.deficit} человек · потребности требуют действия</small></div><Link className="button" href={`/objects/${id}?tab=needs`}>Открыть</Link></div>}{objectShifts.filter(x=>x.deficit>0).map(x=><div className="stack-item" key={x.id}><div><strong>{x.date} · {x.specialty}</strong><small>Назначено {x.assigned} из {x.demand}</small></div><Status tone="warn">дефицит {x.deficit}</Status></div>)}</div></Section><Section title="Ближайшие смены"><ShiftTable rows={objectShifts.slice(0,5)}/></Section></div><div><Section title="Готовность запуска"><div style={{padding:"6px 15px 14px"}}><KeyValue label="Плановая численность" value={object.required}/><KeyValue label="Назначено" value={object.filled}/><KeyValue label="Подтверждено на ближайшие смены" value={objectShifts.reduce((s,x)=>s+Number(x.confirmed??0),0)}/><KeyValue label="Операционный риск" value={<Status tone={object.risk==="critical"?"bad":object.risk==="high"?"warn":"good"}>{object.risk??"normal"}</Status>}/></div></Section>{objFinance&&<Section title="Финансовый факт"><div style={{padding:"6px 15px 14px"}}><KeyValue label="Выручка" value={rub(objFinance.revenue)} sensitive/><KeyValue label="Затраты на персонал" value={rub(objFinance.workerCost)} sensitive/><KeyValue label="Расходы объекта" value={rub(objFinance.expenses)} sensitive/><KeyValue label="Вклад в прибыль" value={rub(objFinance.contribution)} sensitive/></div></Section>}</div></div></>}
 {tab==="needs"&&<Section title="Потребности объекта" note="Каждая потребность связана с заявками кандидатов"><table className="data-table"><thead><tr><th>Позиция</th><th>Нужно</th><th>Закрыто</th><th>Дефицит</th><th>Дедлайн</th><th>Статус</th></tr></thead><tbody>{objectNeeds.map(row=><tr key={row.id}><td className="cell-title">{row.specialty}</td><td className="num">{row.required}</td><td className="num">{row.filled}</td><td className="num">{row.deficit}</td><td>{row.deadline}</td><td><Status tone={row.deficit?"warn":"good"}>{row.status}</Status></td></tr>)}</tbody></table>{!objectNeeds.length&&<Empty title="Потребностей нет" text="Для этого объекта не создано активных потребностей."/>}</Section>}
 {tab==="recruiting"&&<Section title="Подбор на объект"><table className="data-table"><thead><tr><th>Кандидат</th><th>Позиция</th><th>Этап</th><th>Источник</th><th>Следующее действие</th></tr></thead><tbody>{objectCandidates.map(row=><tr key={row.id}><td><Link className="cell-title" href={`/candidates/${row.id}`}>{row.fullName}</Link></td><td>{row.need}</td><td><Status tone="info">{row.stageLabel??row.stage}</Status></td><td>{row.source}</td><td>{row.nextAction}</td></tr>)}</tbody></table>{!objectCandidates.length&&<Empty title="Кандидатов нет" text="На доступные потребности объекта пока нет заявок кандидатов."/>}</Section>}
 {tab==="people"&&<Section title="Сотрудники на объекте"><table className="data-table"><thead><tr><th>Сотрудник</th><th>Оформление</th><th>Источник</th><th>Статус</th></tr></thead><tbody>{objectWorkers.map(row=><tr key={row.id}><td><Link className="cell-title" href={`/workers/${row.id}`}>{row.fullName}</Link></td><td>{row.employment??"—"}</td><td>{row.origin??row.source??"—"}</td><td><Status tone="good">{row.status}</Status></td></tr>)}</tbody></table>{!objectWorkers.length&&<Empty title="Назначений нет" text="На объект не назначены доступные вам сотрудники."/>}</Section>}
 {tab==="shifts"&&<Section title="Смены объекта"><ShiftTable rows={objectShifts}/></Section>}
 {tab==="timesheets"&&<Section title="Табели объекта"><Empty title="Откройте рабочее место табеля" text="Периоды, клиентский вид и сверка доступны в отдельном модуле." action={<Link className="button primary" href="/timesheets">Перейти к табелям</Link>}/></Section>}
 {tab==="finance"&&objFinance&&<Section title="Финансовый факт"><div style={{padding:16,maxWidth:560}}><KeyValue label="Выручка" value={rub(objFinance.revenue)} sensitive/><KeyValue label="Затраты на персонал" value={rub(objFinance.workerCost)} sensitive/><KeyValue label="Прямые расходы" value={rub(objFinance.expenses)} sensitive/><KeyValue label="Вклад в прибыль" value={rub(objFinance.contribution)} sensitive/><KeyValue label="Маржа" value={pct(objFinance.marginPct)} sensitive/></div></Section>}
 {["incidents","documents","expenses","activity"].includes(tab)&&<Section title={labels[tab]}><Empty title={`Нет записей: ${labels[tab].toLowerCase()}`} text="В доступном контуре объекта записи отсутствуют."/></Section>}
 </>;
}
function ShiftTable({rows}:{rows:Awaited<ReturnType<typeof listShifts>>}){return <table className="data-table"><thead><tr><th>Смена</th><th>Позиция</th><th>Потребность</th><th>Назначено</th><th>Резерв</th><th>Дефицит</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.date} · {row.kind}</strong><span className="cell-sub">{row.time}</span></td><td>{row.specialty}</td><td className="num">{row.demand}</td><td className="num">{row.assigned}</td><td className="num">{row.reserve}</td><td className="num">{row.deficit}</td></tr>)}</tbody></table>}
