import Link from "next/link";
import { requireActor } from "@/lib/auth/server";
import { listCommercialCalculations } from "@/lib/data/calculations";
import { PageHeader,Section,Status } from "@/components/UI";
import { CalculatorWorkspace } from "@/components/CalculatorWorkspace";
import { rub,pct } from "@/lib/ui/format";

const scenarioLabels:Record<string,string>={draft:"Черновик",review:"На согласовании",accepted:"Согласован",rejected:"Отклонён"};
export default async function Calculations({searchParams}:{searchParams:Promise<{view?:string;request?:string}>}){
  const {view="all",request}=await searchParams;const actor=await requireActor();const all=await listCommercialCalculations(actor);const rows=view==="requests"?all.filter(x=>x.requestId):view==="standalone"?all.filter(x=>!x.requestId):all;
  return <><PageHeader eyebrow="Коммерция → Экономика" title="Расчёты" subtitle="Один расчётный модуль для заявок и самостоятельных сценариев. Исторические версии сохраняются неизменяемыми." actions={<div className="segmented"><Link className={view==="all"?"active":""} href="/calculations?view=all">Все</Link><Link className={view==="requests"?"active":""} href="/calculations?view=requests">По заявкам</Link><Link className={view==="standalone"?"active":""} href="/calculations?view=standalone">Самостоятельные</Link></div>}/>
  <Section title="Сохранённые сценарии"><table className="data-table"><thead><tr><th>Расчёт / сценарий</th><th>Источник</th><th>Модель</th><th>Сотруднику</th><th>Себестоимость</th><th>Клиент</th><th>Маржа</th><th>Статус</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong className="cell-title">{x.calculationNumber} · v{x.scenarioNumber}</strong><span className="cell-sub">{x.name}</span></td><td>{x.requestId?<Link href={`/requests/${x.requestId}?tab=calculations`}>{x.request} · {x.role}</Link>:"Самостоятельный"}</td><td>{x.model}</td><td className="num">{rub(x.workerNet)}</td><td className="num">{rub(x.totalCost)}</td><td className="num">{rub(x.clientRate)}</td><td className="num">{pct(x.marginPct)}</td><td><Status tone={x.status==="accepted"?"good":x.status==="rejected"?"bad":"warn"}>{scenarioLabels[x.status]??x.status}</Status></td></tr>):<tr><td colSpan={8}>Сценариев в этом представлении пока нет.</td></tr>}</tbody></table></Section><div style={{height:16}}/><PageHeader eyebrow={request?"Расчёт из заявки":"Самостоятельный расчёт"} title="Новый расчёт" subtitle={request?"Условия заявки загружаются автоматически; пользователь уточняет только экономические параметры сценария.":"Расчёт можно сохранить без заявки и позднее связать с коммерческим процессом."}/><CalculatorWorkspace requestId={request}/></>;
}
