import { notFound } from "next/navigation";
import { requireActor } from "@/lib/auth/server";
import { getProposalDocument } from "@/lib/data/proposal-document";
import { PrintProposalButton } from "@/components/PrintProposalButton";
import { rub } from "@/lib/ui/format";

export default async function ProposalPrint({params}:{params:Promise<{id:string}>}){const {id}=await params;const actor=await requireActor();const doc=await getProposalDocument(actor,id);if(!doc)notFound();return <main style={{maxWidth:900,margin:"0 auto",padding:"32px 24px 64px",background:"var(--surface)",color:"var(--text)"}}><div className="no-print" style={{display:"flex",justifyContent:"flex-end",marginBottom:18}}><PrintProposalButton/></div><header style={{borderBottom:"1px solid var(--line)",paddingBottom:18,marginBottom:22}}><div className="eyebrow">{doc.proposalNumber} · v{doc.version}</div><h1 style={{margin:"6px 0"}}>Коммерческое предложение</h1><p>{doc.client} · {doc.requestTitle}</p></header><section><h2>Проект</h2><table className="data-table"><tbody><tr><th>Площадка</th><td>{doc.siteName??"Не указана"}</td></tr><tr><th>Адрес</th><td>{doc.location??"Не указан"}</td></tr><tr><th>Дата предложения</th><td>{doc.createdAt}</td></tr><tr><th>Действует до</th><td>{doc.validUntil??"Не указано"}</td></tr></tbody></table></section><section style={{marginTop:24}}><h2>Позиции и ставки</h2><table className="data-table"><thead><tr><th>Специальность</th><th>Количество</th><th>График</th><th>Ставка</th></tr></thead><tbody>{doc.positions.map((position,index)=><tr key={`${position.name}-${index}`}><td>{position.name}</td><td>{position.count} чел.</td><td>{position.scheduleType??"По условиям заявки"}{position.paidHours?` · ${position.paidHours} оплач. ч`:""}</td><td>{rub(position.clientRate)} / ч</td></tr>)}</tbody></table></section><section style={{marginTop:24}}><h2>Что включено</h2><div className="stack-list">{clientProvision(doc.provision).map(line=><div className="stack-item" key={line}>{line}</div>)}</div></section>{clientTerms(doc.terms).length>0&&<section style={{marginTop:24}}><h2>Дополнительные условия</h2>{clientTerms(doc.terms).map(line=><p key={line}>{line}</p>)}</section>}<style>{`@media print{.no-print,.app-sidebar,.topbar{display:none!important}body{background:white!important}main{max-width:none!important;padding:0!important;color:#111!important}.data-table{font-size:11pt}.section{break-inside:avoid}}`}</style></main>}
function clientProvision(provision:Record<string,unknown>){const labels:Record<string,string>={workwear:"Спецодежда",ppe:"СИЗ",food:"Питание",housing:"Проживание",shuttle:"Развозка",travel:"Проезд иногородних",medical:"Медосмотр",medicalBook:"Медкнижка",training:"Обучение",permits:"Допуски",tools:"Инструменты",other:"Другие расходы"};const rows:string[]=[];for(const [key,label] of Object.entries(labels)){const item=provision[key];if(item&&typeof item==="object"){const provider=(item as Record<string,unknown>).provider;rows.push(`${label}: ${provider==="client"?"предоставляет заказчик":provider==="us"?"включено в предложение":"не требуется"}`)}}return rows.length?rows:["Условия обеспечения — согласно согласованной заявке."]}
function clientTerms(terms:Record<string,unknown>){return ["additionalConditions","included","paymentTerms","notes"].map(key=>terms[key]).filter((value):value is string=>typeof value==="string"&&Boolean(value.trim()))}
