"use client";
import {useState} from "react";
export type ContactValues={fullName:string;position?:string;phone:string;email:string;telegram:string;whatsapp:string;maxContact:string;preferredChannel?:string};
export const emptyContact:ContactValues={fullName:"",position:"",phone:"",email:"",telegram:"",whatsapp:"",maxContact:"",preferredChannel:""};
const channels=[['phone','Телефон'],['email','Эл. почта'],['telegram','Telegram'],['whatsapp','WhatsApp'],['maxContact','MAX']] as const;
export function ContactFields({value,onChange,defaultValue,names={},showPosition=true,required=true,availableChannels}:{value?:ContactValues;onChange?:(next:ContactValues)=>void;defaultValue?:Partial<ContactValues>;names?:Record<string,string>;showPosition?:boolean;required?:boolean;availableChannels?:string[]}){
 const [local,setLocal]=useState<ContactValues>({...emptyContact,...defaultValue});const current=value??local;const choices=channels.filter(([key])=>!availableChannels||availableChannels.includes(key));
 const [visible,setVisible]=useState<string[]>(()=>channels.filter(([key])=>Boolean((value??defaultValue)?.[key])||key==='phone').map(([key])=>key));
 function patch(key:string,text:string){const next={...current,[key]:text};setLocal(next);onChange?.(next);}
 return <div className="sales-contact-fields"><div className="form-grid two"><label><span>ФИО{required?' *':''}</span><input name={names.fullName??'fullName'} required={required} minLength={required?2:undefined} maxLength={180} value={current.fullName} onChange={e=>patch('fullName',e.target.value)}/></label>{showPosition&&<label><span>Должность</span><input name={names.position??'position'} maxLength={180} value={current.position??''} onChange={e=>patch('position',e.target.value)}/></label>}</div>
 {choices.map(([key,label])=>visible.includes(key)?<div className="sales-contact-method" key={key}><label><span>{label}</span><input name={names[key]??key} type={key==='email'?'email':key==='phone'?'tel':'text'} maxLength={key==='email'?240:key==='phone'?80:120} value={current[key]} onChange={e=>patch(key,e.target.value)}/></label><button type="button" className="button" aria-label={`Убрать способ связи: ${label}`} onClick={()=>{setLocal(v=>({...v,[key]:'',preferredChannel:(v.preferredChannel===key||key==='maxContact'&&v.preferredChannel==='max')?'':v.preferredChannel}));onChange?.({...current,[key]:'',preferredChannel:(current.preferredChannel===key||key==='maxContact'&&current.preferredChannel==='max')?'':current.preferredChannel});setVisible(v=>v.filter(x=>x!==key));}}>Убрать</button></div>:<input type="hidden" name={names[key]??key} value={current[key]} key={key}/>)}
 {visible.length<choices.length&&<label className="sales-contact-add"><span>Добавить способ связи</span><select value="" onChange={e=>{const selected=e.target.value;if(selected)setVisible(v=>[...v,selected]);}}><option value="">Выберите канал</option>{choices.filter(([key])=>!visible.includes(key)).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}
 {!availableChannels&&<label className="sales-contact-add"><span>Предпочтительный канал</span><select name="preferredChannel" value={current.preferredChannel??''} onChange={e=>patch('preferredChannel',e.target.value)}><option value="">Не выбран</option>{channels.filter(([key])=>Boolean(current[key])).map(([key,label])=><option value={key==='maxContact'?'max':key} key={key}>{label}</option>)}</select></label>}
 </div>;
}
