import { NextResponse } from "next/server";
import { AccessDeniedError, requireCapability } from "@/lib/access/server";
import { getCurrentActor } from "@/lib/auth/server";
import { withTenant } from "@/lib/db/client";
import { listCompanyEmployees, listOrganizationUnits, listStaffPositions } from "@/lib/organization/service";

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export async function GET(request:Request){try{const actor=await getCurrentActor();if(!actor)return NextResponse.json({error:"Требуется вход"},{status:401});requireCapability(actor,"organization.read");const url=new URL(request.url);const kind=url.searchParams.get("kind");const date=url.searchParams.get("date")??new Date().toISOString().slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return NextResponse.json({error:"Некорректная дата"},{status:400});
if(kind==="snapshot"){const [units,positions,employees]=await Promise.all([listOrganizationUnits(actor),listStaffPositions(actor),listCompanyEmployees(actor)]);return NextResponse.json({date,units,positions,employees})}
if(kind==="responsibility"){const process=url.searchParams.get("process")??"";const step=url.searchParams.get("step")??"";const scopeType=url.searchParams.get("scopeType")??"all_org";const scopeId=url.searchParams.get("scopeId");if(!process||!step||(scopeId&&!uuid.test(scopeId)))return NextResponse.json({error:"Не указан процесс или этап"},{status:400});if(actor.demo)return NextResponse.json({item:null});const [item]=await withTenant(actor.organizationId,actor.userId,sql=>sql.unsafe<Array<{ruleId:string;membershipId:string;userId:string;sourceType:string;sourceId:string;isFallback:boolean;employeeName:string}>>(`SELECT r.rule_id "ruleId",r.membership_id "membershipId",r.user_id "userId",r.source_type "sourceType",r.source_id "sourceId",r.is_fallback "isFallback",u.display_name "employeeName" FROM resolve_organization_responsibility($1,$2,$3,$4::uuid,$5::date) r JOIN app_users u ON u.id=r.user_id`,[process,step,scopeType,scopeId,date]));return NextResponse.json({item:item??null})}
const membershipId=url.searchParams.get("membershipId")??"";if(!uuid.test(membershipId))return NextResponse.json({error:"Некорректный сотрудник"},{status:400});const visible=await listCompanyEmployees(actor);if(!visible.some(item=>item.id===membershipId))return NextResponse.json({error:"Сотрудник недоступен"},{status:404});if(actor.demo)return NextResponse.json({item:null,items:[]});if(kind==="assignment"){const [item]=await withTenant(actor.organizationId,actor.userId,sql=>sql.unsafe(`SELECT * FROM current_position_assignment($1::uuid,$2::date)`,[membershipId,date]));return NextResponse.json({item:item??null})}if(kind==="manager"){const [item]=await withTenant(actor.organizationId,actor.userId,sql=>sql.unsafe<Array<{membershipId:string;name:string}>>(`SELECT m.id "membershipId",u.display_name name FROM organization_memberships m JOIN app_users u ON u.id=m.user_id WHERE m.id=resolve_employee_manager($1::uuid,$2::date)`,[membershipId,date]));return NextResponse.json({item:item??null})}if(kind==="team"){const items=await withTenant(actor.organizationId,actor.userId,sql=>sql.unsafe<Array<{membershipId:string;name:string}>>(`SELECT m.id "membershipId",u.display_name name FROM organization_memberships m JOIN app_users u ON u.id=m.user_id WHERE m.status='active' AND resolve_employee_manager(m.id,$2::date)=$1::uuid ORDER BY u.display_name`,[membershipId,date]));return NextResponse.json({items})}return NextResponse.json({error:"Неизвестный тип разрешения"},{status:400})}catch(error){if(error instanceof AccessDeniedError)return NextResponse.json({error:"Недостаточно прав"},{status:403});console.error(error);return NextResponse.json({error:"Не удалось разрешить организационную связь"},{status:500})}}
